voogasalad_LosTorres: utilities.pathfinding.example.LinkedNode Class Reference
utilities.pathfinding.example.LinkedNode Class Reference
Public Member Functions
LinkedNode (int x, int y)
Collection< LinkedNode > getNeighbors ()
void addNeighbor (LinkedNode neighbor)
int compareTo (LinkedNode o)
Public Member Functions inherited from utilities.pathfinding.example.UnlinkedNode
UnlinkedNode (int x, int y)
int getX ()
int getY ()
boolean equals (Object other)
String toString ()
Package Attributes
Collection< LinkedNode > myNext
Detailed Description
Definition at line 6 of file LinkedNode.java.
Constructor & Destructor Documentation
utilities.pathfinding.example.LinkedNode.LinkedNode (int x, int y)
Definition at line 10 of file LinkedNode.java.
Member Function Documentation
void utilities.pathfinding.example.LinkedNode.addNeighbor (LinkedNode neighbor)
Definition at line 19 of file LinkedNode.java.
Referenced by utilities.pathfinding.example.LinkedNodeExample.updateNodesWithNeighbors().
int utilities.pathfinding.example.LinkedNode.compareTo (LinkedNode o)
Definition at line 24 of file LinkedNode.java.
References utilities.pathfinding.example.UnlinkedNode.getX(), and utilities.pathfinding.example.UnlinkedNode.getY().
Referenced by utilities.pathfinding.example.LinkedNodeAStarFinder.breakTie().
Collection<LinkedNode> utilities.pathfinding.example.LinkedNode.getNeighbors ()
Definition at line 15 of file LinkedNode.java.
References utilities.pathfinding.example.LinkedNode.myNext.
Referenced by utilities.pathfinding.example.LinkedNodeAStarFinder.getNeighbors().
Member Data Documentation
Collection<LinkedNode> utilities.pathfinding.example.LinkedNode.myNext package
Definition at line 8 of file LinkedNode.java.
Referenced by utilities.pathfinding.example.LinkedNode.getNeighbors().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/pathfinding/example/LinkedNode.java