voogasalad_LosTorres: gameEngine.levels.BaseLevel Class Reference
gameEngine.levels.BaseLevel Class Reference
Public Member Functions
void addEnemyCountPair (EnemyCountPair pair)
List< EnemyCountPair > getEnemyCountPairs ()
void setDuration (int i)
int getDuration ()
Private Attributes
List< EnemyCountPair > myEnemyCountPairs = new ArrayList<EnemyCountPair>()
int myDurationSeconds
Detailed Description
Definition at line 7 of file BaseLevel.java.
Member Function Documentation
void gameEngine.levels.BaseLevel.addEnemyCountPair (EnemyCountPair pair)
Definition at line 12 of file BaseLevel.java.
References gameAuthoring.scenes.levelBuilding.EnemyCountPair.getMyEnemy(), and gameAuthoring.scenes.levelBuilding.EnemyCountPair.getMyNumEnemies().
Referenced by gameAuthoring.scenes.levelBuilding.LevelDisplayCell.generateLevel().
int gameEngine.levels.BaseLevel.getDuration ()
Definition at line 30 of file BaseLevel.java.
References gameEngine.levels.BaseLevel.myDurationSeconds.
Referenced by gameEngine.MainEngineManager.loadLevel().
List<EnemyCountPair> gameEngine.levels.BaseLevel.getEnemyCountPairs ()
Definition at line 22 of file BaseLevel.java.
References gameEngine.levels.BaseLevel.myEnemyCountPairs.
Referenced by gameEngine.MainEngineManager.loadLevel().
void gameEngine.levels.BaseLevel.setDuration (int i)
Definition at line 26 of file BaseLevel.java.
Referenced by gameAuthoring.scenes.levelBuilding.LevelDisplayCell.generateLevel().
Member Data Documentation
int gameEngine.levels.BaseLevel.myDurationSeconds private
Definition at line 10 of file BaseLevel.java.
Referenced by gameEngine.levels.BaseLevel.getDuration().
List<EnemyCountPair> gameEngine.levels.BaseLevel.myEnemyCountPairs = new ArrayList<EnemyCountPair>() private
Definition at line 9 of file BaseLevel.java.
Referenced by gameEngine.levels.BaseLevel.getEnemyCountPairs().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/levels/BaseLevel.java