voogasalad_LosTorres: gamePlayer.guiItems.welcome.Header Class Reference
gamePlayer.guiItems.welcome.Header Class Reference
Public Member Functions
void initialize (Dimension2D containerSize)
Node getNode ()
Private Member Functions
void setupPane ()
void setupImage ()
Private Attributes
XMLParser myParser
HBox myRoot
ImageView myImage
Dimension2D mySize
Additional Inherited Members
Static Public Attributes inherited from gamePlayer.guiItems.GuiItem
static String myPropertiesPath = "guiItems/"
Detailed Description
Definition at line 16 of file Header.java.
Member Function Documentation
Node gamePlayer.guiItems.welcome.Header.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 34 of file Header.java.
References gamePlayer.guiItems.welcome.Header.myRoot.
void gamePlayer.guiItems.welcome.Header.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 24 of file Header.java.
References gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_ELEMENT_PROPERTIES_PATH, gamePlayer.guiItems.GuiItem.myPropertiesPath, gamePlayer.guiItems.welcome.Header.setupImage(), and gamePlayer.guiItems.welcome.Header.setupPane().
void gamePlayer.guiItems.welcome.Header.setupImage () private
Definition at line 45 of file Header.java.
References utilities.XMLParsing.XMLParser.getDoubleValuesFromTag(), and utilities.XMLParsing.XMLParser.getValuesFromTag().
Referenced by gamePlayer.guiItems.welcome.Header.initialize().
void gamePlayer.guiItems.welcome.Header.setupPane () private
Definition at line 38 of file Header.java.
Referenced by gamePlayer.guiItems.welcome.Header.initialize().
Member Data Documentation
ImageView gamePlayer.guiItems.welcome.Header.myImage private
Definition at line 20 of file Header.java.
XMLParser gamePlayer.guiItems.welcome.Header.myParser private
Definition at line 18 of file Header.java.
HBox gamePlayer.guiItems.welcome.Header.myRoot private
Definition at line 19 of file Header.java.
Referenced by gamePlayer.guiItems.welcome.Header.getNode().
Dimension2D gamePlayer.guiItems.welcome.Header.mySize private
Definition at line 21 of file Header.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItems/welcome/Header.java