voogasalad_LosTorres: gameEngine.Data.TowerTileGrid Class Reference
gameEngine.Data.TowerTileGrid Class Reference
Public Member Functions
TowerTileGrid (int rowSize, int colSize)
boolean isInRange (int row, int col)
boolean checkTowerTile (int row, int col)
void setTowerTile (int row, int col, boolean towerOn)
void setAsNotChanged ()
boolean hasBeenChanged ()
Private Member Functions
void setChangedStatus (boolean status)
Private Attributes
boolean myChangedFlag
boolean[][] myTowerTileGrid
int myRowSize
int myColSize
Detailed Description
Definition at line 3 of file TowerTileGrid.java.
Constructor & Destructor Documentation
gameEngine.Data.TowerTileGrid.TowerTileGrid (int rowSize, int colSize)
Definition at line 11 of file TowerTileGrid.java.
Member Function Documentation
boolean gameEngine.Data.TowerTileGrid.checkTowerTile (int row, int col)
Definition at line 22 of file TowerTileGrid.java.
Referenced by gameEngine.AI.GridPathFinder.getNeighbors().
boolean gameEngine.Data.TowerTileGrid.hasBeenChanged ()
Definition at line 39 of file TowerTileGrid.java.
References gameEngine.Data.TowerTileGrid.myChangedFlag.
Referenced by gameEngine.MainEngineManager.checkNewPath().
boolean gameEngine.Data.TowerTileGrid.isInRange (int row, int col)
Definition at line 18 of file TowerTileGrid.java.
References gameEngine.Data.TowerTileGrid.myColSize.
Referenced by gameEngine.AI.GridPathFinder.getNeighbors().
void gameEngine.Data.TowerTileGrid.setAsNotChanged ()
Definition at line 35 of file TowerTileGrid.java.
References gameEngine.Data.TowerTileGrid.setChangedStatus().
Referenced by gameEngine.MainEngineManager.createTimeline().
void gameEngine.Data.TowerTileGrid.setChangedStatus (boolean status) private
Definition at line 31 of file TowerTileGrid.java.
Referenced by gameEngine.Data.TowerTileGrid.setAsNotChanged(), and gameEngine.Data.TowerTileGrid.setTowerTile().
void gameEngine.Data.TowerTileGrid.setTowerTile (int row, int col, boolean towerOn)
Definition at line 26 of file TowerTileGrid.java.
References gameEngine.Data.TowerTileGrid.setChangedStatus().
Referenced by gameEngine.MainEngineManager.setTowerTileStatus().
Member Data Documentation
boolean gameEngine.Data.TowerTileGrid.myChangedFlag private
Definition at line 5 of file TowerTileGrid.java.
Referenced by gameEngine.Data.TowerTileGrid.hasBeenChanged().
int gameEngine.Data.TowerTileGrid.myColSize private
Definition at line 9 of file TowerTileGrid.java.
Referenced by gameEngine.Data.TowerTileGrid.isInRange().
int gameEngine.Data.TowerTileGrid.myRowSize private
Definition at line 8 of file TowerTileGrid.java.
boolean [][] gameEngine.Data.TowerTileGrid.myTowerTileGrid private
Definition at line 7 of file TowerTileGrid.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/Data/TowerTileGrid.java