voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.pathComponents.Path Class Reference
gameAuthoring.scenes.pathBuilding.pathComponents.Path Class Reference
Public Member Functions
Path (Group group)
void addComponentToPath (PathComponent componentToAdd)
boolean tryToAddConnectComponentToEndingLocation (PathComponent componentToAdd)
boolean attemptToConnectRoutes (PathComponent comp)
void moveConnectedComponent (PathComponent draggedComponent, double deltaX, double deltaY)
PathStartingLocation addStartingLocation (double x, double y)
PathEndingLocation addEndingLocation (double x, double y)
boolean startingLocationsConfiguredCorrectly ()
boolean endingLocationsConfiguredCorrectly ()
void handleComponentSelection (PathComponent componentClickedOn)
List< PathComponent > deleteSelectedComponent ()
List< PathComponent > getAllPathComponents ()
void clearEnemyStartingLocations ()
void clearEnemyEndingLocations ()
Iterator< PathRoute > iterator ()
boolean isPathCompletedAndRoutesVerified ()
void resetPath ()
boolean intersects (Tile tile)
Protected Member Functions
void connectRoutes (PathRoute connectedComponent1, PathRoute connectedComponent2)
PathRoute getRouteContaining (PathComponent comp)
boolean canCreateLocationAtPoint (double x, double y)
boolean isLocationCloseToPoint (PathLocation pathLocation, Point2D newLocation)
int getNumRoutes ()
List< PathRoute > getRoutes ()
Static Protected Attributes
static final Color VISIBLE_COLOR = Color.BLUE
static final Color INVISIBLE_COLOR = new Color(0, 0, 0, .3)
Private Member Functions
boolean componentAddedToStartingLocation (PathComponent componentToAdd)
void drawComponents (List< PathComponent > components)
boolean addedComponentIsWithinCircle (Point2D pointNearestCircle, Point2D centerCircle)
void createNewRoute (PathComponent componentToAdd)
boolean closeEnoughToConnect (PathComponent last, PathComponent componentToAdd)
boolean isAnotherStartingLocationToClose (double x, double y)
boolean isAnotherEndingLocationToClose (double x, double y)
void ensureLocationsAreInFront ()
void bringComponentToFrontOfGroup (Node comp)
boolean isComponentInPreviouslySelectedComponent (PathComponent componentClickedOn)
void deselectSelectedConnectedComponent ()
Private Attributes
List< PathStartingLocation > myStartingLocations
List< PathEndingLocation > myEndingLocations
List< PathRoute > myPath
PathComponent mySelectedComponent
Static Private Attributes
static final double CONNECT_THRESHOLD = 40
static final double INSIDE_STARTING_LOC_THRESHOLD = 50
static final double MIN_DISTANCE_BTW_LOCS = 150
static Group myGroup
Detailed Description
Holds all of the routes and all of the logic to connect disconnected routes together, to add new routes, and to create forks.
Author
Austin Kyker
Definition at line 23 of file Path.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.pathComponents.Path.Path (Group group)
Definition at line 39 of file Path.java.
Member Function Documentation
void gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath (PathComponent componentToAdd)
First tries to add a component to a starting location and if this fails, the method tries to add the component to another pre-existing route. Otherwise it starts its own new route.
Definition at line 51 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.attemptToConnectRoutes(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.componentAddedToStartingLocation(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.createNewRoute().
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AddSingleCurveComponentTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AddSingleLineComponentTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AttemptToConnectRoutesFORKTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AttemptToConnectRoutesNoForkTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectComponentToEndingLocationTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectComponentToStartingLocationTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectLineToCurveTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectRoutesTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectTwoCurvesTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectTwoLinesTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.CreateTwoRoutesTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.GetRouteContainingComponentTest(), gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.handleBuildScreenClick(), gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.handleBuildScreenClick(), and gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testRoutesTranslation().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.Path.addedComponentIsWithinCircle (Point2D pointNearestCircle, Point2D centerCircle) private
Definition at line 152 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.INSIDE_STARTING_LOC_THRESHOLD.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.componentAddedToStartingLocation(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.tryToAddConnectComponentToEndingLocation().
PathEndingLocation gameAuthoring.scenes.pathBuilding.pathComponents.Path.addEndingLocation (double x, double y)
Definition at line 204 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.canCreateLocationAtPoint().
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AddingStartingLocationWithNearbyEndingLocationTest(), gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane.addNewEndingLocation(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ClearEndingLocationsTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectComponentToEndingLocationTest(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.EndingLocationsMustExistToBeConfiguredCorrectlyTest().
PathStartingLocation gameAuthoring.scenes.pathBuilding.pathComponents.Path.addStartingLocation (double x, double y)
Definition at line 189 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.canCreateLocationAtPoint().
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AddingStartingLocationWithNearbyStartLocationTest(), gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane.addNewStartingLocation(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ClearStartingLocationsTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectComponentToStartingLocationTest(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.StartingLocationsMustExistToBeConfiguredCorrectlyTest().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.Path.attemptToConnectRoutes (PathComponent comp)
Tries to connect two routes together. Not only checks to see if the end of one route can be connected to the beginning of another route and vice versa, but also checks to see if a fork can be made. In the case of the fork the components in the pre-existing route above the fork are copied and added to the head of the added component. This way two routes are generated and they each have seperate components rather than sharing components.
Definition at line 98 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.closeEnoughToConnect(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.connectRoutes(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.drawComponents(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.ensureLocationsAreInFront(), gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.getComponents(), gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.getComponentsBefore(), gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.getFirst(), gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.getLast(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.getRouteContaining().
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AttemptToConnectRoutesFORKTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AttemptToConnectRoutesNoForkTest(), and gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.handleSelectionAndTryToConnectComponents().
void gameAuthoring.scenes.pathBuilding.pathComponents.Path.bringComponentToFrontOfGroup (Node comp) private
Definition at line 271 of file Path.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.ensureLocationsAreInFront(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.handleComponentSelection().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.Path.canCreateLocationAtPoint (double x, double y) protected
Definition at line 213 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.isAnotherEndingLocationToClose(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.isAnotherStartingLocationToClose().
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.addEndingLocation(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AddingStartingLocationWithNearbyEndingLocationTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AddingStartingLocationWithNearbyStartLocationTest(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.addStartingLocation().
void gameAuthoring.scenes.pathBuilding.pathComponents.Path.clearEnemyEndingLocations ()
Definition at line 321 of file Path.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AddingStartingLocationWithNearbyEndingLocationTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ClearEndingLocationsTest(), gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane.createEnemyEndingLocationsSetupComponents(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.resetPath().
void gameAuthoring.scenes.pathBuilding.pathComponents.Path.clearEnemyStartingLocations ()
Definition at line 315 of file Path.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AddingStartingLocationWithNearbyStartLocationTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ClearStartingLocationsTest(), gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane.createEnemyStartingLocationsSetupComponents(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.resetPath().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.Path.closeEnoughToConnect (PathComponent last, PathComponent componentToAdd) private
Definition at line 162 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.getEndingPoint(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.getStartingPoint().
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.attemptToConnectRoutes().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.Path.componentAddedToStartingLocation (PathComponent componentToAdd) private
Checks to see if a starting location is close to the starting point of the component. If so, it connects the component to the starting point.
Definition at line 62 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addedComponentIsWithinCircle(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getRouteContaining(), gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.getStartingPoint(), gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.setStartingLocation(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.setStartingPoint().
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath().
void gameAuthoring.scenes.pathBuilding.pathComponents.Path.connectRoutes (PathRoute connectedComponent1, PathRoute connectedComponent2) protected
Simply connects the ending point of connectedComponent1 to the starting point of connectedComponent2
Definition at line 144 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.addAll(), gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.getEndingPoint(), gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.getFirst(), gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.getLast(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.setStartingPoint().
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.attemptToConnectRoutes(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectRoutesTest().
void gameAuthoring.scenes.pathBuilding.pathComponents.Path.createNewRoute (PathComponent componentToAdd) private
Definition at line 156 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.add().
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath().
List<PathComponent> gameAuthoring.scenes.pathBuilding.pathComponents.Path.deleteSelectedComponent ()
Definition at line 296 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.getComponents(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.getRouteContaining().
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.handleKeyPress().
void gameAuthoring.scenes.pathBuilding.pathComponents.Path.deselectSelectedConnectedComponent () private
Definition at line 286 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.getRouteContaining().
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.handleComponentSelection().
void gameAuthoring.scenes.pathBuilding.pathComponents.Path.drawComponents (List< PathComponent > components) private
Definition at line 134 of file Path.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.attemptToConnectRoutes().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.Path.endingLocationsConfiguredCorrectly ()
Definition at line 232 of file Path.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ClearEndingLocationsTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.EndingLocationsMustExistToBeConfiguredCorrectlyTest(), and gameAuthoring.scenes.pathBuilding.PathBuildingScene.proceedToLineDrawerModeIfLocationsVerified().
void gameAuthoring.scenes.pathBuilding.pathComponents.Path.ensureLocationsAreInFront () private
Ensures that the starting and ending location nodes are in front of the path component nodes to make it more aesthetically pleasing.
Definition at line 262 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.bringComponentToFrontOfGroup().
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.attemptToConnectRoutes(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.handleComponentSelection().
List<PathComponent> gameAuthoring.scenes.pathBuilding.pathComponents.Path.getAllPathComponents ()
Definition at line 307 of file Path.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.ComponentVisibilityPane.addListeners(), gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.addListenersToComponents(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AddSingleCurveComponentTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AddSingleLineComponentTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectLineToCurveTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectTwoCurvesTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectTwoLinesTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.CreateTwoRoutesTest(), gameAuthoring.scenes.pathBuilding.buildingPanes.ComponentVisibilityPane.executeEnterFunction(), gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.executeEnterFunction(), gameAuthoring.scenes.pathBuilding.buildingPanes.ComponentVisibilityPane.executeExitFunction(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.intersects(), gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.removeListenerFromComponents(), and gameAuthoring.scenes.pathBuilding.buildingPanes.ComponentVisibilityPane.removeListeners().
int gameAuthoring.scenes.pathBuilding.pathComponents.Path.getNumRoutes () protected
Definition at line 326 of file Path.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AddSingleCurveComponentTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AddSingleLineComponentTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AttemptToConnectRoutesFORKTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AttemptToConnectRoutesNoForkTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectLineToCurveTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectRoutesTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectTwoCurvesTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectTwoLinesTest(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.CreateTwoRoutesTest().
PathRoute gameAuthoring.scenes.pathBuilding.pathComponents.Path.getRouteContaining (PathComponent comp) protected
Definition at line 180 of file Path.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.attemptToConnectRoutes(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.componentAddedToStartingLocation(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectRoutesTest(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.deleteSelectedComponent(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.deselectSelectedConnectedComponent(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.GetRouteContainingComponentTest(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.handleComponentSelection(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.isComponentInPreviouslySelectedComponent(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.moveConnectedComponent(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.tryToAddConnectComponentToEndingLocation().
List<PathRoute> gameAuthoring.scenes.pathBuilding.pathComponents.Path.getRoutes () protected
Definition at line 332 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.myPath.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectComponentToEndingLocationTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectComponentToStartingLocationTest(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.GetRouteContainingComponentTest().
void gameAuthoring.scenes.pathBuilding.pathComponents.Path.handleComponentSelection (PathComponent componentClickedOn)
Handles the selection of components in selection mode. Ensures that the route that is clicked on is selected (green). If it was already selected, then it is deselected.
Definition at line 241 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.bringComponentToFrontOfGroup(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.deselectSelectedConnectedComponent(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.ensureLocationsAreInFront(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getRouteContaining(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.isComponentInPreviouslySelectedComponent().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.handleSelectionAndTryToConnectComponents().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.Path.intersects (Tile tile)
Definition at line 356 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.getAllPathComponents().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.suggestNoTowerPlacementOnPath().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.Path.isAnotherEndingLocationToClose (double x, double y) private
Definition at line 218 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.isLocationCloseToPoint().
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.canCreateLocationAtPoint().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.Path.isAnotherStartingLocationToClose (double x, double y) private
Definition at line 198 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.isLocationCloseToPoint().
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.canCreateLocationAtPoint().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.Path.isComponentInPreviouslySelectedComponent (PathComponent componentClickedOn) private
Definition at line 276 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.getComponents(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.getRouteContaining().
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.handleComponentSelection().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.Path.isLocationCloseToPoint (PathLocation pathLocation, Point2D newLocation) protected
Definition at line 224 of file Path.java.
References gameAuthoring.scenes.pathBuilding.enemyLocations.PathLocation.getCenterLoc(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.MIN_DISTANCE_BTW_LOCS.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.isAnotherEndingLocationToClose(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.isAnotherStartingLocationToClose(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.IsLocationCloseToMethodTest().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.Path.isPathCompletedAndRoutesVerified ()
Definition at line 341 of file Path.java.
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.handleFinishButtonClick().
Iterator<PathRoute> gameAuthoring.scenes.pathBuilding.pathComponents.Path.iterator ()
Definition at line 337 of file Path.java.
void gameAuthoring.scenes.pathBuilding.pathComponents.Path.moveConnectedComponent (PathComponent draggedComponent, double deltaX, double deltaY)
Moves the entire route. This function is called in selection mode when the user picks up a route and drags it across screen.
Definition at line 170 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.getRouteContaining(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.isNotConnectedToStartOrEndLocations().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.addSelectionListeners().
void gameAuthoring.scenes.pathBuilding.pathComponents.Path.resetPath ()
Definition at line 349 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.clearEnemyEndingLocations(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.clearEnemyStartingLocations().
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.resetBuild().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.Path.startingLocationsConfiguredCorrectly ()
Definition at line 228 of file Path.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ClearStartingLocationsTest(), gameAuthoring.scenes.pathBuilding.PathBuildingScene.proceedToEndLocationsSelection(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.StartingLocationsMustExistToBeConfiguredCorrectlyTest().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.Path.tryToAddConnectComponentToEndingLocation (PathComponent componentToAdd)
Checks to see if the ending point of the component added is close to an ending location. If so, the component is connected to the end point.
Definition at line 79 of file Path.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addedComponentIsWithinCircle(), gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.getEndingPoint(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getRouteContaining(), gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.setEndingLocation(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.setEndingPoint().
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectComponentToEndingLocationTest(), gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.handleBuildScreenClick(), and gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.handleBuildScreenClick().
Member Data Documentation
final double gameAuthoring.scenes.pathBuilding.pathComponents.Path.CONNECT_THRESHOLD = 40 static private
Definition at line 28 of file Path.java.
final double gameAuthoring.scenes.pathBuilding.pathComponents.Path.INSIDE_STARTING_LOC_THRESHOLD = 50 static private
Definition at line 29 of file Path.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.addedComponentIsWithinCircle().
final Color gameAuthoring.scenes.pathBuilding.pathComponents.Path.INVISIBLE_COLOR = new Color(0, 0, 0, .3) static protected
Definition at line 26 of file Path.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.showVisibility(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.showVisibility(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.togglePathComponentVisibility().
final double gameAuthoring.scenes.pathBuilding.pathComponents.Path.MIN_DISTANCE_BTW_LOCS = 150 static private
Definition at line 30 of file Path.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.isLocationCloseToPoint().
List<PathEndingLocation> gameAuthoring.scenes.pathBuilding.pathComponents.Path.myEndingLocations private
Definition at line 33 of file Path.java.
Group gameAuthoring.scenes.pathBuilding.pathComponents.Path.myGroup static private
Definition at line 37 of file Path.java.
List<PathRoute> gameAuthoring.scenes.pathBuilding.pathComponents.Path.myPath private
Definition at line 34 of file Path.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.getRoutes().
PathComponent gameAuthoring.scenes.pathBuilding.pathComponents.Path.mySelectedComponent private
Definition at line 36 of file Path.java.
List<PathStartingLocation> gameAuthoring.scenes.pathBuilding.pathComponents.Path.myStartingLocations private
Definition at line 32 of file Path.java.
final Color gameAuthoring.scenes.pathBuilding.pathComponents.Path.VISIBLE_COLOR = Color.BLUE static protected
Definition at line 25 of file Path.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.showVisibility(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.showVisibility(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.togglePathComponentVisibility().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/pathComponents/Path.java