voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.buildingPanes.ComponentVisibilityPane Class Reference
gameAuthoring.scenes.pathBuilding.buildingPanes.ComponentVisibilityPane Class Reference
Public Member Functions
ComponentVisibilityPane (Group group, Path path)
void executeEnterFunction ()
void executeExitFunction ()
Public Member Functions inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
BuildingPane (Group group)
void drawLocation (Node component)
void drawPathComponent (Node component)
void refreshScreen ()
void removeComponentFromScreen (Node component)
void executeExitFunction ()
void executeEnterFunction ()
Private Member Functions
void addListeners ()
void removeListeners ()
Private Attributes
Path myPath
Additional Inherited Members
Static Public Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
static final double DRAW_SCREEN_WIDTH_RATIO = .80
static final double DRAW_SCREEN_WIDTH
Static Protected Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
static Group myGroup
Detailed Description
A pane to allow the user to select which path components should be visible and invisible. An invisible path component means that the enemy will be hidden from the screen on this path (maybe the enemy went into a tunnel).
Author
Austin Kyker
Definition at line 14 of file ComponentVisibilityPane.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.buildingPanes.ComponentVisibilityPane.ComponentVisibilityPane (Group group, Path path)
Definition at line 18 of file ComponentVisibilityPane.java.
Member Function Documentation
void gameAuthoring.scenes.pathBuilding.buildingPanes.ComponentVisibilityPane.addListeners () private
Definition at line 23 of file ComponentVisibilityPane.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.getAllPathComponents().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.ComponentVisibilityPane.executeEnterFunction().
void gameAuthoring.scenes.pathBuilding.buildingPanes.ComponentVisibilityPane.executeEnterFunction ()
Definition at line 36 of file ComponentVisibilityPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.ComponentVisibilityPane.addListeners(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.getAllPathComponents().
void gameAuthoring.scenes.pathBuilding.buildingPanes.ComponentVisibilityPane.executeExitFunction ()
Definition at line 44 of file ComponentVisibilityPane.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.getAllPathComponents(), and gameAuthoring.scenes.pathBuilding.buildingPanes.ComponentVisibilityPane.removeListeners().
void gameAuthoring.scenes.pathBuilding.buildingPanes.ComponentVisibilityPane.removeListeners () private
Definition at line 29 of file ComponentVisibilityPane.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.getAllPathComponents().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.ComponentVisibilityPane.executeExitFunction().
Member Data Documentation
Path gameAuthoring.scenes.pathBuilding.buildingPanes.ComponentVisibilityPane.myPath private
Definition at line 16 of file ComponentVisibilityPane.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/buildingPanes/ComponentVisibilityPane.java