voogasalad_LosTorres: utilities.pathfinding.AStarPathFinder< T > Class Template Reference
utilities.pathfinding.AStarPathFinder< T > Class Template Reference abstract
Classes
class PQ
class PQTuple
Public Member Functions
abstract Number getHeuristicValue (T node, T destination)
boolean isDestination (T node, T destinationNode)
List< T > findPath (T start, T destination) throws InvalidCostException
Public Member Functions inherited from utilities.pathfinding.IPathFinder< T >
Number getCost (T beginningNode, T endingNode)
Iterable< T > getNeighbors (T node)
int breakTie (T node, T other)
Private Member Functions
Number getAndCheckCost (T beginningNode, T endingNode) throws InvalidCostException
Number getAndCheckHeuristicValue (T node, T destination) throws InvalidCostException
boolean isPositive (Number number)
Number addNumbers (Number...numbers)
Detailed Description
Author
Duke Kim
    Utility class for finding the least cost path in a network of nodes using A* path finding
    algorithm. To use, create a class that extends this abstract, and define all the
    unimplemented behavior, which are namely the heuristic function, how to get the cost
    between nodes and how to get neighbors. Then, instantiate an instance of the extending
    class, and call the method findPath by passing in the starting node and the ending node.
    The only other requirement apart from implementing the abstract methods is that the type
    specified in the generic correctly implements the equals method inherited from Object and
    that cost and heuristic values be positive numbers. Final note about the finder is that
    while any Number object may be returned for the cost and heuristic values, value accuracy
    will be lost for values which are too large or too small.
Parameters
<T> Any object type.
Definition at line 28 of file AStarPathFinder.java.
Member Function Documentation
Number utilities.pathfinding.AStarPathFinder< T >.addNumbers (Number... numbers) private
Definition at line 156 of file AStarPathFinder.java.
Referenced by utilities.pathfinding.AStarPathFinder< Point2D >.findPath().
List<T> utilities.pathfinding.AStarPathFinder< T >.findPath (T start, T destination) throws InvalidCostException
Finds the least cost path from the node specified by start to the one specified by destination
Parameters
start Starting node
destination Ending node
Returns
Path from start to destination in order.
Implements utilities.pathfinding.IPathFinder< T >.
Definition at line 104 of file AStarPathFinder.java.
Referenced by gameEngine.AI.GridPathFinder.getPath(), utilities.pathfinding.example.UnlinkedNodeExample.main(), utilities.pathfinding.example.LinkedNodeExample.main(), and utilities.pathfinding.AStarTest.testAStarLogic().
Number utilities.pathfinding.AStarPathFinder< T >.getAndCheckCost (T beginningNode, T endingNode) throws InvalidCostException private
Definition at line 91 of file AStarPathFinder.java.
Referenced by utilities.pathfinding.AStarPathFinder< Point2D >.findPath().
Number utilities.pathfinding.AStarPathFinder< T >.getAndCheckHeuristicValue (T node, T destination) throws InvalidCostException private
Definition at line 97 of file AStarPathFinder.java.
Referenced by utilities.pathfinding.AStarPathFinder< Point2D >.findPath().
abstract Number utilities.pathfinding.AStarPathFinder< T >.getHeuristicValue (T node, T destination) abstract
Gets the h(x) heuristic value from node to destination. If no heuristic is to be defined, then simply return 0 every time (becomes Djikstra's algorithm then). Heuristics must be positive. Heuristic functions must be consistent.
Parameters
node Node in question
destination Destination node
Returns
Heuristic value
Referenced by utilities.pathfinding.AStarPathFinder< Point2D >.findPath(), and utilities.pathfinding.AStarPathFinder< Point2D >.getAndCheckHeuristicValue().
boolean utilities.pathfinding.AStarPathFinder< T >.isDestination (T node, T destinationNode)
Indicates whether a node is the destination node. In most cases, this method should use the equals method specified in the generic type
Parameters
node Node in question
destinationNode Destination node
Returns
Whether the node is the destination node.
Implements utilities.pathfinding.IPathFinder< T >.
Definition at line 87 of file AStarPathFinder.java.
Referenced by utilities.pathfinding.AStarPathFinder< Point2D >.findPath().
boolean utilities.pathfinding.AStarPathFinder< T >.isPositive (Number number) private
Definition at line 152 of file AStarPathFinder.java.
Referenced by utilities.pathfinding.AStarPathFinder< Point2D >.getAndCheckCost(), and utilities.pathfinding.AStarPathFinder< Point2D >.getAndCheckHeuristicValue().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/pathfinding/AStarPathFinder.java