voogasalad_LosTorres: gameAuthoring.scenes.actorBuildingScenes.BuildingSceneMenu Class Reference
gameAuthoring.scenes.actorBuildingScenes.BuildingSceneMenu Class Reference
Public Member Functions
BuildingSceneMenu ()
MenuBar getNode ()
void addMenuItemToFileMenu (MenuItem item)
Private Member Functions
void handleClick ()
Private Attributes
MenuBar myMenuBar
Menu myFileMenu
Detailed Description
A menu to allow the user to go to the next scene.
Author
Austin Kyker
Definition at line 15 of file BuildingSceneMenu.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.actorBuildingScenes.BuildingSceneMenu.BuildingSceneMenu ()
Definition at line 20 of file BuildingSceneMenu.java.
References gameAuthoring.mainclasses.Constants.FILE, gameAuthoring.mainclasses.Constants.FINISHED, utilities.multilanguage.MultiLanguageUtility.getInstance(), and utilities.multilanguage.MultiLanguageUtility.getStringProperty().
Member Function Documentation
void gameAuthoring.scenes.actorBuildingScenes.BuildingSceneMenu.addMenuItemToFileMenu (MenuItem item)
Definition at line 42 of file BuildingSceneMenu.java.
Referenced by gameAuthoring.scenes.levelBuilding.LevelBuildingScene.createMenuAndAddNewLevelOption(), and gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.setupFileMenu().
MenuBar gameAuthoring.scenes.actorBuildingScenes.BuildingSceneMenu.getNode ()
Definition at line 38 of file BuildingSceneMenu.java.
References gameAuthoring.scenes.actorBuildingScenes.BuildingSceneMenu.myMenuBar.
Referenced by gameAuthoring.scenes.levelBuilding.LevelBuildingScene.createMenuAndAddNewLevelOption(), and gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.setupFileMenu().
void gameAuthoring.scenes.actorBuildingScenes.BuildingSceneMenu.handleClick () private
Definition at line 33 of file BuildingSceneMenu.java.
Member Data Documentation
Menu gameAuthoring.scenes.actorBuildingScenes.BuildingSceneMenu.myFileMenu private
Definition at line 18 of file BuildingSceneMenu.java.
MenuBar gameAuthoring.scenes.actorBuildingScenes.BuildingSceneMenu.myMenuBar private
Definition at line 17 of file BuildingSceneMenu.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.BuildingSceneMenu.getNode().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/actorBuildingScenes/BuildingSceneMenu.java