voogasalad_LosTorres: gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene Class Reference
gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene Class Reference abstract
Public Member Functions
ActorBuildingScene (BorderPane root, String title, String behaviorXMLFileLocation, String actorImageDirectory)
void update (Observable obs, Object arg1)
Public Member Functions inherited from gameAuthoring.scenes.BuildingScene
BuildingScene (BorderPane root, String title)
String getTitle ()
Scene getScene ()
Static Public Attributes
static final int ACTOR_IMG_HEIGHT = 150
static final int ACTOR_IMG_WIDTH = 150
Static Public Attributes inherited from gameAuthoring.scenes.BuildingScene
static final String STYLESHEET_PACKAGE = "./gameAuthoring/Stylesheets/"
Protected Member Functions
abstract void initializeActorsAndBuildActorDisplay ()
abstract HBox addRequiredNumericalTextFields ()
abstract void makeNewActor (Map< String, IBehavior > iBehaviorMap)
void clearFields ()
abstract void clearActorSpecificFields ()
abstract boolean actorSpecificFieldsValid ()
abstract void configureAndDisplayRightPane ()
abstract void finishBuildingActors ()
Protected Attributes
DragAndDropImagePane myDragAndDrop
TextField myActorNameField
String myActorImgPath
List< BehaviorBuilder > myBehaviorBuilders
SliderContainer myRangeSliderContainer
Protected Attributes inherited from gameAuthoring.scenes.BuildingScene
BorderPane myPane
Static Protected Attributes
static final String ADD_TOWER_IMG_PATH
static final int DRAG_AND_DROP_WIDTH = 550
Private Member Functions
void setupBehaviorBuilders (String behaviorXMLFileLocation)
void setupDragAndDropForActorImage ()
void setupFileMenu ()
void createCenterDisplay ()
VBox createActorNameTextField ()
void attemptToSaveActor ()
boolean fieldsAreValidForActiveCreation ()
boolean behaviorsValid ()
Private Attributes
String myActorImageDirectory
String myTitle
Static Private Attributes
static final String NAME = " Name"
static final int MAX_RANGE = 100
static final String DRAG_AND_DROP_CSS = "dragAndDrop"
Detailed Description
Class that is extended by EnemyBuildingScene and TowerBuildingScene. Creates a ListView of the created actors on the left side of the screen so that the user can easily create, edit, and remove them. Builds of the BehaviorBuilder components into a pane in the center of the screen. These JavaFX components allow the user the ability to specify the information that is needed to build the behavior objects that is necessary to ultimately build an actor. Finally a drag and drop file pane on the right side of the screen allows the user to input an image for the actor.
Author
Austin Kyker
Definition at line 42 of file ActorBuildingScene.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.ActorBuildingScene (BorderPane root, String title, String behaviorXMLFileLocation, String actorImageDirectory)
Definition at line 61 of file ActorBuildingScene.java.
References gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.createCenterDisplay(), gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.initializeActorsAndBuildActorDisplay(), gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.setupBehaviorBuilders(), gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.setupDragAndDropForActorImage(), and gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.setupFileMenu().
Member Function Documentation
abstract boolean gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.actorSpecificFieldsValid () abstract protected
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.fieldsAreValidForActiveCreation().
abstract HBox gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.addRequiredNumericalTextFields () abstract protected
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.createCenterDisplay().
void gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.attemptToSaveActor () private
Definition at line 141 of file ActorBuildingScene.java.
References gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorMapBuilder.buildMap(), gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.clearFields(), gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.fieldsAreValidForActiveCreation(), and gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.makeNewActor().
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.setupFileMenu().
boolean gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.behaviorsValid () private
Definition at line 174 of file ActorBuildingScene.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.fieldsAreValidForActiveCreation().
abstract void gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.clearActorSpecificFields () abstract protected
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.clearFields().
void gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.clearFields () protected
Definition at line 152 of file ActorBuildingScene.java.
References gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.clearActorSpecificFields(), utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.getPane(), gameAuthoring.scenes.BuildingScene.myPane, utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.reset(), and utilities.JavaFXutilities.slider.SliderContainer.resetSlider().
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.attemptToSaveActor(), and gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.handleAddUpgrade().
abstract void gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.configureAndDisplayRightPane () abstract protected
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.update().
VBox gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.createActorNameTextField () private
Definition at line 133 of file ActorBuildingScene.java.
References gameAuthoring.mainclasses.Constants.SMALLEST_PADDING.
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.createCenterDisplay().
void gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.createCenterDisplay () private
Definition at line 112 of file ActorBuildingScene.java.
References gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.addRequiredNumericalTextFields(), gameAuthoring.mainclasses.Constants.BEHAVIORS, gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.createActorNameTextField(), utilities.multilanguage.MultiLanguageUtility.getInstance(), utilities.multilanguage.MultiLanguageUtility.getStringProperty(), gameAuthoring.mainclasses.Constants.MED_PADDING, gameAuthoring.scenes.BuildingScene.myPane, and gameAuthoring.mainclasses.Constants.RANGE.
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.ActorBuildingScene().
boolean gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.fieldsAreValidForActiveCreation () private
Definition at line 167 of file ActorBuildingScene.java.
References gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.actorSpecificFieldsValid(), and gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.behaviorsValid().
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.attemptToSaveActor().
abstract void gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.finishBuildingActors () abstract protected
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.update().
abstract void gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.initializeActorsAndBuildActorDisplay () abstract protected
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.ActorBuildingScene().
abstract void gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.makeNewActor (Map< String, IBehavior > iBehaviorMap) abstract protected
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.attemptToSaveActor().
void gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.setupBehaviorBuilders (String behaviorXMLFileLocation) private
Definition at line 76 of file ActorBuildingScene.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.ActorBuildingScene().
void gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.setupDragAndDropForActorImage () private
Definition at line 87 of file ActorBuildingScene.java.
References utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.getPane(), gameAuthoring.scenes.BuildingScene.myPane, and gameAuthoring.mainclasses.AuthorController.SCREEN_HEIGHT.
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.ActorBuildingScene().
void gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.setupFileMenu () private
Definition at line 101 of file ActorBuildingScene.java.
References gameAuthoring.scenes.actorBuildingScenes.BuildingSceneMenu.addMenuItemToFileMenu(), gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.attemptToSaveActor(), utilities.multilanguage.MultiLanguageUtility.getInstance(), gameAuthoring.scenes.actorBuildingScenes.BuildingSceneMenu.getNode(), utilities.multilanguage.MultiLanguageUtility.getStringProperty(), gameAuthoring.scenes.BuildingScene.myPane, and gameAuthoring.mainclasses.Constants.SAVE_ACTORS.
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.ActorBuildingScene().
void gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.update (Observable obs, Object arg1)
Definition at line 183 of file ActorBuildingScene.java.
References gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.configureAndDisplayRightPane(), and gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.finishBuildingActors().
Member Data Documentation
final int gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.ACTOR_IMG_HEIGHT = 150 static
Definition at line 50 of file ActorBuildingScene.java.
final int gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.ACTOR_IMG_WIDTH = 150 static
Definition at line 51 of file ActorBuildingScene.java.
final String gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.ADD_TOWER_IMG_PATH static protected
Initial value:
=
            "./src/gameAuthoring/Resources/otherImages/addTower.png"
Definition at line 47 of file ActorBuildingScene.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.TowerUpgradeGroup.fetchImageViews().
final String gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.DRAG_AND_DROP_CSS = "dragAndDrop" static private
Definition at line 46 of file ActorBuildingScene.java.
final int gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.DRAG_AND_DROP_WIDTH = 550 static protected
Definition at line 49 of file ActorBuildingScene.java.
final int gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.MAX_RANGE = 100 static private
Definition at line 45 of file ActorBuildingScene.java.
String gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.myActorImageDirectory private
Definition at line 58 of file ActorBuildingScene.java.
String gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.myActorImgPath protected
Definition at line 55 of file ActorBuildingScene.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.makeNewActor(), and gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.makeNewActor().
TextField gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.myActorNameField protected
Definition at line 54 of file ActorBuildingScene.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.actorNamesAreUnique(), gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.isAllTowerNamesUnique(), gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.makeNewActor(), and gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.makeNewActor().
List<BehaviorBuilder> gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.myBehaviorBuilders protected
Definition at line 56 of file ActorBuildingScene.java.
DragAndDropImagePane gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.myDragAndDrop protected
Definition at line 53 of file ActorBuildingScene.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.configureAndDisplayRightPane().
SliderContainer gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.myRangeSliderContainer protected
Definition at line 57 of file ActorBuildingScene.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.makeNewActor(), and gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.makeNewActor().
String gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.myTitle private
Definition at line 59 of file ActorBuildingScene.java.
final String gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.NAME = " Name" static private
Definition at line 44 of file ActorBuildingScene.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/actorBuildingScenes/ActorBuildingScene.java