voogasalad_LosTorres: gameEngine.actors.ProjectileInfo Class Reference
gameEngine.actors.ProjectileInfo Class Reference
Public Member Functions
ProjectileInfo (String image, double damage, Map< String, IBehavior > map, List< String > types)
ProjectileInfo (String image, double damage, IBehavior move, List< IBehavior > list, List< String > types)
String getImage ()
List< IBehavior > getOnHit ()
List< String > getEnemiesTypes ()
BaseMovementBehavior getMove ()
double getMyDamage ()
void setMyDamage (double myDamage)
ProjectileInfo copy ()
Private Attributes
String myImage
IBehavior myMovement
List< IBehavior > myOnHitEffects
List< String > myEnemyTypes
double myDamage
Detailed Description
info class that defines projectiles
Definition at line 13 of file ProjectileInfo.java.
Constructor & Destructor Documentation
gameEngine.actors.ProjectileInfo.ProjectileInfo (String image, double damage, Map< String, IBehavior > map, List< String > types)
Definition at line 23 of file ProjectileInfo.java.
References gameEngine.actors.behaviors.IBehavior.copy().
Referenced by gameEngine.actors.ProjectileInfo.copy().
gameEngine.actors.ProjectileInfo.ProjectileInfo (String image, double damage, IBehavior move, List< IBehavior > list, List< String > types)
Definition at line 39 of file ProjectileInfo.java.
Member Function Documentation
ProjectileInfo gameEngine.actors.ProjectileInfo.copy ()
Definition at line 70 of file ProjectileInfo.java.
References gameEngine.actors.behaviors.IBehavior.copy(), gameEngine.actors.ProjectileInfo.myEnemyTypes, gameEngine.actors.ProjectileInfo.myOnHitEffects, and gameEngine.actors.ProjectileInfo.ProjectileInfo().
Referenced by gameEngine.actors.behaviors.RangeAttack.shootActorFromActor().
List<String> gameEngine.actors.ProjectileInfo.getEnemiesTypes ()
Definition at line 56 of file ProjectileInfo.java.
References gameEngine.actors.ProjectileInfo.myEnemyTypes.
Referenced by gameEngine.actors.behaviors.BaseDefendBehavior.checkTypes().
String gameEngine.actors.ProjectileInfo.getImage ()
Definition at line 48 of file ProjectileInfo.java.
References gameEngine.actors.ProjectileInfo.myImage.
Referenced by gameEngine.actors.BaseProjectile.BaseProjectile().
BaseMovementBehavior gameEngine.actors.ProjectileInfo.getMove ()
Definition at line 59 of file ProjectileInfo.java.
References gameEngine.actors.ProjectileInfo.myMovement.
Referenced by gameEngine.actors.BaseProjectile.BaseProjectile(), gameEngine.actors.behaviors.AoEAttack.performAttack(), and gameEngine.actors.behaviors.RangeAttack.shootActorFromActor().
double gameEngine.actors.ProjectileInfo.getMyDamage ()
Definition at line 63 of file ProjectileInfo.java.
References gameEngine.actors.ProjectileInfo.myDamage.
Referenced by gameEngine.actors.behaviors.PiercableDefense.handleBullet(), and gameEngine.actors.behaviors.SimpleDefense.handleBullet().
List<IBehavior> gameEngine.actors.ProjectileInfo.getOnHit ()
Definition at line 52 of file ProjectileInfo.java.
References gameEngine.actors.ProjectileInfo.myOnHitEffects.
Referenced by gameEngine.actors.behaviors.BaseDefendBehavior.gotHit().
void gameEngine.actors.ProjectileInfo.setMyDamage (double myDamage)
Definition at line 67 of file ProjectileInfo.java.
References gameEngine.actors.ProjectileInfo.myDamage.
Referenced by gameEngine.actors.behaviors.PiercableDefense.handleBullet().
Member Data Documentation
double gameEngine.actors.ProjectileInfo.myDamage private
Definition at line 19 of file ProjectileInfo.java.
Referenced by gameEngine.actors.ProjectileInfo.getMyDamage(), and gameEngine.actors.ProjectileInfo.setMyDamage().
List<String> gameEngine.actors.ProjectileInfo.myEnemyTypes private
Definition at line 18 of file ProjectileInfo.java.
Referenced by gameEngine.actors.ProjectileInfo.copy(), and gameEngine.actors.ProjectileInfo.getEnemiesTypes().
String gameEngine.actors.ProjectileInfo.myImage private
Definition at line 15 of file ProjectileInfo.java.
Referenced by gameEngine.actors.ProjectileInfo.getImage().
IBehavior gameEngine.actors.ProjectileInfo.myMovement private
Definition at line 16 of file ProjectileInfo.java.
Referenced by gameEngine.actors.ProjectileInfo.getMove().
List<IBehavior> gameEngine.actors.ProjectileInfo.myOnHitEffects private
Definition at line 17 of file ProjectileInfo.java.
Referenced by gameEngine.actors.ProjectileInfo.copy(), and gameEngine.actors.ProjectileInfo.getOnHit().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/ProjectileInfo.java