voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute Class Reference
gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute Class Reference
Public Member Functions
PathRoute ()
Iterator< PathComponent > iterator ()
void setStartingLocation (PathStartingLocation loc)
void setEndingLocation (PathEndingLocation loc)
void add (PathComponent componentToAdd)
PathComponent getFirst ()
PathComponent getLast ()
void addAll (PathRoute connectedComponent)
List< PathComponent > getComponents ()
boolean isNotConnectedToStartOrEndLocations ()
boolean isConnectedToStartAndEndLocations ()
boolean isConnectedToStartingLocation ()
boolean isConnectToEndingLocation ()
PathRoute getComponentsBefore (PathComponent component)
Private Attributes
PathStartingLocation myStartingLocation
PathEndingLocation myEndingLocation
List< PathComponent > myConnectedComponent
Detailed Description
Defines a route that has a starting location and an ending location as well as a list of path components that connect these locations.
Author
Austin Kyker
Definition at line 17 of file PathRoute.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.PathRoute ()
Definition at line 23 of file PathRoute.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.getComponentsBefore().
Member Function Documentation
void gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.add (PathComponent componentToAdd)
Definition at line 40 of file PathRoute.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.createNewRoute(), gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.getComponentsBefore(), and gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testBackendRouteCreation().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.addAll (PathRoute connectedComponent)
Definition at line 52 of file PathRoute.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.connectRoutes().
List<PathComponent> gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.getComponents ()
Definition at line 58 of file PathRoute.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.myConnectedComponent.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.attemptToConnectRoutes(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.deleteSelectedComponent(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.isComponentInPreviouslySelectedComponent().
PathRoute gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.getComponentsBefore (PathComponent component)
Definition at line 78 of file PathRoute.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.add(), gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.PathRoute(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.setStartingLocation().
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.attemptToConnectRoutes().
PathComponent gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.getFirst ()
Definition at line 44 of file PathRoute.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.attemptToConnectRoutes(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.connectRoutes().
PathComponent gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.getLast ()
Definition at line 48 of file PathRoute.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.attemptToConnectRoutes(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.connectRoutes().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.isConnectedToStartAndEndLocations ()
Definition at line 66 of file PathRoute.java.
boolean gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.isConnectedToStartingLocation ()
Definition at line 70 of file PathRoute.java.
boolean gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.isConnectToEndingLocation ()
Definition at line 74 of file PathRoute.java.
boolean gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.isNotConnectedToStartOrEndLocations ()
Definition at line 62 of file PathRoute.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.moveConnectedComponent().
Iterator<PathComponent> gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.iterator ()
Definition at line 28 of file PathRoute.java.
void gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.setEndingLocation (PathEndingLocation loc)
Definition at line 36 of file PathRoute.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.tryToAddConnectComponentToEndingLocation().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.setStartingLocation (PathStartingLocation loc)
Definition at line 32 of file PathRoute.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.componentAddedToStartingLocation(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.getComponentsBefore().
Member Data Documentation
List<PathComponent> gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.myConnectedComponent private
Definition at line 21 of file PathRoute.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.getComponents().
PathEndingLocation gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.myEndingLocation private
Definition at line 19 of file PathRoute.java.
PathStartingLocation gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.myStartingLocation private
Definition at line 18 of file PathRoute.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/pathComponents/PathRoute.java