voogasalad_LosTorres: gamePlayer.guiItems.gameWorld.GameWorld Class Reference
gamePlayer.guiItems.gameWorld.GameWorld Class Reference
Public Member Functions
GameWorld ()
void initialize (Dimension2D containerSize)
Node getNode ()
Pane getMap ()
void setBackground (String imagePath)
void addEngineGroup (Group myEngineGroup)
Package Attributes
Pane myMap
GameWorldListener myListener
Additional Inherited Members
Static Public Attributes inherited from gamePlayer.guiItems.GuiItem
static String myPropertiesPath = "guiItems/"
Detailed Description
Author
Greg Lyons
    GameWorld serves as the background in which the animation and
    interaction of all of the actors takes place.
Definition at line 23 of file GameWorld.java.
Constructor & Destructor Documentation
gamePlayer.guiItems.gameWorld.GameWorld.GameWorld ()
Definition at line 28 of file GameWorld.java.
References gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_MANAGER.
Member Function Documentation
void gamePlayer.guiItems.gameWorld.GameWorld.addEngineGroup (Group myEngineGroup)
Definition at line 55 of file GameWorld.java.
Pane gamePlayer.guiItems.gameWorld.GameWorld.getMap ()
Definition at line 44 of file GameWorld.java.
References gamePlayer.guiItems.gameWorld.GameWorld.myMap.
Referenced by gamePlayer.mainClasses.managers.GuiManager.deselectTower(), gamePlayer.mainClasses.managers.GuiManager.endGame(), gamePlayer.mainClasses.managers.GuiManager.escapePlace(), gamePlayer.mainClasses.managers.GuiManager.placeTower(), gamePlayer.mainClasses.managers.GuiManager.selectTower(), gamePlayer.mainClasses.managers.GuiManager.sellTower(), gamePlayer.mainClasses.managers.GuiManager.startGame(), gamePlayer.mainClasses.managers.GuiManager.startMultiPlayerGame(), and gamePlayer.mainClasses.managers.GuiManager.startSinglePlayerGame().
Node gamePlayer.guiItems.gameWorld.GameWorld.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 40 of file GameWorld.java.
References gamePlayer.guiItems.gameWorld.GameWorld.myMap.
void gamePlayer.guiItems.gameWorld.GameWorld.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 34 of file GameWorld.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.DRAW_SCREEN_WIDTH, gamePlayer.guiItemsListeners.GameWorldListener.registerGameWorld(), and gameAuthoring.mainclasses.AuthorController.SCREEN_HEIGHT.
void gamePlayer.guiItems.gameWorld.GameWorld.setBackground (String imagePath)
Definition at line 48 of file GameWorld.java.
References utilities.JavaFXutilities.imageView.StringToImageViewConverter.getImageView().
Referenced by gamePlayer.mainClasses.managers.GuiManager.addBackground().
Member Data Documentation
GameWorldListener gamePlayer.guiItems.gameWorld.GameWorld.myListener package
Definition at line 26 of file GameWorld.java.
Pane gamePlayer.guiItems.gameWorld.GameWorld.myMap package
Definition at line 25 of file GameWorld.java.
Referenced by gamePlayer.guiItems.gameWorld.GameWorld.getMap(), and gamePlayer.guiItems.gameWorld.GameWorld.getNode().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItems/gameWorld/GameWorld.java