voogasalad_LosTorres: gameEngine.tests.BehaviorTester Class Reference
gameEngine.tests.BehaviorTester Class Reference
Public Member Functions
void setup ()
void testMovementBehaviorSimple ()
void testMovementBehaviorSimple2 ()
Private Member Functions
BaseActor createActor (Map< String, IBehavior > move)
void updateAndCheck (BaseActor actor, double x, double y)
Private Attributes
List< BackendRoute > myOptions
Static Private Attributes
static final double EPSILON = 0.00000001
Detailed Description
Definition at line 18 of file BehaviorTester.java.
Member Function Documentation
BaseActor gameEngine.tests.BehaviorTester.createActor (Map< String, IBehavior > move) private
Definition at line 60 of file BehaviorTester.java.
Referenced by gameEngine.tests.BehaviorTester.testMovementBehaviorSimple(), and gameEngine.tests.BehaviorTester.testMovementBehaviorSimple2().
void gameEngine.tests.BehaviorTester.setup ()
Definition at line 24 of file BehaviorTester.java.
void gameEngine.tests.BehaviorTester.testMovementBehaviorSimple ()
Definition at line 31 of file BehaviorTester.java.
References gameEngine.tests.BehaviorTester.createActor(), gameEngine.actors.BaseActor.update(), and gameEngine.tests.BehaviorTester.updateAndCheck().
void gameEngine.tests.BehaviorTester.testMovementBehaviorSimple2 ()
Definition at line 47 of file BehaviorTester.java.
References gameEngine.tests.BehaviorTester.createActor(), gameEngine.actors.BaseActor.update(), and gameEngine.tests.BehaviorTester.updateAndCheck().
void gameEngine.tests.BehaviorTester.updateAndCheck (BaseActor actor, double x, double y) private
Definition at line 64 of file BehaviorTester.java.
References gameEngine.tests.BehaviorTester.EPSILON, gameEngine.actors.BaseActor.getX(), gameEngine.actors.BaseActor.getY(), and gameEngine.actors.BaseActor.update().
Referenced by gameEngine.tests.BehaviorTester.testMovementBehaviorSimple(), and gameEngine.tests.BehaviorTester.testMovementBehaviorSimple2().
Member Data Documentation
final double gameEngine.tests.BehaviorTester.EPSILON = 0.00000001 static private
Definition at line 21 of file BehaviorTester.java.
Referenced by gameEngine.tests.BehaviorTester.updateAndCheck().
List<BackendRoute> gameEngine.tests.BehaviorTester.myOptions private
Definition at line 20 of file BehaviorTester.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/tests/BehaviorTester.java