voogasalad_LosTorres: gamePlayer.guiItems.welcome.GameChooser Class Reference
gamePlayer.guiItems.welcome.GameChooser Class Reference
Public Member Functions
GameChooser (String directory)
void initialize (Dimension2D containerSize)
Node getNode ()
Private Member Functions
void loadGameDescriptions (String directory)
Private Attributes
VBox myBox
Additional Inherited Members
Static Public Attributes inherited from gamePlayer.guiItems.GuiItem
static String myPropertiesPath = "guiItems/"
Detailed Description
Definition at line 10 of file GameChooser.java.
Constructor & Destructor Documentation
gamePlayer.guiItems.welcome.GameChooser.GameChooser (String directory)
Definition at line 14 of file GameChooser.java.
References gamePlayer.guiItems.welcome.GameChooser.loadGameDescriptions().
Member Function Documentation
Node gamePlayer.guiItems.welcome.GameChooser.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 34 of file GameChooser.java.
References gamePlayer.guiItems.welcome.GameChooser.myBox.
void gamePlayer.guiItems.welcome.GameChooser.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 28 of file GameChooser.java.
void gamePlayer.guiItems.welcome.GameChooser.loadGameDescriptions (String directory) private
Definition at line 22 of file GameChooser.java.
References gamePlayer.mainClasses.welcomeScreen.availableGames.GameDescriptionLoader.getDescriptions().
Referenced by gamePlayer.guiItems.welcome.GameChooser.GameChooser().
Member Data Documentation
VBox gamePlayer.guiItems.welcome.GameChooser.myBox private
Definition at line 12 of file GameChooser.java.
Referenced by gamePlayer.guiItems.welcome.GameChooser.getNode().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItems/welcome/GameChooser.java