voogasalad_LosTorres: gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore Class Reference
gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore Class Reference
Public Member Functions
UpgradeStore (String towerID)
void initialize (Dimension2D containerSize)
Node getNode ()
Package Attributes
String myIconPath
XMLParser myUpgrade1Parser
XMLParser myUpgrade2Parser
VBox myButtons
Private Member Functions
void buildButtons (double width, double height)
void buildIcon (double width, double height)
void buildHeader (double width, double height)
Private Attributes
int[] upgradeLevel = new int[]{3,2}
String myTowerID
XMLParser myStoreParser
ResourceBundle myTowerResources
VBox root
Label myHeader
ImageView myIcon
Additional Inherited Members
Static Public Attributes inherited from gamePlayer.guiItems.GuiItem
static String myPropertiesPath = "guiItems/"
Detailed Description
Panel that will show up in place of the store when a tower on the map is selected. The switching behavior is handled by the Store class
Author
brianbolze
Definition at line 26 of file UpgradeStore.java.
Constructor & Destructor Documentation
gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.UpgradeStore (String towerID)
Definition at line 37 of file UpgradeStore.java.
Member Function Documentation
void gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.buildButtons (double width, double height) private
Definition at line 71 of file UpgradeStore.java.
References utilities.XMLParsing.XMLParser.getDoubleValuesFromTag(), and utilities.XMLParsing.XMLParser.getValuesFromTag().
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.initialize().
void gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.buildHeader (double width, double height) private
Definition at line 105 of file UpgradeStore.java.
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.initialize().
void gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.buildIcon (double width, double height) private
Definition at line 91 of file UpgradeStore.java.
References utilities.XMLParsing.XMLParser.getValuesFromTag().
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.initialize().
Node gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 114 of file UpgradeStore.java.
References gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.root.
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.store.Store.selectTower().
void gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 49 of file UpgradeStore.java.
References gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.buildButtons(), gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.buildHeader(), gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.buildIcon(), utilities.XMLParsing.XMLParser.getDoubleValuesFromTag(), and gamePlayer.guiItems.GuiItem.myPropertiesPath.
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.store.Store.selectTower().
Member Data Documentation
VBox gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.myButtons package
Definition at line 33 of file UpgradeStore.java.
Label gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.myHeader private
Definition at line 34 of file UpgradeStore.java.
ImageView gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.myIcon private
Definition at line 35 of file UpgradeStore.java.
String gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.myIconPath package
Definition at line 29 of file UpgradeStore.java.
XMLParser gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.myStoreParser private
Definition at line 30 of file UpgradeStore.java.
String gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.myTowerID private
Definition at line 29 of file UpgradeStore.java.
ResourceBundle gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.myTowerResources private
Definition at line 31 of file UpgradeStore.java.
XMLParser gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.myUpgrade1Parser package
Definition at line 30 of file UpgradeStore.java.
XMLParser gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.myUpgrade2Parser package
Definition at line 30 of file UpgradeStore.java.
VBox gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.root private
Definition at line 33 of file UpgradeStore.java.
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.getNode().
int [] gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.upgradeLevel = new int[]{3,2} private
Definition at line 28 of file UpgradeStore.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/unusedCodeWarehouse/guiItems/store/UpgradeStore.java