voogasalad_LosTorres: gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene Class Reference
gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene Class Reference
Public Member Functions
TowerBuildingScene (BorderPane root, ITowerConfiguring controller)
boolean actorSpecificFieldsValid ()
Public Member Functions inherited from gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene
ActorBuildingScene (BorderPane root, String title, String behaviorXMLFileLocation, String actorImageDirectory)
void update (Observable obs, Object arg1)
Public Member Functions inherited from gameAuthoring.scenes.BuildingScene
BuildingScene (BorderPane root, String title)
String getTitle ()
Scene getScene ()
Protected Member Functions
void configureAndDisplayRightPane ()
void makeNewActor (Map< String, IBehavior > iBehaviorMap)
void finishBuildingActors ()
void initializeActorsAndBuildActorDisplay ()
HBox addRequiredNumericalTextFields ()
void clearActorSpecificFields ()
Protected Member Functions inherited from gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene
abstract void initializeActorsAndBuildActorDisplay ()
abstract HBox addRequiredNumericalTextFields ()
abstract void makeNewActor (Map< String, IBehavior > iBehaviorMap)
void clearFields ()
abstract void clearActorSpecificFields ()
abstract boolean actorSpecificFieldsValid ()
abstract void configureAndDisplayRightPane ()
abstract void finishBuildingActors ()
Static Protected Attributes
static final int NUM_UPGRADES_POSSIBLE = 3
Static Protected Attributes inherited from gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene
static final String ADD_TOWER_IMG_PATH
static final int DRAG_AND_DROP_WIDTH = 550
Private Member Functions
void setupEnemyTowerCanShootSelection ()
void redrawTowerDisplay ()
void handleAddUpgrade (TowerUpgradeGroup groupSelected)
boolean isAllTowerNamesUnique ()
Private Attributes
List< BaseEnemy > myEnemiesTowerCanShoot
ProjectilePane myProjectilePane
List< TowerUpgradeGroup > myTowerUpgradeGroups
EnemySelectionDisplay myEnemySelectionView
TilePane myTilePane
TowerUpgradeGroup myCurrentlySelectedTowerGroup
ITowerConfiguring myTowerConfiguringController
LabeledNumericalTextField myBuildCostField
LabeledNumericalTextField mySellValueField
Static Private Attributes
static final int TILE_PANE_WIDTH = 340
static final String SELL = "Sell"
static final String COST = "Cost"
static final double ENEMY_DISPLAY_HEIGHT = 110
static final double DRAG_AND_DROP_HEIGHT = 300
static final String TITLE = "Tower"
static final String IMG_DIR = AuthorController.gameDir + "/towerImages/"
static final String BEHAVIOR_XML_LOC
static final double FIELD_WIDTH = 50
Additional Inherited Members
Static Public Attributes inherited from gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene
static final int ACTOR_IMG_HEIGHT = 150
static final int ACTOR_IMG_WIDTH = 150
Static Public Attributes inherited from gameAuthoring.scenes.BuildingScene
static final String STYLESHEET_PACKAGE = "./gameAuthoring/Stylesheets/"
Protected Attributes inherited from gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene
DragAndDropImagePane myDragAndDrop
TextField myActorNameField
String myActorImgPath
List< BehaviorBuilder > myBehaviorBuilders
SliderContainer myRangeSliderContainer
Protected Attributes inherited from gameAuthoring.scenes.BuildingScene
BorderPane myPane
Detailed Description
Scene to build a new tower.
Author
Austin Kyker
Definition at line 33 of file TowerBuildingScene.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.TowerBuildingScene (BorderPane root, ITowerConfiguring controller)
Definition at line 57 of file TowerBuildingScene.java.
Member Function Documentation
boolean gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.actorSpecificFieldsValid ()
Definition at line 168 of file TowerBuildingScene.java.
References gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.isAllTowerNamesUnique(), gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.isInfoValid(), utilities.JavaFXutilities.numericalTextFields.LabeledNumericalTextField.isValueEntered(), gameAuthoring.mainclasses.Constants.NO_ENEMY_TOWER_CAN_SHOOT, and gameAuthoring.mainclasses.Constants.UNIQUE_NAMES_ERROR.
HBox gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.addRequiredNumericalTextFields () protected
Definition at line 159 of file TowerBuildingScene.java.
References gameAuthoring.mainclasses.Constants.SM_PADDING.
void gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.clearActorSpecificFields () protected
Definition at line 194 of file TowerBuildingScene.java.
References utilities.JavaFXutilities.numericalTextFields.LabeledNumericalTextField.clearField().
void gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.configureAndDisplayRightPane () protected
Adds to the bottom of the right pane, a list view all of all possible enemies so the user can select the enemies that the tower can attack. Enemies that are not selected will be immune to the projectiles of the tower.
Definition at line 68 of file TowerBuildingScene.java.
References gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.getNode(), utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.getPane(), gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.myDragAndDrop, gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.myEnemySelectionView, gameAuthoring.scenes.BuildingScene.myPane, utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane.setHeight(), and gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.setupEnemyTowerCanShootSelection().
void gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.finishBuildingActors () protected
Definition at line 139 of file TowerBuildingScene.java.
References gameAuthoring.mainclasses.controllerInterfaces.ITowerConfiguring.configureTowers().
void gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.handleAddUpgrade (TowerUpgradeGroup groupSelected) private
Definition at line 133 of file TowerBuildingScene.java.
References gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.clearFields().
Referenced by gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.redrawTowerDisplay().
void gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.initializeActorsAndBuildActorDisplay () protected
Definition at line 144 of file TowerBuildingScene.java.
References gameAuthoring.scenes.BuildingScene.myPane, gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.redrawTowerDisplay(), gameAuthoring.mainclasses.Constants.SM_PADDING, and gameAuthoring.mainclasses.Constants.SMALLEST_PADDING.
boolean gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.isAllTowerNamesUnique () private
Ensures all tower names are unique.
Definition at line 184 of file TowerBuildingScene.java.
References gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.myActorNameField.
Referenced by gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.actorSpecificFieldsValid().
void gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.makeNewActor (Map< String, IBehavior > iBehaviorMap) protected
Definition at line 97 of file TowerBuildingScene.java.
References gameAuthoring.scenes.actorBuildingScenes.TowerUpgradeGroup.addTower(), utilities.JavaFXutilities.numericalTextFields.LabeledNumericalTextField.getNumberEntered(), utilities.JavaFXutilities.slider.SliderContainer.getSliderValue(), gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.makeProjectileInfo(), gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.myActorImgPath, gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.myActorNameField, gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.myRangeSliderContainer, and gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.redrawTowerDisplay().
void gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.redrawTowerDisplay () private
Definition at line 116 of file TowerBuildingScene.java.
References gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.handleAddUpgrade().
Referenced by gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.initializeActorsAndBuildActorDisplay(), and gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.makeNewActor().
void gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.setupEnemyTowerCanShootSelection () private
Definition at line 80 of file TowerBuildingScene.java.
References gameAuthoring.mainclasses.controllerInterfaces.ITowerConfiguring.fetchEnemies().
Referenced by gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.configureAndDisplayRightPane().
Member Data Documentation
final String gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.BEHAVIOR_XML_LOC static private
Initial value:
=
            "./src/gameAuthoring/Resources/actorBehaviors/TowerBehaviors.xml"
Definition at line 42 of file TowerBuildingScene.java.
final String gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.COST = "Cost" static private
Definition at line 37 of file TowerBuildingScene.java.
final double gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.DRAG_AND_DROP_HEIGHT = 300 static private
Definition at line 39 of file TowerBuildingScene.java.
final double gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.ENEMY_DISPLAY_HEIGHT = 110 static private
Definition at line 38 of file TowerBuildingScene.java.
final double gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.FIELD_WIDTH = 50 static private
Definition at line 44 of file TowerBuildingScene.java.
final String gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.IMG_DIR = AuthorController.gameDir + "/towerImages/" static private
Definition at line 41 of file TowerBuildingScene.java.
LabeledNumericalTextField gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.myBuildCostField private
Definition at line 54 of file TowerBuildingScene.java.
TowerUpgradeGroup gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.myCurrentlySelectedTowerGroup private
Definition at line 52 of file TowerBuildingScene.java.
List<BaseEnemy> gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.myEnemiesTowerCanShoot private
Definition at line 47 of file TowerBuildingScene.java.
EnemySelectionDisplay gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.myEnemySelectionView private
Definition at line 50 of file TowerBuildingScene.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.configureAndDisplayRightPane().
ProjectilePane gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.myProjectilePane private
Definition at line 48 of file TowerBuildingScene.java.
LabeledNumericalTextField gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.mySellValueField private
Definition at line 55 of file TowerBuildingScene.java.
TilePane gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.myTilePane private
Definition at line 51 of file TowerBuildingScene.java.
ITowerConfiguring gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.myTowerConfiguringController private
Definition at line 53 of file TowerBuildingScene.java.
List<TowerUpgradeGroup> gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.myTowerUpgradeGroups private
Definition at line 49 of file TowerBuildingScene.java.
final int gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.NUM_UPGRADES_POSSIBLE = 3 static protected
Definition at line 45 of file TowerBuildingScene.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.TowerUpgradeGroup.TowerUpgradeGroup().
final String gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.SELL = "Sell" static private
Definition at line 36 of file TowerBuildingScene.java.
final int gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.TILE_PANE_WIDTH = 340 static private
Definition at line 35 of file TowerBuildingScene.java.
final String gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.TITLE = "Tower" static private
Definition at line 40 of file TowerBuildingScene.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/actorBuildingScenes/TowerBuildingScene.java