voogasalad_LosTorres: gameEngine.CoOpManager Class Reference
gameEngine.CoOpManager Class Reference
Public Member Functions
CoOpManager ()
void startNewGame (String directory)
boolean isReady ()
DoubleProperty getTimer ()
boolean joinGame ()
String initializeGame (Pane engineGroup)
void changeRunSpeed (double d)
void removeTower (ImageView node)
ImageView addTower (String name, double x, double y)
Public Member Functions inherited from gameEngine.MainEngineManager
MainEngineManager ()
void setEarthquakeMagnitude (double magnitude)
double getEarthquakeMagnitude ()
GridPane getReferencePane ()
TowerTileGrid getExistingTowerTiles ()
MainEngineManager (Pane engineGroup)
double getMyGold ()
DoubleProperty getGoldProperty ()
void setMyGold (double value)
double getMyHealth ()
DoubleProperty getHealthProperty ()
void setMyHealth (double value)
void revertToOriginalSpeed ()
void changeRunSpeed (double magnitude)
String getTowerName (ImageView node)
void removeTower (ImageView node)
ImageView addTower (String identifier, double x, double y)
List< BaseActor > getRequiredActors (BaseActor actor, Class<?extends BaseActor > infoType)
boolean checkNewPath ()
void pause ()
void resume ()
Collection< TowerInfoObject > getAllTowerTypeInformation ()
void initializeGame (String directory)
boolean validateTower (double x, double y)
boolean checkGold (TowerInfoObject towerInfoObject)
void loadTowers (String directory)
SimpleDoubleProperty getWinStatus ()
SimpleDoubleProperty getCurrentLevelProperty ()
void loadLevel (BaseLevel level)
boolean isRunning ()
void loadAuthoringLevel (BaseLevel level)
void update (Observable o, Object arg)
void saveState (String directory, String fileName)
void clear ()
void loadState (String gameFile)
ImageView upgrade (ImageView n, String name)
void sellTower (ImageView n)
Protected Member Functions
void onLevelEnd ()
Protected Member Functions inherited from gameEngine.MainEngineManager
void addGroups (Pane engineGroup)
void onLevelEnd ()
Private Member Functions
void allowInteraction ()
void startLevel ()
void writeTowersToServer ()
String convertTowersToString ()
void getTowersFromServer ()
void addTower (DataWrapper wrapper)
Private Attributes
DoubleProperty myTimer
String myDirectory
Static Private Attributes
static final int FADE_DURATION = 2
static final String GET_PLAYERS = "get_num_players"
static final String GET_MASTER_JSON = "get_master_json"
static final String UPDATE_MASTER_JSON = "update_master_json"
static final String MASTER_JSON = "master_json="
static final String GAME_DIRECTORY = "game_directory="
static final String MAKE_GAME = "make_game"
static final String SERVER_URL = "https://voogasalad.herokuapp.com/"
static final String JOIN_GAME = "join_game"
static final int REQUIRED_NUM_PLAYERS = 2
static final HTTPConnection HTTP_CONNECTOR = new HTTPConnection(SERVER_URL)
static final int TIMER_END = 15
static final double QUERY_SERVER_TIME = 1.0
Additional Inherited Members
Protected Attributes inherited from gameEngine.MainEngineManager
RangeRestrictedCollection< BaseTower > myTowerGroup
GSONFileReader myFileReader
GSONFileWriter myFileWriter
Detailed Description
Definition at line 19 of file CoOpManager.java.
Constructor & Destructor Documentation
gameEngine.CoOpManager.CoOpManager ()
Definition at line 37 of file CoOpManager.java.
Member Function Documentation
void gameEngine.CoOpManager.addTower (DataWrapper wrapper) private
Definition at line 126 of file CoOpManager.java.
References utilities.GSON.objectWrappers.DataWrapper.getName(), utilities.GSON.objectWrappers.DataWrapper.getX(), and utilities.GSON.objectWrappers.DataWrapper.getY().
Referenced by gameEngine.CoOpManager.getTowersFromServer().
ImageView gameEngine.CoOpManager.addTower (String name, double x, double y)
Definition at line 143 of file CoOpManager.java.
References gameEngine.CoOpManager.getTowersFromServer(), and gameEngine.CoOpManager.writeTowersToServer().
void gameEngine.CoOpManager.allowInteraction () private
Definition at line 69 of file CoOpManager.java.
References gameEngine.CoOpManager.getTowersFromServer(), and gameEngine.CoOpManager.startLevel().
Referenced by gameEngine.CoOpManager.initializeGame(), and gameEngine.CoOpManager.onLevelEnd().
void gameEngine.CoOpManager.changeRunSpeed (double d)
Definition at line 80 of file CoOpManager.java.
String gameEngine.CoOpManager.convertTowersToString () private
Definition at line 100 of file CoOpManager.java.
References utilities.GSON.GSONFileWriter.convertWrappersToJson(), gameEngine.MainEngineManager.myFileWriter, and gameEngine.MainEngineManager.myTowerGroup.
Referenced by gameEngine.CoOpManager.writeTowersToServer().
DoubleProperty gameEngine.CoOpManager.getTimer ()
Definition at line 52 of file CoOpManager.java.
References gameEngine.CoOpManager.myTimer.
Referenced by gamePlayer.mainClasses.managers.GuiManager.startMultiPlayerGame().
void gameEngine.CoOpManager.getTowersFromServer () private
Definition at line 108 of file CoOpManager.java.
References gameEngine.CoOpManager.addTower(), gameEngine.MainEngineManager.myFileReader, gameEngine.MainEngineManager.myTowerGroup, gameEngine.CoOpManager.QUERY_SERVER_TIME, utilities.GSON.GSONFileReader.readWrappers(), and utilities.networking.HTTPConnection.sendGet().
Referenced by gameEngine.CoOpManager.addTower(), gameEngine.CoOpManager.allowInteraction(), gameEngine.CoOpManager.removeTower(), and gameEngine.CoOpManager.startLevel().
String gameEngine.CoOpManager.initializeGame (Pane engineGroup)
Definition at line 61 of file CoOpManager.java.
References gameEngine.MainEngineManager.addGroups(), gameEngine.CoOpManager.allowInteraction(), and gameEngine.CoOpManager.myDirectory.
Referenced by gamePlayer.mainClasses.managers.GuiManager.startMultiPlayerGame().
boolean gameEngine.CoOpManager.isReady ()
Definition at line 48 of file CoOpManager.java.
References utilities.networking.HTTPConnection.sendGet().
Referenced by gamePlayer.mainClasses.managers.GuiManager.multiPlayerGameIsReady().
boolean gameEngine.CoOpManager.joinGame ()
Definition at line 56 of file CoOpManager.java.
References utilities.networking.HTTPConnection.sendPost().
Referenced by gamePlayer.mainClasses.managers.GuiManager.joinMultiPlayerGame().
void gameEngine.CoOpManager.onLevelEnd () protected
Definition at line 91 of file CoOpManager.java.
References gameEngine.CoOpManager.allowInteraction().
void gameEngine.CoOpManager.removeTower (ImageView node)
Definition at line 135 of file CoOpManager.java.
References gameEngine.CoOpManager.getTowersFromServer(), and gameEngine.CoOpManager.writeTowersToServer().
void gameEngine.CoOpManager.startLevel () private
Definition at line 84 of file CoOpManager.java.
References gameEngine.CoOpManager.getTowersFromServer().
Referenced by gameEngine.CoOpManager.allowInteraction().
void gameEngine.CoOpManager.startNewGame (String directory)
Definition at line 43 of file CoOpManager.java.
References utilities.networking.HTTPConnection.sendPost().
Referenced by gamePlayer.mainClasses.managers.GuiManager.prepareMultiPlayerGame().
void gameEngine.CoOpManager.writeTowersToServer () private
Definition at line 96 of file CoOpManager.java.
References gameEngine.CoOpManager.convertTowersToString(), and utilities.networking.HTTPConnection.sendPost().
Referenced by gameEngine.CoOpManager.addTower(), and gameEngine.CoOpManager.removeTower().
Member Data Documentation
final int gameEngine.CoOpManager.FADE_DURATION = 2 static private
Definition at line 21 of file CoOpManager.java.
final String gameEngine.CoOpManager.GAME_DIRECTORY = "game_directory=" static private
Definition at line 26 of file CoOpManager.java.
final String gameEngine.CoOpManager.GET_MASTER_JSON = "get_master_json" static private
Definition at line 23 of file CoOpManager.java.
final String gameEngine.CoOpManager.GET_PLAYERS = "get_num_players" static private
Definition at line 22 of file CoOpManager.java.
final HTTPConnection gameEngine.CoOpManager.HTTP_CONNECTOR = new HTTPConnection(SERVER_URL) static private
Definition at line 31 of file CoOpManager.java.
final String gameEngine.CoOpManager.JOIN_GAME = "join_game" static private
Definition at line 29 of file CoOpManager.java.
final String gameEngine.CoOpManager.MAKE_GAME = "make_game" static private
Definition at line 27 of file CoOpManager.java.
final String gameEngine.CoOpManager.MASTER_JSON = "master_json=" static private
Definition at line 25 of file CoOpManager.java.
String gameEngine.CoOpManager.myDirectory private
Definition at line 35 of file CoOpManager.java.
Referenced by gameEngine.CoOpManager.initializeGame().
DoubleProperty gameEngine.CoOpManager.myTimer private
Definition at line 34 of file CoOpManager.java.
Referenced by gameEngine.CoOpManager.getTimer().
final double gameEngine.CoOpManager.QUERY_SERVER_TIME = 1.0 static private
Definition at line 33 of file CoOpManager.java.
Referenced by gameEngine.CoOpManager.getTowersFromServer().
final int gameEngine.CoOpManager.REQUIRED_NUM_PLAYERS = 2 static private
Definition at line 30 of file CoOpManager.java.
final String gameEngine.CoOpManager.SERVER_URL = "https://voogasalad.herokuapp.com/" static private
Definition at line 28 of file CoOpManager.java.
final int gameEngine.CoOpManager.TIMER_END = 15 static private
Definition at line 32 of file CoOpManager.java.
final String gameEngine.CoOpManager.UPDATE_MASTER_JSON = "update_master_json" static private
Definition at line 24 of file CoOpManager.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/CoOpManager.java