voogasalad_LosTorres: gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health Class Reference
gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health Class Reference
Public Member Functions
Health ()
void initialize (Dimension2D containerSize)
Node getNode ()
Private Member Functions
void makeHeartImage ()
void makeHealthBar ()
Private Attributes
XMLParser myParser
Dimension2D mySize
Dimension2D imageSize
ImageView myHeart
ProgressBar myHealthBar
DoubleProperty healthRemaining
Additional Inherited Members
Static Public Attributes inherited from gamePlayer.guiItems.GuiItem
static String myPropertiesPath = "guiItems/"
Detailed Description
Definition at line 17 of file Health.java.
Constructor & Destructor Documentation
gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.Health ()
Definition at line 29 of file Health.java.
Member Function Documentation
Node gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 48 of file Health.java.
void gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 34 of file Health.java.
References utilities.XMLParsing.XMLParser.getDimension(), gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.makeHealthBar(), gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.makeHeartImage(), and gamePlayer.guiItems.GuiItem.myPropertiesPath.
void gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.makeHealthBar () private
Definition at line 69 of file Health.java.
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.initialize().
void gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.makeHeartImage () private
Definition at line 52 of file Health.java.
References utilities.XMLParsing.XMLParser.getDimension(), and utilities.XMLParsing.XMLParser.getValuesFromTag().
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.initialize().
Member Data Documentation
DoubleProperty gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.healthRemaining private
Definition at line 27 of file Health.java.
Dimension2D gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.imageSize private
Definition at line 21 of file Health.java.
ProgressBar gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.myHealthBar private
Definition at line 23 of file Health.java.
ImageView gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.myHeart private
Definition at line 22 of file Health.java.
XMLParser gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.myParser private
Definition at line 19 of file Health.java.
Dimension2D gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.mySize private
Definition at line 20 of file Health.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/unusedCodeWarehouse/guiItems/headsUpDisplayA/Health.java