voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.PathBuildingScene Class Reference
gameAuthoring.scenes.pathBuilding.PathBuildingScene Class Reference
Public Member Functions
PathBuildingScene (BorderPane root, IPathConfiguring controller)
void proceedToLineDrawerModeIfLocationsVerified ()
void proceedToStartLocationSelection ()
void proceedToEndLocationsSelection ()
void setCurrentBuildingPane (BuildingPane nextPane)
void setBackground (String imageFileName)
Public Member Functions inherited from gameAuthoring.scenes.BuildingScene
BuildingScene (BorderPane root, String title)
String getTitle ()
Scene getScene ()
Static Public Attributes
static final int BUILDING_OPTIONS_PADDING = 10
static final double SIDE_PANE_WIDTH
Static Public Attributes inherited from gameAuthoring.scenes.BuildingScene
static final String STYLESHEET_PACKAGE = "./gameAuthoring/Stylesheets/"
Private Member Functions
void createAndDisplayDefaultMapSelectionPane ()
void createBuildingPanes ()
void handleKeyPress (KeyEvent event)
void createPathBuildingOptions ()
BuildingOptionPane getBuildingOptionsPane (String name, BuildingPane pane)
void resetBuild ()
void handleFinishButtonClick ()
void deselectOptionsComponents ()
boolean canDrawPathComponents ()
boolean isCurrentPane (BuildingPane pane)
void setCurrentDrawingPane (BuildingPane pane)
Private Attributes
Path myPath
BorderPane myPane
PathBackgroundSelectionPane myBackgroundSelectionPane
EnemyStartingLocationsPane myEnemyStartingLocationsPane
EnemyEndingLocationsPane myEnemyEndingLocationsPane
LineDrawingPane myLineDrawingPane
CurveDrawingPane myCurveDrawingPane
SelectComponentPane mySelectionComponentPane
ComponentVisibilityPane myComponentVisibilityPane
TowerRegionsPane myTowerRegionsPane
BuildingPane myCurrentBuildingPane
BuildingOptionPane myFinishedPathBuildingOptionPane
BuildingOptionPane myResetBuildOptionPane
DefaultMapSelectionPane myDefaultMapSelectionPane
IPathConfiguring myPathConfiguringController
VBox myPathBuildingOptionsContainer
Map< BuildingPane, BuildingOptionPane > myBuildingPaneToOptionPaneMap
Static Private Attributes
static final String SELECTED_CSS_CLASS = "selected"
static final String TITLE = "Path"
static Group myGroup
Additional Inherited Members
Protected Attributes inherited from gameAuthoring.scenes.BuildingScene
BorderPane myPane
Detailed Description
This class allows the user to build a path from a starting location to an ending location. The scene manages the different BuildingPanes that allow the user different on-click functionality.
Author
Austin Kyker
Definition at line 43 of file PathBuildingScene.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.PathBuildingScene.PathBuildingScene (BorderPane root, IPathConfiguring controller)
Definition at line 72 of file PathBuildingScene.java.
References gameAuthoring.scenes.pathBuilding.PathBuildingScene.createAndDisplayDefaultMapSelectionPane(), gameAuthoring.scenes.pathBuilding.PathBuildingScene.createBuildingPanes(), gameAuthoring.scenes.pathBuilding.PathBuildingScene.createPathBuildingOptions(), gameAuthoring.scenes.BuildingScene.getScene(), gameAuthoring.scenes.pathBuilding.PathBuildingScene.handleKeyPress(), and gameAuthoring.scenes.pathBuilding.PathBuildingScene.setCurrentBuildingPane().
Member Function Documentation
boolean gameAuthoring.scenes.pathBuilding.PathBuildingScene.canDrawPathComponents () private
Definition at line 178 of file PathBuildingScene.java.
References gameAuthoring.scenes.pathBuilding.PathBuildingScene.isCurrentPane().
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.setCurrentDrawingPane().
void gameAuthoring.scenes.pathBuilding.PathBuildingScene.createAndDisplayDefaultMapSelectionPane () private
Definition at line 86 of file PathBuildingScene.java.
References gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.getDefaultMapsScrollPane().
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.PathBuildingScene().
void gameAuthoring.scenes.pathBuilding.PathBuildingScene.createBuildingPanes () private
Definition at line 91 of file PathBuildingScene.java.
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.PathBuildingScene().
void gameAuthoring.scenes.pathBuilding.PathBuildingScene.createPathBuildingOptions () private
Shows all of the path building options. The options are line drawing, curve drawing, selection, and finished which will check to see if the path is connected, and if it is, will proceed to the next scene (enemy building)
Definition at line 119 of file PathBuildingScene.java.
References gameAuthoring.scenes.pathBuilding.PathBuildingScene.getBuildingOptionsPane(), gameAuthoring.scenes.pathBuilding.PathBuildingScene.handleFinishButtonClick(), and gameAuthoring.scenes.pathBuilding.PathBuildingScene.resetBuild().
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.PathBuildingScene().
void gameAuthoring.scenes.pathBuilding.PathBuildingScene.deselectOptionsComponents () private
Definition at line 172 of file PathBuildingScene.java.
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.resetBuild(), and gameAuthoring.scenes.pathBuilding.PathBuildingScene.setCurrentDrawingPane().
BuildingOptionPane gameAuthoring.scenes.pathBuilding.PathBuildingScene.getBuildingOptionsPane (String name, BuildingPane pane) private
Definition at line 141 of file PathBuildingScene.java.
References gameAuthoring.scenes.pathBuilding.PathBuildingScene.setCurrentDrawingPane().
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.createPathBuildingOptions().
void gameAuthoring.scenes.pathBuilding.PathBuildingScene.handleFinishButtonClick () private
Definition at line 154 of file PathBuildingScene.java.
References gameAuthoring.mainclasses.controllerInterfaces.IPathConfiguring.configurePath(), gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.getBackendTowerRegions(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.isPathCompletedAndRoutesVerified(), gameAuthoring.mainclasses.Constants.PATH_NOT_CONNECTED, and gameAuthoring.mainclasses.controllerInterfaces.IPathConfiguring.setTowerRegions().
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.createPathBuildingOptions().
void gameAuthoring.scenes.pathBuilding.PathBuildingScene.handleKeyPress (KeyEvent event) private
Definition at line 102 of file PathBuildingScene.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.deleteSelectedComponent().
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.PathBuildingScene().
boolean gameAuthoring.scenes.pathBuilding.PathBuildingScene.isCurrentPane (BuildingPane pane) private
Definition at line 183 of file PathBuildingScene.java.
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.canDrawPathComponents(), and gameAuthoring.scenes.pathBuilding.PathBuildingScene.setCurrentDrawingPane().
void gameAuthoring.scenes.pathBuilding.PathBuildingScene.proceedToEndLocationsSelection ()
Definition at line 191 of file PathBuildingScene.java.
References gameAuthoring.scenes.pathBuilding.PathBuildingScene.setCurrentBuildingPane(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.startingLocationsConfiguredCorrectly().
void gameAuthoring.scenes.pathBuilding.PathBuildingScene.proceedToLineDrawerModeIfLocationsVerified ()
Definition at line 165 of file PathBuildingScene.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.endingLocationsConfiguredCorrectly(), and gameAuthoring.scenes.pathBuilding.PathBuildingScene.setCurrentBuildingPane().
void gameAuthoring.scenes.pathBuilding.PathBuildingScene.proceedToStartLocationSelection ()
Definition at line 187 of file PathBuildingScene.java.
References gameAuthoring.scenes.pathBuilding.PathBuildingScene.setCurrentBuildingPane().
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.setBackground().
void gameAuthoring.scenes.pathBuilding.PathBuildingScene.resetBuild () private
Definition at line 148 of file PathBuildingScene.java.
References gameAuthoring.scenes.pathBuilding.PathBuildingScene.deselectOptionsComponents(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.resetPath(), and gameAuthoring.scenes.pathBuilding.PathBuildingScene.setCurrentBuildingPane().
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.createPathBuildingOptions(), and gameAuthoring.scenes.pathBuilding.PathBuildingScene.setBackground().
void gameAuthoring.scenes.pathBuilding.PathBuildingScene.setBackground (String imageFileName)
Implements gameAuthoring.scenes.pathBuilding.buildingPanes.BackgroundBuilding.
Definition at line 229 of file PathBuildingScene.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.DRAW_SCREEN_WIDTH, utilities.JavaFXutilities.imageView.StringToImageViewConverter.getImageView(), gameAuthoring.scenes.pathBuilding.PathBuildingScene.proceedToStartLocationSelection(), gameAuthoring.scenes.pathBuilding.PathBuildingScene.resetBuild(), gameAuthoring.mainclasses.AuthorController.SCREEN_HEIGHT, and gameAuthoring.mainclasses.controllerInterfaces.IPathConfiguring.setBackground().
void gameAuthoring.scenes.pathBuilding.PathBuildingScene.setCurrentBuildingPane (BuildingPane nextPane)
Include all panes: curve, line, regions, enemy starting and ending locations, background selection, etc.
Parameters
nextPane
Definition at line 217 of file PathBuildingScene.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.executeEnterFunction(), gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.executeExitFunction(), and gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.refreshScreen().
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.PathBuildingScene(), gameAuthoring.scenes.pathBuilding.PathBuildingScene.proceedToEndLocationsSelection(), gameAuthoring.scenes.pathBuilding.PathBuildingScene.proceedToLineDrawerModeIfLocationsVerified(), gameAuthoring.scenes.pathBuilding.PathBuildingScene.proceedToStartLocationSelection(), gameAuthoring.scenes.pathBuilding.PathBuildingScene.resetBuild(), and gameAuthoring.scenes.pathBuilding.PathBuildingScene.setCurrentDrawingPane().
void gameAuthoring.scenes.pathBuilding.PathBuildingScene.setCurrentDrawingPane (BuildingPane pane) private
Drawing panes include tower regions, curve drawing, line drawing, and selection.
Parameters
pane
Definition at line 203 of file PathBuildingScene.java.
References gameAuthoring.scenes.pathBuilding.PathBuildingScene.canDrawPathComponents(), gameAuthoring.scenes.pathBuilding.PathBuildingScene.deselectOptionsComponents(), gameAuthoring.scenes.pathBuilding.PathBuildingScene.isCurrentPane(), and gameAuthoring.scenes.pathBuilding.PathBuildingScene.setCurrentBuildingPane().
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.getBuildingOptionsPane().
Member Data Documentation
final int gameAuthoring.scenes.pathBuilding.PathBuildingScene.BUILDING_OPTIONS_PADDING = 10 static
Definition at line 46 of file PathBuildingScene.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingOptionPane.setupOptionsBoxGraphicallyAndDisplayLabel().
PathBackgroundSelectionPane gameAuthoring.scenes.pathBuilding.PathBuildingScene.myBackgroundSelectionPane private
Definition at line 55 of file PathBuildingScene.java.
Map<BuildingPane, BuildingOptionPane> gameAuthoring.scenes.pathBuilding.PathBuildingScene.myBuildingPaneToOptionPaneMap private
Definition at line 70 of file PathBuildingScene.java.
ComponentVisibilityPane gameAuthoring.scenes.pathBuilding.PathBuildingScene.myComponentVisibilityPane private
Definition at line 61 of file PathBuildingScene.java.
BuildingPane gameAuthoring.scenes.pathBuilding.PathBuildingScene.myCurrentBuildingPane private
Definition at line 63 of file PathBuildingScene.java.
CurveDrawingPane gameAuthoring.scenes.pathBuilding.PathBuildingScene.myCurveDrawingPane private
Definition at line 59 of file PathBuildingScene.java.
DefaultMapSelectionPane gameAuthoring.scenes.pathBuilding.PathBuildingScene.myDefaultMapSelectionPane private
Definition at line 67 of file PathBuildingScene.java.
EnemyEndingLocationsPane gameAuthoring.scenes.pathBuilding.PathBuildingScene.myEnemyEndingLocationsPane private
Definition at line 57 of file PathBuildingScene.java.
EnemyStartingLocationsPane gameAuthoring.scenes.pathBuilding.PathBuildingScene.myEnemyStartingLocationsPane private
Definition at line 56 of file PathBuildingScene.java.
BuildingOptionPane gameAuthoring.scenes.pathBuilding.PathBuildingScene.myFinishedPathBuildingOptionPane private
Definition at line 65 of file PathBuildingScene.java.
Group gameAuthoring.scenes.pathBuilding.PathBuildingScene.myGroup static private
Definition at line 53 of file PathBuildingScene.java.
LineDrawingPane gameAuthoring.scenes.pathBuilding.PathBuildingScene.myLineDrawingPane private
Definition at line 58 of file PathBuildingScene.java.
BorderPane gameAuthoring.scenes.pathBuilding.PathBuildingScene.myPane private
Definition at line 52 of file PathBuildingScene.java.
Path gameAuthoring.scenes.pathBuilding.PathBuildingScene.myPath private
Definition at line 51 of file PathBuildingScene.java.
VBox gameAuthoring.scenes.pathBuilding.PathBuildingScene.myPathBuildingOptionsContainer private
Definition at line 69 of file PathBuildingScene.java.
IPathConfiguring gameAuthoring.scenes.pathBuilding.PathBuildingScene.myPathConfiguringController private
Definition at line 68 of file PathBuildingScene.java.
BuildingOptionPane gameAuthoring.scenes.pathBuilding.PathBuildingScene.myResetBuildOptionPane private
Definition at line 66 of file PathBuildingScene.java.
SelectComponentPane gameAuthoring.scenes.pathBuilding.PathBuildingScene.mySelectionComponentPane private
Definition at line 60 of file PathBuildingScene.java.
TowerRegionsPane gameAuthoring.scenes.pathBuilding.PathBuildingScene.myTowerRegionsPane private
Definition at line 62 of file PathBuildingScene.java.
final String gameAuthoring.scenes.pathBuilding.PathBuildingScene.SELECTED_CSS_CLASS = "selected" static private
Definition at line 45 of file PathBuildingScene.java.
final double gameAuthoring.scenes.pathBuilding.PathBuildingScene.SIDE_PANE_WIDTH static
Initial value:
=
            ((AuthorController.SCREEN_WIDTH - BuildingPane.DRAW_SCREEN_WIDTH) / 2)
Definition at line 47 of file PathBuildingScene.java.
Referenced by gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.DefaultMapSelectionPane().
final String gameAuthoring.scenes.pathBuilding.PathBuildingScene.TITLE = "Path" static private
Definition at line 49 of file PathBuildingScene.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/PathBuildingScene.java