voogasalad_LosTorres: gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel Class Reference
gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel Class Reference
Public Member Functions
void initialize (Dimension2D containerSize)
void deselectTower ()
void setCurrentTower (TowerInfoObject current, ImageView towerImageView, TowerIndicator indicator)
Node getNode ()
Static Public Attributes
static final String NO_SELECTED_TOWER = "Click on a tower to upgrade or sell it"
static final String UPGRADE_TEXT = "Upgrade to:" + "\n"
static final String STONE_PATH = "./src/gamePlayer/playerImages/stonewall.jpg"
static final String SELL_PATH = "./src/gamePlayer/playerImages/dollars.jpg"
static final String UP_PATH = "./src/gamePlayer/playerImages/upvote.jpg"
Static Public Attributes inherited from gamePlayer.guiItems.GuiItem
static String myPropertiesPath = "guiItems/"
Private Member Functions
void sell ()
void doUpgrade ()
Private Attributes
HBox myUpgradeBox
Label unselectedLabel
ImageView myIcon
Label myName
VBox myIconBox
String myUpgradeName
Button upgradeButton
Button sellButton
ImageView myTowerImageView
XMLParser myParser
TowerIndicator activeIndicator
Dimension2D mySize
Dimension2D myButtonSize
Dimension2D myIconSize
Dimension2D myLabelSize
UpgradeListener myListener
Detailed Description
Author
Greg Lyons
Definition at line 45 of file TowerUpgradePanel.java.
Member Function Documentation
void gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.deselectTower ()
Definition at line 118 of file TowerUpgradePanel.java.
Referenced by gamePlayer.mainClasses.managers.GuiManager.deselectTower(), gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.doUpgrade(), and gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.sell().
void gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.doUpgrade () private
Definition at line 142 of file TowerUpgradePanel.java.
References gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.deselectTower(), and gamePlayer.guiItemsListeners.UpgradeListener.upgradeTower().
Referenced by gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.initialize().
Node gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 150 of file TowerUpgradePanel.java.
void gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 74 of file TowerUpgradePanel.java.
References utilities.JavaFXutilities.ratioSizing.RatiosToDim.convert(), gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.doUpgrade(), utilities.XMLParsing.XMLParser.getDimension(), gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_ELEMENT_PROPERTIES_PATH, gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_MANAGER, gamePlayer.guiItems.GuiItem.myPropertiesPath, gamePlayer.guiItemsListeners.UpgradeListener.registerUpgradePanel(), and gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.sell().
void gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.sell () private
Definition at line 136 of file TowerUpgradePanel.java.
References gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.deselectTower(), and gamePlayer.guiItemsListeners.UpgradeListener.sellTower().
Referenced by gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.initialize().
void gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.setCurrentTower (TowerInfoObject current, ImageView towerImageView, TowerIndicator indicator)
Definition at line 123 of file TowerUpgradePanel.java.
References gameEngine.Data.TowerInfoObject.getImageLocation(), utilities.JavaFXutilities.imageView.StringToImageViewConverter.getImageView(), gameEngine.Data.TowerInfoObject.getMyUpgrade(), gameEngine.Data.TowerInfoObject.getName(), and gameEngine.Data.TowerInfoObject.getSellCost().
Referenced by gamePlayer.mainClasses.managers.GuiManager.selectTower().
Member Data Documentation
TowerIndicator gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.activeIndicator private
Definition at line 58 of file TowerUpgradePanel.java.
Dimension2D gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.myButtonSize private
Definition at line 61 of file TowerUpgradePanel.java.
ImageView gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.myIcon private
Definition at line 50 of file TowerUpgradePanel.java.
VBox gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.myIconBox private
Definition at line 52 of file TowerUpgradePanel.java.
Dimension2D gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.myIconSize private
Definition at line 62 of file TowerUpgradePanel.java.
Dimension2D gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.myLabelSize private
Definition at line 63 of file TowerUpgradePanel.java.
UpgradeListener gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.myListener private
Definition at line 65 of file TowerUpgradePanel.java.
Label gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.myName private
Definition at line 51 of file TowerUpgradePanel.java.
XMLParser gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.myParser private
Definition at line 57 of file TowerUpgradePanel.java.
Dimension2D gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.mySize private
Definition at line 60 of file TowerUpgradePanel.java.
ImageView gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.myTowerImageView private
Definition at line 56 of file TowerUpgradePanel.java.
HBox gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.myUpgradeBox private
Definition at line 48 of file TowerUpgradePanel.java.
String gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.myUpgradeName private
Definition at line 53 of file TowerUpgradePanel.java.
final String gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.NO_SELECTED_TOWER = "Click on a tower to upgrade or sell it" static
Definition at line 67 of file TowerUpgradePanel.java.
final String gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.SELL_PATH = "./src/gamePlayer/playerImages/dollars.jpg" static
Definition at line 70 of file TowerUpgradePanel.java.
Button gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.sellButton private
Definition at line 55 of file TowerUpgradePanel.java.
final String gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.STONE_PATH = "./src/gamePlayer/playerImages/stonewall.jpg" static
Definition at line 69 of file TowerUpgradePanel.java.
Label gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.unselectedLabel private
Definition at line 49 of file TowerUpgradePanel.java.
final String gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.UP_PATH = "./src/gamePlayer/playerImages/upvote.jpg" static
Definition at line 71 of file TowerUpgradePanel.java.
final String gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.UPGRADE_TEXT = "Upgrade to:" + "\n" static
Definition at line 68 of file TowerUpgradePanel.java.
Button gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.upgradeButton private
Definition at line 54 of file TowerUpgradePanel.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItems/towerUpgrade/TowerUpgradePanel.java