voogasalad_LosTorres: gamePlayer.tests.DragAndDropTester Class Reference
gamePlayer.tests.DragAndDropTester Class Reference
Public Member Functions
void start (Stage primaryStage) throws Exception
Static Public Member Functions
static void main (String[] args)
Package Attributes
AnchorPane myContainer
Dimension2D mySize = new Dimension2D(900,400)
Group myStore
Group myBadSpace
Group myGoodSpace
Node startNode
Private Member Functions
void buildContainer ()
void buildItem ()
void newDrag (double X, double Y)
void drag (Shape node, double X, double Y)
void drop (Node node, double X, double Y)
Image getImage (String name)
Detailed Description
Definition at line 17 of file DragAndDropTester.java.
Member Function Documentation
void gamePlayer.tests.DragAndDropTester.buildContainer () private
Definition at line 36 of file DragAndDropTester.java.
Referenced by gamePlayer.tests.DragAndDropTester.start().
void gamePlayer.tests.DragAndDropTester.buildItem () private
Definition at line 61 of file DragAndDropTester.java.
References gamePlayer.tests.DragAndDropTester.newDrag().
Referenced by gamePlayer.tests.DragAndDropTester.start().
void gamePlayer.tests.DragAndDropTester.drag (Shape node, double X, double Y) private
Definition at line 77 of file DragAndDropTester.java.
Referenced by gamePlayer.tests.DragAndDropTester.newDrag().
void gamePlayer.tests.DragAndDropTester.drop (Node node, double X, double Y) private
Definition at line 87 of file DragAndDropTester.java.
References gamePlayer.tests.DragAndDropTester.getImage().
Referenced by gamePlayer.tests.DragAndDropTester.newDrag().
Image gamePlayer.tests.DragAndDropTester.getImage (String name) private
Definition at line 104 of file DragAndDropTester.java.
Referenced by gamePlayer.tests.DragAndDropTester.drop().
static void gamePlayer.tests.DragAndDropTester.main (String[] args) static
Definition at line 24 of file DragAndDropTester.java.
void gamePlayer.tests.DragAndDropTester.newDrag (double X, double Y) private
Definition at line 69 of file DragAndDropTester.java.
References gamePlayer.tests.DragAndDropTester.drag(), and gamePlayer.tests.DragAndDropTester.drop().
Referenced by gamePlayer.tests.DragAndDropTester.buildItem().
void gamePlayer.tests.DragAndDropTester.start (Stage primaryStage) throws Exception
Definition at line 29 of file DragAndDropTester.java.
References gamePlayer.tests.DragAndDropTester.buildContainer(), and gamePlayer.tests.DragAndDropTester.buildItem().
Member Data Documentation
Group gamePlayer.tests.DragAndDropTester.myBadSpace package
Definition at line 21 of file DragAndDropTester.java.
AnchorPane gamePlayer.tests.DragAndDropTester.myContainer package
Definition at line 19 of file DragAndDropTester.java.
Group gamePlayer.tests.DragAndDropTester.myGoodSpace package
Definition at line 21 of file DragAndDropTester.java.
Dimension2D gamePlayer.tests.DragAndDropTester.mySize = new Dimension2D(900,400) package
Definition at line 20 of file DragAndDropTester.java.
Group gamePlayer.tests.DragAndDropTester.myStore package
Definition at line 21 of file DragAndDropTester.java.
Node gamePlayer.tests.DragAndDropTester.startNode package
Definition at line 22 of file DragAndDropTester.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/tests/DragAndDropTester.java