voogasalad_LosTorres: gameEngine.actors.behaviors.RangeAttack Class Reference
gameEngine.actors.behaviors.RangeAttack Class Reference abstract
Public Member Functions
RangeAttack (double attackSpeed)
RangeAttack (List< Double > list)
Public Member Functions inherited from gameEngine.actors.behaviors.BaseAttack
BaseAttack (double attackSpeed)
BaseAttack (List< Double > list)
void execute (BaseActor actor)
void setAttackSpeed (int i)
String toString ()
double getRange ()
Public Member Functions inherited from gameEngine.actors.behaviors.IBehavior
IBehavior copy ()
Protected Member Functions
void shootActorFromActor (BaseActor target, BaseActor actor)
void performAttack (BaseActor actor)
abstract Comparator< BaseActor > defineComparison (BaseActor actor)
Protected Member Functions inherited from gameEngine.actors.behaviors.BaseAttack
boolean readyToShoot ()
abstract void performAttack (BaseActor actor)
Private Member Functions
double getOrientation (Point2D dif)
Static Private Attributes
static final int IMAGE_ANGLE_OFFSET = 270
static final double DISTANCE_FACTOR = 2.0
Additional Inherited Members
Protected Attributes inherited from gameEngine.actors.behaviors.BaseAttack
List< Double > myList
double myAttackSpeed
double myRange
int myCooldown
Static Protected Attributes inherited from gameEngine.actors.behaviors.BaseAttack
static final int READY_TO_SHOOT = 0
Detailed Description
Definition at line 14 of file RangeAttack.java.
Constructor & Destructor Documentation
gameEngine.actors.behaviors.RangeAttack.RangeAttack (double attackSpeed)
Definition at line 19 of file RangeAttack.java.
gameEngine.actors.behaviors.RangeAttack.RangeAttack (List< Double > list)
Definition at line 23 of file RangeAttack.java.
Member Function Documentation
abstract Comparator<BaseActor> gameEngine.actors.behaviors.RangeAttack.defineComparison (BaseActor actor) abstract protected
Referenced by gameEngine.actors.behaviors.RangeAttack.performAttack().
double gameEngine.actors.behaviors.RangeAttack.getOrientation (Point2D dif) private
Definition at line 56 of file RangeAttack.java.
References gameEngine.actors.behaviors.RangeAttack.IMAGE_ANGLE_OFFSET.
Referenced by gameEngine.actors.behaviors.RangeAttack.shootActorFromActor().
void gameEngine.actors.behaviors.RangeAttack.performAttack (BaseActor actor) protected
Definition at line 45 of file RangeAttack.java.
References gameEngine.actors.behaviors.RangeAttack.defineComparison(), gameEngine.actors.BaseActor.getEnemiesInRange(), gameEngine.actors.behaviors.BaseAttack.myRange, and gameEngine.actors.behaviors.RangeAttack.shootActorFromActor().
void gameEngine.actors.behaviors.RangeAttack.shootActorFromActor (BaseActor target, BaseActor actor) protected
Definition at line 28 of file RangeAttack.java.
References gameEngine.actors.ProjectileInfo.copy(), gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.DRAW_SCREEN_WIDTH, gameEngine.actors.BaseProjectile.getInfo(), gameEngine.actors.ProjectileInfo.getMove(), gameEngine.actors.BaseActor.getNode(), gameEngine.actors.behaviors.RangeAttack.getOrientation(), gameEngine.actors.RealActor.getProjectile(), gameEngine.actors.BaseActor.getX(), gameEngine.actors.BaseActor.getY(), gameEngine.actors.behaviors.BaseMovementBehavior.setRoute(), and gameEngine.actors.RealActor.spawnProjectile().
Referenced by gameEngine.actors.behaviors.RangeAttack.performAttack().
Member Data Documentation
final double gameEngine.actors.behaviors.RangeAttack.DISTANCE_FACTOR = 2.0 static private
Definition at line 17 of file RangeAttack.java.
final int gameEngine.actors.behaviors.RangeAttack.IMAGE_ANGLE_OFFSET = 270 static private
Definition at line 16 of file RangeAttack.java.
Referenced by gameEngine.actors.behaviors.RangeAttack.getOrientation().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/behaviors/RangeAttack.java