voogasalad_LosTorres: utilities.reflection.Reflection Class Reference
utilities.reflection.Reflection Class Reference
Static Public Member Functions
static Object createInstance (String className) throws ReflectionException
static Object createInstance (String name, Object...args) throws ReflectionException
static Object callMethod (Object target, String name) throws ReflectionException
static Object callMethod (Object target, String name, Object...args) throws ReflectionException
static Object getFieldValue (Object target, String name) throws ReflectionException
static Class<?>[] toClasses (Object[] args)
Static Private Member Functions
static boolean typesMatch (Member function, Class<?>[] formals, Object[] actuals)
static Object[] convertArgs (Member function, Class<?>[] formals, Object[] actuals)
static boolean isInstance (Class<?> clss, Object instance)
static boolean isVarArgs (Member function)
static boolean isAssignableFrom (Class<?> formal, Class<?> arg)
Detailed Description
This class provides a variety of convenience methods for dynamically calling methods and allocating classes. This utility class simplifies some of Java's reflection API and fixes some issues.
Definition at line 15 of file Reflection.java.
Member Function Documentation
static Object utilities.reflection.Reflection.callMethod (Object target, String name) throws ReflectionException static
Given a target object with a no argument method of the given name, call the named method on that object and return the result.
If the method's return type is void, null in returned.
Definition at line 59 of file Reflection.java.
static Object utilities.reflection.Reflection.callMethod (Object target, String name, Object... args) throws ReflectionException static
Given a target object with a method of the given name that takes the given actual parameters, call the named method on that object and return the result.
If the method's return type is void, null in returned.
Definition at line 75 of file Reflection.java.
References utilities.reflection.Reflection.convertArgs(), and utilities.reflection.Reflection.typesMatch().
static Object [] utilities.reflection.Reflection.convertArgs (Member function, Class<?>[] formals, Object[] actuals) static private
Definition at line 141 of file Reflection.java.
References utilities.reflection.Reflection.isVarArgs().
Referenced by utilities.reflection.Reflection.callMethod(), and utilities.reflection.Reflection.createInstance().
static Object utilities.reflection.Reflection.createInstance (String className) throws ReflectionException static
Given a String representing the fully qualified name of a class, returns an initialized instance of the corresponding class using default constructor. Returns null if string does not name a valid class.
Definition at line 21 of file Reflection.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.buildBehavior(), gamePlayer.guiItems.welcome.WelcomeNavigator.deviceConnected(), gamePlayer.guiContainers.secondaryContainers.ControlDock.initialize(), gamePlayer.unusedCodeWarehouse.HUDContainer.initialize(), gamePlayer.guiContainers.coreContainers.CoreContainerSetup.initialize(), and gamePlayer.guiItems.welcome.WelcomeNavigator.setupContents().
static Object utilities.reflection.Reflection.createInstance (String name, Object... args) throws ReflectionException static
Given String representing fully qualified name of a class and the actual parameters, returns initialized instance of the corresponding class using matching constructor.
Definition at line 36 of file Reflection.java.
References utilities.reflection.Reflection.convertArgs(), and utilities.reflection.Reflection.typesMatch().
static Object utilities.reflection.Reflection.getFieldValue (Object target, String name) throws ReflectionException static
Given a target object with an instance variable with the given name, get the value of the named variable on that object and return it.
Definition at line 96 of file Reflection.java.
Referenced by utilities.reflection.Reflection.isInstance().
static boolean utilities.reflection.Reflection.isAssignableFrom (Class<?> formal, Class<?> arg) static private
Definition at line 193 of file Reflection.java.
Referenced by utilities.reflection.Reflection.isInstance().
static boolean utilities.reflection.Reflection.isInstance (Class<?> clss, Object instance) static private
Definition at line 162 of file Reflection.java.
References utilities.reflection.Reflection.getFieldValue(), and utilities.reflection.Reflection.isAssignableFrom().
Referenced by utilities.reflection.Reflection.typesMatch().
static boolean utilities.reflection.Reflection.isVarArgs (Member function) static private
Definition at line 186 of file Reflection.java.
Referenced by utilities.reflection.Reflection.convertArgs(), and utilities.reflection.Reflection.typesMatch().
static Class<?> [] utilities.reflection.Reflection.toClasses (Object[] args) static
Given an array of Objects, returns their corresponding Classes.
Definition at line 107 of file Reflection.java.
static boolean utilities.reflection.Reflection.typesMatch (Member function, Class<?>[] formals, Object[] actuals) static private
Definition at line 116 of file Reflection.java.
References utilities.reflection.Reflection.isInstance(), and utilities.reflection.Reflection.isVarArgs().
Referenced by utilities.reflection.Reflection.callMethod(), and utilities.reflection.Reflection.createInstance().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/reflection/Reflection.java