voogasalad_LosTorres: gamePlayer.guiItems.messageDisplay.MessageDisplay Class Reference
gamePlayer.guiItems.messageDisplay.MessageDisplay Class Reference
Public Member Functions
void initialize (Dimension2D containerSize)
Node getNode ()
void clear ()
void showMessage (String message, boolean error)
Static Public Attributes
static final String DEFAULT = "Welcome to TowerDefense!"
Static Public Attributes inherited from gamePlayer.guiItems.GuiItem
static String myPropertiesPath = "guiItems/"
Private Attributes
Dimension2D mySize
TextArea textArea
XMLParser myParser
Detailed Description
Author
brianbolze
Definition at line 22 of file MessageDisplay.java.
Member Function Documentation
void gamePlayer.guiItems.messageDisplay.MessageDisplay.clear ()
Definition at line 51 of file MessageDisplay.java.
Referenced by gamePlayer.mainClasses.managers.GuiManager.clearMessageDisplay().
Node gamePlayer.guiItems.messageDisplay.MessageDisplay.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 47 of file MessageDisplay.java.
References gamePlayer.guiItems.messageDisplay.MessageDisplay.textArea.
void gamePlayer.guiItems.messageDisplay.MessageDisplay.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 30 of file MessageDisplay.java.
References utilities.JavaFXutilities.ratioSizing.RatiosToDim.convert(), gamePlayer.guiItems.towerUpgrade.StandardBorder.get(), utilities.XMLParsing.XMLParser.getDimension(), gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_ELEMENT_PROPERTIES_PATH, gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_MANAGER, gamePlayer.guiItems.GuiItem.myPropertiesPath, and gamePlayer.mainClasses.managers.GuiManager.registerMessageDisplayListener().
void gamePlayer.guiItems.messageDisplay.MessageDisplay.showMessage (String message, boolean error)
Definition at line 55 of file MessageDisplay.java.
Referenced by gamePlayer.mainClasses.managers.GuiManager.displayMessage().
Member Data Documentation
final String gamePlayer.guiItems.messageDisplay.MessageDisplay.DEFAULT = "Welcome to TowerDefense!" static
Definition at line 24 of file MessageDisplay.java.
Referenced by gamePlayer.mainClasses.managers.GuiManager.escapePlace(), and gamePlayer.mainClasses.managers.GuiManager.makeTower().
XMLParser gamePlayer.guiItems.messageDisplay.MessageDisplay.myParser private
Definition at line 27 of file MessageDisplay.java.
Dimension2D gamePlayer.guiItems.messageDisplay.MessageDisplay.mySize private
Definition at line 25 of file MessageDisplay.java.
TextArea gamePlayer.guiItems.messageDisplay.MessageDisplay.textArea private
Definition at line 26 of file MessageDisplay.java.
Referenced by gamePlayer.guiItems.messageDisplay.MessageDisplay.getNode().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItems/messageDisplay/MessageDisplay.java