voogasalad_LosTorres: utilities.chatroom.Chatroom Class Reference
utilities.chatroom.Chatroom Class Reference
Public Member Functions
Chatroom ()
void setupAndBeginMessageRequests ()
void sendMessage (String message)
Static Public Attributes
static final HTTPConnection HTTP_CONNECTOR = new HTTPConnection(SERVER_URL)
Private Member Functions
void setupChatroomGraphics ()
void pollServerForMessages ()
void handleKeyPressed (KeyEvent event)
Private Attributes
TextField myTextField
ScrollPane myScrollPane
Timeline myRequestTimeline
int myMessageIndex
VBox myMessages
Static Private Attributes
static final String NO_MSG_RESPONSE = "None"
static final String MSG_SEPERATOR = "~"
static final String SERVER_URL = "https://voogasalad.herokuapp.com/"
static final double HEIGHT = AuthorController.SCREEN_HEIGHT/2
static final double WIDTH = 400
static final String TITLE = "Chatroom"
Detailed Description
Utility class that easily allows for the creation of error popups in a new window.
Author
Austin Kyker
Definition at line 24 of file Chatroom.java.
Constructor & Destructor Documentation
utilities.chatroom.Chatroom.Chatroom ()
Definition at line 41 of file Chatroom.java.
References utilities.chatroom.Chatroom.setupAndBeginMessageRequests(), and utilities.chatroom.Chatroom.setupChatroomGraphics().
Member Function Documentation
void utilities.chatroom.Chatroom.handleKeyPressed (KeyEvent event) private
Definition at line 88 of file Chatroom.java.
References utilities.chatroom.Chatroom.sendMessage().
void utilities.chatroom.Chatroom.pollServerForMessages () private
Polls the server for unseen messages. If messages exist, the response string is parsed, and the messages are displayed to the user in the ScrollPane.
Definition at line 75 of file Chatroom.java.
References utilities.networking.HTTPConnection.sendGet().
Referenced by utilities.chatroom.Chatroom.setupAndBeginMessageRequests().
void utilities.chatroom.Chatroom.sendMessage (String message)
Sends a message to the server.
Parameters
message
Definition at line 98 of file Chatroom.java.
References utilities.networking.HTTPConnection.sendPost().
Referenced by utilities.chatroom.Chatroom.handleKeyPressed().
void utilities.chatroom.Chatroom.setupAndBeginMessageRequests ()
Definition at line 63 of file Chatroom.java.
References utilities.chatroom.Chatroom.pollServerForMessages().
Referenced by utilities.chatroom.Chatroom.Chatroom().
void utilities.chatroom.Chatroom.setupChatroomGraphics () private
Definition at line 47 of file Chatroom.java.
Referenced by utilities.chatroom.Chatroom.Chatroom().
Member Data Documentation
final double utilities.chatroom.Chatroom.HEIGHT = AuthorController.SCREEN_HEIGHT/2 static private
Definition at line 31 of file Chatroom.java.
final HTTPConnection utilities.chatroom.Chatroom.HTTP_CONNECTOR = new HTTPConnection(SERVER_URL) static
Definition at line 29 of file Chatroom.java.
final String utilities.chatroom.Chatroom.MSG_SEPERATOR = "~" static private
Definition at line 27 of file Chatroom.java.
int utilities.chatroom.Chatroom.myMessageIndex private
Definition at line 37 of file Chatroom.java.
VBox utilities.chatroom.Chatroom.myMessages private
Definition at line 38 of file Chatroom.java.
Timeline utilities.chatroom.Chatroom.myRequestTimeline private
Definition at line 36 of file Chatroom.java.
ScrollPane utilities.chatroom.Chatroom.myScrollPane private
Definition at line 35 of file Chatroom.java.
TextField utilities.chatroom.Chatroom.myTextField private
Definition at line 34 of file Chatroom.java.
final String utilities.chatroom.Chatroom.NO_MSG_RESPONSE = "None" static private
Definition at line 26 of file Chatroom.java.
final String utilities.chatroom.Chatroom.SERVER_URL = "https://voogasalad.herokuapp.com/" static private
Definition at line 28 of file Chatroom.java.
final String utilities.chatroom.Chatroom.TITLE = "Chatroom" static private
Definition at line 33 of file Chatroom.java.
final double utilities.chatroom.Chatroom.WIDTH = 400 static private
Definition at line 32 of file Chatroom.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/chatroom/Chatroom.java