voogasalad_LosTorres: utilities.pathfinding.example.UnlinkedNode Class Reference
utilities.pathfinding.example.UnlinkedNode Class Reference
Public Member Functions
UnlinkedNode (int x, int y)
int getX ()
int getY ()
boolean equals (Object other)
String toString ()
Private Attributes
int myX
int myY
Detailed Description
Definition at line 3 of file UnlinkedNode.java.
Constructor & Destructor Documentation
utilities.pathfinding.example.UnlinkedNode.UnlinkedNode (int x, int y)
Definition at line 8 of file UnlinkedNode.java.
Referenced by utilities.pathfinding.example.UnlinkedNode.equals().
Member Function Documentation
boolean utilities.pathfinding.example.UnlinkedNode.equals (Object other)
Definition at line 22 of file UnlinkedNode.java.
References utilities.pathfinding.example.UnlinkedNode.getX(), utilities.pathfinding.example.UnlinkedNode.getY(), and utilities.pathfinding.example.UnlinkedNode.UnlinkedNode().
int utilities.pathfinding.example.UnlinkedNode.getX ()
Definition at line 13 of file UnlinkedNode.java.
References utilities.pathfinding.example.UnlinkedNode.myX.
Referenced by utilities.pathfinding.example.UnlinkedNodeAStarFinder.breakTie(), utilities.pathfinding.example.LinkedNode.compareTo(), utilities.pathfinding.example.UnlinkedNode.equals(), utilities.pathfinding.example.LinkedNodeAStarFinder.getCost(), utilities.pathfinding.example.UnlinkedNodeAStarFinder.getCost(), utilities.pathfinding.example.LinkedNodeAStarFinder.getHeuristicValue(), utilities.pathfinding.example.UnlinkedNodeAStarFinder.getHeuristicValue(), and utilities.pathfinding.example.UnlinkedNodeAStarFinder.getNeighbors().
int utilities.pathfinding.example.UnlinkedNode.getY ()
Definition at line 17 of file UnlinkedNode.java.
References utilities.pathfinding.example.UnlinkedNode.myY.
Referenced by utilities.pathfinding.example.UnlinkedNodeAStarFinder.breakTie(), utilities.pathfinding.example.LinkedNode.compareTo(), utilities.pathfinding.example.UnlinkedNode.equals(), utilities.pathfinding.example.LinkedNodeAStarFinder.getCost(), utilities.pathfinding.example.UnlinkedNodeAStarFinder.getCost(), utilities.pathfinding.example.LinkedNodeAStarFinder.getHeuristicValue(), utilities.pathfinding.example.UnlinkedNodeAStarFinder.getHeuristicValue(), and utilities.pathfinding.example.UnlinkedNodeAStarFinder.getNeighbors().
String utilities.pathfinding.example.UnlinkedNode.toString ()
Definition at line 29 of file UnlinkedNode.java.
References utilities.pathfinding.example.UnlinkedNode.myY.
Member Data Documentation
int utilities.pathfinding.example.UnlinkedNode.myX private
Definition at line 5 of file UnlinkedNode.java.
Referenced by utilities.pathfinding.example.UnlinkedNode.getX().
int utilities.pathfinding.example.UnlinkedNode.myY private
Definition at line 6 of file UnlinkedNode.java.
Referenced by utilities.pathfinding.example.UnlinkedNode.getY(), and utilities.pathfinding.example.UnlinkedNode.toString().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/pathfinding/example/UnlinkedNode.java