voogasalad_LosTorres: utilities.video.VideoPlayer Class Reference
utilities.video.VideoPlayer Class Reference
Public Member Functions
VideoPlayer (final MediaPlayer player)
Private Member Functions
void createMediaPlayer (final MediaPlayer player)
void defineMediaBarBehavior ()
void definePlayButtonBehavior (final MediaPlayer player, final Button button)
void createAndDefineTimeComponents (final MediaPlayer player)
void createAndDefineVolumeComponents (final MediaPlayer player, final Button button)
void defineMediaPlayerBehavior (final MediaPlayer player, final Button button)
void updateValues ()
Static Private Member Functions
static String calculateElapsedTime (Duration elapsed, Duration videoDuration)
static String formatTime (Duration duration, int intHours, int intMin, int intSec)
Private Attributes
MediaPlayer myMediaPlayer
MediaView myMediaView
Slider myTimeSlider
Label myTimeLabel
Slider myVolumeSlider
Duration myDuration
boolean myVideoWillReplay = true
boolean myVideoIsStopped
boolean myCycleIsComplete
HBox myMediaBar
Static Private Attributes
static final int PADDING = 20
static final int SLIDER_WIDTH = 50
static final int BUTTON_WIDTH = 75
static final int INT_CONVERT = 100
static final int LABEL_WIDTH = 150
static final double DOUBLE_CONVERT = 100.0
static final int SECONDS_PER_MINUTE = 60
static final int MINUTES_PER_HOUR = 60
static final String SPACE = " "
static final String MEDIA_PLAYER_BACKGROUND_COLOR = "-fx-background-color: #bbc0c4;"
static final String MOVIE_PANE_BACKGROUND_COLOR = "-fx-background-color: #000000;"
static final String PLAY_BUTTON_TEXT = "PLAY"
static final String STOP_BUTTON_TEXT = "STOP"
static final String MUTE_BUTTON_TEXT = "MUTE"
static final String UNMUTE_BUTTON_TEXT = "UNMUTE"
static final String VOLUME_LABEL_TEXT = "Volume: "
static final String TIME_LABEL_TEXT = "0:00:00 / 0:00:00"
static final String TIME_FORMAT = "%d:%02d:%02d/%d:%02d:%02d"
Detailed Description
Author
$cotty $haw
The VideoPlayer is a MediaPlayer that plays video files. All users can use it with VideoViewer.java to play any video files placed in this package.
Definition at line 30 of file VideoPlayer.java.
Constructor & Destructor Documentation
utilities.video.VideoPlayer.VideoPlayer (final MediaPlayer player)
Definition at line 68 of file VideoPlayer.java.
References utilities.video.VideoPlayer.createAndDefineTimeComponents(), utilities.video.VideoPlayer.createAndDefineVolumeComponents(), utilities.video.VideoPlayer.createMediaPlayer(), utilities.video.VideoPlayer.defineMediaBarBehavior(), utilities.video.VideoPlayer.defineMediaPlayerBehavior(), and utilities.video.VideoPlayer.definePlayButtonBehavior().
Member Function Documentation
static String utilities.video.VideoPlayer.calculateElapsedTime (Duration elapsed, Duration videoDuration) static private
Definition at line 230 of file VideoPlayer.java.
References utilities.video.VideoPlayer.formatTime(), and utilities.video.VideoPlayer.SECONDS_PER_MINUTE.
Referenced by utilities.video.VideoPlayer.updateValues().
void utilities.video.VideoPlayer.createAndDefineTimeComponents (final MediaPlayer player) private
Definition at line 131 of file VideoPlayer.java.
References utilities.video.VideoPlayer.DOUBLE_CONVERT.
Referenced by utilities.video.VideoPlayer.VideoPlayer().
void utilities.video.VideoPlayer.createAndDefineVolumeComponents (final MediaPlayer player, final Button button) private
Definition at line 149 of file VideoPlayer.java.
References utilities.video.VideoPlayer.DOUBLE_CONVERT, and utilities.video.VideoPlayer.UNMUTE_BUTTON_TEXT.
Referenced by utilities.video.VideoPlayer.VideoPlayer().
void utilities.video.VideoPlayer.createMediaPlayer (final MediaPlayer player) private
Definition at line 83 of file VideoPlayer.java.
Referenced by utilities.video.VideoPlayer.VideoPlayer().
void utilities.video.VideoPlayer.defineMediaBarBehavior () private
Definition at line 93 of file VideoPlayer.java.
Referenced by utilities.video.VideoPlayer.VideoPlayer().
void utilities.video.VideoPlayer.defineMediaPlayerBehavior (final MediaPlayer player, final Button button) private
Definition at line 174 of file VideoPlayer.java.
References utilities.video.VideoPlayer.myVideoWillReplay, and utilities.video.VideoPlayer.updateValues().
Referenced by utilities.video.VideoPlayer.VideoPlayer().
void utilities.video.VideoPlayer.definePlayButtonBehavior (final MediaPlayer player, final Button button) private
Definition at line 102 of file VideoPlayer.java.
References utilities.video.VideoPlayer.updateValues().
Referenced by utilities.video.VideoPlayer.VideoPlayer().
static String utilities.video.VideoPlayer.formatTime (Duration duration, int intHours, int intMin, int intSec) static private
Definition at line 242 of file VideoPlayer.java.
References utilities.video.VideoPlayer.SECONDS_PER_MINUTE.
Referenced by utilities.video.VideoPlayer.calculateElapsedTime().
void utilities.video.VideoPlayer.updateValues () private
Definition at line 205 of file VideoPlayer.java.
References utilities.video.VideoPlayer.calculateElapsedTime(), and utilities.video.VideoPlayer.DOUBLE_CONVERT.
Referenced by utilities.video.VideoPlayer.defineMediaPlayerBehavior(), and utilities.video.VideoPlayer.definePlayButtonBehavior().
Member Data Documentation
final int utilities.video.VideoPlayer.BUTTON_WIDTH = 75 static private
Definition at line 34 of file VideoPlayer.java.
final double utilities.video.VideoPlayer.DOUBLE_CONVERT = 100.0 static private
Definition at line 38 of file VideoPlayer.java.
Referenced by utilities.video.VideoPlayer.createAndDefineTimeComponents(), utilities.video.VideoPlayer.createAndDefineVolumeComponents(), and utilities.video.VideoPlayer.updateValues().
final int utilities.video.VideoPlayer.INT_CONVERT = 100 static private
Definition at line 35 of file VideoPlayer.java.
final int utilities.video.VideoPlayer.LABEL_WIDTH = 150 static private
Definition at line 36 of file VideoPlayer.java.
final String utilities.video.VideoPlayer.MEDIA_PLAYER_BACKGROUND_COLOR = "-fx-background-color: #bbc0c4;" static private
Definition at line 45 of file VideoPlayer.java.
final int utilities.video.VideoPlayer.MINUTES_PER_HOUR = 60 static private
Definition at line 41 of file VideoPlayer.java.
final String utilities.video.VideoPlayer.MOVIE_PANE_BACKGROUND_COLOR = "-fx-background-color: #000000;" static private
Definition at line 46 of file VideoPlayer.java.
final String utilities.video.VideoPlayer.MUTE_BUTTON_TEXT = "MUTE" static private
Definition at line 50 of file VideoPlayer.java.
boolean utilities.video.VideoPlayer.myCycleIsComplete private
Definition at line 65 of file VideoPlayer.java.
Duration utilities.video.VideoPlayer.myDuration private
Definition at line 62 of file VideoPlayer.java.
HBox utilities.video.VideoPlayer.myMediaBar private
Definition at line 66 of file VideoPlayer.java.
MediaPlayer utilities.video.VideoPlayer.myMediaPlayer private
Definition at line 57 of file VideoPlayer.java.
MediaView utilities.video.VideoPlayer.myMediaView private
Definition at line 58 of file VideoPlayer.java.
Label utilities.video.VideoPlayer.myTimeLabel private
Definition at line 60 of file VideoPlayer.java.
Slider utilities.video.VideoPlayer.myTimeSlider private
Definition at line 59 of file VideoPlayer.java.
boolean utilities.video.VideoPlayer.myVideoIsStopped private
Definition at line 64 of file VideoPlayer.java.
boolean utilities.video.VideoPlayer.myVideoWillReplay = true private
Definition at line 63 of file VideoPlayer.java.
Referenced by utilities.video.VideoPlayer.defineMediaPlayerBehavior().
Slider utilities.video.VideoPlayer.myVolumeSlider private
Definition at line 61 of file VideoPlayer.java.
final int utilities.video.VideoPlayer.PADDING = 20 static private
Definition at line 32 of file VideoPlayer.java.
final String utilities.video.VideoPlayer.PLAY_BUTTON_TEXT = "PLAY" static private
Definition at line 48 of file VideoPlayer.java.
final int utilities.video.VideoPlayer.SECONDS_PER_MINUTE = 60 static private
Definition at line 40 of file VideoPlayer.java.
Referenced by utilities.video.VideoPlayer.calculateElapsedTime(), and utilities.video.VideoPlayer.formatTime().
final int utilities.video.VideoPlayer.SLIDER_WIDTH = 50 static private
Definition at line 33 of file VideoPlayer.java.
final String utilities.video.VideoPlayer.SPACE = " " static private
Definition at line 43 of file VideoPlayer.java.
final String utilities.video.VideoPlayer.STOP_BUTTON_TEXT = "STOP" static private
Definition at line 49 of file VideoPlayer.java.
final String utilities.video.VideoPlayer.TIME_FORMAT = "%d:%02d:%02d/%d:%02d:%02d" static private
Definition at line 55 of file VideoPlayer.java.
final String utilities.video.VideoPlayer.TIME_LABEL_TEXT = "0:00:00 / 0:00:00" static private
Definition at line 54 of file VideoPlayer.java.
final String utilities.video.VideoPlayer.UNMUTE_BUTTON_TEXT = "UNMUTE" static private
Definition at line 51 of file VideoPlayer.java.
Referenced by utilities.video.VideoPlayer.createAndDefineVolumeComponents().
final String utilities.video.VideoPlayer.VOLUME_LABEL_TEXT = "Volume: " static private
Definition at line 53 of file VideoPlayer.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/video/VideoPlayer.java