voogasalad_LosTorres: gameEngine.actors.behaviors.TowerRangeEffect Class Reference
gameEngine.actors.behaviors.TowerRangeEffect Class Reference
Public Member Functions
TowerRangeEffect (List< Double > list)
IBehavior copy ()
void during (BaseActor actor)
void start (BaseActor actor)
void end (BaseActor actor)
Public Member Functions inherited from gameEngine.actors.behaviors.BaseEffect
BaseEffect (double duration, double multiplier)
BaseEffect ()
BaseEffect (List< Double > list)
void execute (BaseActor actor)
abstract void during (BaseActor actor)
abstract void start (BaseActor actor)
abstract void end (BaseActor actor)
String toString ()
Private Attributes
double myRange
double myMultiplier
Additional Inherited Members
Protected Attributes inherited from gameEngine.actors.behaviors.BaseEffect
List< Double > myList
String myString
Package Attributes inherited from gameEngine.actors.behaviors.BaseEffect
double myDuration
double myInitialDuration
Detailed Description
Definition at line 6 of file TowerRangeEffect.java.
Constructor & Destructor Documentation
gameEngine.actors.behaviors.TowerRangeEffect.TowerRangeEffect (List< Double > list)
Definition at line 9 of file TowerRangeEffect.java.
References gameEngine.actors.behaviors.BaseEffect.myString.
Referenced by gameEngine.actors.behaviors.TowerRangeEffect.copy().
Member Function Documentation
IBehavior gameEngine.actors.behaviors.TowerRangeEffect.copy ()
Returns a copy of the behavior, which allows for copying entire actors
Returns
copy of the behavior
Implements gameEngine.actors.behaviors.IBehavior.
Definition at line 19 of file TowerRangeEffect.java.
References gameEngine.actors.behaviors.BaseEffect.myList, and gameEngine.actors.behaviors.TowerRangeEffect.TowerRangeEffect().
void gameEngine.actors.behaviors.TowerRangeEffect.during (BaseActor actor)
Definition at line 23 of file TowerRangeEffect.java.
void gameEngine.actors.behaviors.TowerRangeEffect.end (BaseActor actor)
Definition at line 35 of file TowerRangeEffect.java.
void gameEngine.actors.behaviors.TowerRangeEffect.start (BaseActor actor)
Definition at line 28 of file TowerRangeEffect.java.
References gameEngine.actors.BaseActor.getTowersInRange(), and gameEngine.actors.behaviors.TowerRangeEffect.myMultiplier.
Member Data Documentation
double gameEngine.actors.behaviors.TowerRangeEffect.myMultiplier private
Definition at line 8 of file TowerRangeEffect.java.
Referenced by gameEngine.actors.behaviors.TowerRangeEffect.start().
double gameEngine.actors.behaviors.TowerRangeEffect.myRange private
Definition at line 7 of file TowerRangeEffect.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/behaviors/TowerRangeEffect.java