voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingOptionPane Class Reference
gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingOptionPane Class Reference
Public Member Functions
BuildingOptionPane (String componentName)
void selectPane ()
Private Member Functions
void setupOptionsBoxGraphicallyAndDisplayLabel (String componentName)
Static Private Attributes
static final String BORDER_CSS = "border"
static final String SELECTED_CSS = "selected"
static final String COMP_OPTION_CSS = "pathComponentOption"
static final String DRAWING_OPTIONS_IMG_DIR
static final double OPTIONS_IMAGE_WIDTH
static final int OPTIONS_IMAGE_HEIGHT = 40
Detailed Description
Represents the pane on the right side of the PathBuildingScene that has the different types of drawing options. Clicking on these options switches out the BuildingPanes.
Author
Austin Kyker
Definition at line 19 of file BuildingOptionPane.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingOptionPane.BuildingOptionPane (String componentName)
Definition at line 31 of file BuildingOptionPane.java.
References utilities.JavaFXutilities.imageView.StringToImageViewConverter.getImageView(), and gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingOptionPane.setupOptionsBoxGraphicallyAndDisplayLabel().
Member Function Documentation
void gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingOptionPane.selectPane ()
Definition at line 43 of file BuildingOptionPane.java.
void gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingOptionPane.setupOptionsBoxGraphicallyAndDisplayLabel (String componentName) private
Definition at line 49 of file BuildingOptionPane.java.
References gameAuthoring.scenes.pathBuilding.PathBuildingScene.BUILDING_OPTIONS_PADDING, utilities.multilanguage.MultiLanguageUtility.getInstance(), and utilities.multilanguage.MultiLanguageUtility.getStringProperty().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingOptionPane.BuildingOptionPane().
Member Data Documentation
final String gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingOptionPane.BORDER_CSS = "border" static private
Definition at line 21 of file BuildingOptionPane.java.
final String gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingOptionPane.COMP_OPTION_CSS = "pathComponentOption" static private
Definition at line 23 of file BuildingOptionPane.java.
final String gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingOptionPane.DRAWING_OPTIONS_IMG_DIR static private
Initial value:
=
            "./src/gameAuthoring/Resources/PathDrawingOptionsImages/"
Definition at line 24 of file BuildingOptionPane.java.
final int gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingOptionPane.OPTIONS_IMAGE_HEIGHT = 40 static private
Definition at line 28 of file BuildingOptionPane.java.
final double gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingOptionPane.OPTIONS_IMAGE_WIDTH static private
Initial value:
=
            PathBuildingScene.SIDE_PANE_WIDTH - 45
Definition at line 26 of file BuildingOptionPane.java.
final String gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingOptionPane.SELECTED_CSS = "selected" static private
Definition at line 22 of file BuildingOptionPane.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/buildingPanes/BuildingOptionPane.java