voogasalad_LosTorres: gameAuthoring.scenes.levelBuilding.LevelBuildingDisplay Class Reference
gameAuthoring.scenes.levelBuilding.LevelBuildingDisplay Class Reference
Public Member Functions
LevelBuildingDisplay (List< BaseEnemy > enemies, Pane pane)
void addLevel ()
boolean isAllUserInputIsValid ()
List< BaseLevel > transformToLevels ()
Private Attributes
List< BaseEnemy > myEnemies
List< LevelDisplayCell > myLevelCells
VBox myLevelsContainer
Pane myPane
Static Private Attributes
static final double HEIGHT = 600
Detailed Description
A ScrollPane that allows the user to build and visualize all of the levels.
Author
Austin Kyker
Definition at line 17 of file LevelBuildingDisplay.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.levelBuilding.LevelBuildingDisplay.LevelBuildingDisplay (List< BaseEnemy > enemies, Pane pane)
Definition at line 26 of file LevelBuildingDisplay.java.
References gameAuthoring.scenes.levelBuilding.LevelBuildingDisplay.addLevel().
Member Function Documentation
void gameAuthoring.scenes.levelBuilding.LevelBuildingDisplay.addLevel ()
Definition at line 36 of file LevelBuildingDisplay.java.
Referenced by gameAuthoring.scenes.levelBuilding.LevelBuildingScene.createMenuAndAddNewLevelOption(), and gameAuthoring.scenes.levelBuilding.LevelBuildingDisplay.LevelBuildingDisplay().
boolean gameAuthoring.scenes.levelBuilding.LevelBuildingDisplay.isAllUserInputIsValid ()
Definition at line 43 of file LevelBuildingDisplay.java.
Referenced by gameAuthoring.scenes.levelBuilding.LevelBuildingScene.update().
List<BaseLevel> gameAuthoring.scenes.levelBuilding.LevelBuildingDisplay.transformToLevels ()
Definition at line 49 of file LevelBuildingDisplay.java.
Referenced by gameAuthoring.scenes.levelBuilding.LevelBuildingScene.update().
Member Data Documentation
final double gameAuthoring.scenes.levelBuilding.LevelBuildingDisplay.HEIGHT = 600 static private
Definition at line 19 of file LevelBuildingDisplay.java.
List<BaseEnemy> gameAuthoring.scenes.levelBuilding.LevelBuildingDisplay.myEnemies private
Definition at line 21 of file LevelBuildingDisplay.java.
List<LevelDisplayCell> gameAuthoring.scenes.levelBuilding.LevelBuildingDisplay.myLevelCells private
Definition at line 22 of file LevelBuildingDisplay.java.
VBox gameAuthoring.scenes.levelBuilding.LevelBuildingDisplay.myLevelsContainer private
Definition at line 23 of file LevelBuildingDisplay.java.
Pane gameAuthoring.scenes.levelBuilding.LevelBuildingDisplay.myPane private
Definition at line 24 of file LevelBuildingDisplay.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/levelBuilding/LevelBuildingDisplay.java