voogasalad_LosTorres: gamePlayer.mainClasses.ExceptionHandling.ExceptionHandler Class Reference
gamePlayer.mainClasses.ExceptionHandling.ExceptionHandler Class Reference
Public Member Functions
void handle (NullPointerException e)
Static Public Member Functions
static ExceptionHandler getInstance ()
Private Member Functions
ExceptionHandler ()
Static Private Attributes
static ExceptionHandler myReference = null
Detailed Description
Class handles exceptions thrown in the GUI
Author
allankiplagat
Definition at line 8 of file ExceptionHandler.java.
Constructor & Destructor Documentation
gamePlayer.mainClasses.ExceptionHandling.ExceptionHandler.ExceptionHandler () private
Definition at line 10 of file ExceptionHandler.java.
Referenced by gamePlayer.mainClasses.ExceptionHandling.ExceptionHandler.getInstance().
Member Function Documentation
static ExceptionHandler gamePlayer.mainClasses.ExceptionHandling.ExceptionHandler.getInstance () static
Definition at line 13 of file ExceptionHandler.java.
References gamePlayer.mainClasses.ExceptionHandling.ExceptionHandler.ExceptionHandler(), and gamePlayer.mainClasses.ExceptionHandling.ExceptionHandler.myReference.
Referenced by gamePlayer.guiItems.controlDockButtons.ControlDockButton.setupImageViews().
void gamePlayer.mainClasses.ExceptionHandling.ExceptionHandler.handle (NullPointerException e)
Definition at line 21 of file ExceptionHandler.java.
Referenced by gamePlayer.guiItems.controlDockButtons.ControlDockButton.setupImageViews().
Member Data Documentation
ExceptionHandler gamePlayer.mainClasses.ExceptionHandling.ExceptionHandler.myReference = null static private
Definition at line 9 of file ExceptionHandler.java.
Referenced by gamePlayer.mainClasses.ExceptionHandling.ExceptionHandler.getInstance().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/mainClasses/ExceptionHandling/ExceptionHandler.java