voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests Class Reference
gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests Class Reference
Public Member Functions
void setup ()
void testVisibilityPointCreation ()
void testBackendRouteCreation ()
void testRoutesTranslation ()
Private Member Functions
void testCorrectRouteTranslation (Point2D[] expectedPointsForRoute, List< VisibilityPoint > routeVisibilityPoints)
Private Attributes
Path myPath
Detailed Description
This class tests the translation of JavaFX PathComponents to backend route objects.
Author
Austin Kyker
Definition at line 20 of file BackendRouteTranslationTests.java.
Member Function Documentation
void gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.setup ()
Definition at line 25 of file BackendRouteTranslationTests.java.
void gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testBackendRouteCreation ()
Definition at line 39 of file BackendRouteTranslationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathRoute.add(), gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.getEndingPoint(), gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.getPoints(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.getStartingPoint().
void gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testCorrectRouteTranslation (Point2D[] expectedPointsForRoute, List< VisibilityPoint > routeVisibilityPoints) private
Definition at line 75 of file BackendRouteTranslationTests.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testRoutesTranslation().
void gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testRoutesTranslation ()
Definition at line 50 of file BackendRouteTranslationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath(), gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoutesGenerator.getBackendRoutes(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getEndingPoint(), gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.getPoints(), gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.getStartingPoint(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getStartingPoint(), gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.setEndingPoint(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setEndingPoint(), and gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testCorrectRouteTranslation().
void gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testVisibilityPointCreation ()
Definition at line 30 of file BackendRouteTranslationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.VisibilityPoint.getPoint(), and gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.VisibilityPoint.isVisible().
Member Data Documentation
Path gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.myPath private
Definition at line 22 of file BackendRouteTranslationTests.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/pathComponents/routeToPointTranslation/BackendRouteTranslationTests.java