voogasalad_LosTorres: utilities.XMLParsing.XMLParserTest Class Reference
utilities.XMLParsing.XMLParserTest Class Reference
Public Member Functions
void setup ()
void XMLParsingBehaviorOptionsTest ()
void XMLParsingSliderInfo ()
void XMLParsingAllBehaviorTypesTest ()
void XMLParsingIntegerExtractionTest ()
void XMLParsingDoubleExtractionTest ()
void XMLParsingDimensionExtractionTest ()
Private Attributes
XMLParser myParameterExtractionXMLParser
XMLParser myBehaviorExtractionXMLParser
Static Private Attributes
static final String TEST_FILE_1 = "./src/utilities/XMLParsing/testXMLFiles/test1.xml"
static final String TEST_FILE_2 = "./src/utilities/XMLParsing/testXMLFiles/test2.xml"
Detailed Description
Definition at line 12 of file XMLParserTest.java.
Member Function Documentation
void utilities.XMLParsing.XMLParserTest.setup ()
Definition at line 20 of file XMLParserTest.java.
void utilities.XMLParsing.XMLParserTest.XMLParsingAllBehaviorTypesTest ()
Definition at line 58 of file XMLParserTest.java.
References utilities.XMLParsing.XMLParser.getAllBehaviorTypes().
void utilities.XMLParsing.XMLParserTest.XMLParsingBehaviorOptionsTest ()
Definition at line 31 of file XMLParserTest.java.
References utilities.XMLParsing.XMLParser.getBehaviorElementsFromTag().
void utilities.XMLParsing.XMLParserTest.XMLParsingDimensionExtractionTest ()
Definition at line 88 of file XMLParserTest.java.
References utilities.XMLParsing.XMLParser.getDimension().
void utilities.XMLParsing.XMLParserTest.XMLParsingDoubleExtractionTest ()
Definition at line 78 of file XMLParserTest.java.
References utilities.XMLParsing.XMLParser.getDoubleValuesFromTag().
void utilities.XMLParsing.XMLParserTest.XMLParsingIntegerExtractionTest ()
Definition at line 68 of file XMLParserTest.java.
References utilities.XMLParsing.XMLParser.getIntegerValuesFromTag().
void utilities.XMLParsing.XMLParserTest.XMLParsingSliderInfo ()
Definition at line 48 of file XMLParserTest.java.
References utilities.XMLParsing.XMLParser.getSliderInfo().
Member Data Documentation
XMLParser utilities.XMLParsing.XMLParserTest.myBehaviorExtractionXMLParser private
Definition at line 17 of file XMLParserTest.java.
XMLParser utilities.XMLParsing.XMLParserTest.myParameterExtractionXMLParser private
Definition at line 16 of file XMLParserTest.java.
final String utilities.XMLParsing.XMLParserTest.TEST_FILE_1 = "./src/utilities/XMLParsing/testXMLFiles/test1.xml" static private
Definition at line 14 of file XMLParserTest.java.
final String utilities.XMLParsing.XMLParserTest.TEST_FILE_2 = "./src/utilities/XMLParsing/testXMLFiles/test2.xml" static private
Definition at line 15 of file XMLParserTest.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/XMLParsing/XMLParserTest.java