voogasalad_LosTorres: gamePlayer.guiContainers.coreContainers.CoreContainerSetup Class Reference
gamePlayer.guiContainers.coreContainers.CoreContainerSetup Class Reference
Public Member Functions
void setRegion (Region r, String className)
void setDimensions (double width, double height, Dimension2D containerSize)
void initialize (Region r, double width, double height, Dimension2D containerSize)
List< Node > getChildList ()
Static Public Attributes
static final String myPropertiesPath = "guiContainers/"
Private Attributes
XMLParser myParser
Dimension2D mySize
Region myRegion
List< Node > myChildren
Detailed Description
Definition at line 17 of file CoreContainerSetup.java.
Member Function Documentation
List<Node> gamePlayer.guiContainers.coreContainers.CoreContainerSetup.getChildList ()
Definition at line 55 of file CoreContainerSetup.java.
References gamePlayer.guiContainers.coreContainers.CoreContainerSetup.myChildren.
Referenced by gamePlayer.guiContainers.coreContainers.RightContainer.initialize(), gamePlayer.guiContainers.coreContainers.TopContainer.initialize(), gamePlayer.guiContainers.coreContainers.LeftContainer.initialize(), gamePlayer.guiContainers.coreContainers.BottomContainer.initialize(), and gamePlayer.guiContainers.coreContainers.CenterContainer.initialize().
void gamePlayer.guiContainers.coreContainers.CoreContainerSetup.initialize (Region r, double width, double height, Dimension2D containerSize)
Definition at line 41 of file CoreContainerSetup.java.
References utilities.reflection.Reflection.createInstance(), gamePlayer.mainClasses.guiBuilder.GuiElement.getNode(), utilities.XMLParsing.XMLParser.getValuesFromTag(), gamePlayer.mainClasses.guiBuilder.GuiElement.initialize(), gamePlayer.guiContainers.coreContainers.CoreContainerSetup.setDimensions(), and gamePlayer.guiContainers.coreContainers.CoreContainerSetup.setRegion().
Referenced by gamePlayer.guiContainers.coreContainers.RightContainer.initialize(), gamePlayer.guiContainers.coreContainers.TopContainer.initialize(), gamePlayer.guiContainers.coreContainers.LeftContainer.initialize(), gamePlayer.guiContainers.coreContainers.BottomContainer.initialize(), and gamePlayer.guiContainers.coreContainers.CenterContainer.initialize().
void gamePlayer.guiContainers.coreContainers.CoreContainerSetup.setDimensions (double width, double height, Dimension2D containerSize)
Definition at line 34 of file CoreContainerSetup.java.
Referenced by gamePlayer.guiContainers.coreContainers.CoreContainerSetup.initialize().
void gamePlayer.guiContainers.coreContainers.CoreContainerSetup.setRegion (Region r, String className)
Definition at line 26 of file CoreContainerSetup.java.
References gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_ELEMENT_PROPERTIES_PATH.
Referenced by gamePlayer.guiContainers.coreContainers.CoreContainerSetup.initialize().
Member Data Documentation
List<Node> gamePlayer.guiContainers.coreContainers.CoreContainerSetup.myChildren private
Definition at line 22 of file CoreContainerSetup.java.
Referenced by gamePlayer.guiContainers.coreContainers.CoreContainerSetup.getChildList().
XMLParser gamePlayer.guiContainers.coreContainers.CoreContainerSetup.myParser private
Definition at line 19 of file CoreContainerSetup.java.
final String gamePlayer.guiContainers.coreContainers.CoreContainerSetup.myPropertiesPath = "guiContainers/" static
Definition at line 24 of file CoreContainerSetup.java.
Region gamePlayer.guiContainers.coreContainers.CoreContainerSetup.myRegion private
Definition at line 21 of file CoreContainerSetup.java.
Dimension2D gamePlayer.guiContainers.coreContainers.CoreContainerSetup.mySize private
Definition at line 20 of file CoreContainerSetup.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiContainers/coreContainers/CoreContainerSetup.java