voogasalad_LosTorres: gamePlayer.guiItems.gameWorld.SelectableGameItem Class Reference
gamePlayer.guiItems.gameWorld.SelectableGameItem Class Reference
Public Member Functions
SelectableGameItem (int ID, Point2D loc, ImageView imageView)
Public Member Functions inherited from gamePlayer.guiItems.gameWorld.GameItem
GameItem (int ID, Point2D loc, ImageView imageView)
int getID ()
Node getNode ()
Protected Member Functions
void init ()
Protected Member Functions inherited from gamePlayer.guiItems.gameWorld.GameItem
void init ()
Private Member Functions
void select ()
Private Attributes
XMLParser myParser
Circle mySelectCircle
BooleanProperty selectedProperty
Additional Inherited Members
Protected Attributes inherited from gamePlayer.guiItems.gameWorld.GameItem
int myID
DoubleProperty X
ImageView myImageView
Group myGroup
Node myNode
Package Attributes inherited from gamePlayer.guiItems.gameWorld.GameItem
DoubleProperty Y
DoubleProperty rotation
Detailed Description
Author
brianbolze
Definition at line 16 of file SelectableGameItem.java.
Constructor & Destructor Documentation
gamePlayer.guiItems.gameWorld.SelectableGameItem.SelectableGameItem (int ID, Point2D loc, ImageView imageView)
Definition at line 23 of file SelectableGameItem.java.
Member Function Documentation
void gamePlayer.guiItems.gameWorld.SelectableGameItem.init () protected
Definition at line 27 of file SelectableGameItem.java.
References utilities.XMLParsing.XMLParser.getDoubleValuesFromTag(), utilities.XMLParsing.XMLParser.getValuesFromTag(), gamePlayer.guiItems.gameWorld.GameItem.myGroup, and gamePlayer.guiItems.gameWorld.SelectableGameItem.select().
void gamePlayer.guiItems.gameWorld.SelectableGameItem.select () private
Definition at line 47 of file SelectableGameItem.java.
Referenced by gamePlayer.guiItems.gameWorld.SelectableGameItem.init().
Member Data Documentation
XMLParser gamePlayer.guiItems.gameWorld.SelectableGameItem.myParser private
Definition at line 18 of file SelectableGameItem.java.
Circle gamePlayer.guiItems.gameWorld.SelectableGameItem.mySelectCircle private
Definition at line 19 of file SelectableGameItem.java.
BooleanProperty gamePlayer.guiItems.gameWorld.SelectableGameItem.selectedProperty private
Definition at line 20 of file SelectableGameItem.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItems/gameWorld/SelectableGameItem.java