voogasalad_LosTorres: gamePlayer.mainClasses.managers.GuiManager Class Reference
gamePlayer.mainClasses.managers.GuiManager Class Reference
Public Member Functions
GuiManager (Stage stage)
void init ()
void loadGame ()
void loadState ()
void startSinglePlayerGame (String directoryPath)
void play ()
void joinMultiPlayerGame ()
void prepareMultiPlayerGame (String directoryPath)
boolean multiPlayerGameIsReady ()
void startMultiPlayerGame ()
void saveGame ()
void registerStatsBoard (HUD hud)
void registerGameWorld (GameWorld world)
void registerUpgradePanel (TowerUpgradePanel upgradePanel)
void setGameStats (List< GameStat > stats)
void pause ()
void changeTheme ()
void normalSpeed ()
void fastForward ()
void registerStore (Store store)
void fillStore (Collection< TowerInfoObject > towersAvailable)
void refreshStore ()
boolean upgradeTower (ImageView imageView, String upgradeName)
void makeTower (String towerName, double x, double y)
void placeTower (String towerName)
void registerMessageDisplayListener (MessageDisplay display)
void displayMessage (String message, boolean error)
void clearMessageDisplay ()
void sellTower (ImageView myTowerImageView, TowerIndicator indicator)
boolean validPlacement (double x, double y)
void changeSpeed (double d)
void escapePlace ()
void switchGame ()
void replayGame ()
void selectGame ()
Static Public Attributes
static final String LOSS = "GAME OVER"
static final String WIN = "Congratulations, you won"
static final String NO_UPGRADE = "No update available"
static final String NO_GOLD = "Not enough gold available"
static final String ESCAPE_TEXT = "Press ESC to escape from tower placement"
static final String SCORE = "Your score: "
static final String PLAY_AGAIN = "Click anywhere on the map to play again"
Private Member Functions
void startGame (String directoryPath)
void initializeNewGameElements (String directoryPath)
void addBackground (String directory)
void setUpHUD ()
void endGame (String endCondition)
void selectTower (String towerName, ImageView tower)
void deselectTower (TowerIndicator indicator, ImageView tower, String towerName)
boolean checkGold (String towerName)
void makeTowerMap ()
Private Attributes
Stage myStage
MainEngineManager myEngineManager
CoOpManager myCoOpManager
TowerIndicator activeIndicator
ImageView activeTower
boolean interactionAllowed
Store myStore
HUD myHUD
GameWorld myGameWorld
TowerUpgradePanel myUpgradePanel
MessageDisplay myMessageDisplay
Map< String, TowerInfoObject > towerMap
List< GameStat > gameStats
double myScore
boolean isCoOp
String myDirectory
GameStat level
GameStat health
GameStat gold
DoubleProperty endgame
Static Private Attributes
static final String guiBuilderPropertiesPath = "./src/gamePlayer/properties/GuiBuilderProperties.XML"
Detailed Description
Class controls all GUI items and MUST implement ALL of the interfaces in the guiItemsListeners package The game engine accesses GUI resources through this class
Author
allankiplagat, Greg Lyons
Definition at line 54 of file GuiManager.java.
Constructor & Destructor Documentation
gamePlayer.mainClasses.managers.GuiManager.GuiManager (Stage stage)
Definition at line 93 of file GuiManager.java.
References gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_MANAGER.
Member Function Documentation
void gamePlayer.mainClasses.managers.GuiManager.addBackground (String directory) private
Definition at line 209 of file GuiManager.java.
References gamePlayer.guiItems.gameWorld.GameWorld.setBackground().
Referenced by gamePlayer.mainClasses.managers.GuiManager.initializeNewGameElements(), and gamePlayer.mainClasses.managers.GuiManager.startGame().
void gamePlayer.mainClasses.managers.GuiManager.changeSpeed (double d)
Implements gamePlayer.guiItemsListeners.SpeedSliderListener.
Definition at line 436 of file GuiManager.java.
References gameEngine.MainEngineManager.changeRunSpeed().
void gamePlayer.mainClasses.managers.GuiManager.changeTheme ()
Implements gamePlayer.guiItemsListeners.VoogaMenuBarListener.
Definition at line 251 of file GuiManager.java.
References gamePlayer.guiFeatures.FileLoader.getInstance(), and gamePlayer.guiFeatures.FileLoader.load().
Referenced by gamePlayer.guiItems.voogaMenuBar.menuItems.ChangeThemeMenuItem.initialize().
boolean gamePlayer.mainClasses.managers.GuiManager.checkGold (String towerName) private
Definition at line 390 of file GuiManager.java.
References gamePlayer.guiItems.headsUpDisplay.GameStat.getStatValue().
Referenced by gamePlayer.mainClasses.managers.GuiManager.placeTower().
void gamePlayer.mainClasses.managers.GuiManager.clearMessageDisplay ()
Implements gamePlayer.guiItemsListeners.MessageDisplayListener.
Definition at line 417 of file GuiManager.java.
References gamePlayer.guiItems.messageDisplay.MessageDisplay.clear().
void gamePlayer.mainClasses.managers.GuiManager.deselectTower (TowerIndicator indicator, ImageView tower, String towerName) private
Definition at line 381 of file GuiManager.java.
References gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.deselectTower(), gamePlayer.guiItems.gameWorld.GameWorld.getMap(), and gamePlayer.mainClasses.managers.GuiManager.selectTower().
Referenced by gamePlayer.mainClasses.managers.GuiManager.selectTower().
void gamePlayer.mainClasses.managers.GuiManager.displayMessage (String message, boolean error)
Implements gamePlayer.guiItemsListeners.MessageDisplayListener.
Definition at line 412 of file GuiManager.java.
References gamePlayer.guiItems.messageDisplay.MessageDisplay.showMessage().
Referenced by gamePlayer.guiFeatures.TowerPlacer.drop(), gamePlayer.mainClasses.managers.GuiManager.endGame(), gamePlayer.mainClasses.managers.GuiManager.escapePlace(), gamePlayer.mainClasses.managers.GuiManager.makeTower(), gamePlayer.mainClasses.managers.GuiManager.placeTower(), and gamePlayer.mainClasses.managers.GuiManager.upgradeTower().
void gamePlayer.mainClasses.managers.GuiManager.endGame (String endCondition) private
Definition at line 339 of file GuiManager.java.
References gamePlayer.mainClasses.managers.GuiManager.displayMessage(), and gamePlayer.guiItems.gameWorld.GameWorld.getMap().
Referenced by gamePlayer.mainClasses.managers.GuiManager.initializeNewGameElements().
void gamePlayer.mainClasses.managers.GuiManager.escapePlace ()
Implements gamePlayer.guiItemsListeners.StoreListener.
Definition at line 454 of file GuiManager.java.
References gamePlayer.guiItems.messageDisplay.MessageDisplay.DEFAULT, gamePlayer.mainClasses.managers.GuiManager.displayMessage(), and gamePlayer.guiItems.gameWorld.GameWorld.getMap().
void gamePlayer.mainClasses.managers.GuiManager.fastForward ()
Implements gamePlayer.guiItemsListeners.SpeedButtonListener.
Definition at line 269 of file GuiManager.java.
References gamePlayer.mainClasses.managers.GuiManager.play().
void gamePlayer.mainClasses.managers.GuiManager.fillStore (Collection< TowerInfoObject > towersAvailable)
Implements gamePlayer.guiItemsListeners.StoreListener.
Definition at line 281 of file GuiManager.java.
References gamePlayer.guiItems.store.Store.fillStore().
Referenced by gamePlayer.mainClasses.managers.GuiManager.initializeNewGameElements(), and gamePlayer.mainClasses.managers.GuiManager.startGame().
void gamePlayer.mainClasses.managers.GuiManager.init ()
Definition at line 99 of file GuiManager.java.
References gamePlayer.mainClasses.guiBuilder.GuiBuilder.build(), gamePlayer.mainClasses.guiBuilder.GuiConstants.DYNAMIC_SIZING, and gamePlayer.mainClasses.guiBuilder.GuiBuilder.getInstance().
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.newGame(), gamePlayer.mainClasses.managers.GuiManager.replayGame(), gamePlayer.mainClasses.managers.GuiManager.startMultiPlayerGame(), gamePlayer.mainClasses.managers.WelcomeManager.startSinglePlayerGame(), and gamePlayer.mainClasses.welcomeScreen.GameStartManager.startSinglePlayerGame().
void gamePlayer.mainClasses.managers.GuiManager.initializeNewGameElements (String directoryPath) private
Definition at line 191 of file GuiManager.java.
References gamePlayer.mainClasses.managers.GuiManager.addBackground(), gamePlayer.mainClasses.managers.GuiManager.endGame(), gamePlayer.mainClasses.managers.GuiManager.fillStore(), gameEngine.MainEngineManager.getAllTowerTypeInformation(), gameEngine.MainEngineManager.getWinStatus(), gamePlayer.mainClasses.managers.GuiManager.makeTowerMap(), and gamePlayer.mainClasses.managers.GuiManager.setUpHUD().
Referenced by gamePlayer.mainClasses.managers.GuiManager.startMultiPlayerGame(), and gamePlayer.mainClasses.managers.GuiManager.startSinglePlayerGame().
void gamePlayer.mainClasses.managers.GuiManager.joinMultiPlayerGame ()
Definition at line 147 of file GuiManager.java.
References gameEngine.CoOpManager.joinGame(), gamePlayer.mainClasses.managers.GuiManager.myCoOpManager, and gamePlayer.mainClasses.managers.GuiManager.startMultiPlayerGame().
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.joinMultiPlayerGame(), and gamePlayer.mainClasses.welcomeScreen.GameStartManager.joinMultiPlayerGame().
void gamePlayer.mainClasses.managers.GuiManager.loadGame ()
Implements gamePlayer.guiItemsListeners.VoogaMenuBarListener.
Definition at line 117 of file GuiManager.java.
References gamePlayer.guiFeatures.FileLoader.getInstance(), gamePlayer.guiFeatures.FileLoader.loadDirectory(), and gamePlayer.mainClasses.managers.GuiManager.startGame().
void gamePlayer.mainClasses.managers.GuiManager.loadState ()
Implements gamePlayer.guiItemsListeners.VoogaMenuBarListener.
Definition at line 125 of file GuiManager.java.
References gamePlayer.guiFeatures.FileLoader.getInstance(), gamePlayer.guiFeatures.FileLoader.load(), and gameEngine.MainEngineManager.loadState().
void gamePlayer.mainClasses.managers.GuiManager.makeTower (String towerName, double x, double y)
Definition at line 345 of file GuiManager.java.
References gameEngine.MainEngineManager.addTower(), gameEngine.MainEngineManager.checkGold(), gamePlayer.guiItems.messageDisplay.MessageDisplay.DEFAULT, gamePlayer.mainClasses.managers.GuiManager.displayMessage(), gameEngine.MainEngineManager.getGoldProperty(), gamePlayer.mainClasses.managers.GuiManager.selectTower(), and gameEngine.MainEngineManager.setMyGold().
Referenced by gamePlayer.guiFeatures.TowerPlacer.drop().
void gamePlayer.mainClasses.managers.GuiManager.makeTowerMap () private
Definition at line 440 of file GuiManager.java.
References gameEngine.Data.TowerInfoObject.getMyUpgrade(), and gameEngine.Data.TowerInfoObject.getName().
Referenced by gamePlayer.mainClasses.managers.GuiManager.initializeNewGameElements(), and gamePlayer.mainClasses.managers.GuiManager.startGame().
boolean gamePlayer.mainClasses.managers.GuiManager.multiPlayerGameIsReady ()
Definition at line 161 of file GuiManager.java.
References gameEngine.CoOpManager.isReady().
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.pollEngineForMultiPlayerReadiness(), and gamePlayer.mainClasses.welcomeScreen.GameStartManager.pollEngineForMultiPlayerReadiness().
void gamePlayer.mainClasses.managers.GuiManager.normalSpeed ()
Implements gamePlayer.guiItemsListeners.SpeedButtonListener.
Definition at line 262 of file GuiManager.java.
References gamePlayer.mainClasses.managers.GuiManager.play().
void gamePlayer.mainClasses.managers.GuiManager.pause ()
Implements gamePlayer.guiItemsListeners.PlayButtonListener.
Definition at line 244 of file GuiManager.java.
References gameEngine.MainEngineManager.pause().
void gamePlayer.mainClasses.managers.GuiManager.placeTower (String towerName)
Implements gamePlayer.guiItemsListeners.StoreListener.
Definition at line 396 of file GuiManager.java.
References gamePlayer.mainClasses.managers.GuiManager.checkGold(), gamePlayer.mainClasses.managers.GuiManager.displayMessage(), gamePlayer.guiFeatures.TowerPlacer.getInstance(), gamePlayer.guiItems.gameWorld.GameWorld.getMap(), and gamePlayer.guiFeatures.TowerPlacer.placeItem().
void gamePlayer.mainClasses.managers.GuiManager.play ()
Implements gamePlayer.guiItemsListeners.PlayButtonListener.
Definition at line 141 of file GuiManager.java.
References gameEngine.MainEngineManager.resume().
Referenced by gamePlayer.mainClasses.managers.GuiManager.fastForward(), and gamePlayer.mainClasses.managers.GuiManager.normalSpeed().
void gamePlayer.mainClasses.managers.GuiManager.prepareMultiPlayerGame (String directoryPath)
Definition at line 155 of file GuiManager.java.
References gamePlayer.mainClasses.managers.GuiManager.myCoOpManager, and gameEngine.CoOpManager.startNewGame().
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.startMultiPlayerGame(), and gamePlayer.mainClasses.welcomeScreen.GameStartManager.startMultiPlayerGame().
void gamePlayer.mainClasses.managers.GuiManager.refreshStore ()
Implements gamePlayer.guiItemsListeners.StoreListener.
Definition at line 292 of file GuiManager.java.
References gamePlayer.guiItems.store.Store.refreshStore().
Referenced by gamePlayer.mainClasses.testGameManager.TestGameManager.testGuiStore().
void gamePlayer.mainClasses.managers.GuiManager.registerGameWorld (GameWorld world)
Implements gamePlayer.guiItemsListeners.GameWorldListener.
Definition at line 229 of file GuiManager.java.
void gamePlayer.mainClasses.managers.GuiManager.registerMessageDisplayListener (MessageDisplay display)
Implements gamePlayer.guiItemsListeners.MessageDisplayListener.
Definition at line 407 of file GuiManager.java.
Referenced by gamePlayer.guiItems.messageDisplay.MessageDisplay.initialize().
void gamePlayer.mainClasses.managers.GuiManager.registerStatsBoard (HUD hud)
Implements gamePlayer.guiItemsListeners.HUDListener.
Definition at line 224 of file GuiManager.java.
Referenced by gamePlayer.guiItems.headsUpDisplay.HUD.initialize().
void gamePlayer.mainClasses.managers.GuiManager.registerStore (Store store)
Implements gamePlayer.guiItemsListeners.StoreListener.
Definition at line 276 of file GuiManager.java.
void gamePlayer.mainClasses.managers.GuiManager.registerUpgradePanel (TowerUpgradePanel upgradePanel)
Implements gamePlayer.guiItemsListeners.UpgradeListener.
Definition at line 234 of file GuiManager.java.
void gamePlayer.mainClasses.managers.GuiManager.replayGame ()
Definition at line 467 of file GuiManager.java.
References gamePlayer.mainClasses.managers.GuiManager.init(), gamePlayer.mainClasses.managers.GuiManager.startMultiPlayerGame(), and gamePlayer.mainClasses.managers.GuiManager.startSinglePlayerGame().
void gamePlayer.mainClasses.managers.GuiManager.saveGame ()
Implements gamePlayer.guiItemsListeners.VoogaMenuBarListener.
Definition at line 216 of file GuiManager.java.
References gamePlayer.guiFeatures.FileLoader.getInstance(), gamePlayer.guiFeatures.FileLoader.save(), and gameEngine.MainEngineManager.saveState().
void gamePlayer.mainClasses.managers.GuiManager.selectGame ()
Definition at line 473 of file GuiManager.java.
void gamePlayer.mainClasses.managers.GuiManager.selectTower (String towerName, ImageView tower) private
Definition at line 364 of file GuiManager.java.
References gamePlayer.mainClasses.managers.GuiManager.activeIndicator, gamePlayer.mainClasses.managers.GuiManager.deselectTower(), gamePlayer.guiItems.gameWorld.GameWorld.getMap(), gameEngine.MainEngineManager.getTowerName(), utilities.JavaFXutilities.imageView.CenteredImageView.getXCenter(), utilities.JavaFXutilities.imageView.CenteredImageView.getYCenter(), and gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.setCurrentTower().
Referenced by gamePlayer.mainClasses.managers.GuiManager.deselectTower(), gamePlayer.mainClasses.managers.GuiManager.makeTower(), and gamePlayer.mainClasses.managers.GuiManager.upgradeTower().
void gamePlayer.mainClasses.managers.GuiManager.sellTower (ImageView myTowerImageView, TowerIndicator indicator)
Implements gamePlayer.guiItemsListeners.UpgradeListener.
Definition at line 422 of file GuiManager.java.
References gamePlayer.guiItems.gameWorld.GameWorld.getMap(), and gameEngine.MainEngineManager.sellTower().
void gamePlayer.mainClasses.managers.GuiManager.setGameStats (List< GameStat > stats)
Implements gamePlayer.guiItemsListeners.HUDListener.
Definition at line 239 of file GuiManager.java.
References gamePlayer.guiItems.headsUpDisplay.HUD.setGameStats().
Referenced by gamePlayer.mainClasses.managers.GuiManager.setUpHUD(), gamePlayer.mainClasses.managers.GuiManager.startMultiPlayerGame(), and gamePlayer.mainClasses.testGameManager.TestGameManager.testLoadingGuiHUD().
void gamePlayer.mainClasses.managers.GuiManager.setUpHUD () private
Definition at line 317 of file GuiManager.java.
References gameEngine.MainEngineManager.getCurrentLevelProperty(), gameEngine.MainEngineManager.getGoldProperty(), gameEngine.MainEngineManager.getHealthProperty(), gamePlayer.guiItems.headsUpDisplay.GameStat.setGameStat(), gamePlayer.mainClasses.managers.GuiManager.setGameStats(), and gamePlayer.guiItems.headsUpDisplay.GameStat.statValueProperty().
Referenced by gamePlayer.mainClasses.managers.GuiManager.initializeNewGameElements(), and gamePlayer.mainClasses.managers.GuiManager.startGame().
void gamePlayer.mainClasses.managers.GuiManager.startGame (String directoryPath) private
Definition at line 106 of file GuiManager.java.
References gamePlayer.mainClasses.managers.GuiManager.addBackground(), gamePlayer.mainClasses.managers.GuiManager.fillStore(), gameEngine.MainEngineManager.getAllTowerTypeInformation(), gamePlayer.guiItems.gameWorld.GameWorld.getMap(), gameEngine.MainEngineManager.initializeGame(), gamePlayer.mainClasses.managers.GuiManager.makeTowerMap(), and gamePlayer.mainClasses.managers.GuiManager.setUpHUD().
Referenced by gamePlayer.mainClasses.managers.GuiManager.loadGame().
void gamePlayer.mainClasses.managers.GuiManager.startMultiPlayerGame ()
Definition at line 165 of file GuiManager.java.
References gamePlayer.guiItems.store.Store.freeze(), gamePlayer.guiItems.gameWorld.GameWorld.getMap(), gameEngine.CoOpManager.getTimer(), gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_MANAGER, gamePlayer.mainClasses.managers.GuiManager.init(), gameEngine.CoOpManager.initializeGame(), gamePlayer.mainClasses.managers.GuiManager.initializeNewGameElements(), gamePlayer.guiItems.headsUpDisplay.GameStat.setGameStat(), gamePlayer.mainClasses.managers.GuiManager.setGameStats(), gamePlayer.guiItems.headsUpDisplay.GameStat.statValueProperty(), and gamePlayer.guiItems.store.Store.unfreeze().
Referenced by gamePlayer.mainClasses.managers.GuiManager.joinMultiPlayerGame(), gamePlayer.mainClasses.managers.WelcomeManager.pollEngineForMultiPlayerReadiness(), gamePlayer.mainClasses.welcomeScreen.GameStartManager.pollEngineForMultiPlayerReadiness(), and gamePlayer.mainClasses.managers.GuiManager.replayGame().
void gamePlayer.mainClasses.managers.GuiManager.startSinglePlayerGame (String directoryPath)
Definition at line 132 of file GuiManager.java.
References gamePlayer.guiItems.gameWorld.GameWorld.getMap(), gameEngine.MainEngineManager.initializeGame(), and gamePlayer.mainClasses.managers.GuiManager.initializeNewGameElements().
Referenced by gamePlayer.mainClasses.managers.GuiManager.replayGame(), gamePlayer.mainClasses.managers.WelcomeManager.startSinglePlayerGame(), and gamePlayer.mainClasses.welcomeScreen.GameStartManager.startSinglePlayerGame().
void gamePlayer.mainClasses.managers.GuiManager.switchGame ()
Definition at line 463 of file GuiManager.java.
boolean gamePlayer.mainClasses.managers.GuiManager.upgradeTower (ImageView imageView, String upgradeName)
Implements gamePlayer.guiItemsListeners.UpgradeListener.
Definition at line 297 of file GuiManager.java.
References gameEngine.MainEngineManager.checkGold(), gamePlayer.mainClasses.managers.GuiManager.displayMessage(), gameEngine.MainEngineManager.getGoldProperty(), gamePlayer.mainClasses.managers.GuiManager.selectTower(), gameEngine.MainEngineManager.setMyGold(), and gameEngine.MainEngineManager.upgrade().
boolean gamePlayer.mainClasses.managers.GuiManager.validPlacement (double x, double y)
Definition at line 431 of file GuiManager.java.
References gameEngine.MainEngineManager.validateTower().
Referenced by gamePlayer.guiFeatures.TowerPlacer.validPlacement().
Member Data Documentation
TowerIndicator gamePlayer.mainClasses.managers.GuiManager.activeIndicator private
Definition at line 73 of file GuiManager.java.
Referenced by gamePlayer.mainClasses.managers.GuiManager.selectTower().
ImageView gamePlayer.mainClasses.managers.GuiManager.activeTower private
Definition at line 74 of file GuiManager.java.
DoubleProperty gamePlayer.mainClasses.managers.GuiManager.endgame private
Definition at line 91 of file GuiManager.java.
final String gamePlayer.mainClasses.managers.GuiManager.ESCAPE_TEXT = "Press ESC to escape from tower placement" static
Definition at line 65 of file GuiManager.java.
List<GameStat> gamePlayer.mainClasses.managers.GuiManager.gameStats private
Definition at line 83 of file GuiManager.java.
GameStat gamePlayer.mainClasses.managers.GuiManager.gold private
Definition at line 90 of file GuiManager.java.
final String gamePlayer.mainClasses.managers.GuiManager.guiBuilderPropertiesPath = "./src/gamePlayer/properties/GuiBuilderProperties.XML" static private
Definition at line 59 of file GuiManager.java.
GameStat gamePlayer.mainClasses.managers.GuiManager.health private
Definition at line 89 of file GuiManager.java.
boolean gamePlayer.mainClasses.managers.GuiManager.interactionAllowed private
Definition at line 75 of file GuiManager.java.
boolean gamePlayer.mainClasses.managers.GuiManager.isCoOp private
Definition at line 85 of file GuiManager.java.
GameStat gamePlayer.mainClasses.managers.GuiManager.level private
Definition at line 88 of file GuiManager.java.
final String gamePlayer.mainClasses.managers.GuiManager.LOSS = "GAME OVER" static
Definition at line 61 of file GuiManager.java.
CoOpManager gamePlayer.mainClasses.managers.GuiManager.myCoOpManager private
Definition at line 71 of file GuiManager.java.
Referenced by gamePlayer.mainClasses.managers.GuiManager.joinMultiPlayerGame(), and gamePlayer.mainClasses.managers.GuiManager.prepareMultiPlayerGame().
String gamePlayer.mainClasses.managers.GuiManager.myDirectory private
Definition at line 86 of file GuiManager.java.
MainEngineManager gamePlayer.mainClasses.managers.GuiManager.myEngineManager private
Definition at line 70 of file GuiManager.java.
GameWorld gamePlayer.mainClasses.managers.GuiManager.myGameWorld private
Definition at line 79 of file GuiManager.java.
HUD gamePlayer.mainClasses.managers.GuiManager.myHUD private
Definition at line 78 of file GuiManager.java.
MessageDisplay gamePlayer.mainClasses.managers.GuiManager.myMessageDisplay private
Definition at line 81 of file GuiManager.java.
double gamePlayer.mainClasses.managers.GuiManager.myScore private
Definition at line 84 of file GuiManager.java.
Stage gamePlayer.mainClasses.managers.GuiManager.myStage private
Definition at line 69 of file GuiManager.java.
Store gamePlayer.mainClasses.managers.GuiManager.myStore private
Definition at line 77 of file GuiManager.java.
TowerUpgradePanel gamePlayer.mainClasses.managers.GuiManager.myUpgradePanel private
Definition at line 80 of file GuiManager.java.
final String gamePlayer.mainClasses.managers.GuiManager.NO_GOLD = "Not enough gold available" static
Definition at line 64 of file GuiManager.java.
final String gamePlayer.mainClasses.managers.GuiManager.NO_UPGRADE = "No update available" static
Definition at line 63 of file GuiManager.java.
final String gamePlayer.mainClasses.managers.GuiManager.PLAY_AGAIN = "Click anywhere on the map to play again" static
Definition at line 67 of file GuiManager.java.
final String gamePlayer.mainClasses.managers.GuiManager.SCORE = "Your score: " static
Definition at line 66 of file GuiManager.java.
Map<String, TowerInfoObject> gamePlayer.mainClasses.managers.GuiManager.towerMap private
Definition at line 82 of file GuiManager.java.
final String gamePlayer.mainClasses.managers.GuiManager.WIN = "Congratulations, you won" static
Definition at line 62 of file GuiManager.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/mainClasses/managers/GuiManager.java