voogasalad_LosTorres: gameEngine.actors.behaviors.IBehavior Interface Reference
gameEngine.actors.behaviors.IBehavior Interface Reference
Public Member Functions
void execute (BaseActor actor)
IBehavior copy ()
String toString ()
Detailed Description
Interface that defines the behaviors of actors in the game All types of behaviors execute on a specific actor
Author
Chase Malik, Timesh Patel
Definition at line 12 of file IBehavior.java.
Member Function Documentation
IBehavior gameEngine.actors.behaviors.IBehavior.copy ()
Returns a copy of the behavior, which allows for copying entire actors
Returns
copy of the behavior
Implemented in gameEngine.actors.behaviors.EnemyHomingMovement, gameEngine.actors.behaviors.AIMovement, gameEngine.actors.behaviors.LinearMovement, gameEngine.actors.behaviors.ClosestRangeAttack, gameEngine.actors.behaviors.FarthestRangeAttack, gameEngine.actors.behaviors.NullBehavior, gameEngine.actors.behaviors.StrongestRangeAttack, gameEngine.actors.behaviors.SlowEffect, gameEngine.actors.behaviors.AoEEffect, gameEngine.actors.behaviors.AoEAttack, gameEngine.actors.behaviors.DoTOnHit, gameEngine.actors.behaviors.TowerRangeEffect, gameEngine.actors.behaviors.PiercableDefense, gameEngine.actors.behaviors.GoldGenEffect, gameEngine.actors.behaviors.HealEffect, gameEngine.actors.behaviors.SimpleDefense, gameEngine.actors.behaviors.NullAttack, and gameEngine.actors.behaviors.EarthQuakeEffect.
Referenced by gameEngine.actors.ProjectileInfo.copy(), gameEngine.actors.behaviors.BaseDefendBehavior.gotHit(), and gameEngine.actors.ProjectileInfo.ProjectileInfo().
void gameEngine.actors.behaviors.IBehavior.execute (BaseActor actor)
Execute method that executes the specific behavior on the given actor
Parameters
actor that is executed on
Implemented in gameEngine.actors.behaviors.BaseAttack, gameEngine.actors.behaviors.BaseDefendBehavior, gameEngine.actors.behaviors.BaseEffect, gameEngine.actors.behaviors.LinearMovement, gameEngine.actors.behaviors.AIMovement, gameEngine.actors.behaviors.NullBehavior, and gameEngine.actors.behaviors.EnemyHomingMovement.
Referenced by gameEngine.actors.behaviors.BaseDefendBehavior.gotHit().
String gameEngine.actors.behaviors.IBehavior.toString ()
Implemented in gameEngine.actors.behaviors.BaseMovementBehavior, gameEngine.actors.behaviors.BaseEffect, and gameEngine.actors.behaviors.BaseAttack.
Referenced by gameEngine.actors.BaseActor.addDebuff().
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/behaviors/IBehavior.java