voogasalad_LosTorres: utilities.JavaFXutilities.ratioSizing.RatiosToDim Class Reference
utilities.JavaFXutilities.ratioSizing.RatiosToDim Class Reference
Static Public Member Functions
static Dimension2D convert (Dimension2D containerSize, Dimension2D ratio)
Detailed Description
Author
Greg Lyons
This class's static convert method is used to multiply ratios by given width and height dimensions to output a new width and height Dimension2D.
The GuiBuilder system uses many XML files that contain ratios for sizing within dimensions of a container, and this class helps to avoid repeated code in parsing these XML files.
Definition at line 17 of file RatiosToDim.java.
Member Function Documentation
static Dimension2D utilities.JavaFXutilities.ratioSizing.RatiosToDim.convert (Dimension2D containerSize, Dimension2D ratio) static
Definition at line 19 of file RatiosToDim.java.
Referenced by gamePlayer.guiItems.headsUpDisplay.HUD.initialize(), gamePlayer.guiItems.messageDisplay.MessageDisplay.initialize(), gamePlayer.guiItems.store.Store.initialize(), gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.initialize(), and gamePlayer.guiItems.controlDockButtons.ControlDockSlider.setUpSizing().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/JavaFXutilities/ratioSizing/RatiosToDim.java