voogasalad_LosTorres: gamePlayer.guiItems.store.Store Class Reference
gamePlayer.guiItems.store.Store Class Reference
Public Member Functions
void initialize (Dimension2D containerSize)
void fillStore (List< StoreItem > storeItems)
void refreshStore ()
Node getNode ()
void freeze ()
void unfreeze ()
Private Member Functions
void checkEscape (Event ke)
void addStoreItem (StoreItem storeItem)
void placeTower (String towerName)
void showGraphic (Button b, ImageView v)
void showCost (Button b, int cost)
Private Attributes
TilePane myTilePane
XMLParser myParser
Dimension2D myPaneSize
StoreListener myListener = GuiConstants.GUI_MANAGER
Dimension2D buttonSize
Dimension2D imageSize
List< StoreItem > storeItemList
Additional Inherited Members
Static Public Attributes inherited from gamePlayer.guiItems.GuiItem
static String myPropertiesPath = "guiItems/"
Detailed Description
Definition at line 25 of file Store.java.
Member Function Documentation
void gamePlayer.guiItems.store.Store.addStoreItem (StoreItem storeItem) private
Definition at line 75 of file Store.java.
References gamePlayer.guiItems.store.StoreItem.getCost(), gamePlayer.guiItems.store.StoreItem.getImageView(), gamePlayer.guiItems.store.StoreItem.getName(), gamePlayer.guiItems.store.Store.placeTower(), gamePlayer.guiItems.store.Store.showCost(), and gamePlayer.guiItems.store.Store.showGraphic().
Referenced by gamePlayer.guiItems.store.Store.fillStore().
void gamePlayer.guiItems.store.Store.checkEscape (Event ke) private
Definition at line 59 of file Store.java.
References gamePlayer.guiItemsListeners.StoreListener.escapePlace().
Referenced by gamePlayer.guiItems.store.Store.placeTower().
void gamePlayer.guiItems.store.Store.fillStore (List< StoreItem > storeItems)
Definition at line 66 of file Store.java.
References gamePlayer.guiItems.store.Store.addStoreItem(), and gamePlayer.guiItems.store.Store.refreshStore().
Referenced by gamePlayer.mainClasses.managers.GuiManager.fillStore().
void gamePlayer.guiItems.store.Store.freeze ()
Definition at line 130 of file Store.java.
Referenced by gamePlayer.mainClasses.managers.GuiManager.startMultiPlayerGame().
Node gamePlayer.guiItems.store.Store.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 122 of file Store.java.
void gamePlayer.guiItems.store.Store.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 36 of file Store.java.
References utilities.JavaFXutilities.ratioSizing.RatiosToDim.convert(), utilities.XMLParsing.XMLParser.getDimension(), gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_ELEMENT_PROPERTIES_PATH, gamePlayer.guiItems.GuiItem.myPropertiesPath, and gamePlayer.guiItemsListeners.StoreListener.registerStore().
void gamePlayer.guiItems.store.Store.placeTower (String towerName) private
Definition at line 95 of file Store.java.
References gamePlayer.guiItems.store.Store.checkEscape(), and gamePlayer.guiItemsListeners.StoreListener.placeTower().
Referenced by gamePlayer.guiItems.store.Store.addStoreItem().
void gamePlayer.guiItems.store.Store.refreshStore ()
Definition at line 109 of file Store.java.
Referenced by gamePlayer.guiItems.store.Store.fillStore(), and gamePlayer.mainClasses.managers.GuiManager.refreshStore().
void gamePlayer.guiItems.store.Store.showCost (Button b, int cost) private
Definition at line 104 of file Store.java.
Referenced by gamePlayer.guiItems.store.Store.addStoreItem().
void gamePlayer.guiItems.store.Store.showGraphic (Button b, ImageView v) private
Definition at line 100 of file Store.java.
Referenced by gamePlayer.guiItems.store.Store.addStoreItem().
void gamePlayer.guiItems.store.Store.unfreeze ()
Definition at line 134 of file Store.java.
Referenced by gamePlayer.mainClasses.managers.GuiManager.startMultiPlayerGame().
Member Data Documentation
Dimension2D gamePlayer.guiItems.store.Store.buttonSize private
Definition at line 30 of file Store.java.
Dimension2D gamePlayer.guiItems.store.Store.imageSize private
Definition at line 31 of file Store.java.
StoreListener gamePlayer.guiItems.store.Store.myListener = GuiConstants.GUI_MANAGER private
Definition at line 29 of file Store.java.
Dimension2D gamePlayer.guiItems.store.Store.myPaneSize private
Definition at line 28 of file Store.java.
XMLParser gamePlayer.guiItems.store.Store.myParser private
Definition at line 27 of file Store.java.
TilePane gamePlayer.guiItems.store.Store.myTilePane private
Definition at line 26 of file Store.java.
List<StoreItem> gamePlayer.guiItems.store.Store.storeItemList private
Definition at line 33 of file Store.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItems/store/Store.java