voogasalad_LosTorres: utilities.XMLParsing.XMLParser Class Reference
utilities.XMLParsing.XMLParser Class Reference
Public Member Functions
XMLParser (File file)
List< String > getBehaviorElementsFromTag (String tagName)
List< String > getValuesFromTag (String tagName)
List< String > getAllBehaviorTypes ()
List< SliderInfo > getSliderInfo (String behaviorType)
List< Integer > getIntegerValuesFromTag (String tagName)
List< Double > getDoubleValuesFromTag (String tagName)
Dimension2D getDimension (String tagName)
Private Member Functions
List< String > getValues (Element tag)
Private Attributes
Document myDocument
Static Private Attributes
static final String SLIDER_NAME = "name"
static final String SLIDER_MIN = "min"
static final String SLIDER_MAX = "max"
static final String ELEMENTS = "elements"
static final String SLIDERS = "sliders"
Detailed Description
An XML Parser utility that will allow different parts of the application to parse data files for specific information.
Author
Austin Kyker
Definition at line 28 of file XMLParser.java.
Constructor & Destructor Documentation
utilities.XMLParsing.XMLParser.XMLParser (File file)
Definition at line 37 of file XMLParser.java.
References gameAuthoring.mainclasses.Constants.XML_LOADING_ERROR.
Member Function Documentation
List<String> utilities.XMLParsing.XMLParser.getAllBehaviorTypes ()
Definition at line 82 of file XMLParser.java.
Referenced by utilities.XMLParsing.XMLParserTest.XMLParsingAllBehaviorTypesTest().
List<String> utilities.XMLParsing.XMLParser.getBehaviorElementsFromTag (String tagName)
This will be used in game authoring environment to get the different behavior classes. For instance tagName might be "Movement" and the returning list will have "FastMovement", "SlowMovement", "NoMovement", etc.
Parameters
tagName
Definition at line 55 of file XMLParser.java.
References utilities.XMLParsing.XMLParser.getValues().
Referenced by utilities.XMLParsing.XMLParserTest.XMLParsingBehaviorOptionsTest().
Dimension2D utilities.XMLParsing.XMLParser.getDimension (String tagName)
Definition at line 121 of file XMLParser.java.
References utilities.XMLParsing.XMLParser.getDoubleValuesFromTag().
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.addBackgroundImage(), gamePlayer.guiContainers.secondaryContainers.ControlDock.initialize(), gamePlayer.unusedCodeWarehouse.HUDContainer.initialize(), gamePlayer.guiItems.headsUpDisplay.HUD.initialize(), gamePlayer.guiItems.messageDisplay.MessageDisplay.initialize(), gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar.initialize(), gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.initialize(), gamePlayer.guiItems.store.Store.initialize(), gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.initialize(), gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.makeHeartImage(), gamePlayer.guiItems.controlDockButtons.ControlDockSlider.setUpSizing(), gamePlayer.guiItems.controlDockButtons.ControlDockButton.setUpSizing(), and utilities.XMLParsing.XMLParserTest.XMLParsingDimensionExtractionTest().
List<Double> utilities.XMLParsing.XMLParser.getDoubleValuesFromTag (String tagName)
Definition at line 116 of file XMLParser.java.
References utilities.XMLParsing.XMLParser.getValuesFromTag().
Referenced by gamePlayer.mainClasses.guiBuilder.GuiBuilder.build(), gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.buildButtons(), gamePlayer.unusedCodeWarehouse.guiItems.store.Store.buildInventoryContainer(), utilities.XMLParsing.XMLParser.getDimension(), gamePlayer.guiItems.gameWorld.SelectableGameItem.init(), gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.initialize(), gamePlayer.mainClasses.guiBuilder.GuiBuilder.initializeCoreContainers(), gamePlayer.guiItems.headsUpDisplay.HUD.setGameStats(), gamePlayer.guiItems.welcome.WelcomeNavigator.setupContents(), gamePlayer.guiItems.welcome.Header.setupImage(), gamePlayer.guiItems.welcome.ClickAnywherePane.setupPane(), and utilities.XMLParsing.XMLParserTest.XMLParsingDoubleExtractionTest().
List<Integer> utilities.XMLParsing.XMLParser.getIntegerValuesFromTag (String tagName)
Definition at line 111 of file XMLParser.java.
References utilities.XMLParsing.XMLParser.getValuesFromTag().
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.store.Store.buildInventoryContainer(), gamePlayer.guiItems.welcome.WelcomeNavigator.setupNavPane(), and utilities.XMLParsing.XMLParserTest.XMLParsingIntegerExtractionTest().
List<SliderInfo> utilities.XMLParsing.XMLParser.getSliderInfo (String behaviorType)
Definition at line 94 of file XMLParser.java.
Referenced by utilities.XMLParsing.XMLParserTest.XMLParsingSliderInfo().
List<String> utilities.XMLParsing.XMLParser.getValues (Element tag) private
Definition at line 69 of file XMLParser.java.
Referenced by utilities.XMLParsing.XMLParser.getBehaviorElementsFromTag(), and utilities.XMLParsing.XMLParser.getValuesFromTag().
List<String> utilities.XMLParsing.XMLParser.getValuesFromTag (String tagName)
Definition at line 62 of file XMLParser.java.
References utilities.XMLParsing.XMLParser.getValues().
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.addBackgroundImage(), gamePlayer.mainClasses.guiBuilder.GuiBuilder.build(), gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.buildButtons(), gamePlayer.unusedCodeWarehouse.guiItems.store.Store.buildHeader(), gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.buildIcon(), gamePlayer.unusedCodeWarehouse.guiItems.store.Store.buildInventoryItems(), gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar.createMenu(), gamePlayer.guiItems.welcome.WelcomeNavigator.deviceConnected(), utilities.XMLParsing.XMLParser.getDoubleValuesFromTag(), utilities.XMLParsing.XMLParser.getIntegerValuesFromTag(), gamePlayer.guiItems.gameWorld.SelectableGameItem.init(), gamePlayer.mainClasses.welcomeScreen.GameStartManager.init(), gamePlayer.guiItems.controlDockButtons.buttons.SpeedButton.initialize(), gamePlayer.guiContainers.secondaryContainers.ControlDock.initialize(), gamePlayer.guiItems.controlDockButtons.buttons.PlayButton.initialize(), gamePlayer.unusedCodeWarehouse.HUDContainer.initialize(), gamePlayer.guiContainers.coreContainers.CoreContainerSetup.initialize(), gamePlayer.unusedCodeWarehouse.guiItems.store.Store.initialize(), gamePlayer.mainClasses.welcomeScreen.GameStartManager.initializeWelcomeScreen(), gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health.makeHeartImage(), gamePlayer.mainClasses.guiBuilder.GuiBuilder.setStyleSheet(), gamePlayer.guiItems.welcome.WelcomeNavigator.setupContents(), gamePlayer.guiItems.welcome.Header.setupImage(), and gamePlayer.guiItems.welcome.ClickAnywherePane.setupText().
Member Data Documentation
final String utilities.XMLParsing.XMLParser.ELEMENTS = "elements" static private
Definition at line 33 of file XMLParser.java.
Document utilities.XMLParsing.XMLParser.myDocument private
Definition at line 35 of file XMLParser.java.
final String utilities.XMLParsing.XMLParser.SLIDER_MAX = "max" static private
Definition at line 32 of file XMLParser.java.
final String utilities.XMLParsing.XMLParser.SLIDER_MIN = "min" static private
Definition at line 31 of file XMLParser.java.
final String utilities.XMLParsing.XMLParser.SLIDER_NAME = "name" static private
Definition at line 30 of file XMLParser.java.
final String utilities.XMLParsing.XMLParser.SLIDERS = "sliders" static private
Definition at line 34 of file XMLParser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/XMLParsing/XMLParser.java