voogasalad_LosTorres: utilities.multilanguage.MultiLanguageUtility Class Reference
utilities.multilanguage.MultiLanguageUtility Class Reference
Public Member Functions
void initLanguages (String...languageResourceFiles)
boolean setLanguage (String language)
String getCurrentLanguage ()
ObjectProperty< ObservableList< String > > getSupportedLanguages ()
ObjectProperty< String > getStringProperty (String propertyKey)
ObjectProperty< ObservableList< String > > getStringListProperty (String propertyKey) throws LanguagePropertyNotFoundException
Static Public Member Functions
static synchronized MultiLanguageUtility getInstance ()
Package Functions
private< T > ObjectProperty< T > getProperty (Map< String, ObjectProperty< T >> map, String propertyKey) throws LanguagePropertyNotFoundException
Private Member Functions
MultiLanguageUtility ()
void initLanguages (List< String > fileNames)
void addLanguage (ResourceBundle bundle, String languageName)
void createStringProperties ()
void createStringListProperties ()
void updateProperties ()
void updateStringProperties ()
void updateStringListProperties ()
String fileExtension (String filePath)
String fileName (String filePath)
Private Attributes
Map< String, Map< String, String > > myLanguagesToStringsMap
Map< String, Map< String, List< String > > > myLanguagesToStringListsMap
Map< String, ObjectProperty< String > > myStringProperties
Map< String, ObjectProperty< ObservableList< String > > > myStringListProperties
ObjectProperty< ObservableList< String > > myLanguages
String myCurrentLanguage
Static Private Attributes
static final String LANGUAGE_KEY = "Language"
static final String LIST_SPLITTER = "\\|"
static final String DIVIDER = "\\"
static final String PROPERTIES_FILE_EXTENSION = ".properties"
static final String DOT = "."
static MultiLanguageUtility myOnlyInstance
Detailed Description
Utility for supporting multiple languages in the view. The utility works by reading a list of resource files for different languages and uses JavaFX ObjectProperties (which use native JavaFX Observer/Observable pattern) to bind JavaFX nodes to certain texts. Furthermore, switching between languages is supported by a call to the setLanguage(String languageName) method. For any JavaFX node to update it's text it requires a 1-time setup to bind the property e.g., myButton.getTextProperty().bind(MultiLanguageUtility.newInstance().getString("BUTTON_LABEL"));
public API: getInstance() –> instance of the utility initLanguages(String ... resourceFiles) –> initializes the languages in the utility setLanguage(String language) –> sets the language of the utility getCurrentLanguage() –> returns the current language getSupportedLanguages() –> ObjectProperty holding ObservableList for supported languages getStringProperty(String propertyName) –> gets the string property (ObjectProperty holding String) getStringListProperty(String propertyName) –> gets the string list property (ObjectProperty holding ObservableList) Requires a resource (.properties) file for each language. The name of the language must be specified in the resource file as a tag "language=..." If it is not, then the name of the language is assumed to be the name of the file.
Singleton pattern: 1 MultiLanguageUtility instance per program to handle language (assumes that a program can only have 1 language at any given time)
Author
Jonathan Tseng
Definition at line 50 of file MultiLanguageUtility.java.
Constructor & Destructor Documentation
utilities.multilanguage.MultiLanguageUtility.MultiLanguageUtility () private
private constructor for the utility
Definition at line 70 of file MultiLanguageUtility.java.
Referenced by utilities.multilanguage.MultiLanguageUtility.getInstance().
Member Function Documentation
void utilities.multilanguage.MultiLanguageUtility.addLanguage (ResourceBundle bundle, String languageName) private
private helper method to add a single language with resourcebundle to the utility
Parameters
bundle
languageName
Definition at line 218 of file MultiLanguageUtility.java.
Referenced by utilities.multilanguage.MultiLanguageUtility.initLanguages().
void utilities.multilanguage.MultiLanguageUtility.createStringListProperties () private
creates the string list properties that are sent to GUI components to bind to
Definition at line 250 of file MultiLanguageUtility.java.
Referenced by utilities.multilanguage.MultiLanguageUtility.updateProperties().
void utilities.multilanguage.MultiLanguageUtility.createStringProperties () private
creates the string properties that are sent to GUI components to bind to
Definition at line 240 of file MultiLanguageUtility.java.
Referenced by utilities.multilanguage.MultiLanguageUtility.updateProperties().
String utilities.multilanguage.MultiLanguageUtility.fileExtension (String filePath) private
gets the extension of a filePath if no "." found, then returns the given filePath
Parameters
filePath
Definition at line 304 of file MultiLanguageUtility.java.
Referenced by utilities.multilanguage.MultiLanguageUtility.fileName(), and utilities.multilanguage.MultiLanguageUtility.initLanguages().
String utilities.multilanguage.MultiLanguageUtility.fileName (String filePath) private
gets the language name from the file path by removing the extension
Parameters
filePath
Returns
Definition at line 314 of file MultiLanguageUtility.java.
References utilities.multilanguage.MultiLanguageUtility.fileExtension().
Referenced by utilities.multilanguage.MultiLanguageUtility.initLanguages().
String utilities.multilanguage.MultiLanguageUtility.getCurrentLanguage ()
returns the current language
Definition at line 126 of file MultiLanguageUtility.java.
References utilities.multilanguage.MultiLanguageUtility.myCurrentLanguage.
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.createLanguageSelector(), and utilities.multilanguage.ExampleMain.start().
static synchronized MultiLanguageUtility utilities.multilanguage.MultiLanguageUtility.getInstance () static
returns the single instance of the utility in the program
Returns
Definition at line 82 of file MultiLanguageUtility.java.
References utilities.multilanguage.MultiLanguageUtility.MultiLanguageUtility(), and utilities.multilanguage.MultiLanguageUtility.myOnlyInstance.
Referenced by gameAuthoring.scenes.actorBuildingScenes.BuildingSceneMenu.BuildingSceneMenu(), gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.createCenterDisplay(), gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.createCenterDisplay(), gameAuthoring.scenes.actorBuildingScenes.actorListView.CreatedEnemiesDisplay.CreatedEnemiesDisplay(), gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane.createEnemyLocationsSetupComponents(), gameAuthoring.scenes.GeneralSettingScene.createFieldWithLabel(), gameAuthoring.scenes.GeneralSettingScene.createHeadingLabel(), gameAuthoring.scenes.WelcomeScene.createLanguageComboBox(), gameAuthoring.scenes.levelBuilding.LevelDisplayCell.createLevelInfoBox(), gameAuthoring.scenes.levelBuilding.LevelBuildingScene.createMenuAndAddNewLevelOption(), gameAuthoring.scenes.GeneralSettingScene.createNextButton(), gameAuthoring.scenes.WelcomeScene.createWelcomeLabel(), gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane.EnemyEndingLocationsPane(), gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane.EnemyLocationPane(), gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane.EnemyStartingLocationsPane(), utilities.errorPopup.ErrorPopup.ErrorPopup(), gamePlayer.mainClasses.welcomeScreen.GameStartManager.GameStartManager(), utilities.JavaFXutilities.slider.SliderContainer.getNameLabel(), gameAuthoring.scenes.GSONWritingScene.GSONWritingScene(), utilities.JavaFXutilities.numericalTextFields.LabeledNumericalTextField.LabeledNumericalTextField(), gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.ProjectilePane(), gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.setupFileMenu(), gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingOptionPane.setupOptionsBoxGraphicallyAndDisplayLabel(), utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.showInstructionLabel(), utilities.multilanguage.ExampleMain.start(), and gameAuthoring.mainclasses.AuthorController.start().
private<T> ObjectProperty<T> utilities.multilanguage.MultiLanguageUtility.getProperty (Map< String, ObjectProperty< T >> map, String propertyKey) throws LanguagePropertyNotFoundException package
helper method to get a generic objectproperty by key from a map
Parameters
map
propertyKey
Returns
Exceptions
LanguagePropertyNotFoundException
Definition at line 181 of file MultiLanguageUtility.java.
Referenced by utilities.multilanguage.MultiLanguageUtility.getStringListProperty(), and utilities.multilanguage.MultiLanguageUtility.getStringProperty().
ObjectProperty<ObservableList<String> > utilities.multilanguage.MultiLanguageUtility.getStringListProperty (String propertyKey) throws LanguagePropertyNotFoundException
returns the object property with an observablelist for a given key the observablelist is a list of strings in the resource file, a string list property must be "|" separated e.g., animals=dog|cat|fish
Parameters
propertyKey
Returns
Exceptions
LanguagePropertyNotFoundException
Definition at line 168 of file MultiLanguageUtility.java.
References utilities.multilanguage.MultiLanguageUtility.getProperty().
Referenced by utilities.multilanguage.ExampleMain.start().
ObjectProperty<String> utilities.multilanguage.MultiLanguageUtility.getStringProperty (String propertyKey)
returns the string property for a given key
Parameters
propertyKey
Returns
Exceptions
LanguagePropertyNotFoundException
Definition at line 147 of file MultiLanguageUtility.java.
References utilities.multilanguage.MultiLanguageUtility.getProperty().
Referenced by gamePlayer.mainClasses.guiBuilder.GuiBuilder.build(), gameAuthoring.scenes.actorBuildingScenes.BuildingSceneMenu.BuildingSceneMenu(), gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.createCenterDisplay(), gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.createCenterDisplay(), gameAuthoring.scenes.actorBuildingScenes.actorListView.CreatedEnemiesDisplay.CreatedEnemiesDisplay(), gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane.createEnemyLocationsSetupComponents(), gameAuthoring.scenes.GeneralSettingScene.createFieldWithLabel(), gameAuthoring.scenes.GeneralSettingScene.createHeadingLabel(), gameAuthoring.scenes.levelBuilding.LevelDisplayCell.createLevelInfoBox(), gameAuthoring.scenes.levelBuilding.LevelBuildingScene.createMenuAndAddNewLevelOption(), gameAuthoring.scenes.GeneralSettingScene.createNextButton(), gameAuthoring.scenes.WelcomeScene.createWelcomeLabel(), gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane.EnemyEndingLocationsPane(), gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane.EnemyLocationPane(), gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane.EnemyStartingLocationsPane(), utilities.errorPopup.ErrorPopup.ErrorPopup(), utilities.JavaFXutilities.slider.SliderContainer.getNameLabel(), gameAuthoring.scenes.GSONWritingScene.GSONWritingScene(), gamePlayer.guiItems.voogaMenuBar.menuItems.GameSelectionItem.initialize(), gamePlayer.guiItems.voogaMenuBar.menuItems.LoadMenuItem.initialize(), gamePlayer.guiItems.voogaMenuBar.menuItems.ReplayMenuItem.initialize(), gamePlayer.guiItems.voogaMenuBar.menuItems.SaveMenuItem.initialize(), gamePlayer.guiItems.voogaMenuBar.menuItems.SwitchGameMenuItem.initialize(), gamePlayer.guiItems.voogaMenuBar.menuItems.ChangeThemeMenuItem.initialize(), gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar.initializeMenus(), utilities.JavaFXutilities.numericalTextFields.LabeledNumericalTextField.LabeledNumericalTextField(), gamePlayer.mainClasses.welcomeScreen.startingOptions.MultiPlayerOptions.MultiPlayerOptions(), gamePlayer.mainClasses.welcomeScreen.startingOptions.PlayerCountOptions.PlayerCountOptions(), gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.ProjectilePane(), gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.setupFileMenu(), gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingOptionPane.setupOptionsBoxGraphicallyAndDisplayLabel(), utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.showInstructionLabel(), utilities.multilanguage.ExampleMain.start(), gamePlayer.mainClasses.managers.WelcomeManager.startMultiPlayerGame(), and gamePlayer.mainClasses.welcomeScreen.GameStartManager.startMultiPlayerGame().
ObjectProperty<ObservableList<String> > utilities.multilanguage.MultiLanguageUtility.getSupportedLanguages ()
returns an object property containing an observable list of the languages currently parsed and supported by this utility
Returns
Definition at line 136 of file MultiLanguageUtility.java.
References utilities.multilanguage.MultiLanguageUtility.myLanguages.
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.createLanguageSelector(), and utilities.multilanguage.ExampleMain.start().
void utilities.multilanguage.MultiLanguageUtility.initLanguages (String... languageResourceFiles)
initializes the languages available in the utility with the given array of language resource files
Parameters
languageResourceFiles
Definition at line 95 of file MultiLanguageUtility.java.
References utilities.multilanguage.MultiLanguageUtility.updateProperties().
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.GameStartManager(), utilities.multilanguage.ExampleMain.start(), and gameAuthoring.mainclasses.AuthorController.start().
void utilities.multilanguage.MultiLanguageUtility.initLanguages (List< String > fileNames) private
private helper method that takes list of files and reads them also sets a random default language
Definition at line 196 of file MultiLanguageUtility.java.
References utilities.multilanguage.MultiLanguageUtility.addLanguage(), utilities.multilanguage.MultiLanguageUtility.fileExtension(), and utilities.multilanguage.MultiLanguageUtility.fileName().
boolean utilities.multilanguage.MultiLanguageUtility.setLanguage (String language)
sets the current language of the program if the language property file exists
Parameters
language
Exceptions
LanguageNotFoundException
Definition at line 111 of file MultiLanguageUtility.java.
References gameAuthoring.mainclasses.Constants.LANG_NOT_FOUND, and utilities.multilanguage.MultiLanguageUtility.updateProperties().
Referenced by gameAuthoring.scenes.WelcomeScene.createLanguageComboBox(), gamePlayer.mainClasses.welcomeScreen.GameStartManager.createLanguageSelector(), gamePlayer.mainClasses.welcomeScreen.GameStartManager.GameStartManager(), and utilities.multilanguage.ExampleMain.start().
void utilities.multilanguage.MultiLanguageUtility.updateProperties () private
updates the properties that GUI components are bound to
Definition at line 261 of file MultiLanguageUtility.java.
References utilities.multilanguage.MultiLanguageUtility.createStringListProperties(), utilities.multilanguage.MultiLanguageUtility.createStringProperties(), utilities.multilanguage.MultiLanguageUtility.updateStringListProperties(), and utilities.multilanguage.MultiLanguageUtility.updateStringProperties().
Referenced by utilities.multilanguage.MultiLanguageUtility.initLanguages(), and utilities.multilanguage.MultiLanguageUtility.setLanguage().
void utilities.multilanguage.MultiLanguageUtility.updateStringListProperties () private
updates the string list properties that GUI components are bound to
Definition at line 286 of file MultiLanguageUtility.java.
Referenced by utilities.multilanguage.MultiLanguageUtility.updateProperties().
void utilities.multilanguage.MultiLanguageUtility.updateStringProperties () private
updates the string properties that GUI components are bound to
Definition at line 275 of file MultiLanguageUtility.java.
Referenced by utilities.multilanguage.MultiLanguageUtility.updateProperties().
Member Data Documentation
final String utilities.multilanguage.MultiLanguageUtility.DIVIDER = "\\" static private
Definition at line 54 of file MultiLanguageUtility.java.
final String utilities.multilanguage.MultiLanguageUtility.DOT = "." static private
Definition at line 56 of file MultiLanguageUtility.java.
final String utilities.multilanguage.MultiLanguageUtility.LANGUAGE_KEY = "Language" static private
Definition at line 52 of file MultiLanguageUtility.java.
final String utilities.multilanguage.MultiLanguageUtility.LIST_SPLITTER = "\\|" static private
Definition at line 53 of file MultiLanguageUtility.java.
String utilities.multilanguage.MultiLanguageUtility.myCurrentLanguage private
Definition at line 65 of file MultiLanguageUtility.java.
Referenced by utilities.multilanguage.MultiLanguageUtility.getCurrentLanguage().
ObjectProperty<ObservableList<String> > utilities.multilanguage.MultiLanguageUtility.myLanguages private
Definition at line 64 of file MultiLanguageUtility.java.
Referenced by utilities.multilanguage.MultiLanguageUtility.getSupportedLanguages().
Map<String, Map<String, List<String> > > utilities.multilanguage.MultiLanguageUtility.myLanguagesToStringListsMap private
Definition at line 61 of file MultiLanguageUtility.java.
Map<String, Map<String, String> > utilities.multilanguage.MultiLanguageUtility.myLanguagesToStringsMap private
Definition at line 60 of file MultiLanguageUtility.java.
MultiLanguageUtility utilities.multilanguage.MultiLanguageUtility.myOnlyInstance static private
Definition at line 58 of file MultiLanguageUtility.java.
Referenced by utilities.multilanguage.MultiLanguageUtility.getInstance().
Map<String, ObjectProperty<ObservableList<String> > > utilities.multilanguage.MultiLanguageUtility.myStringListProperties private
Definition at line 63 of file MultiLanguageUtility.java.
Map<String, ObjectProperty<String> > utilities.multilanguage.MultiLanguageUtility.myStringProperties private
Definition at line 62 of file MultiLanguageUtility.java.
final String utilities.multilanguage.MultiLanguageUtility.PROPERTIES_FILE_EXTENSION = ".properties" static private
Definition at line 55 of file MultiLanguageUtility.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/multilanguage/MultiLanguageUtility.java