voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests Class Reference
gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests Class Reference
Public Member Functions
void setup ()
void AddSingleLineComponentTest ()
void AddSingleCurveComponentTest ()
void ConnectTwoLinesTest ()
void ConnectTwoCurvesTest ()
void ConnectLineToCurveTest ()
void CreateTwoRoutesTest ()
void StartingLocationsMustExistToBeConfiguredCorrectlyTest ()
void EndingLocationsMustExistToBeConfiguredCorrectlyTest ()
void ClearStartingLocationsTest ()
void ClearEndingLocationsTest ()
void ConnectComponentToStartingLocationTest ()
void ConnectComponentToEndingLocationTest ()
void IsLocationCloseToMethodTest ()
void AddingStartingLocationWithNearbyStartLocationTest ()
void AddingStartingLocationWithNearbyEndingLocationTest ()
void GetRouteContainingComponentTest ()
void ConnectRoutesTest ()
void AttemptToConnectRoutesNoForkTest ()
void AttemptToConnectRoutesFORKTest ()
Private Attributes
Path myPath
Detailed Description
Definition at line 14 of file PathCreationTests.java.
Member Function Documentation
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AddingStartingLocationWithNearbyEndingLocationTest ()
Definition at line 157 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addEndingLocation(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.canCreateLocationAtPoint(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.clearEnemyEndingLocations().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AddingStartingLocationWithNearbyStartLocationTest ()
Definition at line 149 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addStartingLocation(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.canCreateLocationAtPoint(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.clearEnemyStartingLocations().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AddSingleCurveComponentTest ()
Definition at line 33 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getAllPathComponents(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.getNumRoutes().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AddSingleLineComponentTest ()
Definition at line 24 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getAllPathComponents(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.getNumRoutes().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AttemptToConnectRoutesFORKTest ()
Definition at line 219 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.attemptToConnectRoutes(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getNumRoutes(), gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.setEndingPoint(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setEndingPoint(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.setStartingPoint().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AttemptToConnectRoutesNoForkTest ()
Definition at line 196 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.attemptToConnectRoutes(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getNumRoutes(), gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.setEndingPoint(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setEndingPoint(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.setStartingPoint().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ClearEndingLocationsTest ()
Definition at line 114 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addEndingLocation(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.clearEnemyEndingLocations(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.endingLocationsConfiguredCorrectly().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ClearStartingLocationsTest ()
Definition at line 107 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addStartingLocation(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.clearEnemyStartingLocations(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.startingLocationsConfiguredCorrectly().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectComponentToEndingLocationTest ()
Definition at line 130 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.addEndingLocation(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getRoutes(), gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.setEndingPoint(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.tryToAddConnectComponentToEndingLocation().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectComponentToStartingLocationTest ()
Definition at line 121 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.addStartingLocation(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getRoutes(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.setEndingPoint().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectLineToCurveTest ()
Definition at line 66 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getAllPathComponents(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getNumRoutes(), gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.setEndingPoint(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setEndingPoint().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectRoutesTest ()
Definition at line 179 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.connectRoutes(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getNumRoutes(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getRouteContaining(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.setEndingPoint().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectTwoCurvesTest ()
Definition at line 54 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getAllPathComponents(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getNumRoutes(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setEndingPoint().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectTwoLinesTest ()
Definition at line 42 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getAllPathComponents(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getNumRoutes(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.setEndingPoint().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.CreateTwoRoutesTest ()
Definition at line 78 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getAllPathComponents(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getNumRoutes(), gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.setEndingPoint(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setEndingPoint().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.EndingLocationsMustExistToBeConfiguredCorrectlyTest ()
Definition at line 100 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addEndingLocation(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.endingLocationsConfiguredCorrectly().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.GetRouteContainingComponentTest ()
Definition at line 165 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getRouteContaining(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.getRoutes(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.setEndingPoint().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.IsLocationCloseToMethodTest ()
Definition at line 140 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.isLocationCloseToPoint().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.setup ()
Definition at line 19 of file PathCreationTests.java.
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.StartingLocationsMustExistToBeConfiguredCorrectlyTest ()
Definition at line 93 of file PathCreationTests.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addStartingLocation(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.startingLocationsConfiguredCorrectly().
Member Data Documentation
Path gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.myPath private
Definition at line 16 of file PathCreationTests.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/pathComponents/PathCreationTests.java