voogasalad_LosTorres: gamePlayer.guiItems.store.StoreItem Class Reference
gamePlayer.guiItems.store.StoreItem Class Reference
Public Member Functions
StoreItem (String name, String imagePath, int cost, BooleanProperty available)
String getName ()
int getCost ()
ImageView getImageView ()
String getDescription ()
BooleanBinding availableBinding ()
void setImageView (ImageView imageView)
void setDescription (String description)
Static Public Attributes
static final double ICON_SIZE = 100
Private Attributes
String name
int cost
ImageView imageView
String description
BooleanBinding availableBinding
Detailed Description
Definition at line 11 of file StoreItem.java.
Constructor & Destructor Documentation
gamePlayer.guiItems.store.StoreItem.StoreItem (String name, String imagePath, int cost, BooleanProperty available)
Definition at line 20 of file StoreItem.java.
References gamePlayer.guiItems.store.StoreItem.cost, utilities.JavaFXutilities.imageView.StringToImageViewConverter.getImageView(), and gamePlayer.guiItems.store.StoreItem.name.
Member Function Documentation
BooleanBinding gamePlayer.guiItems.store.StoreItem.availableBinding ()
Definition at line 42 of file StoreItem.java.
int gamePlayer.guiItems.store.StoreItem.getCost ()
Definition at line 31 of file StoreItem.java.
References gamePlayer.guiItems.store.StoreItem.cost.
Referenced by gamePlayer.guiItems.store.Store.addStoreItem().
String gamePlayer.guiItems.store.StoreItem.getDescription ()
Definition at line 38 of file StoreItem.java.
References gamePlayer.guiItems.store.StoreItem.description.
ImageView gamePlayer.guiItems.store.StoreItem.getImageView ()
Definition at line 35 of file StoreItem.java.
References gamePlayer.guiItems.store.StoreItem.imageView.
Referenced by gamePlayer.guiItems.store.Store.addStoreItem().
String gamePlayer.guiItems.store.StoreItem.getName ()
Definition at line 27 of file StoreItem.java.
References gamePlayer.guiItems.store.StoreItem.name.
Referenced by gamePlayer.guiItems.store.Store.addStoreItem().
void gamePlayer.guiItems.store.StoreItem.setDescription (String description)
Definition at line 50 of file StoreItem.java.
References gamePlayer.guiItems.store.StoreItem.description.
void gamePlayer.guiItems.store.StoreItem.setImageView (ImageView imageView)
Definition at line 46 of file StoreItem.java.
References gamePlayer.guiItems.store.StoreItem.imageView.
Member Data Documentation
BooleanBinding gamePlayer.guiItems.store.StoreItem.availableBinding private
Definition at line 16 of file StoreItem.java.
int gamePlayer.guiItems.store.StoreItem.cost private
Definition at line 13 of file StoreItem.java.
Referenced by gamePlayer.guiItems.store.StoreItem.getCost(), and gamePlayer.guiItems.store.StoreItem.StoreItem().
String gamePlayer.guiItems.store.StoreItem.description private
Definition at line 15 of file StoreItem.java.
Referenced by gamePlayer.guiItems.store.StoreItem.getDescription(), and gamePlayer.guiItems.store.StoreItem.setDescription().
final double gamePlayer.guiItems.store.StoreItem.ICON_SIZE = 100 static
Definition at line 18 of file StoreItem.java.
ImageView gamePlayer.guiItems.store.StoreItem.imageView private
Definition at line 14 of file StoreItem.java.
Referenced by gamePlayer.guiItems.store.StoreItem.getImageView(), and gamePlayer.guiItems.store.StoreItem.setImageView().
String gamePlayer.guiItems.store.StoreItem.name private
Definition at line 12 of file StoreItem.java.
Referenced by gamePlayer.guiItems.store.StoreItem.getName(), and gamePlayer.guiItems.store.StoreItem.StoreItem().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItems/store/StoreItem.java