voogasalad_LosTorres: gamePlayer.guiItems.controlDockButtons.buttons.PlayButton Class Reference
gamePlayer.guiItems.controlDockButtons.buttons.PlayButton Class Reference
Public Member Functions
void initialize (Dimension2D containerSize)
Node getNode ()
Public Member Functions inherited from gamePlayer.guiItems.controlDockButtons.ControlDockButton
void initialize (Dimension2D containerSize)
Private Member Functions
void play ()
void pause ()
Private Attributes
String playImage
String pauseImage
PlayButtonListener myListener = GuiConstants.GUI_MANAGER
Additional Inherited Members
Static Public Attributes inherited from gamePlayer.guiItems.GuiItem
static String myPropertiesPath = "guiItems/"
Protected Member Functions inherited from gamePlayer.guiItems.controlDockButtons.ControlDockButton
void setupImageViews (String path1, String path2)
void setUpSizing (Dimension2D containerSize)
Protected Attributes inherited from gamePlayer.guiItems.controlDockButtons.ControlDockButton
XMLParser myParser
ImageView myImageView
ToggleButton myButton
Dimension2D buttonSize
Dimension2D imageSize
Detailed Description
Definition at line 19 of file PlayButton.java.
Member Function Documentation
Node gamePlayer.guiItems.controlDockButtons.buttons.PlayButton.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 50 of file PlayButton.java.
References gamePlayer.guiItems.controlDockButtons.ControlDockButton.myButton.
void gamePlayer.guiItems.controlDockButtons.buttons.PlayButton.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 25 of file PlayButton.java.
References utilities.XMLParsing.XMLParser.getValuesFromTag(), gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_ELEMENT_PROPERTIES_PATH, gamePlayer.guiItems.controlDockButtons.ControlDockButton.myButton, gamePlayer.guiItems.controlDockButtons.ControlDockButton.myImageView, gamePlayer.guiItems.controlDockButtons.ControlDockButton.myParser, gamePlayer.guiItems.GuiItem.myPropertiesPath, gamePlayer.guiItems.controlDockButtons.buttons.PlayButton.play(), gamePlayer.guiItems.controlDockButtons.ControlDockButton.setupImageViews(), and gamePlayer.guiItems.controlDockButtons.ControlDockButton.setUpSizing().
void gamePlayer.guiItems.controlDockButtons.buttons.PlayButton.pause () private
Definition at line 44 of file PlayButton.java.
References gamePlayer.guiItems.controlDockButtons.ControlDockButton.myButton, gamePlayer.guiItemsListeners.PlayButtonListener.pause(), and gamePlayer.guiItems.controlDockButtons.buttons.PlayButton.play().
Referenced by gamePlayer.guiItems.controlDockButtons.buttons.PlayButton.play().
void gamePlayer.guiItems.controlDockButtons.buttons.PlayButton.play () private
Definition at line 39 of file PlayButton.java.
References gamePlayer.guiItems.controlDockButtons.ControlDockButton.myButton, gamePlayer.guiItems.controlDockButtons.buttons.PlayButton.pause(), and gamePlayer.guiItemsListeners.PlayButtonListener.play().
Referenced by gamePlayer.guiItems.controlDockButtons.buttons.PlayButton.initialize(), and gamePlayer.guiItems.controlDockButtons.buttons.PlayButton.pause().
Member Data Documentation
PlayButtonListener gamePlayer.guiItems.controlDockButtons.buttons.PlayButton.myListener = GuiConstants.GUI_MANAGER private
Definition at line 22 of file PlayButton.java.
String gamePlayer.guiItems.controlDockButtons.buttons.PlayButton.pauseImage private
Definition at line 21 of file PlayButton.java.
String gamePlayer.guiItems.controlDockButtons.buttons.PlayButton.playImage private
Definition at line 20 of file PlayButton.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItems/controlDockButtons/buttons/PlayButton.java