voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane Class Reference
gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane Class Reference abstract
Public Member Functions
EnemyLocationPane (Group group, Path path)
Public Member Functions inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
BuildingPane (Group group)
void drawLocation (Node component)
void drawPathComponent (Node component)
void refreshScreen ()
void removeComponentFromScreen (Node component)
void executeExitFunction ()
void executeEnterFunction ()
Protected Member Functions
void createEnemyLocationsSetupComponents (Button button, String labelStr)
Protected Attributes
Button myClearLocations
Path myPath
Static Private Attributes
static final double PROMPT_HEIGHT = AuthorController.SCREEN_HEIGHT / 2 - 320
static final double PROMPT_WIDTH = BuildingPane.DRAW_SCREEN_WIDTH / 2 - 80
static final int CONTAINER_PADDING = 15
Additional Inherited Members
Static Public Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
static final double DRAW_SCREEN_WIDTH_RATIO = .80
static final double DRAW_SCREEN_WIDTH
Static Protected Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
static Group myGroup
Detailed Description
Represent a node representing an enemy location. Also defines a pane that allows the user to clear the locations as well as to continue to the next scene.
Author
Austin Kyker
Definition at line 24 of file EnemyLocationPane.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane.EnemyLocationPane (Group group, Path path)
Definition at line 33 of file EnemyLocationPane.java.
References gameAuthoring.mainclasses.Constants.CLEAR_LOCS, utilities.multilanguage.MultiLanguageUtility.getInstance(), and utilities.multilanguage.MultiLanguageUtility.getStringProperty().
Member Function Documentation
void gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane.createEnemyLocationsSetupComponents (Button button, String labelStr) protected
Definition at line 41 of file EnemyLocationPane.java.
References utilities.multilanguage.MultiLanguageUtility.getInstance(), utilities.multilanguage.MultiLanguageUtility.getStringProperty(), and gameAuthoring.mainclasses.Constants.SM_PADDING.
Member Data Documentation
final int gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane.CONTAINER_PADDING = 15 static private
Definition at line 28 of file EnemyLocationPane.java.
Button gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane.myClearLocations protected
Definition at line 30 of file EnemyLocationPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane.createEnemyEndingLocationsSetupComponents(), and gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane.createEnemyStartingLocationsSetupComponents().
Path gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane.myPath protected
Definition at line 31 of file EnemyLocationPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane.addNewEndingLocation(), gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane.addNewStartingLocation(), gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane.createEnemyEndingLocationsSetupComponents(), and gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane.createEnemyStartingLocationsSetupComponents().
final double gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane.PROMPT_HEIGHT = AuthorController.SCREEN_HEIGHT / 2 - 320 static private
Definition at line 26 of file EnemyLocationPane.java.
final double gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane.PROMPT_WIDTH = BuildingPane.DRAW_SCREEN_WIDTH / 2 - 80 static private
Definition at line 27 of file EnemyLocationPane.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/buildingPanes/locationPane/EnemyLocationPane.java