voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane Class Reference
gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane Class Reference
Public Member Functions
LineDrawingPane (Group group, Path path)
void executeEnterFunction ()
void executeExitFunction ()
Public Member Functions inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
BuildingPane (Group group)
void drawLocation (Node component)
void drawPathComponent (Node component)
void refreshScreen ()
void removeComponentFromScreen (Node component)
void executeExitFunction ()
void executeEnterFunction ()
Private Member Functions
void addListeners ()
void removeListeners ()
void stretchLineToEndAtCurrentMousePosition (MouseEvent event)
void handleBuildScreenClick (MouseEvent event)
Private Attributes
PathLine myLineBeingCreated
Path myPath
Static Private Attributes
static final double MIN_LINE_LENGTH = 30
Additional Inherited Members
Static Public Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
static final double DRAW_SCREEN_WIDTH_RATIO = .80
static final double DRAW_SCREEN_WIDTH
Static Protected Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
static Group myGroup
Detailed Description
Defines the pane where the user can draw lines and the click-listener to actually create these lines. Click once to define the starting location of the line and click again to define the ending location of the line.
Author
Austin Kyker
Definition at line 16 of file LineDrawingPane.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.LineDrawingPane (Group group, Path path)
Definition at line 23 of file LineDrawingPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.addListeners().
Member Function Documentation
void gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.addListeners () private
Definition at line 29 of file LineDrawingPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.stretchLineToEndAtCurrentMousePosition().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.executeEnterFunction(), and gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.LineDrawingPane().
void gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.executeEnterFunction ()
Definition at line 70 of file LineDrawingPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.addListeners().
void gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.executeExitFunction ()
Definition at line 75 of file LineDrawingPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.removeListeners().
void gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.handleBuildScreenClick (MouseEvent event) private
Definition at line 52 of file LineDrawingPane.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath(), gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.drawPathComponent(), gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.getLength(), gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.MIN_LINE_LENGTH, gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.myLineBeingCreated, and gameAuthoring.scenes.pathBuilding.pathComponents.Path.tryToAddConnectComponentToEndingLocation().
void gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.removeListeners () private
Definition at line 40 of file LineDrawingPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.executeExitFunction().
void gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.stretchLineToEndAtCurrentMousePosition (MouseEvent event) private
Definition at line 45 of file LineDrawingPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.addListeners().
Member Data Documentation
final double gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.MIN_LINE_LENGTH = 30 static private
Definition at line 18 of file LineDrawingPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.handleBuildScreenClick().
PathLine gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.myLineBeingCreated private
Definition at line 20 of file LineDrawingPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.handleBuildScreenClick().
Path gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.myPath private
Definition at line 21 of file LineDrawingPane.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/buildingPanes/LineDrawingPane.java