voogasalad_LosTorres: utilities.JavaFXutilities.slider.SliderContainer Class Reference
utilities.JavaFXutilities.slider.SliderContainer Class Reference
Public Member Functions
SliderContainer (String name, double min, double max)
SliderContainer (SliderInfo info)
void resetSlider ()
double getSliderValue ()
DoubleProperty getValueProperty ()
Private Member Functions
void setupSlider ()
Label getNameLabel (String name)
Private Attributes
Slider mySlider
SliderInfo mySliderInfo
Label myValueLabel
Static Private Attributes
static final int SLIDER_WIDTH = 120
Detailed Description
Purpose of this class is to allow front-end components to easily be able to build labeled sliders.
Author
Austin Kyker
Definition at line 22 of file SliderContainer.java.
Constructor & Destructor Documentation
utilities.JavaFXutilities.slider.SliderContainer.SliderContainer (String name, double min, double max)
Definition at line 29 of file SliderContainer.java.
References utilities.JavaFXutilities.slider.SliderContainer.getNameLabel(), utilities.JavaFXutilities.slider.SliderContainer.setupSlider(), and gameAuthoring.mainclasses.Constants.SM_PADDING.
utilities.JavaFXutilities.slider.SliderContainer.SliderContainer (SliderInfo info)
Definition at line 39 of file SliderContainer.java.
References gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo.getMyInfo(), utilities.JavaFXutilities.slider.SliderContainer.getNameLabel(), utilities.JavaFXutilities.slider.SliderContainer.setupSlider(), and gameAuthoring.mainclasses.Constants.SM_PADDING.
Member Function Documentation
Label utilities.JavaFXutilities.slider.SliderContainer.getNameLabel (String name) private
Definition at line 62 of file SliderContainer.java.
References utilities.multilanguage.MultiLanguageUtility.getInstance(), and utilities.multilanguage.MultiLanguageUtility.getStringProperty().
Referenced by utilities.JavaFXutilities.slider.SliderContainer.SliderContainer().
double utilities.JavaFXutilities.slider.SliderContainer.getSliderValue ()
Definition at line 72 of file SliderContainer.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.makeNewActor(), gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.makeNewActor(), and gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.makeProjectileInfo().
DoubleProperty utilities.JavaFXutilities.slider.SliderContainer.getValueProperty ()
Definition at line 76 of file SliderContainer.java.
Referenced by gamePlayer.guiItems.controlDockButtons.sliders.SpeedSlider.setUpSlider().
void utilities.JavaFXutilities.slider.SliderContainer.resetSlider ()
Definition at line 68 of file SliderContainer.java.
References gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo.getMyMin().
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.clearFields().
void utilities.JavaFXutilities.slider.SliderContainer.setupSlider () private
Definition at line 49 of file SliderContainer.java.
References gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo.getMyMax(), and gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo.getMyMin().
Referenced by utilities.JavaFXutilities.slider.SliderContainer.SliderContainer().
Member Data Documentation
Slider utilities.JavaFXutilities.slider.SliderContainer.mySlider private
Definition at line 25 of file SliderContainer.java.
SliderInfo utilities.JavaFXutilities.slider.SliderContainer.mySliderInfo private
Definition at line 26 of file SliderContainer.java.
Label utilities.JavaFXutilities.slider.SliderContainer.myValueLabel private
Definition at line 27 of file SliderContainer.java.
final int utilities.JavaFXutilities.slider.SliderContainer.SLIDER_WIDTH = 120 static private
Definition at line 24 of file SliderContainer.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/JavaFXutilities/slider/SliderContainer.java