voogasalad_LosTorres: gamePlayer.guiItems.welcome.WelcomeNavigator Class Reference
gamePlayer.guiItems.welcome.WelcomeNavigator Class Reference
Public Member Functions
void initialize (Dimension2D containerSize)
Node getNode ()
void deviceConnected (boolean connected)
void setContent (Node node)
Package Attributes
int currentScene
Private Member Functions
void setupNavPane ()
void setupContents ()
void shift (int fromScene, int toScene)
Private Attributes
XMLParser myParser
Dimension2D mySize
HBox navPane
int numScenes
Additional Inherited Members
Static Public Attributes inherited from gamePlayer.guiItems.GuiItem
static String myPropertiesPath = "guiItems/"
Detailed Description
Definition at line 20 of file WelcomeNavigator.java.
Member Function Documentation
void gamePlayer.guiItems.welcome.WelcomeNavigator.deviceConnected (boolean connected)
Definition at line 42 of file WelcomeNavigator.java.
References utilities.reflection.Reflection.createInstance(), gamePlayer.mainClasses.guiBuilder.GuiElement.getNode(), utilities.XMLParsing.XMLParser.getValuesFromTag(), gamePlayer.mainClasses.guiBuilder.GuiElement.initialize(), gamePlayer.guiItems.welcome.WelcomeNavigator.numScenes, and gamePlayer.guiItems.welcome.WelcomeNavigator.setupContents().
Node gamePlayer.guiItems.welcome.WelcomeNavigator.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 38 of file WelcomeNavigator.java.
References gamePlayer.guiItems.welcome.WelcomeNavigator.navPane.
void gamePlayer.guiItems.welcome.WelcomeNavigator.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 28 of file WelcomeNavigator.java.
References gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_ELEMENT_PROPERTIES_PATH, gamePlayer.guiItems.GuiItem.myPropertiesPath, gamePlayer.guiItems.welcome.WelcomeNavigator.setupContents(), and gamePlayer.guiItems.welcome.WelcomeNavigator.setupNavPane().
void gamePlayer.guiItems.welcome.WelcomeNavigator.setContent (Node node)
Definition at line 58 of file WelcomeNavigator.java.
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.init(), gamePlayer.mainClasses.managers.WelcomeManager.startMultiPlayerGame(), gamePlayer.mainClasses.managers.WelcomeManager.startMultiPlayerGameChooser(), gamePlayer.mainClasses.managers.WelcomeManager.startMultiPlayerOptions(), and gamePlayer.mainClasses.managers.WelcomeManager.startSinglePlayerGameChooser().
void gamePlayer.guiItems.welcome.WelcomeNavigator.setupContents () private
Definition at line 71 of file WelcomeNavigator.java.
References utilities.reflection.Reflection.createInstance(), utilities.XMLParsing.XMLParser.getDoubleValuesFromTag(), gamePlayer.mainClasses.guiBuilder.GuiElement.getNode(), utilities.XMLParsing.XMLParser.getValuesFromTag(), gamePlayer.mainClasses.guiBuilder.GuiElement.initialize(), gamePlayer.guiItems.welcome.WelcomeNavigator.numScenes, and gamePlayer.guiItems.welcome.WelcomeNavigator.shift().
Referenced by gamePlayer.guiItems.welcome.WelcomeNavigator.deviceConnected(), and gamePlayer.guiItems.welcome.WelcomeNavigator.initialize().
void gamePlayer.guiItems.welcome.WelcomeNavigator.setupNavPane () private
Definition at line 63 of file WelcomeNavigator.java.
References utilities.XMLParsing.XMLParser.getIntegerValuesFromTag(), and gamePlayer.guiItems.welcome.WelcomeNavigator.numScenes.
Referenced by gamePlayer.guiItems.welcome.WelcomeNavigator.initialize().
void gamePlayer.guiItems.welcome.WelcomeNavigator.shift (int fromScene, int toScene) private
Definition at line 99 of file WelcomeNavigator.java.
References gamePlayer.guiItems.welcome.WelcomeNavigator.navPane.
Referenced by gamePlayer.guiItems.welcome.WelcomeNavigator.setupContents().
Member Data Documentation
int gamePlayer.guiItems.welcome.WelcomeNavigator.currentScene package
Definition at line 25 of file WelcomeNavigator.java.
XMLParser gamePlayer.guiItems.welcome.WelcomeNavigator.myParser private
Definition at line 22 of file WelcomeNavigator.java.
Dimension2D gamePlayer.guiItems.welcome.WelcomeNavigator.mySize private
Definition at line 23 of file WelcomeNavigator.java.
HBox gamePlayer.guiItems.welcome.WelcomeNavigator.navPane private
Definition at line 24 of file WelcomeNavigator.java.
Referenced by gamePlayer.guiItems.welcome.WelcomeNavigator.getNode(), and gamePlayer.guiItems.welcome.WelcomeNavigator.shift().
int gamePlayer.guiItems.welcome.WelcomeNavigator.numScenes private
Definition at line 25 of file WelcomeNavigator.java.
Referenced by gamePlayer.guiItems.welcome.WelcomeNavigator.deviceConnected(), gamePlayer.guiItems.welcome.WelcomeNavigator.setupContents(), and gamePlayer.guiItems.welcome.WelcomeNavigator.setupNavPane().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItems/welcome/WelcomeNavigator.java