voogasalad_LosTorres: gameAuthoring.scenes.GeneralSettingScene Class Reference
gameAuthoring.scenes.GeneralSettingScene Class Reference
Public Member Functions
GeneralSettingScene (IGeneralSettingsConfiguring controller)
void createRightImage ()
Scene getScene ()
Private Member Functions
void createHeadingLabel ()
void createOptionFields ()
void createOptions ()
VBox createFieldWithLabel (String labelName, Node node)
VBox createNextButton ()
void handleButtonClick ()
Private Attributes
IGeneralSettingsConfiguring myGeneralSettingsController
Scene myScene
VBox myVBox
TextField myNameTextField
NumericalTextField myStartingHealthField
NumericalTextField myStartingCashField
ComboBox< String > myGameTypeComboBox
Group root
Static Private Attributes
static final int BTN_SPACE = 140
static final String GENERAL_SETTINGS_IMG_PATH
static final double FIELD_WIDTH = AuthorController.SCREEN_WIDTH / 4
static final String MULTIPLAYER = "Coop"
static final String SINGLEPLAYER = "SinglePlayer"
Detailed Description
Definition at line 24 of file GeneralSettingScene.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.GeneralSettingScene.GeneralSettingScene (IGeneralSettingsConfiguring controller)
Definition at line 41 of file GeneralSettingScene.java.
References gameAuthoring.scenes.GeneralSettingScene.createHeadingLabel(), gameAuthoring.scenes.GeneralSettingScene.createNextButton(), gameAuthoring.scenes.GeneralSettingScene.createOptionFields(), gameAuthoring.scenes.GeneralSettingScene.createOptions(), gameAuthoring.scenes.GeneralSettingScene.createRightImage(), gameAuthoring.mainclasses.AuthorController.SCREEN_HEIGHT, and gameAuthoring.mainclasses.AuthorController.SCREEN_WIDTH.
Member Function Documentation
VBox gameAuthoring.scenes.GeneralSettingScene.createFieldWithLabel (String labelName, Node node) private
Definition at line 89 of file GeneralSettingScene.java.
References utilities.multilanguage.MultiLanguageUtility.getInstance(), utilities.multilanguage.MultiLanguageUtility.getStringProperty(), and gameAuthoring.mainclasses.Constants.MED_PADDING.
Referenced by gameAuthoring.scenes.GeneralSettingScene.createOptions().
void gameAuthoring.scenes.GeneralSettingScene.createHeadingLabel () private
Definition at line 58 of file GeneralSettingScene.java.
References gameAuthoring.mainclasses.Constants.GENERAL_SETTING_MSG, utilities.multilanguage.MultiLanguageUtility.getInstance(), and utilities.multilanguage.MultiLanguageUtility.getStringProperty().
Referenced by gameAuthoring.scenes.GeneralSettingScene.GeneralSettingScene().
VBox gameAuthoring.scenes.GeneralSettingScene.createNextButton () private
Definition at line 98 of file GeneralSettingScene.java.
References utilities.multilanguage.MultiLanguageUtility.getInstance(), utilities.multilanguage.MultiLanguageUtility.getStringProperty(), gameAuthoring.scenes.GeneralSettingScene.handleButtonClick(), gameAuthoring.mainclasses.Constants.MED_PADDING, and gameAuthoring.mainclasses.Constants.START_BUILDING.
Referenced by gameAuthoring.scenes.GeneralSettingScene.createOptions(), and gameAuthoring.scenes.GeneralSettingScene.GeneralSettingScene().
void gameAuthoring.scenes.GeneralSettingScene.createOptionFields () private
Definition at line 66 of file GeneralSettingScene.java.
References gameAuthoring.mainclasses.AuthorController.SCREEN_WIDTH.
Referenced by gameAuthoring.scenes.GeneralSettingScene.GeneralSettingScene().
void gameAuthoring.scenes.GeneralSettingScene.createOptions () private
Definition at line 75 of file GeneralSettingScene.java.
References gameAuthoring.scenes.GeneralSettingScene.createFieldWithLabel(), gameAuthoring.scenes.GeneralSettingScene.createNextButton(), gameAuthoring.mainclasses.Constants.NAME_OF_GAME, gameAuthoring.mainclasses.Constants.SELECT_GAME_TYPE, gameAuthoring.mainclasses.Constants.STARTING_CASH, and gameAuthoring.mainclasses.Constants.STARTING_HEALTH.
Referenced by gameAuthoring.scenes.GeneralSettingScene.GeneralSettingScene().
void gameAuthoring.scenes.GeneralSettingScene.createRightImage ()
Definition at line 121 of file GeneralSettingScene.java.
References gameAuthoring.mainclasses.AuthorController.SCREEN_HEIGHT, and gameAuthoring.mainclasses.AuthorController.SCREEN_WIDTH.
Referenced by gameAuthoring.scenes.GeneralSettingScene.GeneralSettingScene().
Scene gameAuthoring.scenes.GeneralSettingScene.getScene ()
Definition at line 131 of file GeneralSettingScene.java.
References gameAuthoring.scenes.GeneralSettingScene.myScene.
Referenced by gameAuthoring.mainclasses.AuthorController.showGeneralSettingScene().
void gameAuthoring.scenes.GeneralSettingScene.handleButtonClick () private
Definition at line 108 of file GeneralSettingScene.java.
References utilities.JavaFXutilities.numericalTextFields.NumericalTextField.getNumber(), utilities.JavaFXutilities.numericalTextFields.NumericalTextField.isValueEntered(), gameAuthoring.mainclasses.controllerInterfaces.IGeneralSettingsConfiguring.makeDirectory(), and gameAuthoring.mainclasses.controllerInterfaces.IGeneralSettingsConfiguring.setGeneralSettings().
Referenced by gameAuthoring.scenes.GeneralSettingScene.createNextButton().
Member Data Documentation
final int gameAuthoring.scenes.GeneralSettingScene.BTN_SPACE = 140 static private
Definition at line 26 of file GeneralSettingScene.java.
final double gameAuthoring.scenes.GeneralSettingScene.FIELD_WIDTH = AuthorController.SCREEN_WIDTH / 4 static private
Definition at line 29 of file GeneralSettingScene.java.
final String gameAuthoring.scenes.GeneralSettingScene.GENERAL_SETTINGS_IMG_PATH static private
Initial value:
=
            "gameAuthoring/scenes/GeneralSettingsImage.png"
Definition at line 27 of file GeneralSettingScene.java.
final String gameAuthoring.scenes.GeneralSettingScene.MULTIPLAYER = "Coop" static private
Definition at line 30 of file GeneralSettingScene.java.
ComboBox<String> gameAuthoring.scenes.GeneralSettingScene.myGameTypeComboBox private
Definition at line 38 of file GeneralSettingScene.java.
IGeneralSettingsConfiguring gameAuthoring.scenes.GeneralSettingScene.myGeneralSettingsController private
Definition at line 32 of file GeneralSettingScene.java.
TextField gameAuthoring.scenes.GeneralSettingScene.myNameTextField private
Definition at line 35 of file GeneralSettingScene.java.
Scene gameAuthoring.scenes.GeneralSettingScene.myScene private
Definition at line 33 of file GeneralSettingScene.java.
Referenced by gameAuthoring.scenes.GeneralSettingScene.getScene().
NumericalTextField gameAuthoring.scenes.GeneralSettingScene.myStartingCashField private
Definition at line 37 of file GeneralSettingScene.java.
NumericalTextField gameAuthoring.scenes.GeneralSettingScene.myStartingHealthField private
Definition at line 36 of file GeneralSettingScene.java.
VBox gameAuthoring.scenes.GeneralSettingScene.myVBox private
Definition at line 34 of file GeneralSettingScene.java.
Group gameAuthoring.scenes.GeneralSettingScene.root private
Definition at line 39 of file GeneralSettingScene.java.
final String gameAuthoring.scenes.GeneralSettingScene.SINGLEPLAYER = "SinglePlayer" static private
Definition at line 31 of file GeneralSettingScene.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/GeneralSettingScene.java