voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve Class Reference
gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve Class Reference
Public Member Functions
PathCurve ()
PathCurve (double initialX, double initialY)
boolean isEndPointSet ()
void endPointIsSet ()
Point2D getStartingPoint ()
Point2D getEndingPoint ()
void setStartingPoint (Point2D startingPoint)
void setEndingPoint (Point2D endingPoint)
void translate (double deltaX, double deltaY)
void select ()
void removeStroke ()
PathComponent deepCopy ()
void setControlPointSetters (Circle setter1, Circle setter2)
double getLength ()
void setControlPoint1 (double x, double y)
void setControlPoint2 (double x, double y)
void calculateAndSetControlPoints ()
List< VisibilityPoint > getInnerPointsRepresentingComponent ()
List< Node > getExtraNodes ()
boolean isPathComponentVisible ()
void togglePathComponentVisibility ()
void showVisibility ()
Public Member Functions inherited from gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent
default Node getNode ()
Private Member Functions
Point2D getControlPoint1 ()
Point2D getControlPoint2 ()
Private Attributes
boolean isEndPointSet
Circle myControlPoint1Setter
Circle myControlPoint2Setter
boolean isPathComponentVisible
Static Private Attributes
static final double NUM_INNER_POINTS = 15.0
Detailed Description
Defines a curve that can be drawn on the screen.
Author
Austin Kyker
Definition at line 19 of file PathCurve.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.PathCurve ()
Definition at line 28 of file PathCurve.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.deepCopy().
gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.PathCurve (double initialX, double initialY)
Definition at line 35 of file PathCurve.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.calculateAndSetControlPoints(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setEndingPoint(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setStartingPoint().
Member Function Documentation
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.calculateAndSetControlPoints ()
Definition at line 118 of file PathCurve.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getEndingPoint(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getStartingPoint(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setControlPoint1(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setControlPoint2().
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.PathCurve(), and gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.stretchLineToEndAtCurrentMousePosition().
PathComponent gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.deepCopy ()
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 90 of file PathCurve.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getEndingPoint(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getStartingPoint(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.PathCurve(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setControlPoint1(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setControlPoint2(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setEndingPoint(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setStartingPoint().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.endPointIsSet ()
Definition at line 47 of file PathCurve.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.handleBuildScreenClick().
Point2D gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getControlPoint1 () private
Definition at line 126 of file PathCurve.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getInnerPointsRepresentingComponent().
Point2D gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getControlPoint2 () private
Definition at line 130 of file PathCurve.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getInnerPointsRepresentingComponent().
Point2D gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getEndingPoint ()
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 57 of file PathCurve.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.calculateAndSetControlPoints(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.deepCopy(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getInnerPointsRepresentingComponent(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getLength(), and gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testRoutesTranslation().
List<Node> gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getExtraNodes ()
When this component gets deleted, the control point setters are deleted as well from the group.
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 166 of file PathCurve.java.
List<VisibilityPoint> gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getInnerPointsRepresentingComponent ()
Uses the formula for the Bezier Curve to calculate several points on the curve. The back-end route needs these points in order to route the enemy from the starting location to the ending location.
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 140 of file PathCurve.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getControlPoint1(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getControlPoint2(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getEndingPoint(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getStartingPoint(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.NUM_INNER_POINTS.
double gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getLength ()
Definition at line 104 of file PathCurve.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getEndingPoint(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getStartingPoint().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.handleBuildScreenClick().
Point2D gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getStartingPoint ()
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 52 of file PathCurve.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.calculateAndSetControlPoints(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.deepCopy(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getInnerPointsRepresentingComponent(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getLength(), and gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testRoutesTranslation().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.isEndPointSet ()
Definition at line 43 of file PathCurve.java.
boolean gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.isPathComponentVisible ()
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 173 of file PathCurve.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.togglePathComponentVisibility().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.removeStroke ()
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 85 of file PathCurve.java.
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.select ()
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 80 of file PathCurve.java.
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setControlPoint1 (double x, double y)
Definition at line 108 of file PathCurve.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.calculateAndSetControlPoints(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.deepCopy(), and gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.moveControlPoint1().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setControlPoint2 (double x, double y)
Definition at line 113 of file PathCurve.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.calculateAndSetControlPoints(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.deepCopy(), and gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.moveControlPoint2().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setControlPointSetters (Circle setter1, Circle setter2)
Definition at line 99 of file PathCurve.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.addControlPointSetters().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setEndingPoint (Point2D endingPoint)
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 68 of file PathCurve.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AttemptToConnectRoutesFORKTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AttemptToConnectRoutesNoForkTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectLineToCurveTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectTwoCurvesTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.CreateTwoRoutesTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.deepCopy(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.PathCurve(), and gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testRoutesTranslation().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setStartingPoint (Point2D startingPoint)
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 62 of file PathCurve.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.deepCopy(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.PathCurve().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.showVisibility ()
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 183 of file PathCurve.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.INVISIBLE_COLOR, and gameAuthoring.scenes.pathBuilding.pathComponents.Path.VISIBLE_COLOR.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.togglePathComponentVisibility().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.togglePathComponentVisibility ()
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 177 of file PathCurve.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.isPathComponentVisible(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.showVisibility().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.translate (double deltaX, double deltaY)
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 74 of file PathCurve.java.
Member Data Documentation
boolean gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.isEndPointSet private
Definition at line 23 of file PathCurve.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.handleBuildScreenClick().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.isPathComponentVisible private
Definition at line 26 of file PathCurve.java.
Circle gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.myControlPoint1Setter private
Definition at line 24 of file PathCurve.java.
Circle gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.myControlPoint2Setter private
Definition at line 25 of file PathCurve.java.
final double gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.NUM_INNER_POINTS = 15.0 static private
Definition at line 21 of file PathCurve.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getInnerPointsRepresentingComponent().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/pathComponents/PathCurve.java