voogasalad_LosTorres: gamePlayer.mainClasses.welcomeScreen.WelcomeScreen Class Reference
gamePlayer.mainClasses.welcomeScreen.WelcomeScreen Class Reference
Public Member Functions
WelcomeScreen ()
void setBackgroundImage (ImageView image)
void setTopContent (Node node)
void setCenterContent (Node node)
void setCenterLargeContent (Node node)
void setBottomContent (Node node)
Static Public Attributes
static final double WIDTH = GuiConstants.WINDOW_WIDTH
static final double HEIGHT = GuiConstants.WINDOW_HEIGHT
static final double CENTER_PANE_WIDTH = 3*WIDTH/4
static final double CENTER_PANE_HEIGHT = 2*HEIGHT/3
static final double CENTER_PANE_LAYOUT_X = WIDTH/2-CENTER_PANE_WIDTH/2
static final double CENTER_PANE_LAYOUT_Y = HEIGHT-CENTER_PANE_HEIGHT-60
static final double VBOX_WIDTH = WIDTH/2.5
static final double VBOX_HEIGHT = HEIGHT
static final double PANE_WIDTH = VBOX_WIDTH
static final double PANE_HEIGHT = VBOX_HEIGHT/3
Private Member Functions
Pane initializeCenterLargePane ()
Pane createPane (Double width, Double height)
void setPaneContent (Pane pane, Node node)
Private Attributes
Pane topPane
Pane centerPane
Pane bottomPane
Pane centerLargePane
VBox vbox
Static Private Attributes
static final double VBOX_PADDING = 20
Detailed Description
Definition at line 10 of file WelcomeScreen.java.
Constructor & Destructor Documentation
gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.WelcomeScreen ()
Definition at line 32 of file WelcomeScreen.java.
References gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.createPane(), and gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.initializeCenterLargePane().
Member Function Documentation
Pane gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.createPane (Double width, Double height) private
Definition at line 57 of file WelcomeScreen.java.
Referenced by gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.WelcomeScreen().
Pane gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.initializeCenterLargePane () private
Definition at line 49 of file WelcomeScreen.java.
Referenced by gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.WelcomeScreen().
void gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setBackgroundImage (ImageView image)
Definition at line 64 of file WelcomeScreen.java.
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.initializeWelcomeScreen().
void gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setBottomContent (Node node)
Definition at line 87 of file WelcomeScreen.java.
References gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setPaneContent().
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.initializeWelcomeScreen().
void gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setCenterContent (Node node)
Definition at line 73 of file WelcomeScreen.java.
References gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setPaneContent().
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.initializeWelcomeScreen(), gamePlayer.mainClasses.welcomeScreen.GameStartManager.startMultiPlayerGame(), and gamePlayer.mainClasses.welcomeScreen.GameStartManager.startMultiPlayerOptions().
void gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setCenterLargeContent (Node node)
Definition at line 77 of file WelcomeScreen.java.
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.startMultiPlayerGameChooser(), and gamePlayer.mainClasses.welcomeScreen.GameStartManager.startSinglePlayerGameChooser().
void gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setPaneContent (Pane pane, Node node) private
Definition at line 91 of file WelcomeScreen.java.
Referenced by gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setBottomContent(), gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setCenterContent(), and gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setTopContent().
void gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setTopContent (Node node)
Definition at line 69 of file WelcomeScreen.java.
References gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setPaneContent().
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.initializeWelcomeScreen().
Member Data Documentation
Pane gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.bottomPane private
Definition at line 28 of file WelcomeScreen.java.
final double gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.CENTER_PANE_HEIGHT = 2*HEIGHT/3 static
Definition at line 15 of file WelcomeScreen.java.
final double gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.CENTER_PANE_LAYOUT_X = WIDTH/2-CENTER_PANE_WIDTH/2 static
Definition at line 16 of file WelcomeScreen.java.
final double gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.CENTER_PANE_LAYOUT_Y = HEIGHT-CENTER_PANE_HEIGHT-60 static
Definition at line 17 of file WelcomeScreen.java.
final double gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.CENTER_PANE_WIDTH = 3*WIDTH/4 static
Definition at line 14 of file WelcomeScreen.java.
Pane gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.centerLargePane private
Definition at line 29 of file WelcomeScreen.java.
Pane gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.centerPane private
Definition at line 27 of file WelcomeScreen.java.
final double gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.HEIGHT = GuiConstants.WINDOW_HEIGHT static
Definition at line 12 of file WelcomeScreen.java.
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.initializeWelcomeScreen().
final double gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.PANE_HEIGHT = VBOX_HEIGHT/3 static
Definition at line 24 of file WelcomeScreen.java.
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.createLanguageSelector(), gamePlayer.mainClasses.welcomeScreen.startingOptions.Options.createOptionButton(), and gamePlayer.mainClasses.welcomeScreen.GameStartManager.initializeWelcomeScreen().
final double gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.PANE_WIDTH = VBOX_WIDTH static
Definition at line 23 of file WelcomeScreen.java.
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.createLanguageSelector(), gamePlayer.mainClasses.welcomeScreen.startingOptions.Options.createOptionButton(), and gamePlayer.mainClasses.welcomeScreen.GameStartManager.initializeWelcomeScreen().
Pane gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.topPane private
Definition at line 26 of file WelcomeScreen.java.
VBox gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.vbox private
Definition at line 30 of file WelcomeScreen.java.
final double gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.VBOX_HEIGHT = HEIGHT static
Definition at line 20 of file WelcomeScreen.java.
final double gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.VBOX_PADDING = 20 static private
Definition at line 21 of file WelcomeScreen.java.
final double gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.VBOX_WIDTH = WIDTH/2.5 static
Definition at line 19 of file WelcomeScreen.java.
final double gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.WIDTH = GuiConstants.WINDOW_WIDTH static
Definition at line 11 of file WelcomeScreen.java.
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.initializeWelcomeScreen().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/mainClasses/welcomeScreen/WelcomeScreen.java