voogasalad_LosTorres: utilities.pathfinding.example.LinkedNodeAStarFinder Class Reference
utilities.pathfinding.example.LinkedNodeAStarFinder Class Reference
Public Member Functions
Number getCost (LinkedNode beginningNode, LinkedNode endingNode)
Iterable< LinkedNode > getNeighbors (LinkedNode node)
int breakTie (LinkedNode node, LinkedNode other)
Number getHeuristicValue (LinkedNode node, LinkedNode destination)
Public Member Functions inherited from utilities.pathfinding.AStarPathFinder< T >
abstract Number getHeuristicValue (T node, T destination)
boolean isDestination (T node, T destinationNode)
List< T > findPath (T start, T destination) throws InvalidCostException
Public Member Functions inherited from utilities.pathfinding.IPathFinder< T >
Number getCost (T beginningNode, T endingNode)
Iterable< T > getNeighbors (T node)
int breakTie (T node, T other)
Detailed Description
Definition at line 5 of file LinkedNodeAStarFinder.java.
Member Function Documentation
int utilities.pathfinding.example.LinkedNodeAStarFinder.breakTie (LinkedNode node, LinkedNode other)
Definition at line 22 of file LinkedNodeAStarFinder.java.
References utilities.pathfinding.example.LinkedNode.compareTo().
Number utilities.pathfinding.example.LinkedNodeAStarFinder.getCost (LinkedNode beginningNode, LinkedNode endingNode)
Definition at line 8 of file LinkedNodeAStarFinder.java.
References utilities.pathfinding.example.UnlinkedNode.getX(), and utilities.pathfinding.example.UnlinkedNode.getY().
Number utilities.pathfinding.example.LinkedNodeAStarFinder.getHeuristicValue (LinkedNode node, LinkedNode destination)
Definition at line 27 of file LinkedNodeAStarFinder.java.
References utilities.pathfinding.example.UnlinkedNode.getX(), and utilities.pathfinding.example.UnlinkedNode.getY().
Iterable<LinkedNode> utilities.pathfinding.example.LinkedNodeAStarFinder.getNeighbors (LinkedNode node)
Definition at line 17 of file LinkedNodeAStarFinder.java.
References utilities.pathfinding.example.LinkedNode.getNeighbors().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/pathfinding/example/LinkedNodeAStarFinder.java