voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.pathComponents.PathLine Class Reference
gameAuthoring.scenes.pathBuilding.pathComponents.PathLine Class Reference
Public Member Functions
PathLine ()
PathLine (double initalMouseClickX, double initialMouseClickY)
Point2D getStartingPoint ()
Point2D getEndingPoint ()
void setStartingPoint (Point2D startingPoint)
void translate (double deltaX, double deltaY)
void setEndingPoint (Point2D endingPoint)
double getLength ()
void select ()
void removeStroke ()
PathComponent deepCopy ()
List< VisibilityPoint > getInnerPointsRepresentingComponent ()
List< Node > getExtraNodes ()
boolean isPathComponentVisible ()
void togglePathComponentVisibility ()
void showVisibility ()
Public Member Functions inherited from gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent
default Node getNode ()
Private Attributes
boolean isPathComponentVisible
Detailed Description
Defines a line that can be drawn on the screen.
Author
Austin Kyker
Definition at line 18 of file PathLine.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.PathLine ()
Definition at line 22 of file PathLine.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.deepCopy().
gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.PathLine (double initalMouseClickX, double initialMouseClickY)
Definition at line 26 of file PathLine.java.
Member Function Documentation
PathComponent gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.deepCopy ()
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 80 of file PathLine.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.getEndingPoint(), gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.getStartingPoint(), gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.PathLine(), gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.setEndingPoint(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.setStartingPoint().
Point2D gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.getEndingPoint ()
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 41 of file PathLine.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.deepCopy(), gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.getLength(), and gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testBackendRouteCreation().
List<Node> gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.getExtraNodes ()
Extra nodes that should be deleted corresponding to a path component These nodes include control points for curves.
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 101 of file PathLine.java.
List<VisibilityPoint> gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.getInnerPointsRepresentingComponent ()
When converting a JavaFX line to a set of points for an enemy to follow, you simply need to include the starting and ending points and no "inner" points. The enemy will simply travel from the starting location to ending location on a linear path.
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 96 of file PathLine.java.
double gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.getLength ()
Definition at line 65 of file PathLine.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.getEndingPoint(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.getStartingPoint().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.handleBuildScreenClick().
Point2D gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.getStartingPoint ()
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 36 of file PathLine.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.deepCopy(), gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.getLength(), gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testBackendRouteCreation(), and gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testRoutesTranslation().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.isPathComponentVisible ()
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 105 of file PathLine.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.togglePathComponentVisibility().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.removeStroke ()
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 75 of file PathLine.java.
void gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.select ()
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 70 of file PathLine.java.
void gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.setEndingPoint (Point2D endingPoint)
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 60 of file PathLine.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AttemptToConnectRoutesFORKTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AttemptToConnectRoutesNoForkTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectComponentToEndingLocationTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectComponentToStartingLocationTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectLineToCurveTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectRoutesTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.ConnectTwoLinesTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.CreateTwoRoutesTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.deepCopy(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.GetRouteContainingComponentTest(), and gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testRoutesTranslation().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.setStartingPoint (Point2D startingPoint)
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 46 of file PathLine.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AttemptToConnectRoutesFORKTest(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCreationTests.AttemptToConnectRoutesNoForkTest(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.deepCopy().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.showVisibility ()
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 116 of file PathLine.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.INVISIBLE_COLOR, and gameAuthoring.scenes.pathBuilding.pathComponents.Path.VISIBLE_COLOR.
void gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.togglePathComponentVisibility ()
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 109 of file PathLine.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.INVISIBLE_COLOR, gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.isPathComponentVisible(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.VISIBLE_COLOR.
void gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.translate (double deltaX, double deltaY)
Implements gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.
Definition at line 52 of file PathLine.java.
Member Data Documentation
boolean gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.isPathComponentVisible private
Definition at line 20 of file PathLine.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/pathComponents/PathLine.java