voogasalad_LosTorres: gameEngine.actors.behaviors.AIMovement Class Reference
gameEngine.actors.behaviors.AIMovement Class Reference
Public Member Functions
AIMovement (List< Double > list)
void execute (BaseActor actor)
IBehavior copy ()
Public Member Functions inherited from gameEngine.actors.behaviors.BaseMovementBehavior
BaseMovementBehavior (double speed)
BaseMovementBehavior (double speed, BackendRoute route)
double getSpeed ()
void setSpeed (double speed)
double getRemainingDistance ()
void setRoute (BackendRoute route)
String toString ()
Private Attributes
transient GridPathFinder myPathFinder
transient List< Point2D > myAIRoute
Additional Inherited Members
Protected Member Functions inherited from gameEngine.actors.behaviors.BaseMovementBehavior
void move (BaseActor a, Point2D point)
void moveTowards (BaseActor a, Point2D current, Point2D target)
void findNextTarget (BaseActor actor, List< Point2D > route)
Protected Attributes inherited from gameEngine.actors.behaviors.BaseMovementBehavior
List< Double > myList
String myString
List< VisibilityPoint > myRoute
double mySpeed
double myRemainingDistance
int myIndex
Package Functions inherited from gameEngine.actors.behaviors.BaseMovementBehavior
BaseMovementBehavior (List< Double > list)
Detailed Description
Definition at line 11 of file AIMovement.java.
Constructor & Destructor Documentation
gameEngine.actors.behaviors.AIMovement.AIMovement (List< Double > list)
Definition at line 15 of file AIMovement.java.
References gameEngine.actors.behaviors.BaseMovementBehavior.myIndex.
Referenced by gameEngine.actors.behaviors.AIMovement.copy().
Member Function Documentation
IBehavior gameEngine.actors.behaviors.AIMovement.copy ()
Returns a copy of the behavior, which allows for copying entire actors
Returns
copy of the behavior
Implements gameEngine.actors.behaviors.IBehavior.
Definition at line 45 of file AIMovement.java.
References gameEngine.actors.behaviors.AIMovement.AIMovement(), and gameEngine.actors.behaviors.BaseMovementBehavior.myList.
void gameEngine.actors.behaviors.AIMovement.execute (BaseActor actor)
Execute method that executes the specific behavior on the given actor
Parameters
actor that is executed on
Implements gameEngine.actors.behaviors.IBehavior.
Definition at line 22 of file AIMovement.java.
References gameEngine.ManagerInterface.InformationInterface.checkNewPath(), gameEngine.actors.behaviors.BaseMovementBehavior.findNextTarget(), gameEngine.ManagerInterface.InformationInterface.getExistingTowerTiles(), gameEngine.actors.BaseActor.getInfoInterface(), gameEngine.actors.BaseActor.getNode(), gameEngine.AI.GridPathFinder.getPath(), gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.VisibilityPoint.getPoint(), gameEngine.ManagerInterface.InformationInterface.getReferencePane(), gameEngine.actors.BaseEnemy.getStart(), gameEngine.actors.behaviors.BaseMovementBehavior.move(), and gameEngine.actors.behaviors.BaseMovementBehavior.myIndex.
Member Data Documentation
transient List<Point2D> gameEngine.actors.behaviors.AIMovement.myAIRoute private
Definition at line 13 of file AIMovement.java.
transient GridPathFinder gameEngine.actors.behaviors.AIMovement.myPathFinder private
Definition at line 12 of file AIMovement.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/behaviors/AIMovement.java