voogasalad_LosTorres: gameEngine.actors.BaseEnemy Class Reference
gameEngine.actors.BaseEnemy Class Reference
Public Member Functions
BaseEnemy (Map< String, IBehavior > behaviors, String image, String name, double range, int damage, ProjectileInfo projectile, List< BackendRoute > route)
BaseEnemy (Map< String, IBehavior > behaviors, String image, String name, double range, int damage, List< BackendRoute > route)
BaseActor copy ()
int getBounty ()
void died ()
void killed ()
VisibilityPoint getStart ()
VisibilityPoint getGoal ()
Public Member Functions inherited from gameEngine.actors.RealActor
RealActor (Map< String, IBehavior > behaviors, String image, String name, double range)
RealActor (Map< String, IBehavior > behaviors, String image, String name, double range, ProjectileInfo projectile)
void update (InformationInterface info)
ProjectileInfo getProjectile ()
void spawnProjectile (BaseActor projectile)
Node getRange ()
abstract BaseActor copy ()
Public Member Functions inherited from gameEngine.actors.BaseActor
BaseActor ()
BaseActor (Map< String, IBehavior > behaviors, String imageName, String name, double range)
void update (InformationInterface info)
boolean addDebuff (IBehavior debuff)
void removeDebuff (IBehavior debuff)
void makeNode (Point2D point)
IBehavior getBehavior (String s)
String toString ()
double getX ()
double getY ()
CenteredImageView getNode ()
String getImagePath ()
abstract Node getRange ()
double getRangeProperty ()
List< BaseActor > getEnemiesInRange (double range)
List< BaseActor > getTowersInRange (double range)
List< BaseActor > getProjectilesInRange (double range)
InformationInterface getInfoInterface ()
Collection< Class<?extends BaseActor > > getTypes ()
void setRange (double d)
void died ()
boolean isDead ()
void changeAndNotify (UpdateObject o)
void killed ()
Protected Member Functions
int[] getSize ()
Protected Member Functions inherited from gameEngine.actors.BaseActor
void makeNode ()
abstract int[] getSize ()
Map< String, IBehavior > copyBehaviors ()
Private Member Functions
void initializeEnemy (Map< String, IBehavior > behaviors, int damage, List< BackendRoute > route)
Private Attributes
List< BackendRoute > myRoutes
int myDamage
VisibilityPoint myStart
VisibilityPoint myGoal
long MY_SEED =828
Additional Inherited Members
Protected Attributes inherited from gameEngine.actors.RealActor
ProjectileInfo myProjectile
Protected Attributes inherited from gameEngine.actors.BaseActor
Map< String, IBehavior > myBehaviors
String myName
transient CenteredImageView myNode
transient InformationInterface myInfo
double myRange
int myBounty
String myImagePath
transient Set< Class<?extends BaseActor > > myTypes
boolean myIsRemovable
Map< String, IBehavior > myDebuffs
Set< IBehavior > myDebuffsToRemove
Detailed Description
Author
Chase Malik, Timesh Patel
Definition at line 19 of file BaseEnemy.java.
Constructor & Destructor Documentation
gameEngine.actors.BaseEnemy.BaseEnemy (Map< String, IBehavior > behaviors, String image, String name, double range, int damage, ProjectileInfo projectile, List< BackendRoute > route)
Definition at line 26 of file BaseEnemy.java.
References gameEngine.actors.BaseEnemy.initializeEnemy().
Referenced by gameEngine.actors.BaseEnemy.copy().
gameEngine.actors.BaseEnemy.BaseEnemy (Map< String, IBehavior > behaviors, String image, String name, double range, int damage, List< BackendRoute > route)
Definition at line 30 of file BaseEnemy.java.
References gameEngine.actors.BaseEnemy.initializeEnemy().
Member Function Documentation
BaseActor gameEngine.actors.BaseEnemy.copy ()
Definition at line 47 of file BaseEnemy.java.
References gameEngine.actors.BaseEnemy.BaseEnemy(), gameEngine.actors.BaseActor.copyBehaviors(), gameEngine.actors.BaseActor.getNode(), gameEngine.actors.BaseActor.myBounty, gameEngine.actors.BaseActor.myImagePath, gameEngine.actors.BaseActor.myName, gameEngine.actors.RealActor.myProjectile, and gameEngine.actors.BaseActor.myRange.
Referenced by gameEngine.MainEngineManager.loadLevel().
void gameEngine.actors.BaseEnemy.died ()
Definition at line 62 of file BaseEnemy.java.
References gameEngine.actors.BaseActor.changeAndNotify(), and gameEngine.actors.BaseActor.myIsRemovable.
int gameEngine.actors.BaseEnemy.getBounty ()
Definition at line 58 of file BaseEnemy.java.
References gameEngine.actors.BaseActor.myBounty.
VisibilityPoint gameEngine.actors.BaseEnemy.getGoal ()
Definition at line 77 of file BaseEnemy.java.
References gameEngine.actors.BaseEnemy.myGoal.
Referenced by gameEngine.AI.GridPathFinder.getPath().
int [] gameEngine.actors.BaseEnemy.getSize () protected
Definition at line 55 of file BaseEnemy.java.
VisibilityPoint gameEngine.actors.BaseEnemy.getStart ()
Definition at line 73 of file BaseEnemy.java.
References gameEngine.actors.BaseEnemy.myStart.
Referenced by gameEngine.actors.behaviors.AIMovement.execute().
void gameEngine.actors.BaseEnemy.initializeEnemy (Map< String, IBehavior > behaviors, int damage, List< BackendRoute > route) private
Definition at line 35 of file BaseEnemy.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.getPoints().
Referenced by gameEngine.actors.BaseEnemy.BaseEnemy().
void gameEngine.actors.BaseEnemy.killed ()
Definition at line 68 of file BaseEnemy.java.
References gameEngine.actors.BaseActor.changeAndNotify(), gameEngine.actors.BaseActor.myBounty, and gameEngine.actors.BaseActor.myIsRemovable.
Member Data Documentation
long gameEngine.actors.BaseEnemy.MY_SEED =828 private
Definition at line 25 of file BaseEnemy.java.
int gameEngine.actors.BaseEnemy.myDamage private
Definition at line 22 of file BaseEnemy.java.
VisibilityPoint gameEngine.actors.BaseEnemy.myGoal private
Definition at line 24 of file BaseEnemy.java.
Referenced by gameEngine.actors.BaseEnemy.getGoal().
List<BackendRoute> gameEngine.actors.BaseEnemy.myRoutes private
Definition at line 21 of file BaseEnemy.java.
VisibilityPoint gameEngine.actors.BaseEnemy.myStart private
Definition at line 23 of file BaseEnemy.java.
Referenced by gameEngine.actors.BaseEnemy.getStart().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/BaseEnemy.java