voogasalad_LosTorres: utilities.JavaFXutilities.numericalTextFields.LabeledNumericalTextField Class Reference
utilities.JavaFXutilities.numericalTextFields.LabeledNumericalTextField Class Reference
Public Member Functions
LabeledNumericalTextField (String label, double textFieldWidth)
int getNumberEntered ()
boolean isValueEntered ()
void clearField ()
Private Attributes
NumericalTextField myTextField
Static Private Attributes
static final int SPACING = 10
Detailed Description
Definition at line 7 of file LabeledNumericalTextField.java.
Constructor & Destructor Documentation
utilities.JavaFXutilities.numericalTextFields.LabeledNumericalTextField.LabeledNumericalTextField (String label, double textFieldWidth)
Definition at line 12 of file LabeledNumericalTextField.java.
References utilities.multilanguage.MultiLanguageUtility.getInstance(), and utilities.multilanguage.MultiLanguageUtility.getStringProperty().
Member Function Documentation
void utilities.JavaFXutilities.numericalTextFields.LabeledNumericalTextField.clearField ()
Definition at line 28 of file LabeledNumericalTextField.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.clearActorSpecificFields(), and gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.clearActorSpecificFields().
int utilities.JavaFXutilities.numericalTextFields.LabeledNumericalTextField.getNumberEntered ()
Definition at line 20 of file LabeledNumericalTextField.java.
References utilities.JavaFXutilities.numericalTextFields.NumericalTextField.getNumber().
Referenced by gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.makeNewActor(), and gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.makeNewActor().
boolean utilities.JavaFXutilities.numericalTextFields.LabeledNumericalTextField.isValueEntered ()
Definition at line 24 of file LabeledNumericalTextField.java.
References utilities.JavaFXutilities.numericalTextFields.NumericalTextField.isValueEntered().
Referenced by gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.actorSpecificFieldsValid(), and gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.actorSpecificFieldsValid().
Member Data Documentation
NumericalTextField utilities.JavaFXutilities.numericalTextFields.LabeledNumericalTextField.myTextField private
Definition at line 10 of file LabeledNumericalTextField.java.
final int utilities.JavaFXutilities.numericalTextFields.LabeledNumericalTextField.SPACING = 10 static private
Definition at line 8 of file LabeledNumericalTextField.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/JavaFXutilities/numericalTextFields/LabeledNumericalTextField.java