voogasalad_LosTorres: gameEngine.actors.behaviors.SimpleDefense Class Reference
gameEngine.actors.behaviors.SimpleDefense Class Reference
Public Member Functions
SimpleDefense (double health)
SimpleDefense (List< Double > list)
IBehavior copy ()
void onDeath (BaseActor actor)
void handleBullet (BaseProjectile p)
Public Member Functions inherited from gameEngine.actors.behaviors.BaseDefendBehavior
double getHealth ()
void execute (BaseActor actor)
void setHealth (double d)
void gotHit (BaseActor actor, BaseProjectile p)
abstract void handleBullet (BaseProjectile p)
abstract void onDeath (BaseActor actor)
Public Member Functions inherited from gameEngine.actors.behaviors.IBehavior
String toString ()
Additional Inherited Members
Protected Attributes inherited from gameEngine.actors.behaviors.BaseDefendBehavior
List< Double > myList
double myHealth
double myInitialHealth
Package Functions inherited from gameEngine.actors.behaviors.BaseDefendBehavior
BaseDefendBehavior (List< Double > list)
BaseDefendBehavior (double health)
Detailed Description
Definition at line 8 of file SimpleDefense.java.
Constructor & Destructor Documentation
gameEngine.actors.behaviors.SimpleDefense.SimpleDefense (double health)
Definition at line 9 of file SimpleDefense.java.
Referenced by gameEngine.actors.behaviors.SimpleDefense.copy().
gameEngine.actors.behaviors.SimpleDefense.SimpleDefense (List< Double > list)
Definition at line 12 of file SimpleDefense.java.
Member Function Documentation
IBehavior gameEngine.actors.behaviors.SimpleDefense.copy ()
Returns a copy of the behavior, which allows for copying entire actors
Returns
copy of the behavior
Implements gameEngine.actors.behaviors.IBehavior.
Definition at line 16 of file SimpleDefense.java.
References gameEngine.actors.behaviors.BaseDefendBehavior.myList, and gameEngine.actors.behaviors.SimpleDefense.SimpleDefense().
void gameEngine.actors.behaviors.SimpleDefense.handleBullet (BaseProjectile p)
Definition at line 27 of file SimpleDefense.java.
References gameEngine.actors.BaseActor.died(), gameEngine.actors.BaseProjectile.getInfo(), gameEngine.actors.ProjectileInfo.getMyDamage(), and gameEngine.actors.behaviors.BaseDefendBehavior.myHealth.
void gameEngine.actors.behaviors.SimpleDefense.onDeath (BaseActor actor)
Definition at line 21 of file SimpleDefense.java.
References gameEngine.actors.BaseActor.killed().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/behaviors/SimpleDefense.java