voogasalad_LosTorres: gameEngine.AI.GridPathFinder Class Reference
gameEngine.AI.GridPathFinder Class Reference
Public Member Functions
Number getCost (Point2D beginningNode, Point2D endingNode)
List< Point2D > getPath (BaseEnemy enemy, GridPane tilePane, TowerTileGrid tileLocations)
Iterable< Point2D > getNeighbors (Point2D node)
int breakTie (Point2D node, Point2D other)
Number getHeuristicValue (Point2D node, Point2D destination)
Public Member Functions inherited from utilities.pathfinding.AStarPathFinder< T >
abstract Number getHeuristicValue (T node, T destination)
boolean isDestination (T node, T destinationNode)
List< T > findPath (T start, T destination) throws InvalidCostException
Public Member Functions inherited from utilities.pathfinding.IPathFinder< T >
Number getCost (T beginningNode, T endingNode)
Iterable< T > getNeighbors (T node)
int breakTie (T node, T other)
Private Attributes
Collection< int[]> myEnemyTileDirections
TowerTileGrid myTowerLocations
Static Private Attributes
static final int DIRECTION_SIZE = 2
static final int[][] SQUARE_2D_DIRECTION
Detailed Description
Definition at line 18 of file GridPathFinder.java.
Member Function Documentation
int gameEngine.AI.GridPathFinder.breakTie (Point2D node, Point2D other)
Definition at line 115 of file GridPathFinder.java.
Number gameEngine.AI.GridPathFinder.getCost (Point2D beginningNode, Point2D endingNode)
Definition at line 29 of file GridPathFinder.java.
Number gameEngine.AI.GridPathFinder.getHeuristicValue (Point2D node, Point2D destination)
Definition at line 124 of file GridPathFinder.java.
Iterable<Point2D> gameEngine.AI.GridPathFinder.getNeighbors (Point2D node)
Definition at line 84 of file GridPathFinder.java.
References gameEngine.Data.TowerTileGrid.checkTowerTile(), and gameEngine.Data.TowerTileGrid.isInRange().
List<Point2D> gameEngine.AI.GridPathFinder.getPath (BaseEnemy enemy, GridPane tilePane, TowerTileGrid tileLocations)
Definition at line 33 of file GridPathFinder.java.
References gameEngine.AI.GridPathFinder.DIRECTION_SIZE, gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.DRAW_SCREEN_WIDTH, utilities.pathfinding.AStarPathFinder< T >.findPath(), gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.getColumn(), gameEngine.actors.BaseEnemy.getGoal(), gameEngine.actors.BaseActor.getNode(), gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.VisibilityPoint.getPoint(), gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.getRow(), gameEngine.actors.BaseActor.getX(), gameEngine.actors.BaseActor.getY(), gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.NUM_COLS, gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.NUM_ROWS, and gameAuthoring.mainclasses.AuthorController.SCREEN_HEIGHT.
Referenced by gameEngine.actors.behaviors.AIMovement.execute().
Member Data Documentation
final int gameEngine.AI.GridPathFinder.DIRECTION_SIZE = 2 static private
Definition at line 20 of file GridPathFinder.java.
Referenced by gameEngine.AI.GridPathFinder.getPath().
Collection<int[]> gameEngine.AI.GridPathFinder.myEnemyTileDirections private
Definition at line 25 of file GridPathFinder.java.
TowerTileGrid gameEngine.AI.GridPathFinder.myTowerLocations private
Definition at line 26 of file GridPathFinder.java.
final int [][] gameEngine.AI.GridPathFinder.SQUARE_2D_DIRECTION static private
Initial value:
= { { -1, -1 }, { -1, 0 },
            { -1, 1 }, { 0, -1 }, { 0, 1 }, { 1, -1 }, { 1, 0 },
            { 1, 1 } }
Definition at line 21 of file GridPathFinder.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/AI/GridPathFinder.java