voogasalad_LosTorres: gamePlayer.guiFeatures.FileLoader Class Reference
gamePlayer.guiFeatures.FileLoader Class Reference
Public Member Functions
File loadDirectory (Window stage)
File load (Window stage, String fileType, String...extensions)
File save (Window stage)
Static Public Member Functions
static FileLoader getInstance ()
Private Member Functions
FileLoader ()
Static Private Attributes
static FileLoader myReference = null
Detailed Description
Class loads directories
Author
allankiplagat
Definition at line 16 of file FileLoader.java.
Constructor & Destructor Documentation
gamePlayer.guiFeatures.FileLoader.FileLoader () private
Definition at line 18 of file FileLoader.java.
Referenced by gamePlayer.guiFeatures.FileLoader.getInstance().
Member Function Documentation
static FileLoader gamePlayer.guiFeatures.FileLoader.getInstance () static
Definition at line 21 of file FileLoader.java.
References gamePlayer.guiFeatures.FileLoader.FileLoader(), and gamePlayer.guiFeatures.FileLoader.myReference.
Referenced by gamePlayer.mainClasses.managers.GuiManager.changeTheme(), gamePlayer.mainClasses.managers.GuiManager.loadGame(), gamePlayer.mainClasses.managers.GuiManager.loadState(), and gamePlayer.mainClasses.managers.GuiManager.saveGame().
File gamePlayer.guiFeatures.FileLoader.load (Window stage, String fileType, String... extensions)
Parameters
stage the stage that file loading is associated with
extensions to be filtered
Returns
Definition at line 43 of file FileLoader.java.
Referenced by gamePlayer.mainClasses.managers.GuiManager.changeTheme(), and gamePlayer.mainClasses.managers.GuiManager.loadState().
File gamePlayer.guiFeatures.FileLoader.loadDirectory (Window stage)
Parameters
stage the stage that directory loading is associated with
Returns
Definition at line 32 of file FileLoader.java.
Referenced by gamePlayer.mainClasses.managers.GuiManager.loadGame().
File gamePlayer.guiFeatures.FileLoader.save (Window stage)
Definition at line 55 of file FileLoader.java.
Referenced by gamePlayer.mainClasses.managers.GuiManager.saveGame().
Member Data Documentation
FileLoader gamePlayer.guiFeatures.FileLoader.myReference = null static private
Definition at line 17 of file FileLoader.java.
Referenced by gamePlayer.guiFeatures.FileLoader.getInstance().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiFeatures/FileLoader.java