voogasalad_LosTorres: gamePlayer.mainClasses.guiBuilder.GuiElement Interface Reference
gamePlayer.mainClasses.guiBuilder.GuiElement Interface Reference
Public Member Functions
abstract void initialize (Dimension2D containerSize)
abstract Node getNode ()
Detailed Description
Everything on the GUI is a GuiElement and this class defines universal GuiElement behavior Known implementing classes: GuiItem and GuiContainer interfaces
Author
allankiplagat
Definition at line 12 of file GuiElement.java.
Member Function Documentation
abstract Node gamePlayer.mainClasses.guiBuilder.GuiElement.getNode () abstract
Returns
this GuiElement's Node
Implemented in gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel, gamePlayer.guiItems.store.Store, gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore, gamePlayer.unusedCodeWarehouse.guiItems.store.Store, gamePlayer.guiItems.headsUpDisplay.HUD, gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar, gamePlayer.unusedCodeWarehouse.guiItems.store.StoreItemCell, gamePlayer.guiItems.controlDockButtons.buttons.PlayButton, gamePlayer.unusedCodeWarehouse.HUDContainer, gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health, gamePlayer.guiItems.messageDisplay.MessageDisplay, gamePlayer.guiItems.welcome.ClickAnywherePane, gamePlayer.guiItems.controlDockButtons.buttons.SpeedButton, gamePlayer.guiContainers.secondaryContainers.ControlDock, gamePlayer.guiItems.controlDockButtons.sliders.SpeedSlider, gamePlayer.guiItems.gameWorld.GameWorld, gamePlayer.guiItems.welcome.WelcomeNavigator, gamePlayer.guiContainers.coreContainers.CenterContainer, gamePlayer.guiContainers.coreContainers.BottomContainer, gamePlayer.guiContainers.coreContainers.TopContainer, gamePlayer.guiItems.welcome.GameChooser, gamePlayer.guiItems.welcome.Header, gamePlayer.guiContainers.coreContainers.LeftContainer, gamePlayer.guiContainers.coreContainers.RightContainer, gamePlayer.guiItems.placeholders.BottomItemPlaceholder, gamePlayer.guiItems.placeholders.CenterItemPlaceholder, gamePlayer.guiItems.placeholders.LeftItemPlaceholder, gamePlayer.guiItems.placeholders.RightItemPlaceholder, and gamePlayer.guiItems.placeholders.TopItemPlaceholder.
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.store.Store.buildInventoryItems(), gamePlayer.guiItems.welcome.WelcomeNavigator.deviceConnected(), gamePlayer.guiContainers.secondaryContainers.ControlDock.initialize(), gamePlayer.unusedCodeWarehouse.HUDContainer.initialize(), gamePlayer.guiContainers.coreContainers.CoreContainerSetup.initialize(), and gamePlayer.guiItems.welcome.WelcomeNavigator.setupContents().
abstract void gamePlayer.mainClasses.guiBuilder.GuiElement.initialize (Dimension2D containerSize) abstract
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implemented in gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel, gamePlayer.unusedCodeWarehouse.guiItems.store.Store, gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore, gamePlayer.guiItems.store.Store, gamePlayer.guiItems.welcome.ClickAnywherePane, gamePlayer.guiItems.gameWorld.GameWorld, gamePlayer.unusedCodeWarehouse.guiItems.headsUpDisplayA.Health, gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar, gamePlayer.guiItems.headsUpDisplay.HUD, gamePlayer.guiItems.messageDisplay.MessageDisplay, gamePlayer.guiContainers.coreContainers.CenterContainer, gamePlayer.guiItems.welcome.GameChooser, gamePlayer.guiItems.welcome.WelcomeNavigator, gamePlayer.unusedCodeWarehouse.HUDContainer, gamePlayer.guiContainers.coreContainers.BottomContainer, gamePlayer.guiContainers.coreContainers.LeftContainer, gamePlayer.guiContainers.coreContainers.TopContainer, gamePlayer.guiContainers.coreContainers.RightContainer, gamePlayer.guiItems.controlDockButtons.buttons.PlayButton, gamePlayer.guiItems.welcome.Header, gamePlayer.unusedCodeWarehouse.guiItems.store.StoreItemCell, gamePlayer.guiItems.controlDockButtons.ControlDockSlider, gamePlayer.guiItems.controlDockButtons.sliders.SpeedSlider, gamePlayer.guiItems.controlDockButtons.ControlDockButton, gamePlayer.guiItems.placeholders.BottomItemPlaceholder, gamePlayer.guiItems.placeholders.CenterItemPlaceholder, gamePlayer.guiItems.placeholders.LeftItemPlaceholder, gamePlayer.guiItems.placeholders.RightItemPlaceholder, gamePlayer.guiItems.placeholders.TopItemPlaceholder, gamePlayer.guiContainers.secondaryContainers.ControlDock, and gamePlayer.guiItems.controlDockButtons.buttons.SpeedButton.
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.store.Store.buildInventoryItems(), gamePlayer.guiItems.welcome.WelcomeNavigator.deviceConnected(), gamePlayer.guiContainers.secondaryContainers.ControlDock.initialize(), gamePlayer.unusedCodeWarehouse.HUDContainer.initialize(), gamePlayer.guiContainers.coreContainers.CoreContainerSetup.initialize(), and gamePlayer.guiItems.welcome.WelcomeNavigator.setupContents().
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/mainClasses/guiBuilder/GuiElement.java