voogasalad_LosTorres: gamePlayer.guiItems.controlDockButtons.ControlDockSlider Class Reference
gamePlayer.guiItems.controlDockButtons.ControlDockSlider Class Reference abstract
Public Member Functions
void initialize (Dimension2D containerSize)
Public Member Functions inherited from gamePlayer.mainClasses.guiBuilder.GuiElement
abstract Node getNode ()
Static Public Attributes
static final String LABEL = "GameSpeed"
Static Public Attributes inherited from gamePlayer.guiItems.GuiItem
static String myPropertiesPath = "guiItems/"
Protected Member Functions
void setUpSizing (Dimension2D containerSize)
Protected Attributes
XMLParser myParser
SliderContainer mySlider
Detailed Description
Definition at line 15 of file ControlDockSlider.java.
Member Function Documentation
void gamePlayer.guiItems.controlDockButtons.ControlDockSlider.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 22 of file ControlDockSlider.java.
void gamePlayer.guiItems.controlDockButtons.ControlDockSlider.setUpSizing (Dimension2D containerSize) protected
Definition at line 26 of file ControlDockSlider.java.
References utilities.JavaFXutilities.ratioSizing.RatiosToDim.convert(), and utilities.XMLParsing.XMLParser.getDimension().
Referenced by gamePlayer.guiItems.controlDockButtons.sliders.SpeedSlider.initialize().
Member Data Documentation
final String gamePlayer.guiItems.controlDockButtons.ControlDockSlider.LABEL = "GameSpeed" static
Definition at line 19 of file ControlDockSlider.java.
XMLParser gamePlayer.guiItems.controlDockButtons.ControlDockSlider.myParser protected
Definition at line 16 of file ControlDockSlider.java.
Referenced by gamePlayer.guiItems.controlDockButtons.sliders.SpeedSlider.initialize().
SliderContainer gamePlayer.guiItems.controlDockButtons.ControlDockSlider.mySlider protected
Definition at line 17 of file ControlDockSlider.java.
Referenced by gamePlayer.guiItems.controlDockButtons.sliders.SpeedSlider.getNode(), and gamePlayer.guiItems.controlDockButtons.sliders.SpeedSlider.setUpSlider().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItems/controlDockButtons/ControlDockSlider.java