voogasalad_LosTorres: gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder Class Reference
gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder Class Reference
Public Member Functions
BehaviorBuilder (String behaviorType, List< String > behaviorOptions, List< SliderInfo > sliderInfoObjects)
IBehaviorKeyValuePair buildBehavior ()
void createCenterDisplay ()
VBox getContainer ()
void reset ()
boolean isValid ()
Protected Attributes
ComboBox< String > myComboBox
VBox myContainer
SliderInfo mySliderInfo
Private Member Functions
ComboBox< String > createComboBox ()
Private Attributes
List< SliderContainer > mySliderContainers
String myBehaviorType
List< String > myBehaviorOptions
Static Private Attributes
static final double COMBO_BOX_WIDTH = 160
Detailed Description
A class representing JavaFX components used to build a behavior that will be added to an actors list of behaviors. When a new type of behavior (like attack or movement) is added, a new behavior builder class should be constructed title "BehaviorType"Builder. In the behavior xml file (there is one for towers and one for enemies), the different kinds of this type of behavior should be listed. This class will automatically create a comboBox with all of these options. It is your job to create the sliders and other components you need to get all the information to actually make the behavior object. This behavior creation is done in the buildBehavior method which all subclasses must use. To get some good examples, see MovementBuilder and AttackBuilder.
Author
Austin Kyker
Definition at line 29 of file BehaviorBuilder.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.BehaviorBuilder (String behaviorType, List< String > behaviorOptions, List< SliderInfo > sliderInfoObjects)
Definition at line 40 of file BehaviorBuilder.java.
References gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.createCenterDisplay().
Member Function Documentation
IBehaviorKeyValuePair gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.buildBehavior ()
Definition at line 52 of file BehaviorBuilder.java.
References utilities.reflection.Reflection.createInstance().
void gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.createCenterDisplay ()
Definition at line 62 of file BehaviorBuilder.java.
References gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.createComboBox(), utilities.multilanguage.MultiLanguageUtility.getInstance(), utilities.multilanguage.MultiLanguageUtility.getStringProperty(), and gameAuthoring.mainclasses.Constants.LG_PADDING.
Referenced by gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.BehaviorBuilder().
ComboBox<String> gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.createComboBox () private
Definition at line 74 of file BehaviorBuilder.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.createCenterDisplay().
VBox gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.getContainer ()
Definition at line 82 of file BehaviorBuilder.java.
References gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.myContainer.
boolean gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.isValid ()
Definition at line 93 of file BehaviorBuilder.java.
References gameAuthoring.mainclasses.Constants.EMPTY_BEHAVIOR.
void gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.reset ()
Definition at line 86 of file BehaviorBuilder.java.
Member Data Documentation
final double gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.COMBO_BOX_WIDTH = 160 static private
Definition at line 31 of file BehaviorBuilder.java.
List<String> gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.myBehaviorOptions private
Definition at line 38 of file BehaviorBuilder.java.
String gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.myBehaviorType private
Definition at line 37 of file BehaviorBuilder.java.
ComboBox<String> gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.myComboBox protected
Definition at line 33 of file BehaviorBuilder.java.
VBox gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.myContainer protected
Definition at line 34 of file BehaviorBuilder.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.getContainer().
List<SliderContainer> gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.mySliderContainers private
Definition at line 35 of file BehaviorBuilder.java.
SliderInfo gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorBuilder.mySliderInfo protected
Definition at line 36 of file BehaviorBuilder.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/actorBuildingScenes/behaviorBuilders/BehaviorBuilder.java