voogasalad_LosTorres: gamePlayer.guiItems.controlDockButtons.buttons.SpeedButton Class Reference
gamePlayer.guiItems.controlDockButtons.buttons.SpeedButton Class Reference
Public Member Functions
void initialize (Dimension2D containerSize)
Node getNode ()
Public Member Functions inherited from gamePlayer.guiItems.controlDockButtons.ControlDockButton
void initialize (Dimension2D containerSize)
Private Member Functions
void fastForward ()
void normalSpeed ()
Private Attributes
String ffImage
String slowImage
SpeedButtonListener myListener = GuiConstants.GUI_MANAGER
Additional Inherited Members
Static Public Attributes inherited from gamePlayer.guiItems.GuiItem
static String myPropertiesPath = "guiItems/"
Protected Member Functions inherited from gamePlayer.guiItems.controlDockButtons.ControlDockButton
void setupImageViews (String path1, String path2)
void setUpSizing (Dimension2D containerSize)
Protected Attributes inherited from gamePlayer.guiItems.controlDockButtons.ControlDockButton
XMLParser myParser
ImageView myImageView
ToggleButton myButton
Dimension2D buttonSize
Dimension2D imageSize
Detailed Description
Definition at line 13 of file SpeedButton.java.
Member Function Documentation
void gamePlayer.guiItems.controlDockButtons.buttons.SpeedButton.fastForward () private
Definition at line 33 of file SpeedButton.java.
References gamePlayer.guiItemsListeners.SpeedButtonListener.fastForward(), gamePlayer.guiItems.controlDockButtons.ControlDockButton.myButton, and gamePlayer.guiItems.controlDockButtons.buttons.SpeedButton.normalSpeed().
Node gamePlayer.guiItems.controlDockButtons.buttons.SpeedButton.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 44 of file SpeedButton.java.
References gamePlayer.guiItems.controlDockButtons.ControlDockButton.myButton.
void gamePlayer.guiItems.controlDockButtons.buttons.SpeedButton.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 19 of file SpeedButton.java.
References utilities.XMLParsing.XMLParser.getValuesFromTag(), gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_ELEMENT_PROPERTIES_PATH, gamePlayer.guiItems.controlDockButtons.ControlDockButton.myButton, gamePlayer.guiItems.controlDockButtons.ControlDockButton.myImageView, gamePlayer.guiItems.controlDockButtons.ControlDockButton.myParser, gamePlayer.guiItems.GuiItem.myPropertiesPath, gamePlayer.guiItems.controlDockButtons.buttons.SpeedButton.normalSpeed(), gamePlayer.guiItems.controlDockButtons.ControlDockButton.setupImageViews(), and gamePlayer.guiItems.controlDockButtons.ControlDockButton.setUpSizing().
void gamePlayer.guiItems.controlDockButtons.buttons.SpeedButton.normalSpeed () private
Definition at line 38 of file SpeedButton.java.
References gamePlayer.guiItemsListeners.SpeedButtonListener.normalSpeed().
Referenced by gamePlayer.guiItems.controlDockButtons.buttons.SpeedButton.fastForward(), and gamePlayer.guiItems.controlDockButtons.buttons.SpeedButton.initialize().
Member Data Documentation
String gamePlayer.guiItems.controlDockButtons.buttons.SpeedButton.ffImage private
Definition at line 14 of file SpeedButton.java.
SpeedButtonListener gamePlayer.guiItems.controlDockButtons.buttons.SpeedButton.myListener = GuiConstants.GUI_MANAGER private
Definition at line 16 of file SpeedButton.java.
String gamePlayer.guiItems.controlDockButtons.buttons.SpeedButton.slowImage private
Definition at line 15 of file SpeedButton.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItems/controlDockButtons/buttons/SpeedButton.java