voogasalad_LosTorres: gameEngine.MainEngineManager Class Reference
gameEngine.MainEngineManager Class Reference
Public Member Functions
MainEngineManager ()
void setEarthquakeMagnitude (double magnitude)
double getEarthquakeMagnitude ()
GridPane getReferencePane ()
TowerTileGrid getExistingTowerTiles ()
MainEngineManager (Pane engineGroup)
double getMyGold ()
DoubleProperty getGoldProperty ()
void setMyGold (double value)
double getMyHealth ()
DoubleProperty getHealthProperty ()
void setMyHealth (double value)
void revertToOriginalSpeed ()
void changeRunSpeed (double magnitude)
String getTowerName (ImageView node)
void removeTower (ImageView node)
ImageView addTower (String identifier, double x, double y)
List< BaseActor > getRequiredActors (BaseActor actor, Class<?extends BaseActor > infoType)
boolean checkNewPath ()
void pause ()
void resume ()
Collection< TowerInfoObject > getAllTowerTypeInformation ()
void initializeGame (String directory)
boolean validateTower (double x, double y)
boolean checkGold (TowerInfoObject towerInfoObject)
void loadTowers (String directory)
SimpleDoubleProperty getWinStatus ()
SimpleDoubleProperty getCurrentLevelProperty ()
void loadLevel (BaseLevel level)
boolean isRunning ()
void loadAuthoringLevel (BaseLevel level)
void update (Observable o, Object arg)
void saveState (String directory, String fileName)
void clear ()
void loadState (String gameFile)
ImageView upgrade (ImageView n, String name)
void sellTower (ImageView n)
Protected Member Functions
void addGroups (Pane engineGroup)
void onLevelEnd ()
Protected Attributes
RangeRestrictedCollection< BaseTower > myTowerGroup
GSONFileReader myFileReader
GSONFileWriter myFileWriter
Private Member Functions
void setTowerTileStatus (BaseTower tower, boolean towerTileStatus)
Collection< Node > getIntersectingTowerTileNode (Node towerNode, Collection< Node > nodeList)
Timeline createTimeline ()
void gameUpdate ()
void onGameLose ()
void addEnemies ()
void updateActors (RangeRestrictedCollection<?extends BaseActor > actorGroup)
boolean isInRangeOfField (BaseActor actor)
void loadGameSettings (String directory)
void loadLocations (String dir)
GridPane createGameSizedGridPane ()
boolean listCollidesWith (List< Node > list, double x, double y)
void loadLevelFile (String directory)
void loadNextLevel ()
List< DataWrapper > wrapTowers ()
Private Attributes
double myLastUpdateTime
Timeline myTimeline
double myUpdateRate
AtomicBoolean myReadyToPlay
RangeRestrictedCollection< BaseEnemy > myEnemyGroup
RangeRestrictedCollection< BaseProjectile > myProjectileGroup
double duration
List< BaseLevel > myLevels
int myCurrentLevelIndex
GridPane myValidRegions
SimpleDoubleProperty myGold
Map< String, BaseTower > myPrototypeTowerMap
double myIntervalBetweenEnemies
Queue< BaseEnemy > myEnemiesToAdd
SimpleDoubleProperty myHealth
SimpleDoubleProperty myEarthquakeMagnitude
Map< Node, BaseTower > myNodeToTower
Collection< TowerInfoObject > myTowerInformation
TowerTileGrid myTowerLocationByGrid
GridPane myTowerTiles
double myFieldWidth
double myFieldHeight
boolean myPausedFlag
String myCurrentGameName
SimpleDoubleProperty myCurrentLevelProperty
SimpleDoubleProperty myWinStatus
Static Private Attributes
static final String UNKNOWN_SAVE_STATE_FILE_MESSAGE = "Unknown problem loading save file"
static final String INCORRECT_SAVE_STATE_MESSAGE = "Save state does not correspond to this game"
static final String JSON_EXTENSION = ".json"
static final String DIRECTORY_SPLIT = "/"
static final int FPS = 30
static final double FRAME_DURATION = 1000.0 / 30
Detailed Description
Definition at line 55 of file MainEngineManager.java.
Constructor & Destructor Documentation
gameEngine.MainEngineManager.MainEngineManager ()
Definition at line 97 of file MainEngineManager.java.
References gameEngine.MainEngineManager.createGameSizedGridPane(), and gameEngine.MainEngineManager.createTimeline().
gameEngine.MainEngineManager.MainEngineManager (Pane engineGroup)
Definition at line 142 of file MainEngineManager.java.
References gameEngine.MainEngineManager.addGroups().
Member Function Documentation
void gameEngine.MainEngineManager.addEnemies () private
Definition at line 306 of file MainEngineManager.java.
References gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.add(), and gameEngine.MainEngineManager.myIntervalBetweenEnemies.
Referenced by gameEngine.MainEngineManager.gameUpdate().
void gameEngine.MainEngineManager.addGroups (Pane engineGroup) protected
Definition at line 147 of file MainEngineManager.java.
Referenced by gameEngine.CoOpManager.initializeGame(), and gameEngine.MainEngineManager.MainEngineManager().
ImageView gameEngine.MainEngineManager.addTower (String identifier, double x, double y)
Definition at line 205 of file MainEngineManager.java.
References gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.add(), gameEngine.actors.BaseTower.copy(), gameEngine.actors.BaseActor.getNode(), gameEngine.MainEngineManager.setTowerTileStatus(), utilities.JavaFXutilities.imageView.CenteredImageView.setXCenter(), and utilities.JavaFXutilities.imageView.CenteredImageView.setYCenter().
Referenced by gameEngine.MainEngineManager.loadState(), gamePlayer.mainClasses.managers.GuiManager.makeTower(), and gameEngine.MainEngineManager.upgrade().
void gameEngine.MainEngineManager.changeRunSpeed (double magnitude)
Definition at line 187 of file MainEngineManager.java.
Referenced by gamePlayer.mainClasses.managers.GuiManager.changeSpeed(), and gameEngine.MainEngineManager.revertToOriginalSpeed().
boolean gameEngine.MainEngineManager.checkGold (TowerInfoObject towerInfoObject)
Definition at line 436 of file MainEngineManager.java.
References gameEngine.Data.TowerInfoObject.getBuyCost().
Referenced by gamePlayer.mainClasses.managers.GuiManager.makeTower(), and gamePlayer.mainClasses.managers.GuiManager.upgradeTower().
boolean gameEngine.MainEngineManager.checkNewPath ()
Implements gameEngine.ManagerInterface.InformationInterface.
Definition at line 358 of file MainEngineManager.java.
References gameEngine.Data.TowerTileGrid.hasBeenChanged().
void gameEngine.MainEngineManager.clear ()
Definition at line 561 of file MainEngineManager.java.
References gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.clear().
Referenced by gameEngine.MainEngineManager.loadState().
GridPane gameEngine.MainEngineManager.createGameSizedGridPane () private
Definition at line 420 of file MainEngineManager.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.DRAW_SCREEN_WIDTH, and gameAuthoring.mainclasses.AuthorController.SCREEN_HEIGHT.
Referenced by gameEngine.MainEngineManager.loadLocations(), and gameEngine.MainEngineManager.MainEngineManager().
Timeline gameEngine.MainEngineManager.createTimeline () private
Definition at line 240 of file MainEngineManager.java.
References gameEngine.MainEngineManager.gameUpdate(), gameEngine.MainEngineManager.myUpdateRate, and gameEngine.Data.TowerTileGrid.setAsNotChanged().
Referenced by gameEngine.MainEngineManager.MainEngineManager().
void gameEngine.MainEngineManager.gameUpdate () private
Definition at line 271 of file MainEngineManager.java.
References gameEngine.MainEngineManager.addEnemies(), gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.clearAndExecuteRemoveBuffer(), gameEngine.MainEngineManager.onGameLose(), gameEngine.MainEngineManager.onLevelEnd(), and gameEngine.MainEngineManager.updateActors().
Referenced by gameEngine.MainEngineManager.createTimeline().
Collection<TowerInfoObject> gameEngine.MainEngineManager.getAllTowerTypeInformation ()
Definition at line 372 of file MainEngineManager.java.
References gameEngine.MainEngineManager.myTowerInformation.
Referenced by gamePlayer.mainClasses.managers.GuiManager.initializeNewGameElements(), and gamePlayer.mainClasses.managers.GuiManager.startGame().
SimpleDoubleProperty gameEngine.MainEngineManager.getCurrentLevelProperty ()
Definition at line 485 of file MainEngineManager.java.
References gameEngine.MainEngineManager.myCurrentLevelProperty.
Referenced by gamePlayer.mainClasses.managers.GuiManager.setUpHUD().
double gameEngine.MainEngineManager.getEarthquakeMagnitude ()
Implements gameEngine.ManagerInterface.InformationInterface.
Definition at line 128 of file MainEngineManager.java.
TowerTileGrid gameEngine.MainEngineManager.getExistingTowerTiles ()
Implements gameEngine.ManagerInterface.InformationInterface.
Definition at line 138 of file MainEngineManager.java.
References gameEngine.MainEngineManager.myTowerLocationByGrid.
DoubleProperty gameEngine.MainEngineManager.getGoldProperty ()
Definition at line 160 of file MainEngineManager.java.
References gameEngine.MainEngineManager.myGold.
Referenced by gamePlayer.mainClasses.managers.GuiManager.makeTower(), gamePlayer.mainClasses.managers.GuiManager.setUpHUD(), and gamePlayer.mainClasses.managers.GuiManager.upgradeTower().
DoubleProperty gameEngine.MainEngineManager.getHealthProperty ()
Definition at line 174 of file MainEngineManager.java.
References gameEngine.MainEngineManager.myHealth.
Referenced by gamePlayer.mainClasses.managers.GuiManager.setUpHUD().
Collection<Node> gameEngine.MainEngineManager.getIntersectingTowerTileNode (Node towerNode, Collection< Node > nodeList) private
Definition at line 232 of file MainEngineManager.java.
Referenced by gameEngine.MainEngineManager.setTowerTileStatus().
double gameEngine.MainEngineManager.getMyGold ()
Implements gameEngine.ManagerInterface.UpdateInterface.
Definition at line 156 of file MainEngineManager.java.
double gameEngine.MainEngineManager.getMyHealth ()
Implements gameEngine.ManagerInterface.UpdateInterface.
Definition at line 170 of file MainEngineManager.java.
GridPane gameEngine.MainEngineManager.getReferencePane ()
Implements gameEngine.ManagerInterface.InformationInterface.
Definition at line 133 of file MainEngineManager.java.
References gameEngine.MainEngineManager.myTowerTiles.
List<BaseActor> gameEngine.MainEngineManager.getRequiredActors (BaseActor actor, Class<?extends BaseActor > infoType)
Implements gameEngine.ManagerInterface.InformationInterface.
Definition at line 341 of file MainEngineManager.java.
References gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.getActorsInRange().
String gameEngine.MainEngineManager.getTowerName (ImageView node)
Definition at line 193 of file MainEngineManager.java.
References gameEngine.actors.BaseActor.toString().
Referenced by gamePlayer.mainClasses.managers.GuiManager.selectTower().
SimpleDoubleProperty gameEngine.MainEngineManager.getWinStatus ()
Definition at line 481 of file MainEngineManager.java.
References gameEngine.MainEngineManager.myWinStatus.
Referenced by gamePlayer.mainClasses.managers.GuiManager.initializeNewGameElements().
void gameEngine.MainEngineManager.initializeGame (String directory)
Definition at line 377 of file MainEngineManager.java.
References gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.clear(), gameEngine.MainEngineManager.DIRECTORY_SPLIT, gameEngine.MainEngineManager.loadGameSettings(), gameEngine.MainEngineManager.loadLevelFile(), gameEngine.MainEngineManager.loadLocations(), gameEngine.MainEngineManager.loadNextLevel(), and gameEngine.MainEngineManager.loadTowers().
Referenced by gamePlayer.mainClasses.managers.GuiManager.startGame(), and gamePlayer.mainClasses.managers.GuiManager.startSinglePlayerGame().
boolean gameEngine.MainEngineManager.isInRangeOfField (BaseActor actor) private
Definition at line 333 of file MainEngineManager.java.
References gameEngine.actors.BaseActor.getX(), gameEngine.actors.BaseActor.getY(), and gameEngine.MainEngineManager.myFieldHeight.
Referenced by gameEngine.MainEngineManager.updateActors().
boolean gameEngine.MainEngineManager.isRunning ()
Definition at line 502 of file MainEngineManager.java.
Referenced by gameAuthoring.scenes.levelBuilding.LevelDisplayCell.LevelDisplayCell().
boolean gameEngine.MainEngineManager.listCollidesWith (List< Node > list, double x, double y) private
Definition at line 432 of file MainEngineManager.java.
Referenced by gameEngine.MainEngineManager.validateTower().
void gameEngine.MainEngineManager.loadAuthoringLevel (BaseLevel level)
Definition at line 506 of file MainEngineManager.java.
References gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.clear(), gameEngine.MainEngineManager.loadLevel(), and gameEngine.MainEngineManager.pause().
Referenced by gameAuthoring.scenes.levelBuilding.LevelDisplayCell.LevelDisplayCell().
void gameEngine.MainEngineManager.loadGameSettings (String directory) private
Definition at line 393 of file MainEngineManager.java.
References utilities.GSON.objectWrappers.GeneralSettingsWrapper.getStartingCash(), utilities.GSON.objectWrappers.GeneralSettingsWrapper.getStartingHealth(), and utilities.GSON.GSONFileReader.readGeneralSettingsWrapper().
Referenced by gameEngine.MainEngineManager.initializeGame().
void gameEngine.MainEngineManager.loadLevel (BaseLevel level)
Definition at line 489 of file MainEngineManager.java.
References gameEngine.actors.BaseEnemy.copy(), gameEngine.levels.BaseLevel.getDuration(), and gameEngine.levels.BaseLevel.getEnemyCountPairs().
Referenced by gameEngine.MainEngineManager.loadAuthoringLevel(), gameEngine.MainEngineManager.loadNextLevel(), and gameEngine.MainEngineManager.loadState().
void gameEngine.MainEngineManager.loadLevelFile (String directory) private
Definition at line 466 of file MainEngineManager.java.
References utilities.GSON.GSONFileReader.readLevelsFromGameDirectory().
Referenced by gameEngine.MainEngineManager.initializeGame().
void gameEngine.MainEngineManager.loadLocations (String dir) private
Definition at line 399 of file MainEngineManager.java.
References gameEngine.MainEngineManager.createGameSizedGridPane(), and utilities.GSON.GSONFileReader.readTowerRegionsFromGameDirectory().
Referenced by gameEngine.MainEngineManager.initializeGame().
void gameEngine.MainEngineManager.loadNextLevel () private
Definition at line 470 of file MainEngineManager.java.
References gameEngine.MainEngineManager.loadLevel().
Referenced by gameEngine.MainEngineManager.initializeGame(), and gameEngine.MainEngineManager.onLevelEnd().
void gameEngine.MainEngineManager.loadState (String gameFile)
Definition at line 573 of file MainEngineManager.java.
References gameEngine.MainEngineManager.addTower(), gameEngine.MainEngineManager.clear(), utilities.GSON.objectWrappers.GameStateWrapper.getHealth(), utilities.GSON.objectWrappers.GameStateWrapper.getLevel(), utilities.GSON.objectWrappers.GameStateWrapper.getMoney(), utilities.GSON.objectWrappers.GameStateWrapper.getName(), utilities.GSON.objectWrappers.GameStateWrapper.getTowerWrappers(), gameEngine.MainEngineManager.loadLevel(), and utilities.GSON.GSONFileReader.readGameStateFromJSon().
Referenced by gamePlayer.mainClasses.managers.GuiManager.loadState().
void gameEngine.MainEngineManager.loadTowers (String directory)
Definition at line 440 of file MainEngineManager.java.
References utilities.GSON.GSONFileReader.readTowersFromGameDirectory(), and gameEngine.Data.TowerInfoObject.setNextTower().
Referenced by gameEngine.MainEngineManager.initializeGame().
void gameEngine.MainEngineManager.onGameLose () private
Definition at line 288 of file MainEngineManager.java.
References gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.clear(), and gameEngine.MainEngineManager.pause().
Referenced by gameEngine.MainEngineManager.gameUpdate().
void gameEngine.MainEngineManager.onLevelEnd () protected
Definition at line 297 of file MainEngineManager.java.
References gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.clear(), gameEngine.MainEngineManager.loadNextLevel(), and gameEngine.MainEngineManager.pause().
Referenced by gameEngine.MainEngineManager.gameUpdate().
void gameEngine.MainEngineManager.pause ()
Definition at line 362 of file MainEngineManager.java.
Referenced by gameEngine.MainEngineManager.loadAuthoringLevel(), gameEngine.MainEngineManager.onGameLose(), gameEngine.MainEngineManager.onLevelEnd(), and gamePlayer.mainClasses.managers.GuiManager.pause().
void gameEngine.MainEngineManager.removeTower (ImageView node)
Definition at line 198 of file MainEngineManager.java.
References gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.remove(), and gameEngine.MainEngineManager.setTowerTileStatus().
Referenced by gameEngine.MainEngineManager.sellTower(), and gameEngine.MainEngineManager.upgrade().
void gameEngine.MainEngineManager.resume ()
Definition at line 367 of file MainEngineManager.java.
Referenced by gameAuthoring.scenes.levelBuilding.LevelDisplayCell.LevelDisplayCell(), and gamePlayer.mainClasses.managers.GuiManager.play().
void gameEngine.MainEngineManager.revertToOriginalSpeed ()
Definition at line 183 of file MainEngineManager.java.
References gameEngine.MainEngineManager.changeRunSpeed().
void gameEngine.MainEngineManager.saveState (String directory, String fileName)
Definition at line 534 of file MainEngineManager.java.
References gameEngine.MainEngineManager.JSON_EXTENSION, gameEngine.MainEngineManager.wrapTowers(), and utilities.GSON.GSONFileWriter.writeGameStateToJSon().
Referenced by gamePlayer.mainClasses.managers.GuiManager.saveGame().
void gameEngine.MainEngineManager.sellTower (ImageView n)
Definition at line 607 of file MainEngineManager.java.
References gameEngine.MainEngineManager.removeTower().
Referenced by gamePlayer.mainClasses.managers.GuiManager.sellTower().
void gameEngine.MainEngineManager.setEarthquakeMagnitude (double magnitude)
Definition at line 123 of file MainEngineManager.java.
void gameEngine.MainEngineManager.setMyGold (double value)
Implements gameEngine.ManagerInterface.UpdateInterface.
Definition at line 165 of file MainEngineManager.java.
Referenced by gamePlayer.mainClasses.managers.GuiManager.makeTower(), and gamePlayer.mainClasses.managers.GuiManager.upgradeTower().
void gameEngine.MainEngineManager.setMyHealth (double value)
Implements gameEngine.ManagerInterface.UpdateInterface.
Definition at line 179 of file MainEngineManager.java.
void gameEngine.MainEngineManager.setTowerTileStatus (BaseTower tower, boolean towerTileStatus) private
Definition at line 220 of file MainEngineManager.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.getColumn(), gameEngine.MainEngineManager.getIntersectingTowerTileNode(), gameEngine.actors.BaseActor.getNode(), gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.getRow(), and gameEngine.Data.TowerTileGrid.setTowerTile().
Referenced by gameEngine.MainEngineManager.addTower(), and gameEngine.MainEngineManager.removeTower().
void gameEngine.MainEngineManager.update (Observable o, Object arg)
Definition at line 517 of file MainEngineManager.java.
References gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.add().
void gameEngine.MainEngineManager.updateActors (RangeRestrictedCollection<?extends BaseActor > actorGroup) private
Definition at line 318 of file MainEngineManager.java.
References gameEngine.MainEngineManager.isInRangeOfField().
Referenced by gameEngine.MainEngineManager.gameUpdate().
ImageView gameEngine.MainEngineManager.upgrade (ImageView n, String name)
Definition at line 600 of file MainEngineManager.java.
References gameEngine.MainEngineManager.addTower(), and gameEngine.MainEngineManager.removeTower().
Referenced by gamePlayer.mainClasses.managers.GuiManager.upgradeTower().
boolean gameEngine.MainEngineManager.validateTower (double x, double y)
Definition at line 427 of file MainEngineManager.java.
References gameEngine.MainEngineManager.listCollidesWith().
Referenced by gamePlayer.mainClasses.managers.GuiManager.validPlacement().
List<DataWrapper> gameEngine.MainEngineManager.wrapTowers () private
Definition at line 552 of file MainEngineManager.java.
Referenced by gameEngine.MainEngineManager.saveState().
Member Data Documentation
final String gameEngine.MainEngineManager.DIRECTORY_SPLIT = "/" static private
Definition at line 60 of file MainEngineManager.java.
Referenced by gameEngine.MainEngineManager.initializeGame().
double gameEngine.MainEngineManager.duration private
Definition at line 71 of file MainEngineManager.java.
final int gameEngine.MainEngineManager.FPS = 30 static private
Definition at line 61 of file MainEngineManager.java.
final double gameEngine.MainEngineManager.FRAME_DURATION = 1000.0 / 30 static private
Definition at line 62 of file MainEngineManager.java.
final String gameEngine.MainEngineManager.INCORRECT_SAVE_STATE_MESSAGE = "Save state does not correspond to this game" static private
Definition at line 58 of file MainEngineManager.java.
final String gameEngine.MainEngineManager.JSON_EXTENSION = ".json" static private
Definition at line 59 of file MainEngineManager.java.
Referenced by gameEngine.MainEngineManager.saveState().
String gameEngine.MainEngineManager.myCurrentGameName private
Definition at line 93 of file MainEngineManager.java.
int gameEngine.MainEngineManager.myCurrentLevelIndex private
Definition at line 73 of file MainEngineManager.java.
SimpleDoubleProperty gameEngine.MainEngineManager.myCurrentLevelProperty private
Definition at line 94 of file MainEngineManager.java.
Referenced by gameEngine.MainEngineManager.getCurrentLevelProperty().
SimpleDoubleProperty gameEngine.MainEngineManager.myEarthquakeMagnitude private
Definition at line 80 of file MainEngineManager.java.
Queue<BaseEnemy> gameEngine.MainEngineManager.myEnemiesToAdd private
Definition at line 78 of file MainEngineManager.java.
RangeRestrictedCollection<BaseEnemy> gameEngine.MainEngineManager.myEnemyGroup private
Definition at line 69 of file MainEngineManager.java.
double gameEngine.MainEngineManager.myFieldHeight private
Definition at line 90 of file MainEngineManager.java.
Referenced by gameEngine.MainEngineManager.isInRangeOfField().
double gameEngine.MainEngineManager.myFieldWidth private
Definition at line 89 of file MainEngineManager.java.
GSONFileReader gameEngine.MainEngineManager.myFileReader protected
Definition at line 83 of file MainEngineManager.java.
Referenced by gameEngine.CoOpManager.getTowersFromServer().
GSONFileWriter gameEngine.MainEngineManager.myFileWriter protected
Definition at line 84 of file MainEngineManager.java.
Referenced by gameEngine.CoOpManager.convertTowersToString().
SimpleDoubleProperty gameEngine.MainEngineManager.myGold private
Definition at line 75 of file MainEngineManager.java.
Referenced by gameEngine.MainEngineManager.getGoldProperty().
SimpleDoubleProperty gameEngine.MainEngineManager.myHealth private
Definition at line 79 of file MainEngineManager.java.
Referenced by gameEngine.MainEngineManager.getHealthProperty().
double gameEngine.MainEngineManager.myIntervalBetweenEnemies private
Definition at line 77 of file MainEngineManager.java.
Referenced by gameEngine.MainEngineManager.addEnemies().
double gameEngine.MainEngineManager.myLastUpdateTime private
Definition at line 64 of file MainEngineManager.java.
List<BaseLevel> gameEngine.MainEngineManager.myLevels private
Definition at line 72 of file MainEngineManager.java.
Map<Node, BaseTower> gameEngine.MainEngineManager.myNodeToTower private
Definition at line 81 of file MainEngineManager.java.
boolean gameEngine.MainEngineManager.myPausedFlag private
Definition at line 92 of file MainEngineManager.java.
RangeRestrictedCollection<BaseProjectile> gameEngine.MainEngineManager.myProjectileGroup private
Definition at line 70 of file MainEngineManager.java.
Map<String, BaseTower> gameEngine.MainEngineManager.myPrototypeTowerMap private
Definition at line 76 of file MainEngineManager.java.
AtomicBoolean gameEngine.MainEngineManager.myReadyToPlay private
Definition at line 67 of file MainEngineManager.java.
Timeline gameEngine.MainEngineManager.myTimeline private
Definition at line 65 of file MainEngineManager.java.
RangeRestrictedCollection<BaseTower> gameEngine.MainEngineManager.myTowerGroup protected
Definition at line 68 of file MainEngineManager.java.
Referenced by gameEngine.CoOpManager.convertTowersToString(), and gameEngine.CoOpManager.getTowersFromServer().
Collection<TowerInfoObject> gameEngine.MainEngineManager.myTowerInformation private
Definition at line 82 of file MainEngineManager.java.
Referenced by gameEngine.MainEngineManager.getAllTowerTypeInformation().
TowerTileGrid gameEngine.MainEngineManager.myTowerLocationByGrid private
Definition at line 86 of file MainEngineManager.java.
Referenced by gameEngine.MainEngineManager.getExistingTowerTiles().
GridPane gameEngine.MainEngineManager.myTowerTiles private
Definition at line 87 of file MainEngineManager.java.
Referenced by gameEngine.MainEngineManager.getReferencePane().
double gameEngine.MainEngineManager.myUpdateRate private
Definition at line 66 of file MainEngineManager.java.
Referenced by gameEngine.MainEngineManager.createTimeline().
GridPane gameEngine.MainEngineManager.myValidRegions private
Definition at line 74 of file MainEngineManager.java.
SimpleDoubleProperty gameEngine.MainEngineManager.myWinStatus private
Definition at line 95 of file MainEngineManager.java.
Referenced by gameEngine.MainEngineManager.getWinStatus().
final String gameEngine.MainEngineManager.UNKNOWN_SAVE_STATE_FILE_MESSAGE = "Unknown problem loading save file" static private
Definition at line 57 of file MainEngineManager.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/MainEngineManager.java