voogasalad_LosTorres: utilities.GSON.objectWrappers.GameStateWrapper Class Reference
utilities.GSON.objectWrappers.GameStateWrapper Class Reference
Public Member Functions
GameStateWrapper (String name, int level, double health, double money, List< DataWrapper > towers)
String getName ()
int getLevel ()
double getHealth ()
double getMoney ()
List< DataWrapper > getTowerWrappers ()
Private Attributes
int myLevel
double myHealth
double myMoney
String myName
List< DataWrapper > myTowers
Detailed Description
Definition at line 5 of file GameStateWrapper.java.
Constructor & Destructor Documentation
utilities.GSON.objectWrappers.GameStateWrapper.GameStateWrapper (String name, int level, double health, double money, List< DataWrapper > towers)
Definition at line 13 of file GameStateWrapper.java.
Member Function Documentation
double utilities.GSON.objectWrappers.GameStateWrapper.getHealth ()
Definition at line 29 of file GameStateWrapper.java.
References utilities.GSON.objectWrappers.GameStateWrapper.myHealth.
Referenced by gameEngine.MainEngineManager.loadState().
int utilities.GSON.objectWrappers.GameStateWrapper.getLevel ()
Definition at line 25 of file GameStateWrapper.java.
References utilities.GSON.objectWrappers.GameStateWrapper.myLevel.
Referenced by gameEngine.MainEngineManager.loadState().
double utilities.GSON.objectWrappers.GameStateWrapper.getMoney ()
Definition at line 33 of file GameStateWrapper.java.
References utilities.GSON.objectWrappers.GameStateWrapper.myMoney.
Referenced by gameEngine.MainEngineManager.loadState().
String utilities.GSON.objectWrappers.GameStateWrapper.getName ()
Definition at line 21 of file GameStateWrapper.java.
References utilities.GSON.objectWrappers.GameStateWrapper.myName.
Referenced by gameEngine.MainEngineManager.loadState().
List<DataWrapper> utilities.GSON.objectWrappers.GameStateWrapper.getTowerWrappers ()
Definition at line 37 of file GameStateWrapper.java.
References utilities.GSON.objectWrappers.GameStateWrapper.myTowers.
Referenced by gameEngine.MainEngineManager.loadState().
Member Data Documentation
double utilities.GSON.objectWrappers.GameStateWrapper.myHealth private
Definition at line 8 of file GameStateWrapper.java.
Referenced by utilities.GSON.objectWrappers.GameStateWrapper.getHealth().
int utilities.GSON.objectWrappers.GameStateWrapper.myLevel private
Definition at line 7 of file GameStateWrapper.java.
Referenced by utilities.GSON.objectWrappers.GameStateWrapper.getLevel().
double utilities.GSON.objectWrappers.GameStateWrapper.myMoney private
Definition at line 9 of file GameStateWrapper.java.
Referenced by utilities.GSON.objectWrappers.GameStateWrapper.getMoney().
String utilities.GSON.objectWrappers.GameStateWrapper.myName private
Definition at line 10 of file GameStateWrapper.java.
Referenced by utilities.GSON.objectWrappers.GameStateWrapper.getName().
List<DataWrapper> utilities.GSON.objectWrappers.GameStateWrapper.myTowers private
Definition at line 11 of file GameStateWrapper.java.
Referenced by utilities.GSON.objectWrappers.GameStateWrapper.getTowerWrappers().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/GSON/objectWrappers/GameStateWrapper.java