voogasalad_LosTorres: gamePlayer.guiItems.welcome.ClickAnywherePane Class Reference
gamePlayer.guiItems.welcome.ClickAnywherePane Class Reference
Public Member Functions
void initialize (Dimension2D containerSize)
Node getNode ()
Private Member Functions
void setupPane ()
void setupText ()
void setupStatusIndicator ()
void mouseListener ()
void dummyLoop (Timeline timeline)
Private Attributes
XMLParser myParser
Dimension2D mySize
VBox myPane
ProgressIndicator indicator
Label myText
Animation textAnimation
Additional Inherited Members
Static Public Attributes inherited from gamePlayer.guiItems.GuiItem
static String myPropertiesPath = "guiItems/"
Detailed Description
Author
brianbolze
Definition at line 26 of file ClickAnywherePane.java.
Member Function Documentation
void gamePlayer.guiItems.welcome.ClickAnywherePane.dummyLoop (Timeline timeline) private
Definition at line 88 of file ClickAnywherePane.java.
Referenced by gamePlayer.guiItems.welcome.ClickAnywherePane.mouseListener().
Node gamePlayer.guiItems.welcome.ClickAnywherePane.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 47 of file ClickAnywherePane.java.
References gamePlayer.guiItems.welcome.ClickAnywherePane.myPane.
void gamePlayer.guiItems.welcome.ClickAnywherePane.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 36 of file ClickAnywherePane.java.
References gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_ELEMENT_PROPERTIES_PATH, gamePlayer.guiItems.welcome.ClickAnywherePane.mouseListener(), gamePlayer.guiItems.GuiItem.myPropertiesPath, gamePlayer.guiItems.welcome.ClickAnywherePane.setupPane(), gamePlayer.guiItems.welcome.ClickAnywherePane.setupStatusIndicator(), and gamePlayer.guiItems.welcome.ClickAnywherePane.setupText().
void gamePlayer.guiItems.welcome.ClickAnywherePane.mouseListener () private
Definition at line 78 of file ClickAnywherePane.java.
References gamePlayer.guiItems.welcome.ClickAnywherePane.dummyLoop().
Referenced by gamePlayer.guiItems.welcome.ClickAnywherePane.initialize().
void gamePlayer.guiItems.welcome.ClickAnywherePane.setupPane () private
Definition at line 51 of file ClickAnywherePane.java.
References utilities.XMLParsing.XMLParser.getDoubleValuesFromTag().
Referenced by gamePlayer.guiItems.welcome.ClickAnywherePane.initialize().
void gamePlayer.guiItems.welcome.ClickAnywherePane.setupStatusIndicator () private
Definition at line 72 of file ClickAnywherePane.java.
Referenced by gamePlayer.guiItems.welcome.ClickAnywherePane.initialize().
void gamePlayer.guiItems.welcome.ClickAnywherePane.setupText () private
Definition at line 59 of file ClickAnywherePane.java.
References utilities.XMLParsing.XMLParser.getValuesFromTag(), and gamePlayer.guiItems.welcome.ClickAnywherePane.myText.
Referenced by gamePlayer.guiItems.welcome.ClickAnywherePane.initialize().
Member Data Documentation
ProgressIndicator gamePlayer.guiItems.welcome.ClickAnywherePane.indicator private
Definition at line 31 of file ClickAnywherePane.java.
VBox gamePlayer.guiItems.welcome.ClickAnywherePane.myPane private
Definition at line 30 of file ClickAnywherePane.java.
Referenced by gamePlayer.guiItems.welcome.ClickAnywherePane.getNode().
XMLParser gamePlayer.guiItems.welcome.ClickAnywherePane.myParser private
Definition at line 28 of file ClickAnywherePane.java.
Dimension2D gamePlayer.guiItems.welcome.ClickAnywherePane.mySize private
Definition at line 29 of file ClickAnywherePane.java.
Label gamePlayer.guiItems.welcome.ClickAnywherePane.myText private
Definition at line 32 of file ClickAnywherePane.java.
Referenced by gamePlayer.guiItems.welcome.ClickAnywherePane.setupText().
Animation gamePlayer.guiItems.welcome.ClickAnywherePane.textAnimation private
Definition at line 33 of file ClickAnywherePane.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItems/welcome/ClickAnywherePane.java