voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent Interface Reference
gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent Interface Reference
Public Member Functions
Point2D getStartingPoint ()
Point2D getEndingPoint ()
void setStartingPoint (Point2D endingPoint)
void setEndingPoint (Point2D startingPoint)
void translate (double deltaX, double deltaY)
void select ()
void removeStroke ()
PathComponent deepCopy ()
List< VisibilityPoint > getInnerPointsRepresentingComponent ()
List< Node > getExtraNodes ()
default Node getNode ()
boolean isPathComponentVisible ()
void togglePathComponentVisibility ()
void showVisibility ()
Detailed Description
An interface that defines the behaviors of drawn component. Implemented by PathLine and PathCurve.
Author
Austin Kyker
Definition at line 17 of file PathComponent.java.
Member Function Documentation
PathComponent gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.deepCopy ()
Implemented in gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve, and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.
Point2D gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.getEndingPoint ()
Implemented in gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve, and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.closeEnoughToConnect(), gameAuthoring.scenes.pathBuilding.pathComponents.Path.connectRoutes(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.tryToAddConnectComponentToEndingLocation().
List<Node> gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.getExtraNodes ()
Extra nodes that should be deleted corresponding to a path component These nodes include control points for curves.
Implemented in gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve, and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.
List<VisibilityPoint> gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.getInnerPointsRepresentingComponent ()
Implemented in gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve, and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.
default Node gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.getNode ()
Definition at line 42 of file PathComponent.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.addSelectionListeners().
Point2D gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.getStartingPoint ()
Implemented in gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve, and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.closeEnoughToConnect(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.componentAddedToStartingLocation().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.isPathComponentVisible ()
Implemented in gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve, and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.
void gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.removeStroke ()
Implemented in gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve, and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.
void gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.select ()
Implemented in gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve, and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.
void gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.setEndingPoint (Point2D startingPoint)
Implemented in gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve, and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.tryToAddConnectComponentToEndingLocation().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.setStartingPoint (Point2D endingPoint)
Implemented in gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve, and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.Path.componentAddedToStartingLocation(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.connectRoutes().
void gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.showVisibility ()
Implemented in gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve, and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.
void gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.togglePathComponentVisibility ()
Implemented in gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve, and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.
void gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.translate (double deltaX, double deltaY)
Implemented in gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve, and gameAuthoring.scenes.pathBuilding.pathComponents.PathLine.
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/pathComponents/PathComponent.java