voogasalad_LosTorres: gamePlayer.guiContainers.secondaryContainers.ControlDock Class Reference
gamePlayer.guiContainers.secondaryContainers.ControlDock Class Reference
Public Member Functions
void initialize (Dimension2D containerSize)
Node getNode ()
Private Attributes
XMLParser myParser
Additional Inherited Members
Public Attributes inherited from gamePlayer.guiContainers.GuiContainer
String myPropertiesPath = "guiContainers/"
Detailed Description
Definition at line 16 of file ControlDock.java.
Member Function Documentation
Node gamePlayer.guiContainers.secondaryContainers.ControlDock.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 42 of file ControlDock.java.
void gamePlayer.guiContainers.secondaryContainers.ControlDock.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 20 of file ControlDock.java.
References utilities.reflection.Reflection.createInstance(), utilities.XMLParsing.XMLParser.getDimension(), gamePlayer.mainClasses.guiBuilder.GuiElement.getNode(), utilities.XMLParsing.XMLParser.getValuesFromTag(), gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_ELEMENT_PROPERTIES_PATH, gamePlayer.mainClasses.guiBuilder.GuiElement.initialize(), and gamePlayer.guiContainers.GuiContainer.myPropertiesPath.
Member Data Documentation
XMLParser gamePlayer.guiContainers.secondaryContainers.ControlDock.myParser private
Definition at line 17 of file ControlDock.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiContainers/secondaryContainers/ControlDock.java