voogasalad_LosTorres: gamePlayer.mainClasses.testGameManager.TestGameManager Class Reference
gamePlayer.mainClasses.testGameManager.TestGameManager Class Reference
Public Member Functions
TestGameManager (Stage stage)
void run ()
Private Member Functions
void testGuiStore ()
void testLoadingGuiHUD ()
Private Attributes
GuiManager myGuiManager
List< GameStat > gameStats
Detailed Description
Class simulates an engine GameManager for testing purposes
Author
allankiplagat
Definition at line 21 of file TestGameManager.java.
Constructor & Destructor Documentation
gamePlayer.mainClasses.testGameManager.TestGameManager.TestGameManager (Stage stage)
Definition at line 25 of file TestGameManager.java.
Member Function Documentation
void gamePlayer.mainClasses.testGameManager.TestGameManager.run ()
Definition at line 29 of file TestGameManager.java.
References gamePlayer.mainClasses.testGameManager.TestGameManager.testGuiStore(), and gamePlayer.mainClasses.testGameManager.TestGameManager.testLoadingGuiHUD().
void gamePlayer.mainClasses.testGameManager.TestGameManager.testGuiStore () private
Definition at line 34 of file TestGameManager.java.
References gamePlayer.mainClasses.managers.GuiManager.refreshStore().
Referenced by gamePlayer.mainClasses.testGameManager.TestGameManager.run().
void gamePlayer.mainClasses.testGameManager.TestGameManager.testLoadingGuiHUD () private
Definition at line 67 of file TestGameManager.java.
References gamePlayer.guiItems.headsUpDisplay.GameStat.setGameStat(), gamePlayer.mainClasses.managers.GuiManager.setGameStats(), and gamePlayer.guiItems.headsUpDisplay.GameStat.setStatValue().
Referenced by gamePlayer.mainClasses.testGameManager.TestGameManager.run().
Member Data Documentation
List<GameStat> gamePlayer.mainClasses.testGameManager.TestGameManager.gameStats private
Definition at line 23 of file TestGameManager.java.
GuiManager gamePlayer.mainClasses.testGameManager.TestGameManager.myGuiManager private
Definition at line 22 of file TestGameManager.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/mainClasses/testGameManager/TestGameManager.java