voogasalad_LosTorres: utilities.GSON.objectWrappers.DataWrapper Class Reference
utilities.GSON.objectWrappers.DataWrapper Class Reference
Public Member Functions
DataWrapper (BaseActor actor)
String getName ()
double getX ()
double getY ()
boolean equals (Object obj)
int hashCode ()
Private Attributes
String myName
double myX
double myY
Detailed Description
Definition at line 5 of file DataWrapper.java.
Constructor & Destructor Documentation
utilities.GSON.objectWrappers.DataWrapper.DataWrapper (BaseActor actor)
Definition at line 11 of file DataWrapper.java.
References gameEngine.actors.BaseActor.getX(), gameEngine.actors.BaseActor.getY(), and gameEngine.actors.BaseActor.toString().
Referenced by utilities.GSON.objectWrappers.DataWrapper.equals().
Member Function Documentation
boolean utilities.GSON.objectWrappers.DataWrapper.equals (Object obj)
Definition at line 28 of file DataWrapper.java.
References utilities.GSON.objectWrappers.DataWrapper.DataWrapper(), utilities.GSON.objectWrappers.DataWrapper.getName(), utilities.GSON.objectWrappers.DataWrapper.getX(), utilities.GSON.objectWrappers.DataWrapper.getY(), utilities.GSON.objectWrappers.DataWrapper.myX, and utilities.GSON.objectWrappers.DataWrapper.myY.
String utilities.GSON.objectWrappers.DataWrapper.getName ()
Definition at line 16 of file DataWrapper.java.
References utilities.GSON.objectWrappers.DataWrapper.myName.
Referenced by gameEngine.CoOpManager.addTower(), and utilities.GSON.objectWrappers.DataWrapper.equals().
double utilities.GSON.objectWrappers.DataWrapper.getX ()
Definition at line 19 of file DataWrapper.java.
References utilities.GSON.objectWrappers.DataWrapper.myX.
Referenced by gameEngine.CoOpManager.addTower(), and utilities.GSON.objectWrappers.DataWrapper.equals().
double utilities.GSON.objectWrappers.DataWrapper.getY ()
Definition at line 23 of file DataWrapper.java.
References utilities.GSON.objectWrappers.DataWrapper.myY.
Referenced by gameEngine.CoOpManager.addTower(), and utilities.GSON.objectWrappers.DataWrapper.equals().
int utilities.GSON.objectWrappers.DataWrapper.hashCode ()
Definition at line 37 of file DataWrapper.java.
References utilities.GSON.objectWrappers.DataWrapper.myY.
Member Data Documentation
String utilities.GSON.objectWrappers.DataWrapper.myName private
Definition at line 7 of file DataWrapper.java.
Referenced by utilities.GSON.objectWrappers.DataWrapper.getName().
double utilities.GSON.objectWrappers.DataWrapper.myX private
Definition at line 8 of file DataWrapper.java.
Referenced by utilities.GSON.objectWrappers.DataWrapper.equals(), and utilities.GSON.objectWrappers.DataWrapper.getX().
double utilities.GSON.objectWrappers.DataWrapper.myY private
Definition at line 9 of file DataWrapper.java.
Referenced by utilities.GSON.objectWrappers.DataWrapper.equals(), utilities.GSON.objectWrappers.DataWrapper.getY(), and utilities.GSON.objectWrappers.DataWrapper.hashCode().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/GSON/objectWrappers/DataWrapper.java