voogasalad_LosTorres: utilities.pathfinding.example.UnlinkedNodeExample Class Reference
utilities.pathfinding.example.UnlinkedNodeExample Class Reference
Static Public Member Functions
static void main (String[] args)
Static Private Member Functions
static UnlinkedNode[][] createMap (int xMax, int yMax)
Detailed Description
Author
Duke
    An example using Node. Refer to NodeAStarFinder for actual AStarFinder implementation.
    Exact same map structure and finder implementation as the AStarTest.
    Represents the same 2D array based data structure used in LinkedNodeExample.
    However, instead of using a linked map, it uses nodes arranged in a 2D array The
    neighbors are nodes on the left/right and on top/bottom. No diagonals.
Definition at line 17 of file UnlinkedNodeExample.java.
Member Function Documentation
static UnlinkedNode [][] utilities.pathfinding.example.UnlinkedNodeExample.createMap (int xMax, int yMax) static private
Definition at line 39 of file UnlinkedNodeExample.java.
Referenced by utilities.pathfinding.example.UnlinkedNodeExample.main().
static void utilities.pathfinding.example.UnlinkedNodeExample.main (String[] args) static
Definition at line 19 of file UnlinkedNodeExample.java.
References utilities.pathfinding.example.UnlinkedNodeExample.createMap(), and utilities.pathfinding.AStarPathFinder< T >.findPath().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/pathfinding/example/UnlinkedNodeExample.java