voogasalad_LosTorres: utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane Class Reference
utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane Class Reference abstract
Public Member Functions
DragAndDropFilePane (double width, double height, String[] validExtensions)
Pane getPane ()
void reset ()
Protected Member Functions
abstract void actOnFile (File file)
Protected Attributes
VBox myContainer
VBox myDragAndDropPane
File myFile
Private Member Functions
void showInstructionLabel (double width, double height)
void handleFileDrop (DragEvent event)
void handleDragExit (DragEvent event)
void handleDragOver (DragEvent event)
Private Attributes
String[] myValidExtensions
Static Private Attributes
static final int LAYOUTX_ADJ = 50
static final int LAYOUTY_ADJ = 20
Detailed Description
This utility allows for the creation of drag and drop file panes. Simply specify the extensions of files you accept, and where you want the file to be dropped. The class extends Observable so you can set up an observer class to listen for when a file is dropped.
Author
Austin Kyker
Definition at line 21 of file DragAndDropFilePane.java.
Constructor & Destructor Documentation
utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.DragAndDropFilePane (double width, double height, String[] validExtensions)
Parameters
validExtensions The acceptable extensions drag and dropped file. Ex: [.jpg, .png]
fileDestination where you want the file dragged and dropped to be saved.
Definition at line 35 of file DragAndDropFilePane.java.
References utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.showInstructionLabel().
Member Function Documentation
abstract void utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.actOnFile (File file) abstract protected
Referenced by utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.handleFileDrop().
Pane utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.getPane ()
Definition at line 94 of file DragAndDropFilePane.java.
References utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.myContainer.
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.clearFields(), gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.configureAndDisplayRightPane(), gameAuthoring.scenes.pathBuilding.buildingPanes.PathBackgroundSelectionPane.PathBackgroundSelectionPane(), gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.ProjectilePane(), gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.setupDragAndDropForActorImage(), and gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.update().
void utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.handleDragExit (DragEvent event) private
Definition at line 78 of file DragAndDropFilePane.java.
void utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.handleDragOver (DragEvent event) private
Definition at line 83 of file DragAndDropFilePane.java.
void utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.handleFileDrop (DragEvent event) private
Definition at line 57 of file DragAndDropFilePane.java.
References utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.actOnFile().
void utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.reset ()
Definition at line 98 of file DragAndDropFilePane.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.clearFields().
void utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.showInstructionLabel (double width, double height) private
Definition at line 48 of file DragAndDropFilePane.java.
Referenced by utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.DragAndDropFilePane().
Member Data Documentation
final int utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.LAYOUTX_ADJ = 50 static private
Definition at line 23 of file DragAndDropFilePane.java.
final int utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.LAYOUTY_ADJ = 20 static private
Definition at line 24 of file DragAndDropFilePane.java.
VBox utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.myContainer protected
Definition at line 27 of file DragAndDropFilePane.java.
Referenced by utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane.displayImage(), utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.getPane(), and utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane.setHeight().
VBox utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.myDragAndDropPane protected
Definition at line 28 of file DragAndDropFilePane.java.
Referenced by utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane.displayImage().
File utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.myFile protected
Definition at line 29 of file DragAndDropFilePane.java.
Referenced by utilities.JavaFXutilities.DragAndDropFilePanes.audioPanes.DragAndDropAudioPane.actOnFile(), and utilities.JavaFXutilities.DragAndDropFilePanes.videoPanes.DragAndDropVideoPane.actOnFile().
String [] utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.myValidExtensions private
Definition at line 26 of file DragAndDropFilePane.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/JavaFXutilities/DragAndDropFilePanes/imagePanes/DragAndDropFilePane.java