voogasalad_LosTorres: gameEngine.actors.behaviors.BaseMovementBehavior Class Reference
gameEngine.actors.behaviors.BaseMovementBehavior Class Reference abstract
Public Member Functions
BaseMovementBehavior (double speed)
BaseMovementBehavior (double speed, BackendRoute route)
double getSpeed ()
void setSpeed (double speed)
double getRemainingDistance ()
void setRoute (BackendRoute route)
String toString ()
Public Member Functions inherited from gameEngine.actors.behaviors.IBehavior
void execute (BaseActor actor)
IBehavior copy ()
Protected Member Functions
void move (BaseActor a, Point2D point)
void moveTowards (BaseActor a, Point2D current, Point2D target)
void findNextTarget (BaseActor actor, List< Point2D > route)
Protected Attributes
List< Double > myList
String myString
List< VisibilityPoint > myRoute
double mySpeed
double myRemainingDistance
int myIndex
Package Functions
BaseMovementBehavior (List< Double > list)
Private Member Functions
double calculateTotalDistance (List< VisibilityPoint > route)
Detailed Description
Behavior that defines the movement of an actor
Author
Chase Malik, Timesh Patel
Definition at line 17 of file BaseMovementBehavior.java.
Constructor & Destructor Documentation
gameEngine.actors.behaviors.BaseMovementBehavior.BaseMovementBehavior (List< Double > list) package
Definition at line 26 of file BaseMovementBehavior.java.
gameEngine.actors.behaviors.BaseMovementBehavior.BaseMovementBehavior (double speed)
Definition at line 32 of file BaseMovementBehavior.java.
gameEngine.actors.behaviors.BaseMovementBehavior.BaseMovementBehavior (double speed, BackendRoute route)
Definition at line 36 of file BaseMovementBehavior.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.getPoints().
Member Function Documentation
double gameEngine.actors.behaviors.BaseMovementBehavior.calculateTotalDistance (List< VisibilityPoint > route) private
Definition at line 43 of file BaseMovementBehavior.java.
Referenced by gameEngine.actors.behaviors.BaseMovementBehavior.setRoute().
void gameEngine.actors.behaviors.BaseMovementBehavior.findNextTarget (BaseActor actor, List< Point2D > route) protected
Definition at line 83 of file BaseMovementBehavior.java.
References gameEngine.actors.BaseActor.died(), gameEngine.actors.BaseActor.getX(), gameEngine.actors.BaseActor.getY(), gameEngine.actors.behaviors.BaseMovementBehavior.moveTowards(), and gameEngine.actors.behaviors.BaseMovementBehavior.mySpeed.
Referenced by gameEngine.actors.behaviors.AIMovement.execute(), and gameEngine.actors.behaviors.LinearMovement.execute().
double gameEngine.actors.behaviors.BaseMovementBehavior.getRemainingDistance ()
Definition at line 57 of file BaseMovementBehavior.java.
References gameEngine.actors.behaviors.BaseMovementBehavior.myRemainingDistance.
double gameEngine.actors.behaviors.BaseMovementBehavior.getSpeed ()
Definition at line 51 of file BaseMovementBehavior.java.
References gameEngine.actors.behaviors.BaseMovementBehavior.mySpeed.
Referenced by gameEngine.actors.behaviors.SlowEffect.start().
void gameEngine.actors.behaviors.BaseMovementBehavior.move (BaseActor a, Point2D point) protected
Definition at line 70 of file BaseMovementBehavior.java.
References gameEngine.actors.BaseActor.getNode(), utilities.JavaFXutilities.imageView.CenteredImageView.setXCenter(), and utilities.JavaFXutilities.imageView.CenteredImageView.setYCenter().
Referenced by gameEngine.actors.behaviors.EnemyHomingMovement.execute(), gameEngine.actors.behaviors.AIMovement.execute(), and gameEngine.actors.behaviors.BaseMovementBehavior.moveTowards().
void gameEngine.actors.behaviors.BaseMovementBehavior.moveTowards (BaseActor a, Point2D current, Point2D target) protected
Definition at line 76 of file BaseMovementBehavior.java.
References gameEngine.actors.behaviors.BaseMovementBehavior.move(), and gameEngine.actors.behaviors.BaseMovementBehavior.mySpeed.
Referenced by gameEngine.actors.behaviors.EnemyHomingMovement.execute(), and gameEngine.actors.behaviors.BaseMovementBehavior.findNextTarget().
void gameEngine.actors.behaviors.BaseMovementBehavior.setRoute (BackendRoute route)
Definition at line 60 of file BaseMovementBehavior.java.
References gameEngine.actors.behaviors.BaseMovementBehavior.calculateTotalDistance(), and gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.getPoints().
Referenced by gameEngine.actors.behaviors.AoEAttack.performAttack(), and gameEngine.actors.behaviors.RangeAttack.shootActorFromActor().
void gameEngine.actors.behaviors.BaseMovementBehavior.setSpeed (double speed)
Definition at line 54 of file BaseMovementBehavior.java.
Referenced by gameEngine.actors.behaviors.SlowEffect.end(), and gameEngine.actors.behaviors.SlowEffect.start().
String gameEngine.actors.behaviors.BaseMovementBehavior.toString ()
Implements gameEngine.actors.behaviors.IBehavior.
Definition at line 64 of file BaseMovementBehavior.java.
References gameEngine.actors.behaviors.BaseMovementBehavior.myString.
Member Data Documentation
int gameEngine.actors.behaviors.BaseMovementBehavior.myIndex protected
Definition at line 24 of file BaseMovementBehavior.java.
Referenced by gameEngine.actors.behaviors.AIMovement.AIMovement(), gameEngine.actors.behaviors.AIMovement.execute(), and gameEngine.actors.behaviors.LinearMovement.execute().
List<Double> gameEngine.actors.behaviors.BaseMovementBehavior.myList protected
Definition at line 19 of file BaseMovementBehavior.java.
Referenced by gameEngine.actors.behaviors.LinearMovement.copy(), gameEngine.actors.behaviors.AIMovement.copy(), and gameEngine.actors.behaviors.EnemyHomingMovement.copy().
double gameEngine.actors.behaviors.BaseMovementBehavior.myRemainingDistance protected
Definition at line 23 of file BaseMovementBehavior.java.
Referenced by gameEngine.actors.behaviors.BaseMovementBehavior.getRemainingDistance().
List<VisibilityPoint> gameEngine.actors.behaviors.BaseMovementBehavior.myRoute protected
Definition at line 21 of file BaseMovementBehavior.java.
Referenced by gameEngine.actors.behaviors.EnemyHomingMovement.execute(), and gameEngine.actors.behaviors.LinearMovement.execute().
double gameEngine.actors.behaviors.BaseMovementBehavior.mySpeed protected
Definition at line 22 of file BaseMovementBehavior.java.
Referenced by gameEngine.actors.behaviors.BaseMovementBehavior.findNextTarget(), gameEngine.actors.behaviors.BaseMovementBehavior.getSpeed(), and gameEngine.actors.behaviors.BaseMovementBehavior.moveTowards().
String gameEngine.actors.behaviors.BaseMovementBehavior.myString protected
Definition at line 20 of file BaseMovementBehavior.java.
Referenced by gameEngine.actors.behaviors.BaseMovementBehavior.toString().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/behaviors/BaseMovementBehavior.java