voogasalad_LosTorres: gameEngine.actors.behaviors.AoEEffect Class Reference
gameEngine.actors.behaviors.AoEEffect Class Reference
Public Member Functions
AoEEffect (List< Double > list)
AoEEffect (double d, double r)
IBehavior copy ()
void during (BaseActor actor)
void start (BaseActor actor)
void end (BaseActor actor)
Public Member Functions inherited from gameEngine.actors.behaviors.BaseEffect
BaseEffect (double duration, double multiplier)
BaseEffect ()
BaseEffect (List< Double > list)
void execute (BaseActor actor)
abstract void during (BaseActor actor)
abstract void start (BaseActor actor)
abstract void end (BaseActor actor)
String toString ()
Private Attributes
double myDamage
double myRange
Additional Inherited Members
Protected Attributes inherited from gameEngine.actors.behaviors.BaseEffect
List< Double > myList
String myString
Package Attributes inherited from gameEngine.actors.behaviors.BaseEffect
double myDuration
double myInitialDuration
Detailed Description
Definition at line 6 of file AoEEffect.java.
Constructor & Destructor Documentation
gameEngine.actors.behaviors.AoEEffect.AoEEffect (List< Double > list)
Definition at line 9 of file AoEEffect.java.
References gameEngine.actors.behaviors.BaseEffect.myDuration, gameEngine.actors.behaviors.BaseEffect.myInitialDuration, and gameEngine.actors.behaviors.BaseEffect.myString.
Referenced by gameEngine.actors.behaviors.AoEEffect.copy().
gameEngine.actors.behaviors.AoEEffect.AoEEffect (double d, double r)
Definition at line 19 of file AoEEffect.java.
Member Function Documentation
IBehavior gameEngine.actors.behaviors.AoEEffect.copy ()
Returns a copy of the behavior, which allows for copying entire actors
Returns
copy of the behavior
Implements gameEngine.actors.behaviors.IBehavior.
Definition at line 24 of file AoEEffect.java.
References gameEngine.actors.behaviors.AoEEffect.AoEEffect().
void gameEngine.actors.behaviors.AoEEffect.during (BaseActor actor)
Definition at line 30 of file AoEEffect.java.
void gameEngine.actors.behaviors.AoEEffect.end (BaseActor actor)
Definition at line 50 of file AoEEffect.java.
References gameEngine.actors.BaseActor.removeDebuff().
void gameEngine.actors.behaviors.AoEEffect.start (BaseActor actor)
Definition at line 36 of file AoEEffect.java.
References gameEngine.actors.BaseActor.getEnemiesInRange(), gameEngine.actors.behaviors.BaseDefendBehavior.getHealth(), gameEngine.actors.behaviors.AoEEffect.myDamage, gameEngine.actors.behaviors.BaseDefendBehavior.onDeath(), and gameEngine.actors.behaviors.BaseDefendBehavior.setHealth().
Member Data Documentation
double gameEngine.actors.behaviors.AoEEffect.myDamage private
Definition at line 7 of file AoEEffect.java.
Referenced by gameEngine.actors.behaviors.AoEEffect.start().
double gameEngine.actors.behaviors.AoEEffect.myRange private
Definition at line 8 of file AoEEffect.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/behaviors/AoEEffect.java