voogasalad_LosTorres: utilities.multilanguage.ExampleMain Class Reference
utilities.multilanguage.ExampleMain Class Reference
Public Member Functions
void start (Stage primaryStage)
Static Public Member Functions
static void main (String[] args)
Detailed Description
An example class to show how the load style utility works. Disclaimer: The code here for the GUI is poorly written (everything is done in this class in code), and is merely to demonstrate the function calls of the load style utility.
Author
Jonathan Tseng
Definition at line 22 of file ExampleMain.java.
Member Function Documentation
static void utilities.multilanguage.ExampleMain.main (String[] args) static
Definition at line 80 of file ExampleMain.java.
void utilities.multilanguage.ExampleMain.start (Stage primaryStage)
Definition at line 25 of file ExampleMain.java.
References utilities.multilanguage.MultiLanguageUtility.getCurrentLanguage(), utilities.multilanguage.MultiLanguageUtility.getInstance(), utilities.multilanguage.MultiLanguageUtility.getStringListProperty(), utilities.multilanguage.MultiLanguageUtility.getStringProperty(), utilities.multilanguage.MultiLanguageUtility.getSupportedLanguages(), utilities.multilanguage.MultiLanguageUtility.initLanguages(), and utilities.multilanguage.MultiLanguageUtility.setLanguage().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/multilanguage/ExampleMain.java