voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.VisibilityPoint Class Reference
gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.VisibilityPoint Class Reference
Public Member Functions
VisibilityPoint (boolean visibility, Point2D point)
boolean isVisible ()
Point2D getPoint ()
Private Attributes
boolean myVisibility
Point2D myPoint
Detailed Description
A point on the route from the starting location to the ending location for an enemy. The visibility boolean determines if the enemy will be visible or invisible while traveling to the next point in the BackendRoute object.
Author
Austin Kyker
Definition at line 15 of file VisibilityPoint.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.VisibilityPoint.VisibilityPoint (boolean visibility, Point2D point)
Definition at line 19 of file VisibilityPoint.java.
Member Function Documentation
Point2D gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.VisibilityPoint.getPoint ()
Definition at line 28 of file VisibilityPoint.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.VisibilityPoint.myPoint.
Referenced by gameEngine.actors.behaviors.AIMovement.execute(), gameEngine.AI.GridPathFinder.getPath(), gameEngine.actors.behaviors.LinearMovement.move(), and gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testVisibilityPointCreation().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.VisibilityPoint.isVisible ()
Definition at line 24 of file VisibilityPoint.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.VisibilityPoint.myVisibility.
Referenced by gameEngine.actors.behaviors.LinearMovement.move(), and gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testVisibilityPointCreation().
Member Data Documentation
Point2D gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.VisibilityPoint.myPoint private
Definition at line 17 of file VisibilityPoint.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.VisibilityPoint.getPoint().
boolean gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.VisibilityPoint.myVisibility private
Definition at line 16 of file VisibilityPoint.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.VisibilityPoint.isVisible().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/pathComponents/routeToPointTranslation/VisibilityPoint.java