voogasalad_LosTorres: utilities.GSON.GSONFileWriter Class Reference
utilities.GSON.GSONFileWriter Class Reference
Public Member Functions
GSONFileWriter ()
void writeGameFile (List< TowerUpgradeGroup > towerGroups, List< BaseLevel > levels, String directory)
void writeTowerRegions (String directory, boolean[][] validRegions)
void writeToFile (String fileName, String json)
String convertWrappersToJson (Iterable< DataWrapper > wrapper)
void writeGameStateToJSon (String fileName, GameStateWrapper gsw)
void writeGeneralSettings (String directory, GeneralSettingsWrapper wrapper)
Private Attributes
GsonBuilder gson = new GsonBuilder()
Detailed Description
Definition at line 20 of file GSONFileWriter.java.
Constructor & Destructor Documentation
utilities.GSON.GSONFileWriter.GSONFileWriter ()
Definition at line 24 of file GSONFileWriter.java.
Member Function Documentation
String utilities.GSON.GSONFileWriter.convertWrappersToJson (Iterable< DataWrapper > wrapper)
Definition at line 51 of file GSONFileWriter.java.
Referenced by gameEngine.CoOpManager.convertTowersToString().
void utilities.GSON.GSONFileWriter.writeGameFile (List< TowerUpgradeGroup > towerGroups, List< BaseLevel > levels, String directory)
Definition at line 28 of file GSONFileWriter.java.
References utilities.GSON.GSONFileWriter.writeToFile().
Referenced by gameAuthoring.mainclasses.AuthorController.showGSONWritingScene().
void utilities.GSON.GSONFileWriter.writeGameStateToJSon (String fileName, GameStateWrapper gsw)
Definition at line 56 of file GSONFileWriter.java.
References utilities.GSON.GSONFileWriter.writeToFile().
Referenced by gameEngine.MainEngineManager.saveState().
void utilities.GSON.GSONFileWriter.writeGeneralSettings (String directory, GeneralSettingsWrapper wrapper)
Definition at line 60 of file GSONFileWriter.java.
References utilities.GSON.GSONFileWriter.writeToFile().
Referenced by gameAuthoring.mainclasses.AuthorController.setGeneralSettings().
void utilities.GSON.GSONFileWriter.writeToFile (String fileName, String json)
Definition at line 40 of file GSONFileWriter.java.
Referenced by utilities.GSON.GSONFileWriter.writeGameFile(), utilities.GSON.GSONFileWriter.writeGameStateToJSon(), utilities.GSON.GSONFileWriter.writeGeneralSettings(), and utilities.GSON.GSONFileWriter.writeTowerRegions().
void utilities.GSON.GSONFileWriter.writeTowerRegions (String directory, boolean validRegions[][])
Definition at line 36 of file GSONFileWriter.java.
References utilities.GSON.GSONFileWriter.writeToFile().
Referenced by gameAuthoring.mainclasses.AuthorController.setTowerRegions().
Member Data Documentation
GsonBuilder utilities.GSON.GSONFileWriter.gson = new GsonBuilder() private
Definition at line 22 of file GSONFileWriter.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/GSON/GSONFileWriter.java