voogasalad_LosTorres: gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo Class Reference
gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo Class Reference
Public Member Functions
SliderInfo (String info, double min, double max)
String getMyInfo ()
double getMyMin ()
double getMyMax ()
Private Attributes
String myInfo
double myMin
double myMax
Detailed Description
A class to hold information about a slider.
Author
Austin Kyker
Definition at line 8 of file SliderInfo.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo.SliderInfo (String info, double min, double max)
Definition at line 13 of file SliderInfo.java.
Member Function Documentation
String gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo.getMyInfo ()
Definition at line 19 of file SliderInfo.java.
References gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo.myInfo.
Referenced by utilities.JavaFXutilities.slider.SliderContainer.SliderContainer().
double gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo.getMyMax ()
Definition at line 27 of file SliderInfo.java.
References gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo.myMax.
Referenced by utilities.JavaFXutilities.slider.SliderContainer.setupSlider().
double gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo.getMyMin ()
Definition at line 23 of file SliderInfo.java.
References gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo.myMin.
Referenced by utilities.JavaFXutilities.slider.SliderContainer.resetSlider(), and utilities.JavaFXutilities.slider.SliderContainer.setupSlider().
Member Data Documentation
String gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo.myInfo private
Definition at line 9 of file SliderInfo.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo.getMyInfo().
double gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo.myMax private
Definition at line 11 of file SliderInfo.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo.getMyMax().
double gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo.myMin private
Definition at line 10 of file SliderInfo.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.SliderInfo.getMyMin().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/actorBuildingScenes/behaviorBuilders/SliderInfo.java