voogasalad_LosTorres: utilities.pathfinding.AStarTest.TestAStarFinder Class Reference
utilities.pathfinding.AStarTest.TestAStarFinder Class Reference
Public Member Functions
TestAStarFinder (TestNode[][] nodeMap)
Double getCost (TestNode beginningNode, TestNode endingNode)
Collection< TestNode > getNeighbors (TestNode node)
Double getHeuristicValue (TestNode node, TestNode destination)
int breakTie (TestNode node, TestNode other)
Public Member Functions inherited from utilities.pathfinding.AStarPathFinder< TestNode >
abstract Number getHeuristicValue (T node, T destination)
boolean isDestination (T node, T destinationNode)
List< T > findPath (T start, T destination) throws InvalidCostException
Private Attributes
TestNode[][] myMap
Detailed Description
Definition at line 86 of file AStarTest.java.
Constructor & Destructor Documentation
utilities.pathfinding.AStarTest.TestAStarFinder.TestAStarFinder (TestNode nodeMap[][])
Definition at line 90 of file AStarTest.java.
Member Function Documentation
int utilities.pathfinding.AStarTest.TestAStarFinder.breakTie (TestNode node, TestNode other)
Definition at line 136 of file AStarTest.java.
References utilities.pathfinding.AStarTest.TestNode.getX(), and utilities.pathfinding.AStarTest.TestNode.getY().
Double utilities.pathfinding.AStarTest.TestAStarFinder.getCost (TestNode beginningNode, TestNode endingNode)
Definition at line 95 of file AStarTest.java.
References utilities.pathfinding.AStarTest.TestNode.getX(), and utilities.pathfinding.AStarTest.TestNode.getY().
Double utilities.pathfinding.AStarTest.TestAStarFinder.getHeuristicValue (TestNode node, TestNode destination)
Definition at line 126 of file AStarTest.java.
References utilities.pathfinding.AStarTest.TestNode.getX(), and utilities.pathfinding.AStarTest.TestNode.getY().
Collection<TestNode> utilities.pathfinding.AStarTest.TestAStarFinder.getNeighbors (TestNode node)
Definition at line 104 of file AStarTest.java.
References utilities.pathfinding.AStarTest.TestNode.getX(), and utilities.pathfinding.AStarTest.TestNode.getY().
Member Data Documentation
TestNode [][] utilities.pathfinding.AStarTest.TestAStarFinder.myMap private
Definition at line 88 of file AStarTest.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/pathfinding/AStarTest.java