voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane Class Reference
gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane Class Reference
Public Member Functions
EnemyEndingLocationsPane (Group group, Path path, PathBuildingScene pathBuildingScene)
Public Member Functions inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane
EnemyLocationPane (Group group, Path path)
Public Member Functions inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
BuildingPane (Group group)
void drawLocation (Node component)
void drawPathComponent (Node component)
void refreshScreen ()
void removeComponentFromScreen (Node component)
void executeExitFunction ()
void executeEnterFunction ()
Private Member Functions
void createEnemyEndingLocationsSetupComponents ()
void addNewEndingLocation (MouseEvent event)
Private Attributes
Button mySaveEndsButton
PathBuildingScene myPathBuildingScene
Additional Inherited Members
Static Public Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
static final double DRAW_SCREEN_WIDTH_RATIO = .80
static final double DRAW_SCREEN_WIDTH
Protected Member Functions inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane
void createEnemyLocationsSetupComponents (Button button, String labelStr)
Protected Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane
Button myClearLocations
Path myPath
Static Protected Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
static Group myGroup
Detailed Description
Allows the user to place ending locations on the screen.
Author
Austin Kyker
Definition at line 19 of file EnemyEndingLocationsPane.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane.EnemyEndingLocationsPane (Group group, Path path, PathBuildingScene pathBuildingScene)
Definition at line 24 of file EnemyEndingLocationsPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane.addNewEndingLocation(), gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane.createEnemyEndingLocationsSetupComponents(), utilities.multilanguage.MultiLanguageUtility.getInstance(), utilities.multilanguage.MultiLanguageUtility.getStringProperty(), and gameAuthoring.mainclasses.Constants.SET_END_LOCS.
Member Function Documentation
void gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane.addNewEndingLocation (MouseEvent event) private
Definition at line 42 of file EnemyEndingLocationsPane.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addEndingLocation(), gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.drawLocation(), and gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane.myPath.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane.EnemyEndingLocationsPane().
void gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane.createEnemyEndingLocationsSetupComponents () private
Definition at line 34 of file EnemyEndingLocationsPane.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.clearEnemyEndingLocations(), gameAuthoring.mainclasses.Constants.ENEMY_ENDING_LOC_PROMPT, gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane.myClearLocations, and gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane.myPath.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane.EnemyEndingLocationsPane().
Member Data Documentation
PathBuildingScene gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane.myPathBuildingScene private
Definition at line 22 of file EnemyEndingLocationsPane.java.
Button gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane.mySaveEndsButton private
Definition at line 21 of file EnemyEndingLocationsPane.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/buildingPanes/locationPane/EnemyEndingLocationsPane.java