voogasalad_LosTorres: gamePlayer.mainClasses.welcomeScreen.GameStartManager Class Reference
gamePlayer.mainClasses.welcomeScreen.GameStartManager Class Reference
Public Member Functions
GameStartManager (Stage stage)
void init ()
void joinMultiPlayerGame ()
void startSinglePlayerGame (String directoryPath)
void startGame (File file)
Static Public Attributes
static final String propertiesPath = "./src/gamePlayer/properties/WelcomeScreenProperties.XML"
Private Member Functions
void initializeWelcomeScreen (Group group)
ComboBox createLanguageSelector ()
void startSinglePlayerGameChooser ()
void startMultiPlayerGameChooser ()
void startMultiPlayerOptions ()
void startMultiPlayerGame (String directoryPath)
void pollEngineForMultiPlayerReadiness (GuiManager manager, Timeline timeline)
ImageView getImageFromPath (String imagePath, double width, double height)
Private Attributes
Stage myStage
XMLParser parser
WelcomeScreen welcomeScreen
String gameTypeBeingChosen
Detailed Description
Definition at line 25 of file GameStartManager.java.
Constructor & Destructor Documentation
gamePlayer.mainClasses.welcomeScreen.GameStartManager.GameStartManager (Stage stage)
Definition at line 32 of file GameStartManager.java.
References gamePlayer.mainClasses.guiBuilder.GuiConstants.GAME_START_MANAGER, utilities.multilanguage.MultiLanguageUtility.getInstance(), gamePlayer.mainClasses.welcomeScreen.GameStartManager.init(), utilities.multilanguage.MultiLanguageUtility.initLanguages(), gamePlayer.mainClasses.guiBuilder.GuiConstants.MULTILANGUAGE, and utilities.multilanguage.MultiLanguageUtility.setLanguage().
Member Function Documentation
ComboBox gamePlayer.mainClasses.welcomeScreen.GameStartManager.createLanguageSelector () private
Definition at line 83 of file GameStartManager.java.
References utilities.multilanguage.MultiLanguageUtility.getCurrentLanguage(), utilities.multilanguage.MultiLanguageUtility.getSupportedLanguages(), gamePlayer.mainClasses.guiBuilder.GuiConstants.MULTILANGUAGE, gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.PANE_HEIGHT, gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.PANE_WIDTH, and utilities.multilanguage.MultiLanguageUtility.setLanguage().
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.initializeWelcomeScreen().
ImageView gamePlayer.mainClasses.welcomeScreen.GameStartManager.getImageFromPath (String imagePath, double width, double height) private
Definition at line 158 of file GameStartManager.java.
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.initializeWelcomeScreen().
void gamePlayer.mainClasses.welcomeScreen.GameStartManager.init ()
Definition at line 51 of file GameStartManager.java.
References gamePlayer.mainClasses.guiBuilder.GuiConstants.DYNAMIC_SIZING, utilities.XMLParsing.XMLParser.getValuesFromTag(), gamePlayer.mainClasses.welcomeScreen.GameStartManager.initializeWelcomeScreen(), gamePlayer.mainClasses.guiBuilder.GuiConstants.WINDOW_HEIGHT, and gamePlayer.mainClasses.guiBuilder.GuiConstants.WINDOW_WIDTH.
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.GameStartManager().
void gamePlayer.mainClasses.welcomeScreen.GameStartManager.initializeWelcomeScreen (Group group) private
Definition at line 66 of file GameStartManager.java.
References gamePlayer.mainClasses.welcomeScreen.GameStartManager.createLanguageSelector(), gamePlayer.mainClasses.welcomeScreen.GameStartManager.getImageFromPath(), gamePlayer.mainClasses.welcomeScreen.startingOptions.PlayerCountOptions.getMultiPlayerOption(), gamePlayer.mainClasses.welcomeScreen.startingOptions.PlayerCountOptions.getSinglePlayerOption(), utilities.XMLParsing.XMLParser.getValuesFromTag(), gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.HEIGHT, gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.PANE_HEIGHT, gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.PANE_WIDTH, gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setBackgroundImage(), gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setBottomContent(), gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setCenterContent(), gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setTopContent(), and gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.WIDTH.
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.init().
void gamePlayer.mainClasses.welcomeScreen.GameStartManager.joinMultiPlayerGame ()
Definition at line 108 of file GameStartManager.java.
References gamePlayer.mainClasses.managers.GuiManager.joinMultiPlayerGame().
void gamePlayer.mainClasses.welcomeScreen.GameStartManager.pollEngineForMultiPlayerReadiness (GuiManager manager, Timeline timeline) private
Definition at line 151 of file GameStartManager.java.
References gamePlayer.mainClasses.managers.GuiManager.multiPlayerGameIsReady(), and gamePlayer.mainClasses.managers.GuiManager.startMultiPlayerGame().
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.startMultiPlayerGame().
void gamePlayer.mainClasses.welcomeScreen.GameStartManager.startGame (File file)
Definition at line 163 of file GameStartManager.java.
References gamePlayer.mainClasses.guiBuilder.GuiConstants.MULTI_PLAYER_GAME, gamePlayer.mainClasses.guiBuilder.GuiConstants.SINGLE_PLAYER_GAME, gamePlayer.mainClasses.welcomeScreen.GameStartManager.startMultiPlayerGame(), and gamePlayer.mainClasses.welcomeScreen.GameStartManager.startSinglePlayerGame().
void gamePlayer.mainClasses.welcomeScreen.GameStartManager.startMultiPlayerGame (String directoryPath) private
Definition at line 138 of file GameStartManager.java.
References utilities.multilanguage.MultiLanguageUtility.getStringProperty(), gamePlayer.mainClasses.guiBuilder.GuiConstants.MULTILANGUAGE, gamePlayer.mainClasses.welcomeScreen.GameStartManager.pollEngineForMultiPlayerReadiness(), gamePlayer.mainClasses.managers.GuiManager.prepareMultiPlayerGame(), gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setCenterContent(), and gamePlayer.mainClasses.guiBuilder.GuiText.WAITING_FOR_CHALLENGER.
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.startGame().
void gamePlayer.mainClasses.welcomeScreen.GameStartManager.startMultiPlayerGameChooser () private
Definition at line 119 of file GameStartManager.java.
References gamePlayer.mainClasses.guiBuilder.GuiConstants.MULTI_PLAYER_GAME, gamePlayer.mainClasses.guiBuilder.GuiConstants.MULTI_PLAYER_GAMES_DIRECTORY, and gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setCenterLargeContent().
void gamePlayer.mainClasses.welcomeScreen.GameStartManager.startMultiPlayerOptions () private
Definition at line 125 of file GameStartManager.java.
References gamePlayer.mainClasses.welcomeScreen.startingOptions.MultiPlayerOptions.getJoinGameOption(), gamePlayer.mainClasses.welcomeScreen.startingOptions.MultiPlayerOptions.getNewGameOption(), and gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setCenterContent().
void gamePlayer.mainClasses.welcomeScreen.GameStartManager.startSinglePlayerGame (String directoryPath)
Definition at line 132 of file GameStartManager.java.
References gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_MANAGER, gamePlayer.mainClasses.managers.GuiManager.init(), and gamePlayer.mainClasses.managers.GuiManager.startSinglePlayerGame().
Referenced by gamePlayer.mainClasses.welcomeScreen.GameStartManager.startGame().
void gamePlayer.mainClasses.welcomeScreen.GameStartManager.startSinglePlayerGameChooser () private
Definition at line 113 of file GameStartManager.java.
References gamePlayer.mainClasses.welcomeScreen.WelcomeScreen.setCenterLargeContent(), gamePlayer.mainClasses.guiBuilder.GuiConstants.SINGLE_PLAYER_GAME, and gamePlayer.mainClasses.guiBuilder.GuiConstants.SINGLE_PLAYER_GAMES_DIRECTORY.
Member Data Documentation
String gamePlayer.mainClasses.welcomeScreen.GameStartManager.gameTypeBeingChosen private
Definition at line 30 of file GameStartManager.java.
Stage gamePlayer.mainClasses.welcomeScreen.GameStartManager.myStage private
Definition at line 26 of file GameStartManager.java.
XMLParser gamePlayer.mainClasses.welcomeScreen.GameStartManager.parser private
Definition at line 28 of file GameStartManager.java.
final String gamePlayer.mainClasses.welcomeScreen.GameStartManager.propertiesPath = "./src/gamePlayer/properties/WelcomeScreenProperties.XML" static
Definition at line 27 of file GameStartManager.java.
WelcomeScreen gamePlayer.mainClasses.welcomeScreen.GameStartManager.welcomeScreen private
Definition at line 29 of file GameStartManager.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/mainClasses/welcomeScreen/GameStartManager.java