voogasalad_LosTorres: utilities.JavaFXutilities.imageView.StringToImageViewConverter Class Reference
utilities.JavaFXutilities.imageView.StringToImageViewConverter Class Reference
Static Public Member Functions
static CenteredImageView getImageView (double width, double height, String path)
Detailed Description
The purpose of this class is to allow the user to get an image view from a string. This will be used throughout AuthoringEnvironment and may also appear in the GameEngine and front-end Player
Author
Austin Kyker
Definition at line 17 of file StringToImageViewConverter.java.
Member Function Documentation
static CenteredImageView utilities.JavaFXutilities.imageView.StringToImageViewConverter.getImageView (double width, double height, String path) static
Definition at line 19 of file StringToImageViewConverter.java.
References gameAuthoring.mainclasses.Constants.FILE_NOT_LOADED.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingOptionPane.BuildingOptionPane(), gameAuthoring.scenes.levelBuilding.LevelDisplayCell.createEnemiesBox(), gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.DefaultMapSelectionPane(), utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane.displayImage(), utilities.errorPopup.ErrorPopup.ErrorPopup(), gameAuthoring.scenes.actorBuildingScenes.TowerUpgradeGroup.fetchImageViews(), gamePlayer.mainClasses.welcomeScreen.availableGames.GameDescriptionLoader.getDescriptions(), gameEngine.actors.BaseActor.makeNode(), gamePlayer.guiItems.gameWorld.GameWorld.setBackground(), gameAuthoring.scenes.pathBuilding.PathBuildingScene.setBackground(), gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.setCurrentTower(), gameAuthoring.scenes.levelBuilding.LevelBuildingScene.setupLevelDisplay(), and gamePlayer.guiItems.store.StoreItem.StoreItem().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/JavaFXutilities/imageView/StringToImageViewConverter.java