voogasalad_LosTorres: gameAuthoring.mainclasses.controllerInterfaces.IPathConfiguring Interface Reference
gameAuthoring.mainclasses.controllerInterfaces.IPathConfiguring Interface Reference
Public Member Functions
void configurePath (Path path)
void setBackground (String imageFileName)
void setTowerRegions (boolean[][] backendTowerRegions)
Detailed Description
An interface for building the path. Provides a means of providing the Authoring Controller with the path after it has been drawn.
Author
Austin Kyker
Definition at line 11 of file IPathConfiguring.java.
Member Function Documentation
void gameAuthoring.mainclasses.controllerInterfaces.IPathConfiguring.configurePath (Path path)
Implemented in gameAuthoring.mainclasses.AuthorController.
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.handleFinishButtonClick().
void gameAuthoring.mainclasses.controllerInterfaces.IPathConfiguring.setBackground (String imageFileName)
Implemented in gameAuthoring.mainclasses.AuthorController.
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.setBackground().
void gameAuthoring.mainclasses.controllerInterfaces.IPathConfiguring.setTowerRegions (boolean backendTowerRegions[][])
Implemented in gameAuthoring.mainclasses.AuthorController.
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.handleFinishButtonClick().
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/mainclasses/controllerInterfaces/IPathConfiguring.java