voogasalad_LosTorres: gamePlayer.guiFeatures.TowerPlacer Class Reference
gamePlayer.guiFeatures.TowerPlacer Class Reference
Public Member Functions
void placeItem (String towerName, Pane rootNode, double range)
Static Public Member Functions
static TowerPlacer getInstance ()
Private Member Functions
void drag (Circle node, double X, double Y, Pane root)
void drop (Circle node, double X, double Y, String towerName, Node rootNode)
boolean validPlacement (double X, double Y)
Private Attributes
boolean dragging
Static Private Attributes
static TowerPlacer myReference = null
Detailed Description
Singleton class to drag towers from the store and place them on the game map
Author
brianbolze
Definition at line 15 of file TowerPlacer.java.
Member Function Documentation
void gamePlayer.guiFeatures.TowerPlacer.drag (Circle node, double X, double Y, Pane root) private
Definition at line 41 of file TowerPlacer.java.
References gamePlayer.guiFeatures.TowerPlacer.validPlacement().
Referenced by gamePlayer.guiFeatures.TowerPlacer.placeItem().
void gamePlayer.guiFeatures.TowerPlacer.drop (Circle node, double X, double Y, String towerName, Node rootNode) private
Definition at line 54 of file TowerPlacer.java.
References gamePlayer.mainClasses.managers.GuiManager.displayMessage(), gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_MANAGER, gamePlayer.mainClasses.managers.GuiManager.makeTower(), and gamePlayer.guiFeatures.TowerPlacer.validPlacement().
Referenced by gamePlayer.guiFeatures.TowerPlacer.placeItem().
static TowerPlacer gamePlayer.guiFeatures.TowerPlacer.getInstance () static
Definition at line 20 of file TowerPlacer.java.
References gamePlayer.guiFeatures.TowerPlacer.myReference.
Referenced by gamePlayer.mainClasses.managers.GuiManager.placeTower().
void gamePlayer.guiFeatures.TowerPlacer.placeItem (String towerName, Pane rootNode, double range)
Drags an item and attempts to place it on the map
Parameters
rootNode : The Node to attach the mouseListener to
Definition at line 32 of file TowerPlacer.java.
References gamePlayer.guiFeatures.TowerPlacer.drag(), and gamePlayer.guiFeatures.TowerPlacer.drop().
Referenced by gamePlayer.mainClasses.managers.GuiManager.placeTower().
boolean gamePlayer.guiFeatures.TowerPlacer.validPlacement (double X, double Y) private
Definition at line 68 of file TowerPlacer.java.
References gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_MANAGER, and gamePlayer.mainClasses.managers.GuiManager.validPlacement().
Referenced by gamePlayer.guiFeatures.TowerPlacer.drag(), and gamePlayer.guiFeatures.TowerPlacer.drop().
Member Data Documentation
boolean gamePlayer.guiFeatures.TowerPlacer.dragging private
Definition at line 18 of file TowerPlacer.java.
TowerPlacer gamePlayer.guiFeatures.TowerPlacer.myReference = null static private
Definition at line 17 of file TowerPlacer.java.
Referenced by gamePlayer.guiFeatures.TowerPlacer.getInstance().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiFeatures/TowerPlacer.java