voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile Class Reference
gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile Class Reference
Public Member Functions
Tile (int row, int col)
int getRow ()
int getColumn ()
void toggleSelection ()
boolean isSelected ()
Static Protected Attributes
static final double WIDTH
static final double HEIGHT
Private Attributes
boolean isSelected
int myRow
int myCol
Static Private Attributes
static final double TRANSLUCENT = 0.2
static final double LESS_TRANSLUCENT = 0.5
Detailed Description
A class to represents the tiles in the grid used by the user to select the regions where towers can and cannot be placed.
Author
Austin Kyker
Definition at line 14 of file Tile.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.Tile (int row, int col)
Definition at line 29 of file Tile.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.HEIGHT, gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.toggleSelection(), and gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.WIDTH.
Member Function Documentation
int gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.getColumn ()
Definition at line 50 of file Tile.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.myCol.
Referenced by gameEngine.AI.GridPathFinder.getPath(), and gameEngine.MainEngineManager.setTowerTileStatus().
int gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.getRow ()
Definition at line 46 of file Tile.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.myRow.
Referenced by gameEngine.AI.GridPathFinder.getPath(), and gameEngine.MainEngineManager.setTowerTileStatus().
boolean gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.isSelected ()
Definition at line 60 of file Tile.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.toggleSelection().
void gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.toggleSelection ()
Definition at line 54 of file Tile.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.isSelected().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.suggestNoTowerPlacementOnPath(), and gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.Tile().
Member Data Documentation
final double gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.HEIGHT static protected
Initial value:
=
            AuthorController.SCREEN_HEIGHT / TowerRegionsPane.NUM_ROWS
Definition at line 18 of file Tile.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.Tile().
boolean gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.isSelected private
Definition at line 24 of file Tile.java.
final double gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.LESS_TRANSLUCENT = 0.5 static private
Definition at line 22 of file Tile.java.
int gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.myCol private
Definition at line 27 of file Tile.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.getColumn().
int gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.myRow private
Definition at line 26 of file Tile.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.getRow().
final double gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.TRANSLUCENT = 0.2 static private
Definition at line 21 of file Tile.java.
final double gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.WIDTH static protected
Initial value:
=
            BuildingPane.DRAW_SCREEN_WIDTH / TowerRegionsPane.NUM_COLS
Definition at line 16 of file Tile.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.Tile().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/buildingPanes/towerRegions/Tile.java