voogasalad_LosTorres: utilities.GSON.GSONFileReader Class Reference
utilities.GSON.GSONFileReader Class Reference
Public Member Functions
GSONFileReader ()
List< TowerUpgradeGroup > readTowersFromGameDirectory (String gameDir)
List< BaseLevel > readLevelsFromGameDirectory (String gameDir)
List< DataWrapper > readWrappers (String towers)
boolean[][] readTowerRegionsFromGameDirectory (String gameDir)
GameStateWrapper readGameStateFromJSon (String fileName)
GeneralSettingsWrapper readGeneralSettingsWrapper (String directory)
Package Attributes
GsonBuilder gson
Private Attributes
List< TowerUpgradeGroup > towerList
List< BaseLevel > levelList
boolean[][] locations
GameStateWrapper gameState
GeneralSettingsWrapper generalSettings
Detailed Description
Definition at line 20 of file GSONFileReader.java.
Constructor & Destructor Documentation
utilities.GSON.GSONFileReader.GSONFileReader ()
Definition at line 31 of file GSONFileReader.java.
Member Function Documentation
GameStateWrapper utilities.GSON.GSONFileReader.readGameStateFromJSon (String fileName)
Definition at line 75 of file GSONFileReader.java.
References utilities.GSON.GSONFileReader.gameState.
Referenced by gameEngine.MainEngineManager.loadState().
GeneralSettingsWrapper utilities.GSON.GSONFileReader.readGeneralSettingsWrapper (String directory)
Definition at line 87 of file GSONFileReader.java.
References utilities.GSON.GSONFileReader.generalSettings.
Referenced by gameEngine.MainEngineManager.loadGameSettings().
List<BaseLevel> utilities.GSON.GSONFileReader.readLevelsFromGameDirectory (String gameDir)
Definition at line 47 of file GSONFileReader.java.
References utilities.GSON.GSONFileReader.levelList.
Referenced by gameEngine.MainEngineManager.loadLevelFile().
boolean [][] utilities.GSON.GSONFileReader.readTowerRegionsFromGameDirectory (String gameDir)
Definition at line 64 of file GSONFileReader.java.
References utilities.GSON.GSONFileReader.locations.
Referenced by gameEngine.MainEngineManager.loadLocations().
List<TowerUpgradeGroup> utilities.GSON.GSONFileReader.readTowersFromGameDirectory (String gameDir)
Definition at line 36 of file GSONFileReader.java.
References utilities.GSON.GSONFileReader.towerList.
Referenced by gameEngine.MainEngineManager.loadTowers().
List<DataWrapper> utilities.GSON.GSONFileReader.readWrappers (String towers)
Definition at line 58 of file GSONFileReader.java.
Referenced by gameEngine.CoOpManager.getTowersFromServer().
Member Data Documentation
GameStateWrapper utilities.GSON.GSONFileReader.gameState private
Definition at line 28 of file GSONFileReader.java.
Referenced by utilities.GSON.GSONFileReader.readGameStateFromJSon().
GeneralSettingsWrapper utilities.GSON.GSONFileReader.generalSettings private
Definition at line 29 of file GSONFileReader.java.
Referenced by utilities.GSON.GSONFileReader.readGeneralSettingsWrapper().
GsonBuilder utilities.GSON.GSONFileReader.gson package
Definition at line 24 of file GSONFileReader.java.
List<BaseLevel> utilities.GSON.GSONFileReader.levelList private
Definition at line 26 of file GSONFileReader.java.
Referenced by utilities.GSON.GSONFileReader.readLevelsFromGameDirectory().
boolean [][] utilities.GSON.GSONFileReader.locations private
Definition at line 27 of file GSONFileReader.java.
Referenced by utilities.GSON.GSONFileReader.readTowerRegionsFromGameDirectory().
List<TowerUpgradeGroup> utilities.GSON.GSONFileReader.towerList private
Definition at line 25 of file GSONFileReader.java.
Referenced by utilities.GSON.GSONFileReader.readTowersFromGameDirectory().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/GSON/GSONFileReader.java