voogasalad_LosTorres: gameEngine.actors.BaseActor Class Reference
gameEngine.actors.BaseActor Class Reference abstract
Public Member Functions
BaseActor ()
BaseActor (Map< String, IBehavior > behaviors, String imageName, String name, double range)
void update (InformationInterface info)
boolean addDebuff (IBehavior debuff)
void removeDebuff (IBehavior debuff)
void makeNode (Point2D point)
IBehavior getBehavior (String s)
String toString ()
double getX ()
double getY ()
CenteredImageView getNode ()
String getImagePath ()
abstract Node getRange ()
double getRangeProperty ()
List< BaseActor > getEnemiesInRange (double range)
List< BaseActor > getTowersInRange (double range)
List< BaseActor > getProjectilesInRange (double range)
InformationInterface getInfoInterface ()
Collection< Class<?extends BaseActor > > getTypes ()
void setRange (double d)
void died ()
boolean isDead ()
void changeAndNotify (UpdateObject o)
void killed ()
Protected Member Functions
void makeNode ()
abstract int[] getSize ()
Map< String, IBehavior > copyBehaviors ()
Protected Attributes
Map< String, IBehavior > myBehaviors
String myName
transient CenteredImageView myNode
transient InformationInterface myInfo
double myRange
int myBounty
String myImagePath
transient Set< Class<?extends BaseActor > > myTypes
boolean myIsRemovable
Map< String, IBehavior > myDebuffs
Set< IBehavior > myDebuffsToRemove
Detailed Description
Base Actor class that represents all of the actors on the screen (enemies, towers, projectiles) Stores its behaviors, image, and a name On an update call, it simply loops over its current behaviors and executes them
Author
Chase Malik, Timesh Patel
Definition at line 28 of file BaseActor.java.
Constructor & Destructor Documentation
gameEngine.actors.BaseActor.BaseActor ()
Definition at line 41 of file BaseActor.java.
gameEngine.actors.BaseActor.BaseActor (Map< String, IBehavior > behaviors, String imageName, String name, double range)
Definition at line 45 of file BaseActor.java.
References gameEngine.actors.BaseActor.makeNode().
Member Function Documentation
boolean gameEngine.actors.BaseActor.addDebuff (IBehavior debuff)
Definition at line 73 of file BaseActor.java.
References gameEngine.actors.behaviors.IBehavior.toString().
Referenced by gameEngine.actors.behaviors.BaseDefendBehavior.gotHit().
void gameEngine.actors.BaseActor.changeAndNotify (UpdateObject o)
Definition at line 183 of file BaseActor.java.
Referenced by gameEngine.actors.BaseEnemy.died(), gameEngine.actors.BaseEnemy.killed(), gameEngine.actors.behaviors.GoldGenEffect.start(), and gameEngine.actors.behaviors.HealEffect.start().
Map<String, IBehavior> gameEngine.actors.BaseActor.copyBehaviors () protected
Copies the current actor to create another one This is used when creating x amount of enemies of the same type on a specific level The copy is created by copying all of the behaviors and creating a new BaseActor object
Returns
Definition at line 109 of file BaseActor.java.
Referenced by gameEngine.actors.BaseTower.copy(), and gameEngine.actors.BaseEnemy.copy().
void gameEngine.actors.BaseActor.died ()
Definition at line 175 of file BaseActor.java.
Referenced by gameEngine.actors.behaviors.BaseMovementBehavior.findNextTarget(), gameEngine.actors.behaviors.PiercableDefense.handleBullet(), and gameEngine.actors.behaviors.SimpleDefense.handleBullet().
IBehavior gameEngine.actors.BaseActor.getBehavior (String s)
Definition at line 117 of file BaseActor.java.
Referenced by gameEngine.actors.behaviors.FarthestRangeAttack.defineComparison(), gameEngine.actors.behaviors.StrongestRangeAttack.defineComparison(), gameEngine.actors.behaviors.DoTOnHit.during(), gameEngine.actors.behaviors.SlowEffect.end(), gameEngine.actors.BaseActor.getRangeProperty(), and gameEngine.actors.behaviors.SlowEffect.start().
List<BaseActor> gameEngine.actors.BaseActor.getEnemiesInRange (double range)
Definition at line 148 of file BaseActor.java.
References gameEngine.ManagerInterface.InformationInterface.getRequiredActors(), and gameEngine.actors.BaseActor.setRange().
Referenced by gameEngine.actors.behaviors.EarthQuakeEffect.during(), gameEngine.actors.behaviors.EnemyHomingMovement.execute(), gameEngine.actors.behaviors.AoEAttack.performAttack(), gameEngine.actors.behaviors.RangeAttack.performAttack(), and gameEngine.actors.behaviors.AoEEffect.start().
String gameEngine.actors.BaseActor.getImagePath ()
Definition at line 138 of file BaseActor.java.
References gameEngine.actors.BaseActor.myImagePath.
InformationInterface gameEngine.actors.BaseActor.getInfoInterface ()
Definition at line 163 of file BaseActor.java.
References gameEngine.actors.BaseActor.myInfo.
Referenced by gameEngine.actors.behaviors.EarthQuakeEffect.during(), and gameEngine.actors.behaviors.AIMovement.execute().
CenteredImageView gameEngine.actors.BaseActor.getNode ()
Definition at line 134 of file BaseActor.java.
References gameEngine.actors.BaseActor.myNode.
Referenced by gameEngine.MainEngineManager.addTower(), gameEngine.actors.BaseEnemy.copy(), gameEngine.actors.behaviors.EnemyHomingMovement.execute(), gameEngine.actors.behaviors.AIMovement.execute(), gameEngine.actors.behaviors.LinearMovement.execute(), gameEngine.actors.behaviors.BaseDefendBehavior.execute(), gameEngine.AI.GridPathFinder.getPath(), gameEngine.actors.behaviors.LinearMovement.move(), gameEngine.actors.behaviors.BaseMovementBehavior.move(), gameEngine.MainEngineManager.setTowerTileStatus(), gameEngine.actors.behaviors.RangeAttack.shootActorFromActor(), and gameAuthoring.scenes.actorBuildingScenes.actorListView.listViewCells.EnemyCell.updateItem().
List<BaseActor> gameEngine.actors.BaseActor.getProjectilesInRange (double range)
Definition at line 158 of file BaseActor.java.
References gameEngine.ManagerInterface.InformationInterface.getRequiredActors(), and gameEngine.actors.BaseActor.setRange().
Referenced by gameEngine.actors.behaviors.BaseDefendBehavior.execute().
abstract Node gameEngine.actors.BaseActor.getRange () abstract
Referenced by gameEngine.Data.RangeRestrictedCollection< gameEngine.actors.BaseTower >.getActorsInRange().
double gameEngine.actors.BaseActor.getRangeProperty ()
Definition at line 144 of file BaseActor.java.
References gameEngine.actors.BaseActor.getBehavior().
abstract int [] gameEngine.actors.BaseActor.getSize () abstract protected
Referenced by gameEngine.actors.BaseActor.makeNode().
List<BaseActor> gameEngine.actors.BaseActor.getTowersInRange (double range)
Definition at line 153 of file BaseActor.java.
References gameEngine.ManagerInterface.InformationInterface.getRequiredActors(), and gameEngine.actors.BaseActor.setRange().
Referenced by gameEngine.actors.behaviors.TowerRangeEffect.start().
Collection<Class<? extends BaseActor> > gameEngine.actors.BaseActor.getTypes ()
Definition at line 167 of file BaseActor.java.
References gameEngine.actors.BaseActor.myTypes.
double gameEngine.actors.BaseActor.getX ()
Definition at line 126 of file BaseActor.java.
References utilities.JavaFXutilities.imageView.CenteredImageView.getXCenter().
Referenced by utilities.GSON.objectWrappers.DataWrapper.DataWrapper(), gameEngine.actors.behaviors.ClosestRangeAttack.defineComparison(), gameEngine.actors.behaviors.EnemyHomingMovement.execute(), gameEngine.actors.behaviors.BaseMovementBehavior.findNextTarget(), gameEngine.AI.GridPathFinder.getPath(), gameEngine.MainEngineManager.isInRangeOfField(), gameEngine.actors.behaviors.AoEAttack.performAttack(), gameEngine.actors.behaviors.RangeAttack.shootActorFromActor(), and gameEngine.tests.BehaviorTester.updateAndCheck().
double gameEngine.actors.BaseActor.getY ()
Definition at line 130 of file BaseActor.java.
References utilities.JavaFXutilities.imageView.CenteredImageView.getYCenter().
Referenced by utilities.GSON.objectWrappers.DataWrapper.DataWrapper(), gameEngine.actors.behaviors.ClosestRangeAttack.defineComparison(), gameEngine.actors.behaviors.EnemyHomingMovement.execute(), gameEngine.actors.behaviors.BaseMovementBehavior.findNextTarget(), gameEngine.AI.GridPathFinder.getPath(), gameEngine.MainEngineManager.isInRangeOfField(), gameEngine.actors.behaviors.AoEAttack.performAttack(), gameEngine.actors.behaviors.RangeAttack.shootActorFromActor(), and gameEngine.tests.BehaviorTester.updateAndCheck().
boolean gameEngine.actors.BaseActor.isDead ()
Definition at line 179 of file BaseActor.java.
References gameEngine.actors.BaseActor.myIsRemovable.
Referenced by gameEngine.actors.behaviors.EnemyHomingMovement.execute().
void gameEngine.actors.BaseActor.killed ()
Definition at line 189 of file BaseActor.java.
Referenced by gameEngine.actors.behaviors.DoTOnHit.during(), gameEngine.actors.behaviors.EnemyHomingMovement.execute(), gameEngine.actors.behaviors.SimpleDefense.onDeath(), and gameEngine.actors.behaviors.PiercableDefense.onDeath().
void gameEngine.actors.BaseActor.makeNode () protected
Definition at line 83 of file BaseActor.java.
References utilities.JavaFXutilities.imageView.StringToImageViewConverter.getImageView(), and gameEngine.actors.BaseActor.getSize().
Referenced by gameEngine.actors.BaseActor.BaseActor(), and gameEngine.actors.BaseProjectile.BaseProjectile().
void gameEngine.actors.BaseActor.makeNode (Point2D point)
Definition at line 90 of file BaseActor.java.
References utilities.JavaFXutilities.imageView.StringToImageViewConverter.getImageView(), gameEngine.actors.BaseActor.getSize(), utilities.JavaFXutilities.imageView.CenteredImageView.setXCenter(), and utilities.JavaFXutilities.imageView.CenteredImageView.setYCenter().
void gameEngine.actors.BaseActor.removeDebuff (IBehavior debuff)
Definition at line 79 of file BaseActor.java.
Referenced by gameEngine.actors.behaviors.SlowEffect.end(), gameEngine.actors.behaviors.DoTOnHit.end(), and gameEngine.actors.behaviors.AoEEffect.end().
void gameEngine.actors.BaseActor.setRange (double d)
Definition at line 171 of file BaseActor.java.
Referenced by gameEngine.actors.BaseActor.getEnemiesInRange(), gameEngine.actors.BaseActor.getProjectilesInRange(), and gameEngine.actors.BaseActor.getTowersInRange().
String gameEngine.actors.BaseActor.toString ()
Definition at line 122 of file BaseActor.java.
References gameEngine.actors.BaseActor.myName.
Referenced by gameEngine.actors.behaviors.BaseDefendBehavior.checkTypes(), utilities.GSON.objectWrappers.DataWrapper.DataWrapper(), gameEngine.MainEngineManager.getTowerName(), and gameAuthoring.scenes.actorBuildingScenes.actorListView.listViewCells.EnemyCell.updateItem().
void gameEngine.actors.BaseActor.update (InformationInterface info)
Updates the actor by looping over all of its behaviors and performing them
Definition at line 61 of file BaseActor.java.
Referenced by gameEngine.tests.BehaviorTester.testMovementBehaviorSimple(), gameEngine.tests.BehaviorTester.testMovementBehaviorSimple2(), and gameEngine.tests.BehaviorTester.updateAndCheck().
Member Data Documentation
Map<String, IBehavior> gameEngine.actors.BaseActor.myBehaviors protected
Definition at line 29 of file BaseActor.java.
Referenced by gameEngine.actors.BaseProjectile.BaseProjectile(), gameEngine.actors.BaseProjectile.setMove(), and gameEngine.actors.RealActor.update().
int gameEngine.actors.BaseActor.myBounty protected
Definition at line 34 of file BaseActor.java.
Referenced by gameEngine.actors.BaseEnemy.copy(), gameEngine.actors.BaseEnemy.getBounty(), and gameEngine.actors.BaseEnemy.killed().
Map<String, IBehavior> gameEngine.actors.BaseActor.myDebuffs protected
Definition at line 38 of file BaseActor.java.
Referenced by gameEngine.actors.RealActor.update().
Set<IBehavior> gameEngine.actors.BaseActor.myDebuffsToRemove protected
Definition at line 39 of file BaseActor.java.
Referenced by gameEngine.actors.RealActor.update().
String gameEngine.actors.BaseActor.myImagePath protected
Definition at line 35 of file BaseActor.java.
Referenced by gameEngine.actors.BaseProjectile.BaseProjectile(), gameEngine.actors.BaseTower.copy(), gameEngine.actors.BaseEnemy.copy(), and gameEngine.actors.BaseActor.getImagePath().
transient InformationInterface gameEngine.actors.BaseActor.myInfo protected
Definition at line 32 of file BaseActor.java.
Referenced by gameEngine.actors.BaseActor.getInfoInterface(), and gameEngine.actors.RealActor.update().
boolean gameEngine.actors.BaseActor.myIsRemovable protected
Definition at line 37 of file BaseActor.java.
Referenced by gameEngine.actors.BaseEnemy.died(), gameEngine.actors.BaseActor.isDead(), and gameEngine.actors.BaseEnemy.killed().
String gameEngine.actors.BaseActor.myName protected
Definition at line 30 of file BaseActor.java.
Referenced by gameEngine.actors.BaseTower.copy(), gameEngine.actors.BaseEnemy.copy(), and gameEngine.actors.BaseActor.toString().
transient CenteredImageView gameEngine.actors.BaseActor.myNode protected
Definition at line 31 of file BaseActor.java.
Referenced by gameEngine.actors.BaseProjectile.BaseProjectile(), gameEngine.actors.BaseActor.getNode(), gameEngine.actors.BaseProjectile.getRange(), and gameEngine.actors.RealActor.getRange().
double gameEngine.actors.BaseActor.myRange protected
Definition at line 33 of file BaseActor.java.
Referenced by gameEngine.actors.BaseTower.copy(), gameEngine.actors.BaseEnemy.copy(), gameEngine.actors.RealActor.getRange(), and gameEngine.actors.BaseProjectile.getRange().
transient Set<Class<? extends BaseActor> > gameEngine.actors.BaseActor.myTypes protected
Definition at line 36 of file BaseActor.java.
Referenced by gameEngine.actors.BaseProjectile.BaseProjectile(), and gameEngine.actors.BaseActor.getTypes().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/BaseActor.java