voogasalad_LosTorres: gamePlayer.guiItems.headsUpDisplay.GameStat Class Reference
gamePlayer.guiItems.headsUpDisplay.GameStat Class Reference
Public Member Functions
void setGameStat (String value)
String getGameStat ()
StringProperty gameStatProperty ()
void setStatValue (double value)
double getStatValue ()
DoubleProperty statValueProperty ()
Private Attributes
StringProperty gameStat
DoubleProperty statValue
Detailed Description
This engine class encapsulates the overall game statistics such as score and health that are going to be observable on the GUI
Author
allankiplagat
Definition at line 16 of file GameStat.java.
Member Function Documentation
StringProperty gamePlayer.guiItems.headsUpDisplay.GameStat.gameStatProperty ()
Definition at line 27 of file GameStat.java.
References gamePlayer.guiItems.headsUpDisplay.GameStat.gameStat.
Referenced by gamePlayer.guiItems.headsUpDisplay.GameStat.getGameStat(), and gamePlayer.guiItems.headsUpDisplay.GameStat.setGameStat().
String gamePlayer.guiItems.headsUpDisplay.GameStat.getGameStat ()
Definition at line 23 of file GameStat.java.
References gamePlayer.guiItems.headsUpDisplay.GameStat.gameStatProperty().
double gamePlayer.guiItems.headsUpDisplay.GameStat.getStatValue ()
Definition at line 37 of file GameStat.java.
References gamePlayer.guiItems.headsUpDisplay.GameStat.statValueProperty().
Referenced by gamePlayer.mainClasses.managers.GuiManager.checkGold().
void gamePlayer.guiItems.headsUpDisplay.GameStat.setGameStat (String value)
Definition at line 19 of file GameStat.java.
References gamePlayer.guiItems.headsUpDisplay.GameStat.gameStatProperty().
Referenced by gamePlayer.mainClasses.managers.GuiManager.setUpHUD(), gamePlayer.mainClasses.managers.GuiManager.startMultiPlayerGame(), and gamePlayer.mainClasses.testGameManager.TestGameManager.testLoadingGuiHUD().
void gamePlayer.guiItems.headsUpDisplay.GameStat.setStatValue (double value)
Definition at line 33 of file GameStat.java.
References gamePlayer.guiItems.headsUpDisplay.GameStat.statValueProperty().
Referenced by gamePlayer.mainClasses.testGameManager.TestGameManager.testLoadingGuiHUD().
DoubleProperty gamePlayer.guiItems.headsUpDisplay.GameStat.statValueProperty ()
Definition at line 41 of file GameStat.java.
References gamePlayer.guiItems.headsUpDisplay.GameStat.statValue.
Referenced by gamePlayer.guiItems.headsUpDisplay.GameStat.getStatValue(), gamePlayer.guiItems.headsUpDisplay.GameStat.setStatValue(), gamePlayer.mainClasses.managers.GuiManager.setUpHUD(), and gamePlayer.mainClasses.managers.GuiManager.startMultiPlayerGame().
Member Data Documentation
StringProperty gamePlayer.guiItems.headsUpDisplay.GameStat.gameStat private
Definition at line 17 of file GameStat.java.
Referenced by gamePlayer.guiItems.headsUpDisplay.GameStat.gameStatProperty().
DoubleProperty gamePlayer.guiItems.headsUpDisplay.GameStat.statValue private
Definition at line 32 of file GameStat.java.
Referenced by gamePlayer.guiItems.headsUpDisplay.GameStat.statValueProperty().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItems/headsUpDisplay/GameStat.java