voogasalad_LosTorres: gameEngine.actors.behaviors.BaseDefendBehavior Class Reference
gameEngine.actors.behaviors.BaseDefendBehavior Class Reference abstract
Public Member Functions
double getHealth ()
void execute (BaseActor actor)
void setHealth (double d)
void gotHit (BaseActor actor, BaseProjectile p)
abstract void handleBullet (BaseProjectile p)
abstract void onDeath (BaseActor actor)
Public Member Functions inherited from gameEngine.actors.behaviors.IBehavior
IBehavior copy ()
String toString ()
Protected Attributes
List< Double > myList
double myHealth
double myInitialHealth
Package Functions
BaseDefendBehavior (List< Double > list)
BaseDefendBehavior (double health)
Private Member Functions
boolean checkTypes (BaseProjectile p, BaseActor a)
Detailed Description
Behavior that defines the defense of an actor
Author
Chase Malik, Timesh Patel
Definition at line 15 of file BaseDefendBehavior.java.
Constructor & Destructor Documentation
gameEngine.actors.behaviors.BaseDefendBehavior.BaseDefendBehavior (List< Double > list) package
Definition at line 20 of file BaseDefendBehavior.java.
References gameEngine.actors.behaviors.BaseDefendBehavior.myHealth.
gameEngine.actors.behaviors.BaseDefendBehavior.BaseDefendBehavior (double health) package
Definition at line 26 of file BaseDefendBehavior.java.
Member Function Documentation
boolean gameEngine.actors.behaviors.BaseDefendBehavior.checkTypes (BaseProjectile p, BaseActor a) private
Definition at line 76 of file BaseDefendBehavior.java.
References gameEngine.actors.ProjectileInfo.getEnemiesTypes(), gameEngine.actors.BaseProjectile.getInfo(), and gameEngine.actors.BaseActor.toString().
Referenced by gameEngine.actors.behaviors.BaseDefendBehavior.execute().
void gameEngine.actors.behaviors.BaseDefendBehavior.execute (BaseActor actor)
Execute method that executes the specific behavior on the given actor
Parameters
actor that is executed on
Implements gameEngine.actors.behaviors.IBehavior.
Definition at line 36 of file BaseDefendBehavior.java.
References gameEngine.actors.behaviors.BaseDefendBehavior.checkTypes(), gameEngine.actors.BaseActor.getNode(), gameEngine.actors.BaseActor.getProjectilesInRange(), and gameEngine.actors.behaviors.BaseDefendBehavior.gotHit().
double gameEngine.actors.behaviors.BaseDefendBehavior.getHealth ()
Definition at line 31 of file BaseDefendBehavior.java.
References gameEngine.actors.behaviors.BaseDefendBehavior.myHealth.
Referenced by gameEngine.actors.behaviors.EarthQuakeEffect.during(), gameEngine.actors.behaviors.DoTOnHit.during(), and gameEngine.actors.behaviors.AoEEffect.start().
void gameEngine.actors.behaviors.BaseDefendBehavior.gotHit (BaseActor actor, BaseProjectile p)
Definition at line 52 of file BaseDefendBehavior.java.
References gameEngine.actors.BaseActor.addDebuff(), gameEngine.actors.behaviors.IBehavior.copy(), gameEngine.actors.behaviors.IBehavior.execute(), gameEngine.actors.BaseProjectile.getInfo(), gameEngine.actors.ProjectileInfo.getOnHit(), gameEngine.actors.behaviors.BaseDefendBehavior.handleBullet(), and gameEngine.actors.behaviors.BaseDefendBehavior.onDeath().
Referenced by gameEngine.actors.behaviors.BaseDefendBehavior.execute().
abstract void gameEngine.actors.behaviors.BaseDefendBehavior.handleBullet (BaseProjectile p) abstract
Referenced by gameEngine.actors.behaviors.BaseDefendBehavior.gotHit().
abstract void gameEngine.actors.behaviors.BaseDefendBehavior.onDeath (BaseActor actor) abstract
Referenced by gameEngine.actors.behaviors.EarthQuakeEffect.during(), gameEngine.actors.behaviors.BaseDefendBehavior.gotHit(), and gameEngine.actors.behaviors.AoEEffect.start().
void gameEngine.actors.behaviors.BaseDefendBehavior.setHealth (double d)
Definition at line 45 of file BaseDefendBehavior.java.
Referenced by gameEngine.actors.behaviors.EarthQuakeEffect.during(), gameEngine.actors.behaviors.DoTOnHit.during(), and gameEngine.actors.behaviors.AoEEffect.start().
Member Data Documentation
double gameEngine.actors.behaviors.BaseDefendBehavior.myHealth protected
Definition at line 17 of file BaseDefendBehavior.java.
Referenced by gameEngine.actors.behaviors.BaseDefendBehavior.BaseDefendBehavior(), gameEngine.actors.behaviors.BaseDefendBehavior.getHealth(), gameEngine.actors.behaviors.PiercableDefense.handleBullet(), and gameEngine.actors.behaviors.SimpleDefense.handleBullet().
double gameEngine.actors.behaviors.BaseDefendBehavior.myInitialHealth protected
Definition at line 18 of file BaseDefendBehavior.java.
List<Double> gameEngine.actors.behaviors.BaseDefendBehavior.myList protected
Definition at line 16 of file BaseDefendBehavior.java.
Referenced by gameEngine.actors.behaviors.SimpleDefense.copy(), and gameEngine.actors.behaviors.PiercableDefense.copy().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/behaviors/BaseDefendBehavior.java