voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane Class Reference
gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane Class Reference
Public Member Functions
BuildingPane (Group group)
void drawLocation (Node component)
void drawPathComponent (Node component)
void refreshScreen ()
void removeComponentFromScreen (Node component)
void executeExitFunction ()
void executeEnterFunction ()
Static Public Attributes
static final double DRAW_SCREEN_WIDTH_RATIO = .80
static final double DRAW_SCREEN_WIDTH
Static Protected Attributes
static Group myGroup
Static Private Attributes
static final String BUILD_SCREEN_CSS_CLASS = "buildScreen"
Detailed Description
This BuildingPane is important. In the PathBuildingScene it defines a unique functionality or option. For instance, one option might be line drawing and another might be selection mode. In each of these cases, these panes act different and must implement their own on-click action. Notice that of the panes share a common group so that what is on the screen even when the panes switch.
Author
Austin Kyker
Definition at line 19 of file BuildingPane.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.BuildingPane (Group group)
Definition at line 27 of file BuildingPane.java.
Member Function Documentation
void gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.drawLocation (Node component)
Definition at line 34 of file BuildingPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.refreshScreen().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyEndingLocationsPane.addNewEndingLocation(), and gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane.addNewStartingLocation().
void gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.drawPathComponent (Node component)
Definition at line 39 of file BuildingPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.refreshScreen().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.LineDrawingPane.handleBuildScreenClick(), and gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.handleBuildScreenClick().
void gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.executeEnterFunction ()
Executed when building pane is selected and becomes currently selected pane. Default function is to do nothing. Overridden in CurveDrawingPane.
Definition at line 65 of file BuildingPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.setCurrentBuildingPane().
void gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.executeExitFunction ()
Executed when a new building pane is selected and the currently selected pane will no longer be selected. Default function is to do nothing. Overridden in CurveDrawingPane.
Definition at line 58 of file BuildingPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.setCurrentBuildingPane().
void gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.refreshScreen ()
Definition at line 44 of file BuildingPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.drawLocation(), gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.drawPathComponent(), and gameAuthoring.scenes.pathBuilding.PathBuildingScene.setCurrentBuildingPane().
void gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.removeComponentFromScreen (Node component)
Definition at line 49 of file BuildingPane.java.
Member Data Documentation
final String gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.BUILD_SCREEN_CSS_CLASS = "buildScreen" static private
Definition at line 24 of file BuildingPane.java.
final double gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.DRAW_SCREEN_WIDTH static
Initial value:
=
            AuthorController.SCREEN_WIDTH * DRAW_SCREEN_WIDTH_RATIO
Definition at line 22 of file BuildingPane.java.
Referenced by gameEngine.MainEngineManager.createGameSizedGridPane(), gameEngine.AI.GridPathFinder.getPath(), gamePlayer.guiItems.gameWorld.GameWorld.initialize(), gameAuthoring.scenes.pathBuilding.buildingPanes.PathBackgroundSelectionPane.PathBackgroundSelectionPane(), gameAuthoring.scenes.pathBuilding.PathBuildingScene.setBackground(), gameAuthoring.scenes.levelBuilding.LevelBuildingScene.setupLevelDisplay(), gameEngine.actors.behaviors.RangeAttack.shootActorFromActor(), and gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.TowerRegionsPane().
final double gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.DRAW_SCREEN_WIDTH_RATIO = .80 static
Definition at line 21 of file BuildingPane.java.
Group gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.myGroup static protected
Definition at line 25 of file BuildingPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.executeEnterFunction(), and gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.executeExitFunction().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/buildingPanes/BuildingPane.java