voogasalad_LosTorres: gameEngine.actors.behaviors.DoTOnHit Class Reference
gameEngine.actors.behaviors.DoTOnHit Class Reference
Public Member Functions
DoTOnHit (List< Double > list)
DoTOnHit (double duration, double damage)
DoTOnHit (double damage)
IBehavior copy ()
void during (BaseActor actor)
void start (BaseActor actor)
void end (BaseActor actor)
Public Member Functions inherited from gameEngine.actors.behaviors.BaseEffect
BaseEffect (double duration, double multiplier)
BaseEffect ()
BaseEffect (List< Double > list)
void execute (BaseActor actor)
abstract void during (BaseActor actor)
abstract void start (BaseActor actor)
abstract void end (BaseActor actor)
String toString ()
Private Attributes
double myDamage
Additional Inherited Members
Protected Attributes inherited from gameEngine.actors.behaviors.BaseEffect
List< Double > myList
String myString
Package Attributes inherited from gameEngine.actors.behaviors.BaseEffect
double myDuration
double myInitialDuration
Detailed Description
Definition at line 7 of file DoTOnHit.java.
Constructor & Destructor Documentation
gameEngine.actors.behaviors.DoTOnHit.DoTOnHit (List< Double > list)
Definition at line 9 of file DoTOnHit.java.
Referenced by gameEngine.actors.behaviors.DoTOnHit.copy().
gameEngine.actors.behaviors.DoTOnHit.DoTOnHit (double duration, double damage)
Definition at line 13 of file DoTOnHit.java.
gameEngine.actors.behaviors.DoTOnHit.DoTOnHit (double damage)
Definition at line 17 of file DoTOnHit.java.
Member Function Documentation
IBehavior gameEngine.actors.behaviors.DoTOnHit.copy ()
Returns a copy of the behavior, which allows for copying entire actors
Returns
copy of the behavior
Implements gameEngine.actors.behaviors.IBehavior.
Definition at line 22 of file DoTOnHit.java.
References gameEngine.actors.behaviors.DoTOnHit.DoTOnHit(), and gameEngine.actors.behaviors.BaseEffect.myList.
void gameEngine.actors.behaviors.DoTOnHit.during (BaseActor actor)
Definition at line 27 of file DoTOnHit.java.
References gameEngine.actors.BaseActor.getBehavior(), gameEngine.actors.behaviors.BaseDefendBehavior.getHealth(), gameEngine.actors.BaseActor.killed(), gameEngine.actors.behaviors.BaseEffect.myInitialDuration, and gameEngine.actors.behaviors.BaseDefendBehavior.setHealth().
void gameEngine.actors.behaviors.DoTOnHit.end (BaseActor actor)
Definition at line 44 of file DoTOnHit.java.
References gameEngine.actors.BaseActor.removeDebuff().
void gameEngine.actors.behaviors.DoTOnHit.start (BaseActor actor)
Definition at line 39 of file DoTOnHit.java.
Member Data Documentation
double gameEngine.actors.behaviors.DoTOnHit.myDamage private
Definition at line 8 of file DoTOnHit.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/behaviors/DoTOnHit.java