voogasalad_LosTorres: gameEngine.actors.behaviors.SlowEffect Class Reference
gameEngine.actors.behaviors.SlowEffect Class Reference
Public Member Functions
SlowEffect (double duration, double multiplier)
SlowEffect (double multiplier)
SlowEffect (List< Double > list)
IBehavior copy ()
void end (BaseActor actor)
void during (BaseActor actor)
void start (BaseActor actor)
Public Member Functions inherited from gameEngine.actors.behaviors.BaseEffect
BaseEffect (double duration, double multiplier)
BaseEffect ()
BaseEffect (List< Double > list)
void execute (BaseActor actor)
abstract void during (BaseActor actor)
abstract void start (BaseActor actor)
abstract void end (BaseActor actor)
String toString ()
Private Attributes
double myMultiplier
double myInitialSpeed
Additional Inherited Members
Protected Attributes inherited from gameEngine.actors.behaviors.BaseEffect
List< Double > myList
String myString
Package Attributes inherited from gameEngine.actors.behaviors.BaseEffect
double myDuration
double myInitialDuration
Detailed Description
Definition at line 6 of file SlowEffect.java.
Constructor & Destructor Documentation
gameEngine.actors.behaviors.SlowEffect.SlowEffect (double duration, double multiplier)
Definition at line 9 of file SlowEffect.java.
References gameEngine.actors.behaviors.BaseEffect.myString.
Referenced by gameEngine.actors.behaviors.SlowEffect.copy().
gameEngine.actors.behaviors.SlowEffect.SlowEffect (double multiplier)
Definition at line 15 of file SlowEffect.java.
gameEngine.actors.behaviors.SlowEffect.SlowEffect (List< Double > list)
Definition at line 18 of file SlowEffect.java.
Member Function Documentation
IBehavior gameEngine.actors.behaviors.SlowEffect.copy ()
Returns a copy of the behavior, which allows for copying entire actors
Returns
copy of the behavior
Implements gameEngine.actors.behaviors.IBehavior.
Definition at line 25 of file SlowEffect.java.
References gameEngine.actors.behaviors.BaseEffect.myList, and gameEngine.actors.behaviors.SlowEffect.SlowEffect().
void gameEngine.actors.behaviors.SlowEffect.during (BaseActor actor)
Definition at line 38 of file SlowEffect.java.
void gameEngine.actors.behaviors.SlowEffect.end (BaseActor actor)
Definition at line 31 of file SlowEffect.java.
References gameEngine.actors.BaseActor.getBehavior(), gameEngine.actors.BaseActor.removeDebuff(), and gameEngine.actors.behaviors.BaseMovementBehavior.setSpeed().
void gameEngine.actors.behaviors.SlowEffect.start (BaseActor actor)
Definition at line 42 of file SlowEffect.java.
References gameEngine.actors.BaseActor.getBehavior(), gameEngine.actors.behaviors.BaseMovementBehavior.getSpeed(), gameEngine.actors.behaviors.SlowEffect.myMultiplier, and gameEngine.actors.behaviors.BaseMovementBehavior.setSpeed().
Member Data Documentation
double gameEngine.actors.behaviors.SlowEffect.myInitialSpeed private
Definition at line 8 of file SlowEffect.java.
double gameEngine.actors.behaviors.SlowEffect.myMultiplier private
Definition at line 7 of file SlowEffect.java.
Referenced by gameEngine.actors.behaviors.SlowEffect.start().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/behaviors/SlowEffect.java