voogasalad_LosTorres: gameEngine.actors.behaviors.AoEAttack Class Reference
gameEngine.actors.behaviors.AoEAttack Class Reference
Public Member Functions
AoEAttack (List< Double > list)
IBehavior copy ()
Public Member Functions inherited from gameEngine.actors.behaviors.BaseAttack
BaseAttack (double attackSpeed)
BaseAttack (List< Double > list)
void execute (BaseActor actor)
void setAttackSpeed (int i)
String toString ()
double getRange ()
Protected Member Functions
void performAttack (BaseActor actor)
Protected Member Functions inherited from gameEngine.actors.behaviors.BaseAttack
boolean readyToShoot ()
abstract void performAttack (BaseActor actor)
Private Attributes
double myNumBullets
Additional Inherited Members
Protected Attributes inherited from gameEngine.actors.behaviors.BaseAttack
List< Double > myList
double myAttackSpeed
double myRange
int myCooldown
Static Protected Attributes inherited from gameEngine.actors.behaviors.BaseAttack
static final int READY_TO_SHOOT = 0
Detailed Description
Definition at line 11 of file AoEAttack.java.
Constructor & Destructor Documentation
gameEngine.actors.behaviors.AoEAttack.AoEAttack (List< Double > list)
Definition at line 14 of file AoEAttack.java.
Referenced by gameEngine.actors.behaviors.AoEAttack.copy().
Member Function Documentation
IBehavior gameEngine.actors.behaviors.AoEAttack.copy ()
Returns a copy of the behavior, which allows for copying entire actors
Returns
copy of the behavior
Implements gameEngine.actors.behaviors.IBehavior.
Definition at line 22 of file AoEAttack.java.
References gameEngine.actors.behaviors.AoEAttack.AoEAttack(), and gameEngine.actors.behaviors.BaseAttack.myList.
Referenced by gameEngine.actors.behaviors.AoEAttack.performAttack().
void gameEngine.actors.behaviors.AoEAttack.performAttack (BaseActor actor) protected
Definition at line 28 of file AoEAttack.java.
References gameEngine.actors.behaviors.AoEAttack.copy(), gameEngine.actors.BaseActor.getEnemiesInRange(), gameEngine.actors.BaseProjectile.getInfo(), gameEngine.actors.ProjectileInfo.getMove(), gameEngine.actors.BaseActor.getX(), gameEngine.actors.BaseActor.getY(), gameEngine.actors.behaviors.AoEAttack.myNumBullets, gameEngine.actors.behaviors.BaseAttack.myRange, and gameEngine.actors.behaviors.BaseMovementBehavior.setRoute().
Member Data Documentation
double gameEngine.actors.behaviors.AoEAttack.myNumBullets private
Definition at line 13 of file AoEAttack.java.
Referenced by gameEngine.actors.behaviors.AoEAttack.performAttack().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/behaviors/AoEAttack.java