voogasalad_LosTorres: utilities.JavaFXutilities.imageView.CenteredImageView Class Reference
utilities.JavaFXutilities.imageView.CenteredImageView Class Reference
Public Member Functions
double getXCenter ()
double getYCenter ()
void setXCenter (double x)
void setYCenter (double y)
Detailed Description
Definition at line 5 of file CenteredImageView.java.
Member Function Documentation
double utilities.JavaFXutilities.imageView.CenteredImageView.getXCenter ()
Definition at line 7 of file CenteredImageView.java.
Referenced by gameEngine.actors.BaseProjectile.getRange(), gameEngine.actors.RealActor.getRange(), gameEngine.actors.BaseActor.getX(), and gamePlayer.mainClasses.managers.GuiManager.selectTower().
double utilities.JavaFXutilities.imageView.CenteredImageView.getYCenter ()
Definition at line 11 of file CenteredImageView.java.
Referenced by gameEngine.actors.BaseProjectile.getRange(), gameEngine.actors.RealActor.getRange(), gameEngine.actors.BaseActor.getY(), and gamePlayer.mainClasses.managers.GuiManager.selectTower().
void utilities.JavaFXutilities.imageView.CenteredImageView.setXCenter (double x)
Definition at line 15 of file CenteredImageView.java.
Referenced by gameEngine.MainEngineManager.addTower(), gameEngine.actors.BaseActor.makeNode(), and gameEngine.actors.behaviors.BaseMovementBehavior.move().
void utilities.JavaFXutilities.imageView.CenteredImageView.setYCenter (double y)
Definition at line 19 of file CenteredImageView.java.
Referenced by gameEngine.MainEngineManager.addTower(), gameEngine.actors.BaseActor.makeNode(), and gameEngine.actors.behaviors.BaseMovementBehavior.move().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/JavaFXutilities/imageView/CenteredImageView.java