voogasalad_LosTorres: utilities.pathfinding.AStarTest.TestNode Class Reference
utilities.pathfinding.AStarTest.TestNode Class Reference
Public Member Functions
TestNode (int x, int y)
int getX ()
int getY ()
boolean equals (Object other)
String toString ()
Private Attributes
int myX
int myY
Detailed Description
Definition at line 55 of file AStarTest.java.
Constructor & Destructor Documentation
utilities.pathfinding.AStarTest.TestNode.TestNode (int x, int y)
Definition at line 60 of file AStarTest.java.
Referenced by utilities.pathfinding.AStarTest.TestNode.equals().
Member Function Documentation
boolean utilities.pathfinding.AStarTest.TestNode.equals (Object other)
Definition at line 74 of file AStarTest.java.
References utilities.pathfinding.AStarTest.TestNode.getX(), utilities.pathfinding.AStarTest.TestNode.getY(), and utilities.pathfinding.AStarTest.TestNode.TestNode().
int utilities.pathfinding.AStarTest.TestNode.getX ()
Definition at line 65 of file AStarTest.java.
References utilities.pathfinding.AStarTest.TestNode.myX.
Referenced by utilities.pathfinding.AStarTest.TestAStarFinder.breakTie(), utilities.pathfinding.AStarTest.TestNode.equals(), utilities.pathfinding.AStarTest.TestAStarFinder.getCost(), utilities.pathfinding.AStarTest.TestAStarFinder.getHeuristicValue(), and utilities.pathfinding.AStarTest.TestAStarFinder.getNeighbors().
int utilities.pathfinding.AStarTest.TestNode.getY ()
Definition at line 69 of file AStarTest.java.
References utilities.pathfinding.AStarTest.TestNode.myY.
Referenced by utilities.pathfinding.AStarTest.TestAStarFinder.breakTie(), utilities.pathfinding.AStarTest.TestNode.equals(), utilities.pathfinding.AStarTest.TestAStarFinder.getCost(), utilities.pathfinding.AStarTest.TestAStarFinder.getHeuristicValue(), and utilities.pathfinding.AStarTest.TestAStarFinder.getNeighbors().
String utilities.pathfinding.AStarTest.TestNode.toString ()
Definition at line 81 of file AStarTest.java.
References utilities.pathfinding.AStarTest.TestNode.myY.
Member Data Documentation
int utilities.pathfinding.AStarTest.TestNode.myX private
Definition at line 57 of file AStarTest.java.
Referenced by utilities.pathfinding.AStarTest.TestNode.getX().
int utilities.pathfinding.AStarTest.TestNode.myY private
Definition at line 58 of file AStarTest.java.
Referenced by utilities.pathfinding.AStarTest.TestNode.getY(), and utilities.pathfinding.AStarTest.TestNode.toString().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/pathfinding/AStarTest.java