voogasalad_LosTorres: gamePlayer.mainClasses.welcomeScreen.startingOptions.PlayerCountOptions Class Reference
gamePlayer.mainClasses.welcomeScreen.startingOptions.PlayerCountOptions Class Reference
Public Member Functions
PlayerCountOptions ()
Node getSinglePlayerOption ()
Node getMultiPlayerOption ()
Private Attributes
Button singlePlayerOption
Button multiPlayerOption
Additional Inherited Members
Protected Member Functions inherited from gamePlayer.mainClasses.welcomeScreen.startingOptions.Options
Button createOptionButton (ObjectProperty< String > objectProperty)
Detailed Description
Definition at line 8 of file PlayerCountOptions.java.
Constructor & Destructor Documentation
gamePlayer.mainClasses.welcomeScreen.startingOptions.PlayerCountOptions.PlayerCountOptions ()
Definition at line 12 of file PlayerCountOptions.java.
References gamePlayer.mainClasses.welcomeScreen.startingOptions.Options.createOptionButton(), utilities.multilanguage.MultiLanguageUtility.getStringProperty(), gamePlayer.mainClasses.guiBuilder.GuiText.MULTI_PLAYER, gamePlayer.mainClasses.guiBuilder.GuiConstants.MULTILANGUAGE, and gamePlayer.mainClasses.guiBuilder.GuiText.SINGLE_PLAYER.
Member Function Documentation
Node gamePlayer.mainClasses.welcomeScreen.startingOptions.PlayerCountOptions.getMultiPlayerOption ()
Definition at line 24 of file PlayerCountOptions.java.
References gamePlayer.mainClasses.welcomeScreen.startingOptions.PlayerCountOptions.multiPlayerOption.
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.init(), and gamePlayer.mainClasses.welcomeScreen.GameStartManager.initializeWelcomeScreen().
Node gamePlayer.mainClasses.welcomeScreen.startingOptions.PlayerCountOptions.getSinglePlayerOption ()
Definition at line 20 of file PlayerCountOptions.java.
References gamePlayer.mainClasses.welcomeScreen.startingOptions.PlayerCountOptions.singlePlayerOption.
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.init(), and gamePlayer.mainClasses.welcomeScreen.GameStartManager.initializeWelcomeScreen().
Member Data Documentation
Button gamePlayer.mainClasses.welcomeScreen.startingOptions.PlayerCountOptions.multiPlayerOption private
Definition at line 10 of file PlayerCountOptions.java.
Referenced by gamePlayer.mainClasses.welcomeScreen.startingOptions.PlayerCountOptions.getMultiPlayerOption().
Button gamePlayer.mainClasses.welcomeScreen.startingOptions.PlayerCountOptions.singlePlayerOption private
Definition at line 9 of file PlayerCountOptions.java.
Referenced by gamePlayer.mainClasses.welcomeScreen.startingOptions.PlayerCountOptions.getSinglePlayerOption().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/mainClasses/welcomeScreen/startingOptions/PlayerCountOptions.java