voogasalad_LosTorres: utilities.pathfinding.IPathFinder< T > Interface Template Reference
utilities.pathfinding.IPathFinder< T > Interface Template Reference
Public Member Functions
Number getCost (T beginningNode, T endingNode)
Iterable< T > getNeighbors (T node)
boolean isDestination (T node, T destinationNode)
List< T > findPath (T start, T destination)
int breakTie (T node, T other)
Detailed Description
Author
Duke Interface for finding a path from a certain node to a destination node. Can take in any data object as the generic.
Parameters
<T> Any object type.
Definition at line 13 of file IPathFinder.java.
Member Function Documentation
int utilities.pathfinding.IPathFinder< T >.breakTie (T node, T other)
Specifies the behavior for breaking ties when the cost values for getting to two nodes is the same. Should return something similar to Comparable's compareTo(other) method.
Parameters
node Node in question. In the case of a class implementing Comparable's compareTo(other), it would be the equivalent of this.
other The other node. In the case of a class implementing Comparable's compareTo(other), it would be the equivalent of the parameter.
Returns
Result of tie breaker.
Referenced by utilities.pathfinding.AStarPathFinder< T >.PQTuple.compareTo().
List<T> utilities.pathfinding.IPathFinder< T >.findPath (T start, T destination)
Finds the least cost path from the node specified by start to the one specified by destination
Parameters
start Starting node
destination Ending node
Returns
Path from start to destination in order.
Implemented in utilities.pathfinding.AStarPathFinder< T >.
Number utilities.pathfinding.IPathFinder< T >.getCost (T beginningNode, T endingNode)
Gets the cost of traveling from beginningNode to endingNode.
Parameters
beginningNode The beginning node in question
endingNode The ending node in question
Returns
Cost of traveling from beginningNode to endingNode
Referenced by utilities.pathfinding.AStarPathFinder< Point2D >.getAndCheckCost().
Iterable<T> utilities.pathfinding.IPathFinder< T >.getNeighbors (T node)
Gets the neighbors to which one can move to from the node specified in the parameter.
Parameters
node Node in question
Returns
A collection of neighboring nodes
Referenced by utilities.pathfinding.AStarPathFinder< Point2D >.findPath().
boolean utilities.pathfinding.IPathFinder< T >.isDestination (T node, T destinationNode)
Indicates whether a node is the destination node. In most cases, this method should use the equals method specified in the generic type
Parameters
node Node in question
destinationNode Destination node
Returns
Whether the node is the destination node.
Implemented in utilities.pathfinding.AStarPathFinder< T >.
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/pathfinding/IPathFinder.java