voogasalad_LosTorres: gameEngine.Data.TowerInfoObject Class Reference
gameEngine.Data.TowerInfoObject Class Reference
Public Member Functions
TowerInfoObject (String towerName, String imageLocation, int buyCost, int sellCost, double range)
void setNextTower (TowerInfoObject upgrade)
String getName ()
String getImageLocation ()
int getBuyCost ()
int getSellCost ()
double getRange ()
TowerInfoObject getMyUpgrade ()
Private Attributes
TowerInfoObject myUpgrade
String myName
String myImageLocation
int myBuyCost
int mySellCost
double myRange
Detailed Description
Definition at line 5 of file TowerInfoObject.java.
Constructor & Destructor Documentation
gameEngine.Data.TowerInfoObject.TowerInfoObject (String towerName, String imageLocation, int buyCost, int sellCost, double range)
Definition at line 14 of file TowerInfoObject.java.
Member Function Documentation
int gameEngine.Data.TowerInfoObject.getBuyCost ()
Definition at line 38 of file TowerInfoObject.java.
References gameEngine.Data.TowerInfoObject.myBuyCost.
Referenced by gameEngine.MainEngineManager.checkGold().
String gameEngine.Data.TowerInfoObject.getImageLocation ()
Definition at line 34 of file TowerInfoObject.java.
References gameEngine.Data.TowerInfoObject.myImageLocation.
Referenced by gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.setCurrentTower().
TowerInfoObject gameEngine.Data.TowerInfoObject.getMyUpgrade ()
Definition at line 50 of file TowerInfoObject.java.
References gameEngine.Data.TowerInfoObject.myUpgrade.
Referenced by gamePlayer.mainClasses.managers.GuiManager.makeTowerMap(), and gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.setCurrentTower().
String gameEngine.Data.TowerInfoObject.getName ()
Definition at line 30 of file TowerInfoObject.java.
References gameEngine.Data.TowerInfoObject.myName.
Referenced by gamePlayer.mainClasses.managers.GuiManager.makeTowerMap(), and gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.setCurrentTower().
double gameEngine.Data.TowerInfoObject.getRange ()
Definition at line 46 of file TowerInfoObject.java.
References gameEngine.Data.TowerInfoObject.myRange.
int gameEngine.Data.TowerInfoObject.getSellCost ()
Definition at line 42 of file TowerInfoObject.java.
References gameEngine.Data.TowerInfoObject.mySellCost.
Referenced by gamePlayer.guiItems.towerUpgrade.TowerUpgradePanel.setCurrentTower().
void gameEngine.Data.TowerInfoObject.setNextTower (TowerInfoObject upgrade)
Definition at line 26 of file TowerInfoObject.java.
Referenced by gameEngine.MainEngineManager.loadTowers().
Member Data Documentation
int gameEngine.Data.TowerInfoObject.myBuyCost private
Definition at line 10 of file TowerInfoObject.java.
Referenced by gameEngine.Data.TowerInfoObject.getBuyCost().
String gameEngine.Data.TowerInfoObject.myImageLocation private
Definition at line 9 of file TowerInfoObject.java.
Referenced by gameEngine.Data.TowerInfoObject.getImageLocation().
String gameEngine.Data.TowerInfoObject.myName private
Definition at line 8 of file TowerInfoObject.java.
Referenced by gameEngine.Data.TowerInfoObject.getName().
double gameEngine.Data.TowerInfoObject.myRange private
Definition at line 12 of file TowerInfoObject.java.
Referenced by gameEngine.Data.TowerInfoObject.getRange().
int gameEngine.Data.TowerInfoObject.mySellCost private
Definition at line 11 of file TowerInfoObject.java.
Referenced by gameEngine.Data.TowerInfoObject.getSellCost().
TowerInfoObject gameEngine.Data.TowerInfoObject.myUpgrade private
Definition at line 7 of file TowerInfoObject.java.
Referenced by gameEngine.Data.TowerInfoObject.getMyUpgrade().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/Data/TowerInfoObject.java