voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane Class Reference
gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane Class Reference
Public Member Functions
TowerRegionsPane (Group group, Path path)
void executeEnterFunction ()
void executeExitFunction ()
boolean[][] getBackendTowerRegions ()
Public Member Functions inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
BuildingPane (Group group)
void drawLocation (Node component)
void drawPathComponent (Node component)
void refreshScreen ()
void removeComponentFromScreen (Node component)
void executeExitFunction ()
void executeEnterFunction ()
Static Public Attributes
static final int NUM_COLS = 20
static final int NUM_ROWS = 20
Static Public Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
static final double DRAW_SCREEN_WIDTH_RATIO = .80
static final double DRAW_SCREEN_WIDTH
Private Member Functions
void suggestNoTowerPlacementOnPath ()
void generateBackendGrid ()
Private Attributes
GridPane myPane
Path myPath
boolean[][] myBackendGrid
boolean isRegionSelected
Additional Inherited Members
Static Protected Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
static Group myGroup
Detailed Description
A pane of tiles representing the locations towers will be able to be placed during the game. The user can select and deselect these locations by clicking or dragging over grid tiles.
Author
Austin Kyker
Definition at line 19 of file TowerRegionsPane.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.TowerRegionsPane (Group group, Path path)
Definition at line 31 of file TowerRegionsPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.DRAW_SCREEN_WIDTH, and gameAuthoring.mainclasses.AuthorController.SCREEN_HEIGHT.
Member Function Documentation
void gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.executeEnterFunction ()
Definition at line 41 of file TowerRegionsPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.myGroup, and gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.suggestNoTowerPlacementOnPath().
void gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.executeExitFunction ()
Definition at line 62 of file TowerRegionsPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.myGroup.
void gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.generateBackendGrid () private
Definition at line 67 of file TowerRegionsPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.NUM_COLS, and gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.NUM_ROWS.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.getBackendTowerRegions().
boolean [][] gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.getBackendTowerRegions ()
Definition at line 80 of file TowerRegionsPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.generateBackendGrid(), and gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.myBackendGrid.
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.handleFinishButtonClick().
void gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.suggestNoTowerPlacementOnPath () private
Definition at line 49 of file TowerRegionsPane.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.intersects(), gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.NUM_COLS, gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.NUM_ROWS, and gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.Tile.toggleSelection().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.executeEnterFunction().
Member Data Documentation
boolean gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.isRegionSelected private
Definition at line 29 of file TowerRegionsPane.java.
boolean [][] gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.myBackendGrid private
Definition at line 26 of file TowerRegionsPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.getBackendTowerRegions().
GridPane gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.myPane private
Definition at line 24 of file TowerRegionsPane.java.
Path gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.myPath private
Definition at line 25 of file TowerRegionsPane.java.
final int gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.NUM_COLS = 20 static
Definition at line 21 of file TowerRegionsPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.generateBackendGrid(), gameEngine.AI.GridPathFinder.getPath(), and gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.suggestNoTowerPlacementOnPath().
final int gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.NUM_ROWS = 20 static
Definition at line 22 of file TowerRegionsPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.generateBackendGrid(), gameEngine.AI.GridPathFinder.getPath(), and gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.suggestNoTowerPlacementOnPath().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/buildingPanes/towerRegions/TowerRegionsPane.java