voogasalad_LosTorres: gameAuthoring.scenes.actorBuildingScenes.ProjectilePane Class Reference
gameAuthoring.scenes.actorBuildingScenes.ProjectilePane Class Reference
Public Member Functions
ProjectilePane ()
VBox getNode ()
ProjectileInfo makeProjectileInfo (List< BaseEnemy > enemiesCanDamage)
void update (Observable arg0, Object arg1)
boolean isInfoValid ()
Private Attributes
VBox myContainer
DragAndDropImagePane myDropImgPane
ArrayList< BehaviorBuilder > myBehaviorBuilders
SliderContainer myDamageSlider
Static Private Attributes
static final int MAX_DAMAGE = 5
static final int RT_BOX_WIDTH = 120
static final String TITLE_CSS = "title"
static final String RIGHT_BOX_CSS = "projectileRightBox"
static final int LARGE_PADDING = 20
static final int SMALL_PADDING = 10
static final int PROJECTILE_IMG_HEIGHT = 80
static final int PROJECTILE_IMG_WIDTH = 100
static final String DRAG_N_DROP_CSS = "borderedPane"
static final String PROJECTILE_IMG_DIR
static final String PROJECTILE_BEHAVIORS_XML
Detailed Description
Definition at line 26 of file ProjectilePane.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.ProjectilePane ()
Definition at line 46 of file ProjectilePane.java.
References gameAuthoring.mainclasses.Constants.DAMAGE, utilities.multilanguage.MultiLanguageUtility.getInstance(), utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.getPane(), utilities.multilanguage.MultiLanguageUtility.getStringProperty(), gameAuthoring.mainclasses.Constants.PROJECTILE, and gameAuthoring.mainclasses.Constants.SM_PADDING.
Member Function Documentation
VBox gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.getNode ()
Definition at line 86 of file ProjectilePane.java.
References gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.myContainer.
Referenced by gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.configureAndDisplayRightPane().
boolean gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.isInfoValid ()
Definition at line 108 of file ProjectilePane.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.actorSpecificFieldsValid().
ProjectileInfo gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.makeProjectileInfo (List< BaseEnemy > enemiesCanDamage)
Definition at line 90 of file ProjectilePane.java.
References gameAuthoring.scenes.actorBuildingScenes.behaviorBuilders.BehaviorMapBuilder.buildMap(), utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane.getImagePath(), and utilities.JavaFXutilities.slider.SliderContainer.getSliderValue().
Referenced by gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.makeNewActor().
void gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.update (Observable arg0, Object arg1)
Called when Projectile image is dragged in.
Definition at line 104 of file ProjectilePane.java.
References utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.getPane().
Member Data Documentation
final String gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.DRAG_N_DROP_CSS = "borderedPane" static private
Definition at line 36 of file ProjectilePane.java.
final int gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.LARGE_PADDING = 20 static private
Definition at line 32 of file ProjectilePane.java.
final int gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.MAX_DAMAGE = 5 static private
Definition at line 28 of file ProjectilePane.java.
ArrayList<BehaviorBuilder> gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.myBehaviorBuilders private
Definition at line 43 of file ProjectilePane.java.
VBox gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.myContainer private
Definition at line 41 of file ProjectilePane.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.getNode().
SliderContainer gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.myDamageSlider private
Definition at line 44 of file ProjectilePane.java.
DragAndDropImagePane gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.myDropImgPane private
Definition at line 42 of file ProjectilePane.java.
final String gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.PROJECTILE_BEHAVIORS_XML static private
Initial value:
=
            "./src/gameAuthoring/Resources/actorBehaviors/ProjectileBehaviors.xml"
Definition at line 39 of file ProjectilePane.java.
final String gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.PROJECTILE_IMG_DIR static private
Initial value:
=
            AuthorController.gameDir + "projectileImages/"
Definition at line 37 of file ProjectilePane.java.
final int gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.PROJECTILE_IMG_HEIGHT = 80 static private
Definition at line 34 of file ProjectilePane.java.
final int gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.PROJECTILE_IMG_WIDTH = 100 static private
Definition at line 35 of file ProjectilePane.java.
final String gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.RIGHT_BOX_CSS = "projectileRightBox" static private
Definition at line 31 of file ProjectilePane.java.
final int gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.RT_BOX_WIDTH = 120 static private
Definition at line 29 of file ProjectilePane.java.
final int gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.SMALL_PADDING = 10 static private
Definition at line 33 of file ProjectilePane.java.
final String gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.TITLE_CSS = "title" static private
Definition at line 30 of file ProjectilePane.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/actorBuildingScenes/ProjectilePane.java