voogasalad_LosTorres: gameAuthoring.scenes.levelBuilding.LevelDisplayCell Class Reference
gameAuthoring.scenes.levelBuilding.LevelDisplayCell Class Reference
Public Member Functions
LevelDisplayCell (List< BaseEnemy > baseEnemies, int levelNum, Pane pane)
BaseLevel generateLevel ()
boolean isUserInputValid ()
Private Member Functions
HBox createEnemiesBox ()
VBox createLevelInfoBox ()
boolean isAllEnemyFieldsValid ()
Private Attributes
List< BaseEnemy > myEnemies
int myLevelNum
Map< BaseEnemy, NumericalTextField > enemyToEnemyCountMap
NumericalTextField myLevelDurationField
boolean myEngineInstantiatedFlag
MainEngineManager myEngineManager
Static Private Attributes
static final String LVL_CONTAINER_CLASS = "levelContainer"
static final int SPACE_BTW_LEVEL_INFO_AND_ENEMIES = 50
static final int TEXT_FIELD_WIDTH = 50
static final double FIT_SIZE = 80
static final int GENERAL_PADDING = 10
static final String PLAYLEVELBUTTON_IMG_PATH
Detailed Description
Definition at line 23 of file LevelDisplayCell.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.levelBuilding.LevelDisplayCell.LevelDisplayCell (List< BaseEnemy > baseEnemies, int levelNum, Pane pane)
Definition at line 40 of file LevelDisplayCell.java.
References gameAuthoring.scenes.levelBuilding.LevelDisplayCell.createEnemiesBox(), gameAuthoring.scenes.levelBuilding.LevelDisplayCell.createLevelInfoBox(), gameAuthoring.scenes.levelBuilding.LevelDisplayCell.generateLevel(), gameEngine.MainEngineManager.isRunning(), gameEngine.MainEngineManager.loadAuthoringLevel(), and gameEngine.MainEngineManager.resume().
Member Function Documentation
HBox gameAuthoring.scenes.levelBuilding.LevelDisplayCell.createEnemiesBox () private
Definition at line 68 of file LevelDisplayCell.java.
References utilities.JavaFXutilities.imageView.StringToImageViewConverter.getImageView(), and gameAuthoring.mainclasses.Constants.SMALLEST_PADDING.
Referenced by gameAuthoring.scenes.levelBuilding.LevelDisplayCell.LevelDisplayCell().
VBox gameAuthoring.scenes.levelBuilding.LevelDisplayCell.createLevelInfoBox () private
Definition at line 89 of file LevelDisplayCell.java.
References utilities.multilanguage.MultiLanguageUtility.getInstance(), utilities.multilanguage.MultiLanguageUtility.getStringProperty(), gameAuthoring.mainclasses.Constants.MED_PADDING, gameAuthoring.mainclasses.Constants.SECONDS, and gameAuthoring.mainclasses.Constants.SM_PADDING.
Referenced by gameAuthoring.scenes.levelBuilding.LevelDisplayCell.LevelDisplayCell().
BaseLevel gameAuthoring.scenes.levelBuilding.LevelDisplayCell.generateLevel ()
Definition at line 105 of file LevelDisplayCell.java.
References gameEngine.levels.BaseLevel.addEnemyCountPair(), utilities.JavaFXutilities.numericalTextFields.NumericalTextField.getNumber(), and gameEngine.levels.BaseLevel.setDuration().
Referenced by gameAuthoring.scenes.levelBuilding.LevelDisplayCell.LevelDisplayCell().
boolean gameAuthoring.scenes.levelBuilding.LevelDisplayCell.isAllEnemyFieldsValid () private
Definition at line 120 of file LevelDisplayCell.java.
Referenced by gameAuthoring.scenes.levelBuilding.LevelDisplayCell.isUserInputValid().
boolean gameAuthoring.scenes.levelBuilding.LevelDisplayCell.isUserInputValid ()
Definition at line 115 of file LevelDisplayCell.java.
References utilities.JavaFXutilities.numericalTextFields.NumericalTextField.getNumber(), gameAuthoring.scenes.levelBuilding.LevelDisplayCell.isAllEnemyFieldsValid(), and utilities.JavaFXutilities.numericalTextFields.NumericalTextField.isValueEntered().
Member Data Documentation
Map<BaseEnemy, NumericalTextField> gameAuthoring.scenes.levelBuilding.LevelDisplayCell.enemyToEnemyCountMap private
Definition at line 35 of file LevelDisplayCell.java.
final double gameAuthoring.scenes.levelBuilding.LevelDisplayCell.FIT_SIZE = 80 static private
Definition at line 28 of file LevelDisplayCell.java.
final int gameAuthoring.scenes.levelBuilding.LevelDisplayCell.GENERAL_PADDING = 10 static private
Definition at line 29 of file LevelDisplayCell.java.
final String gameAuthoring.scenes.levelBuilding.LevelDisplayCell.LVL_CONTAINER_CLASS = "levelContainer" static private
Definition at line 25 of file LevelDisplayCell.java.
List<BaseEnemy> gameAuthoring.scenes.levelBuilding.LevelDisplayCell.myEnemies private
Definition at line 33 of file LevelDisplayCell.java.
boolean gameAuthoring.scenes.levelBuilding.LevelDisplayCell.myEngineInstantiatedFlag private
Definition at line 37 of file LevelDisplayCell.java.
MainEngineManager gameAuthoring.scenes.levelBuilding.LevelDisplayCell.myEngineManager private
Definition at line 38 of file LevelDisplayCell.java.
NumericalTextField gameAuthoring.scenes.levelBuilding.LevelDisplayCell.myLevelDurationField private
Definition at line 36 of file LevelDisplayCell.java.
int gameAuthoring.scenes.levelBuilding.LevelDisplayCell.myLevelNum private
Definition at line 34 of file LevelDisplayCell.java.
final String gameAuthoring.scenes.levelBuilding.LevelDisplayCell.PLAYLEVELBUTTON_IMG_PATH static private
Initial value:
=
            "gameAuthoring/scenes/levelBuilding/PlayLevelButton.png"
Definition at line 30 of file LevelDisplayCell.java.
final int gameAuthoring.scenes.levelBuilding.LevelDisplayCell.SPACE_BTW_LEVEL_INFO_AND_ENEMIES = 50 static private
Definition at line 26 of file LevelDisplayCell.java.
final int gameAuthoring.scenes.levelBuilding.LevelDisplayCell.TEXT_FIELD_WIDTH = 50 static private
Definition at line 27 of file LevelDisplayCell.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/levelBuilding/LevelDisplayCell.java