voogasalad_LosTorres: gamePlayer.mainClasses.managers.WelcomeManager Class Reference
gamePlayer.mainClasses.managers.WelcomeManager Class Reference
Public Member Functions
WelcomeManager (Stage stage)
void init ()
void newGame ()
void startGame (File file)
void registerWelcomeNavigator (WelcomeNavigator navigator)
void joinMultiPlayerGame ()
void startSinglePlayerGame (String directoryPath)
Private Member Functions
void startSinglePlayerGameChooser ()
void startMultiPlayerGameChooser ()
void startMultiPlayerOptions ()
void startMultiPlayerGame (String directoryPath)
void pollEngineForMultiPlayerReadiness (GuiManager manager, Timeline timeline, String directoryPath)
ImageView getImageFromPath (String imagePath, double width, double height)
void addBackgroundImage ()
Private Attributes
XMLParser myParser
WelcomeNavigator navigator
Stage myStage
Group myGroup
String gameTypeBeingChosen
Static Private Attributes
static String guiBuilderPropertiesPath = "./src/gamePlayer/properties/welcome/WelcomeBuilderProperties.XML"
Detailed Description
Definition at line 26 of file WelcomeManager.java.
Constructor & Destructor Documentation
gamePlayer.mainClasses.managers.WelcomeManager.WelcomeManager (Stage stage)
Definition at line 35 of file WelcomeManager.java.
Member Function Documentation
void gamePlayer.mainClasses.managers.WelcomeManager.addBackgroundImage () private
Definition at line 135 of file WelcomeManager.java.
References utilities.XMLParsing.XMLParser.getDimension(), gamePlayer.mainClasses.managers.WelcomeManager.getImageFromPath(), and utilities.XMLParsing.XMLParser.getValuesFromTag().
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.init().
ImageView gamePlayer.mainClasses.managers.WelcomeManager.getImageFromPath (String imagePath, double width, double height) private
Definition at line 129 of file WelcomeManager.java.
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.addBackgroundImage().
void gamePlayer.mainClasses.managers.WelcomeManager.init ()
Definition at line 40 of file WelcomeManager.java.
References gamePlayer.mainClasses.managers.WelcomeManager.addBackgroundImage(), gamePlayer.mainClasses.guiBuilder.GuiBuilder.build(), gamePlayer.mainClasses.guiBuilder.GuiConstants.DYNAMIC_SIZING, gamePlayer.mainClasses.guiBuilder.GuiBuilder.getInstance(), gamePlayer.mainClasses.welcomeScreen.startingOptions.PlayerCountOptions.getMultiPlayerOption(), gamePlayer.mainClasses.welcomeScreen.startingOptions.PlayerCountOptions.getSinglePlayerOption(), and gamePlayer.guiItems.welcome.WelcomeNavigator.setContent().
void gamePlayer.mainClasses.managers.WelcomeManager.joinMultiPlayerGame ()
Definition at line 70 of file WelcomeManager.java.
References gamePlayer.mainClasses.managers.GuiManager.joinMultiPlayerGame().
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.startMultiPlayerOptions().
void gamePlayer.mainClasses.managers.WelcomeManager.newGame ()
Definition at line 53 of file WelcomeManager.java.
References gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_MANAGER, and gamePlayer.mainClasses.managers.GuiManager.init().
void gamePlayer.mainClasses.managers.WelcomeManager.pollEngineForMultiPlayerReadiness (GuiManager manager, Timeline timeline, String directoryPath) private
Definition at line 121 of file WelcomeManager.java.
References gamePlayer.mainClasses.managers.GuiManager.multiPlayerGameIsReady(), and gamePlayer.mainClasses.managers.GuiManager.startMultiPlayerGame().
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.startMultiPlayerGame().
void gamePlayer.mainClasses.managers.WelcomeManager.registerWelcomeNavigator (WelcomeNavigator navigator)
Implements gamePlayer.guiItemsListeners.NavigatorListener.
Definition at line 66 of file WelcomeManager.java.
References gamePlayer.mainClasses.managers.WelcomeManager.navigator.
void gamePlayer.mainClasses.managers.WelcomeManager.startGame (File file)
Definition at line 57 of file WelcomeManager.java.
References gamePlayer.mainClasses.guiBuilder.GuiConstants.MULTI_PLAYER_GAME, gamePlayer.mainClasses.guiBuilder.GuiConstants.SINGLE_PLAYER_GAME, gamePlayer.mainClasses.managers.WelcomeManager.startMultiPlayerGame(), and gamePlayer.mainClasses.managers.WelcomeManager.startSinglePlayerGame().
void gamePlayer.mainClasses.managers.WelcomeManager.startMultiPlayerGame (String directoryPath) private
Definition at line 104 of file WelcomeManager.java.
References utilities.multilanguage.MultiLanguageUtility.getStringProperty(), gamePlayer.mainClasses.guiBuilder.GuiConstants.MULTILANGUAGE, gamePlayer.mainClasses.managers.WelcomeManager.pollEngineForMultiPlayerReadiness(), gamePlayer.mainClasses.managers.GuiManager.prepareMultiPlayerGame(), gamePlayer.guiItems.welcome.WelcomeNavigator.setContent(), and gamePlayer.mainClasses.guiBuilder.GuiText.WAITING_FOR_CHALLENGER.
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.startGame().
void gamePlayer.mainClasses.managers.WelcomeManager.startMultiPlayerGameChooser () private
Definition at line 82 of file WelcomeManager.java.
References gamePlayer.mainClasses.guiBuilder.GuiConstants.MULTI_PLAYER_GAME, gamePlayer.mainClasses.guiBuilder.GuiConstants.MULTI_PLAYER_GAMES_DIRECTORY, and gamePlayer.guiItems.welcome.WelcomeNavigator.setContent().
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.startMultiPlayerOptions().
void gamePlayer.mainClasses.managers.WelcomeManager.startMultiPlayerOptions () private
Definition at line 89 of file WelcomeManager.java.
References gamePlayer.mainClasses.welcomeScreen.startingOptions.MultiPlayerOptions.getJoinGameOption(), gamePlayer.mainClasses.welcomeScreen.startingOptions.MultiPlayerOptions.getNewGameOption(), gamePlayer.mainClasses.managers.WelcomeManager.joinMultiPlayerGame(), gamePlayer.guiItems.welcome.WelcomeNavigator.setContent(), and gamePlayer.mainClasses.managers.WelcomeManager.startMultiPlayerGameChooser().
void gamePlayer.mainClasses.managers.WelcomeManager.startSinglePlayerGame (String directoryPath)
Definition at line 98 of file WelcomeManager.java.
References gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_MANAGER, gamePlayer.mainClasses.managers.GuiManager.init(), and gamePlayer.mainClasses.managers.GuiManager.startSinglePlayerGame().
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.startGame().
void gamePlayer.mainClasses.managers.WelcomeManager.startSinglePlayerGameChooser () private
Definition at line 75 of file WelcomeManager.java.
References gamePlayer.guiItems.welcome.WelcomeNavigator.setContent(), gamePlayer.mainClasses.guiBuilder.GuiConstants.SINGLE_PLAYER_GAME, and gamePlayer.mainClasses.guiBuilder.GuiConstants.SINGLE_PLAYER_GAMES_DIRECTORY.
Member Data Documentation
String gamePlayer.mainClasses.managers.WelcomeManager.gameTypeBeingChosen private
Definition at line 33 of file WelcomeManager.java.
String gamePlayer.mainClasses.managers.WelcomeManager.guiBuilderPropertiesPath = "./src/gamePlayer/properties/welcome/WelcomeBuilderProperties.XML" static private
Definition at line 28 of file WelcomeManager.java.
Group gamePlayer.mainClasses.managers.WelcomeManager.myGroup private
Definition at line 32 of file WelcomeManager.java.
XMLParser gamePlayer.mainClasses.managers.WelcomeManager.myParser private
Definition at line 29 of file WelcomeManager.java.
Stage gamePlayer.mainClasses.managers.WelcomeManager.myStage private
Definition at line 31 of file WelcomeManager.java.
WelcomeNavigator gamePlayer.mainClasses.managers.WelcomeManager.navigator private
Definition at line 30 of file WelcomeManager.java.
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.registerWelcomeNavigator().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/mainClasses/managers/WelcomeManager.java