voogasalad_LosTorres: gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar Class Reference
gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar Class Reference
Public Member Functions
void initialize (Dimension2D containerSize)
Node getNode ()
Private Member Functions
void initializeMenus ()
Menu createMenu (String menuName)
Private Attributes
XMLParser myParser
MenuBar myMenuBar
Dimension2D myMenuBarSize
Additional Inherited Members
Static Public Attributes inherited from gamePlayer.guiItems.GuiItem
static String myPropertiesPath = "guiItems/"
Detailed Description
This GuiItem initializes and manages the menu bar
Author
allankiplagat
Definition at line 25 of file VoogaMenuBar.java.
Member Function Documentation
Menu gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar.createMenu (String menuName) private
Definition at line 57 of file VoogaMenuBar.java.
References utilities.XMLParsing.XMLParser.getValuesFromTag(), and gamePlayer.guiItems.voogaMenuBar.VoogaMenuItem.initialize().
Referenced by gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar.initializeMenus().
Node gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 71 of file VoogaMenuBar.java.
References gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar.myMenuBar.
void gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 31 of file VoogaMenuBar.java.
References utilities.XMLParsing.XMLParser.getDimension(), gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_ELEMENT_PROPERTIES_PATH, gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar.initializeMenus(), and gamePlayer.guiItems.GuiItem.myPropertiesPath.
void gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar.initializeMenus () private
Definition at line 50 of file VoogaMenuBar.java.
References gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar.createMenu(), gamePlayer.mainClasses.guiBuilder.GuiText.FILE, utilities.multilanguage.MultiLanguageUtility.getStringProperty(), and gamePlayer.mainClasses.guiBuilder.GuiConstants.MULTILANGUAGE.
Referenced by gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar.initialize().
Member Data Documentation
MenuBar gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar.myMenuBar private
Definition at line 27 of file VoogaMenuBar.java.
Referenced by gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar.getNode().
Dimension2D gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar.myMenuBarSize private
Definition at line 28 of file VoogaMenuBar.java.
XMLParser gamePlayer.guiItems.voogaMenuBar.VoogaMenuBar.myParser private
Definition at line 26 of file VoogaMenuBar.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItems/voogaMenuBar/VoogaMenuBar.java