voogasalad_LosTorres: utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane Class Reference
utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane Class Reference abstract
Public Member Functions
DragAndDropImagePane (double width, double height)
ImageView getImageView ()
String getImagePath ()
void setHeight (double height)
void displayImage ()
boolean hasFileBeenDropped ()
Public Member Functions inherited from utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane
DragAndDropFilePane (double width, double height, String[] validExtensions)
Pane getPane ()
void reset ()
Protected Attributes
ImageView myImageView
File myFile
Protected Attributes inherited from utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane
VBox myContainer
VBox myDragAndDropPane
File myFile
Additional Inherited Members
Protected Member Functions inherited from utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane
abstract void actOnFile (File file)
Detailed Description
Definition at line 10 of file DragAndDropImagePane.java.
Constructor & Destructor Documentation
utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane.DragAndDropImagePane (double width, double height)
Definition at line 15 of file DragAndDropImagePane.java.
Member Function Documentation
void utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane.displayImage ()
Definition at line 35 of file DragAndDropImagePane.java.
References utilities.JavaFXutilities.imageView.StringToImageViewConverter.getImageView(), utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.myContainer, and utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.myDragAndDropPane.
Referenced by utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropNoCopyImagePane.actOnFile(), and utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropCopyImagePane.actOnFile().
String utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane.getImagePath ()
Definition at line 24 of file DragAndDropImagePane.java.
Referenced by gameAuthoring.scenes.actorBuildingScenes.ProjectilePane.makeProjectileInfo().
ImageView utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane.getImageView ()
Definition at line 20 of file DragAndDropImagePane.java.
References utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane.myImageView.
boolean utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane.hasFileBeenDropped ()
Definition at line 45 of file DragAndDropImagePane.java.
References gameAuthoring.mainclasses.Constants.NO_PROJECTILE_IMG.
void utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane.setHeight (double height)
Definition at line 28 of file DragAndDropImagePane.java.
References utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropFilePane.myContainer.
Referenced by gameAuthoring.scenes.actorBuildingScenes.TowerBuildingScene.configureAndDisplayRightPane().
Member Data Documentation
File utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane.myFile protected
Definition at line 13 of file DragAndDropImagePane.java.
Referenced by utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropNoCopyImagePane.actOnFile(), and utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropCopyImagePane.actOnFile().
ImageView utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane.myImageView protected
Definition at line 12 of file DragAndDropImagePane.java.
Referenced by utilities.JavaFXutilities.DragAndDropFilePanes.imagePanes.DragAndDropImagePane.getImageView().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/JavaFXutilities/DragAndDropFilePanes/imagePanes/DragAndDropImagePane.java