voogasalad_LosTorres: gameEngine.actors.behaviors.EnemyHomingMovement Class Reference
gameEngine.actors.behaviors.EnemyHomingMovement Class Reference
Public Member Functions
void execute (BaseActor actor)
IBehavior copy ()
Public Member Functions inherited from gameEngine.actors.behaviors.BaseMovementBehavior
BaseMovementBehavior (double speed)
BaseMovementBehavior (double speed, BackendRoute route)
double getSpeed ()
void setSpeed (double speed)
double getRemainingDistance ()
void setRoute (BackendRoute route)
String toString ()
Package Functions
EnemyHomingMovement (List< Double > list)
Package Functions inherited from gameEngine.actors.behaviors.BaseMovementBehavior
BaseMovementBehavior (List< Double > list)
Private Attributes
BaseActor myHomedEnemy
boolean myEnemyFound
Additional Inherited Members
Protected Member Functions inherited from gameEngine.actors.behaviors.BaseMovementBehavior
void move (BaseActor a, Point2D point)
void moveTowards (BaseActor a, Point2D current, Point2D target)
void findNextTarget (BaseActor actor, List< Point2D > route)
Protected Attributes inherited from gameEngine.actors.behaviors.BaseMovementBehavior
List< Double > myList
String myString
List< VisibilityPoint > myRoute
double mySpeed
double myRemainingDistance
int myIndex
Detailed Description
Definition at line 8 of file EnemyHomingMovement.java.
Constructor & Destructor Documentation
gameEngine.actors.behaviors.EnemyHomingMovement.EnemyHomingMovement (List< Double > list) package
Definition at line 13 of file EnemyHomingMovement.java.
Referenced by gameEngine.actors.behaviors.EnemyHomingMovement.copy().
Member Function Documentation
IBehavior gameEngine.actors.behaviors.EnemyHomingMovement.copy ()
Returns a copy of the behavior, which allows for copying entire actors
Returns
copy of the behavior
Implements gameEngine.actors.behaviors.IBehavior.
Definition at line 50 of file EnemyHomingMovement.java.
References gameEngine.actors.behaviors.EnemyHomingMovement.EnemyHomingMovement(), and gameEngine.actors.behaviors.BaseMovementBehavior.myList.
void gameEngine.actors.behaviors.EnemyHomingMovement.execute (BaseActor actor)
Execute method that executes the specific behavior on the given actor
Parameters
actor that is executed on
Implements gameEngine.actors.behaviors.IBehavior.
Definition at line 20 of file EnemyHomingMovement.java.
References gameEngine.actors.BaseActor.getEnemiesInRange(), gameEngine.actors.BaseActor.getNode(), gameEngine.actors.BaseActor.getX(), gameEngine.actors.BaseActor.getY(), gameEngine.actors.BaseActor.isDead(), gameEngine.actors.BaseActor.killed(), gameEngine.actors.behaviors.BaseMovementBehavior.move(), gameEngine.actors.behaviors.BaseMovementBehavior.moveTowards(), and gameEngine.actors.behaviors.BaseMovementBehavior.myRoute.
Member Data Documentation
boolean gameEngine.actors.behaviors.EnemyHomingMovement.myEnemyFound private
Definition at line 11 of file EnemyHomingMovement.java.
BaseActor gameEngine.actors.behaviors.EnemyHomingMovement.myHomedEnemy private
Definition at line 10 of file EnemyHomingMovement.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/behaviors/EnemyHomingMovement.java