voogasalad_LosTorres: gameEngine.actors.BaseTower Class Reference
gameEngine.actors.BaseTower Class Reference
Public Member Functions
BaseTower (Map< String, IBehavior > behaviors, String image, String name, double range, int buyCost, int sellCost, ProjectileInfo projectile)
BaseActor copy ()
int getBuyCost ()
int getSellCost ()
Public Member Functions inherited from gameEngine.actors.RealActor
RealActor (Map< String, IBehavior > behaviors, String image, String name, double range)
RealActor (Map< String, IBehavior > behaviors, String image, String name, double range, ProjectileInfo projectile)
void update (InformationInterface info)
ProjectileInfo getProjectile ()
void spawnProjectile (BaseActor projectile)
Node getRange ()
abstract BaseActor copy ()
Public Member Functions inherited from gameEngine.actors.BaseActor
BaseActor ()
BaseActor (Map< String, IBehavior > behaviors, String imageName, String name, double range)
void update (InformationInterface info)
boolean addDebuff (IBehavior debuff)
void removeDebuff (IBehavior debuff)
void makeNode (Point2D point)
IBehavior getBehavior (String s)
String toString ()
double getX ()
double getY ()
CenteredImageView getNode ()
String getImagePath ()
abstract Node getRange ()
double getRangeProperty ()
List< BaseActor > getEnemiesInRange (double range)
List< BaseActor > getTowersInRange (double range)
List< BaseActor > getProjectilesInRange (double range)
InformationInterface getInfoInterface ()
Collection< Class<?extends BaseActor > > getTypes ()
void setRange (double d)
void died ()
boolean isDead ()
void changeAndNotify (UpdateObject o)
void killed ()
Protected Member Functions
int[] getSize ()
Protected Member Functions inherited from gameEngine.actors.BaseActor
void makeNode ()
abstract int[] getSize ()
Map< String, IBehavior > copyBehaviors ()
Private Attributes
int myBuyCost
int mySellCost
Additional Inherited Members
Protected Attributes inherited from gameEngine.actors.RealActor
ProjectileInfo myProjectile
Protected Attributes inherited from gameEngine.actors.BaseActor
Map< String, IBehavior > myBehaviors
String myName
transient CenteredImageView myNode
transient InformationInterface myInfo
double myRange
int myBounty
String myImagePath
transient Set< Class<?extends BaseActor > > myTypes
boolean myIsRemovable
Map< String, IBehavior > myDebuffs
Set< IBehavior > myDebuffsToRemove
Detailed Description
Definition at line 7 of file BaseTower.java.
Constructor & Destructor Documentation
gameEngine.actors.BaseTower.BaseTower (Map< String, IBehavior > behaviors, String image, String name, double range, int buyCost, int sellCost, ProjectileInfo projectile)
Definition at line 12 of file BaseTower.java.
Referenced by gameEngine.actors.BaseTower.copy().
Member Function Documentation
BaseActor gameEngine.actors.BaseTower.copy ()
Definition at line 29 of file BaseTower.java.
References gameEngine.actors.BaseTower.BaseTower(), gameEngine.actors.BaseActor.copyBehaviors(), gameEngine.actors.BaseActor.myImagePath, gameEngine.actors.BaseActor.myName, gameEngine.actors.RealActor.myProjectile, and gameEngine.actors.BaseActor.myRange.
Referenced by gameEngine.MainEngineManager.addTower().
int gameEngine.actors.BaseTower.getBuyCost ()
Definition at line 34 of file BaseTower.java.
References gameEngine.actors.BaseTower.myBuyCost.
int gameEngine.actors.BaseTower.getSellCost ()
Definition at line 38 of file BaseTower.java.
References gameEngine.actors.BaseTower.mySellCost.
int [] gameEngine.actors.BaseTower.getSize () protected
Definition at line 24 of file BaseTower.java.
Member Data Documentation
int gameEngine.actors.BaseTower.myBuyCost private
Definition at line 9 of file BaseTower.java.
Referenced by gameEngine.actors.BaseTower.getBuyCost().
int gameEngine.actors.BaseTower.mySellCost private
Definition at line 10 of file BaseTower.java.
Referenced by gameEngine.actors.BaseTower.getSellCost().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/BaseTower.java