voogasalad_LosTorres: gameAuthoring.scenes.WelcomeScene Class Reference
gameAuthoring.scenes.WelcomeScene Class Reference
Public Member Functions
WelcomeScene ()
Scene getScene ()
Private Member Functions
void createLanguageComboBox ()
void createWelcomeLabel ()
Private Attributes
Scene myScene
VBox myVBox
Group root
ComboBox< String > myLanguageCB
Static Private Attributes
static final int TOPDOWN_PADDING = 200
static final int BOX_SPACING = 50
static final String CHOOSE_LANG = "Choose Your Language"
static final String CHINESE = "Chinese"
static final String ENGLISH = "English"
static final String SPANISH = "Spanish"
Detailed Description
A welcome scene for the user to choose their language of preference.
Author
Austin Kyker
Definition at line 20 of file WelcomeScene.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.WelcomeScene.WelcomeScene ()
Definition at line 34 of file WelcomeScene.java.
References gameAuthoring.scenes.WelcomeScene.createWelcomeLabel(), gameAuthoring.mainclasses.AuthorController.SCREEN_HEIGHT, and gameAuthoring.mainclasses.AuthorController.SCREEN_WIDTH.
Member Function Documentation
void gameAuthoring.scenes.WelcomeScene.createLanguageComboBox () private
Definition at line 46 of file WelcomeScene.java.
References utilities.multilanguage.MultiLanguageUtility.getInstance(), gameAuthoring.mainclasses.Constants.MED_PADDING, and utilities.multilanguage.MultiLanguageUtility.setLanguage().
Referenced by gameAuthoring.scenes.WelcomeScene.createWelcomeLabel().
void gameAuthoring.scenes.WelcomeScene.createWelcomeLabel () private
Definition at line 63 of file WelcomeScene.java.
References gameAuthoring.scenes.WelcomeScene.createLanguageComboBox(), utilities.multilanguage.MultiLanguageUtility.getInstance(), utilities.multilanguage.MultiLanguageUtility.getStringProperty(), and gameAuthoring.mainclasses.Constants.WELCOME_MSG.
Referenced by gameAuthoring.scenes.WelcomeScene.WelcomeScene().
Scene gameAuthoring.scenes.WelcomeScene.getScene ()
Definition at line 72 of file WelcomeScene.java.
References gameAuthoring.scenes.WelcomeScene.myScene.
Referenced by gameAuthoring.mainclasses.AuthorController.showWelcomeScene().
Member Data Documentation
final int gameAuthoring.scenes.WelcomeScene.BOX_SPACING = 50 static private
Definition at line 24 of file WelcomeScene.java.
final String gameAuthoring.scenes.WelcomeScene.CHINESE = "Chinese" static private
Definition at line 30 of file WelcomeScene.java.
final String gameAuthoring.scenes.WelcomeScene.CHOOSE_LANG = "Choose Your Language" static private
Definition at line 25 of file WelcomeScene.java.
final String gameAuthoring.scenes.WelcomeScene.ENGLISH = "English" static private
Definition at line 31 of file WelcomeScene.java.
ComboBox<String> gameAuthoring.scenes.WelcomeScene.myLanguageCB private
Definition at line 29 of file WelcomeScene.java.
Scene gameAuthoring.scenes.WelcomeScene.myScene private
Definition at line 26 of file WelcomeScene.java.
Referenced by gameAuthoring.scenes.WelcomeScene.getScene().
VBox gameAuthoring.scenes.WelcomeScene.myVBox private
Definition at line 27 of file WelcomeScene.java.
Group gameAuthoring.scenes.WelcomeScene.root private
Definition at line 28 of file WelcomeScene.java.
final String gameAuthoring.scenes.WelcomeScene.SPANISH = "Spanish" static private
Definition at line 32 of file WelcomeScene.java.
final int gameAuthoring.scenes.WelcomeScene.TOPDOWN_PADDING = 200 static private
Definition at line 23 of file WelcomeScene.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/WelcomeScene.java