voogasalad_LosTorres: utilities.reflection.ReflectionException Class Reference
utilities.reflection.ReflectionException Class Reference
Public Member Functions
ReflectionException (String message, Object...args)
ReflectionException (Throwable exception)
ReflectionException (Throwable cause, String message, Object...args)
Static Private Member Functions
static String format (String message, Object...args)
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
A general exception that represents all possible Java Reflection exceptions.
Author
Robert C. Duvall
Definition at line 9 of file ReflectionException.java.
Constructor & Destructor Documentation
utilities.reflection.ReflectionException.ReflectionException (String message, Object... args)
Create an exception based on an issue in our code.
Definition at line 16 of file ReflectionException.java.
References utilities.reflection.ReflectionException.format().
utilities.reflection.ReflectionException.ReflectionException (Throwable exception)
Create an exception based on a caught exception.
Definition at line 23 of file ReflectionException.java.
utilities.reflection.ReflectionException.ReflectionException (Throwable cause, String message, Object... args)
Create an exception based on a caught exception with a different message.
Definition at line 30 of file ReflectionException.java.
References utilities.reflection.ReflectionException.format().
Member Function Documentation
static String utilities.reflection.ReflectionException.format (String message, Object... args) static private
Definition at line 35 of file ReflectionException.java.
Referenced by utilities.reflection.ReflectionException.ReflectionException().
Member Data Documentation
final long utilities.reflection.ReflectionException.serialVersionUID = 1L static private
Definition at line 11 of file ReflectionException.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/reflection/ReflectionException.java