voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane Class Reference
gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane Class Reference
Public Member Functions
DefaultMapSelectionPane (BackgroundBuilding controller)
ScrollPane getDefaultMapsScrollPane ()
Private Member Functions
void handleImageClick (File fileCorrespondingToMapSelected)
Private Attributes
ScrollPane myScrollPane
VBox myImageDisplayVBox
BackgroundBuilding myPathBackgroundBuildingController
Static Private Attributes
static final String DEFAULT_MAP_IMAGES_DIR
static final double IMAGE_PADDING = 10.0
static final double IMAGE_WIDTH = 95.0
static final double IMAGE_HEIGHT = 60.0
static final double SCROLLPANE_WIDTH
Detailed Description
A pane of default maps that the user can select as their background. This pane will be on the left of the PathBuildingScene. Users can also drag and drop image files on the drag and drop file pane in the center of the screen during this background selection process.
Author
Austin Kyker
Definition at line 22 of file DefaultMapSelectionPane.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.DefaultMapSelectionPane (BackgroundBuilding controller)
Definition at line 36 of file DefaultMapSelectionPane.java.
References utilities.JavaFXutilities.imageView.StringToImageViewConverter.getImageView(), gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.handleImageClick(), gameAuthoring.mainclasses.AuthorController.SCREEN_HEIGHT, and gameAuthoring.scenes.pathBuilding.PathBuildingScene.SIDE_PANE_WIDTH.
Member Function Documentation
ScrollPane gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.getDefaultMapsScrollPane ()
Definition at line 64 of file DefaultMapSelectionPane.java.
References gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.myScrollPane.
Referenced by gameAuthoring.scenes.pathBuilding.PathBuildingScene.createAndDisplayDefaultMapSelectionPane().
void gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.handleImageClick (File fileCorrespondingToMapSelected) private
Definition at line 60 of file DefaultMapSelectionPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.BackgroundBuilding.setBackground().
Referenced by gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.DefaultMapSelectionPane().
Member Data Documentation
final String gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.DEFAULT_MAP_IMAGES_DIR static private
Initial value:
=
            "./src/gameAuthoring/Resources/DefaultMapImages/"
Definition at line 24 of file DefaultMapSelectionPane.java.
final double gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.IMAGE_HEIGHT = 60.0 static private
Definition at line 28 of file DefaultMapSelectionPane.java.
final double gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.IMAGE_PADDING = 10.0 static private
Definition at line 26 of file DefaultMapSelectionPane.java.
final double gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.IMAGE_WIDTH = 95.0 static private
Definition at line 27 of file DefaultMapSelectionPane.java.
VBox gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.myImageDisplayVBox private
Definition at line 33 of file DefaultMapSelectionPane.java.
BackgroundBuilding gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.myPathBackgroundBuildingController private
Definition at line 34 of file DefaultMapSelectionPane.java.
ScrollPane gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.myScrollPane private
Definition at line 32 of file DefaultMapSelectionPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.getDefaultMapsScrollPane().
final double gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.SCROLLPANE_WIDTH static private
Initial value:
=
            IMAGE_WIDTH + 2 * IMAGE_PADDING + 13
Definition at line 29 of file DefaultMapSelectionPane.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/DefaultMapSelectionPane.java