voogasalad_LosTorres: utilities.pathfinding.example.UnlinkedNodeAStarFinder Class Reference
utilities.pathfinding.example.UnlinkedNodeAStarFinder Class Reference
Public Member Functions
UnlinkedNodeAStarFinder (UnlinkedNode[][] nodeMap)
Integer getCost (UnlinkedNode beginningNode, UnlinkedNode endingNode)
Collection< UnlinkedNode > getNeighbors (UnlinkedNode node)
Number getHeuristicValue (UnlinkedNode node, UnlinkedNode destination)
int breakTie (UnlinkedNode node, UnlinkedNode other)
Public Member Functions inherited from utilities.pathfinding.AStarPathFinder< T >
abstract Number getHeuristicValue (T node, T destination)
boolean isDestination (T node, T destinationNode)
List< T > findPath (T start, T destination) throws InvalidCostException
Public Member Functions inherited from utilities.pathfinding.IPathFinder< T >
Number getCost (T beginningNode, T endingNode)
Iterable< T > getNeighbors (T node)
int breakTie (T node, T other)
Private Attributes
UnlinkedNode[][] myMap
Detailed Description
Definition at line 7 of file UnlinkedNodeAStarFinder.java.
Constructor & Destructor Documentation
utilities.pathfinding.example.UnlinkedNodeAStarFinder.UnlinkedNodeAStarFinder (UnlinkedNode nodeMap[][])
Definition at line 11 of file UnlinkedNodeAStarFinder.java.
Member Function Documentation
int utilities.pathfinding.example.UnlinkedNodeAStarFinder.breakTie (UnlinkedNode node, UnlinkedNode other)
Definition at line 52 of file UnlinkedNodeAStarFinder.java.
References utilities.pathfinding.example.UnlinkedNode.getX(), and utilities.pathfinding.example.UnlinkedNode.getY().
Integer utilities.pathfinding.example.UnlinkedNodeAStarFinder.getCost (UnlinkedNode beginningNode, UnlinkedNode endingNode)
Definition at line 16 of file UnlinkedNodeAStarFinder.java.
References utilities.pathfinding.example.UnlinkedNode.getX(), and utilities.pathfinding.example.UnlinkedNode.getY().
Number utilities.pathfinding.example.UnlinkedNodeAStarFinder.getHeuristicValue (UnlinkedNode node, UnlinkedNode destination)
Definition at line 42 of file UnlinkedNodeAStarFinder.java.
References utilities.pathfinding.example.UnlinkedNode.getX(), and utilities.pathfinding.example.UnlinkedNode.getY().
Collection<UnlinkedNode> utilities.pathfinding.example.UnlinkedNodeAStarFinder.getNeighbors (UnlinkedNode node)
Definition at line 25 of file UnlinkedNodeAStarFinder.java.
References utilities.pathfinding.example.UnlinkedNode.getX(), and utilities.pathfinding.example.UnlinkedNode.getY().
Member Data Documentation
UnlinkedNode [][] utilities.pathfinding.example.UnlinkedNodeAStarFinder.myMap private
Definition at line 9 of file UnlinkedNodeAStarFinder.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/pathfinding/example/UnlinkedNodeAStarFinder.java