voogasalad_LosTorres: gameEngine.actors.behaviors.EarthQuakeEffect Class Reference
gameEngine.actors.behaviors.EarthQuakeEffect Class Reference
Public Member Functions
EarthQuakeEffect (List< Double > list)
IBehavior copy ()
void during (BaseActor actor)
void start (BaseActor actor)
void end (BaseActor actor)
Public Member Functions inherited from gameEngine.actors.behaviors.BaseEffect
BaseEffect (double duration, double multiplier)
BaseEffect ()
BaseEffect (List< Double > list)
void execute (BaseActor actor)
abstract void during (BaseActor actor)
abstract void start (BaseActor actor)
abstract void end (BaseActor actor)
String toString ()
Additional Inherited Members
Protected Attributes inherited from gameEngine.actors.behaviors.BaseEffect
List< Double > myList
String myString
Package Attributes inherited from gameEngine.actors.behaviors.BaseEffect
double myDuration
double myInitialDuration
Detailed Description
Definition at line 6 of file EarthQuakeEffect.java.
Constructor & Destructor Documentation
gameEngine.actors.behaviors.EarthQuakeEffect.EarthQuakeEffect (List< Double > list)
Definition at line 8 of file EarthQuakeEffect.java.
Referenced by gameEngine.actors.behaviors.EarthQuakeEffect.copy().
Member Function Documentation
IBehavior gameEngine.actors.behaviors.EarthQuakeEffect.copy ()
Returns a copy of the behavior, which allows for copying entire actors
Returns
copy of the behavior
Implements gameEngine.actors.behaviors.IBehavior.
Definition at line 12 of file EarthQuakeEffect.java.
References gameEngine.actors.behaviors.EarthQuakeEffect.EarthQuakeEffect().
void gameEngine.actors.behaviors.EarthQuakeEffect.during (BaseActor actor)
Definition at line 18 of file EarthQuakeEffect.java.
References gameEngine.ManagerInterface.InformationInterface.getEarthquakeMagnitude(), gameEngine.actors.BaseActor.getEnemiesInRange(), gameEngine.actors.behaviors.BaseDefendBehavior.getHealth(), gameEngine.actors.BaseActor.getInfoInterface(), gameEngine.actors.behaviors.BaseDefendBehavior.onDeath(), and gameEngine.actors.behaviors.BaseDefendBehavior.setHealth().
void gameEngine.actors.behaviors.EarthQuakeEffect.end (BaseActor actor)
Definition at line 41 of file EarthQuakeEffect.java.
void gameEngine.actors.behaviors.EarthQuakeEffect.start (BaseActor actor)
Definition at line 35 of file EarthQuakeEffect.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/behaviors/EarthQuakeEffect.java