voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute Class Reference
gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute Class Reference
Public Member Functions
BackendRoute ()
BackendRoute (Point2D start, Point2D end)
BackendRoute (PathRoute route)
List< VisibilityPoint > getPoints ()
BackendRoute deepCopy ()
Private Member Functions
void setUpBackendRouteFromFrontEndRoute (PathRoute route)
Private Attributes
List< VisibilityPoint > myPoints
Detailed Description
Represents a back-end representation of a single enemy route. The points specify how the enemy will traverse the screen from the starting location to the ending location. The first point represents the starting location and the last point represents the ending locations. The visibility of the visibility point determines if the enemy will be visible or invisible while it heads to the next point in the route.
Author
Austin Kyker
Definition at line 22 of file BackendRoute.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.BackendRoute ()
Definition at line 25 of file BackendRoute.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.deepCopy().
gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.BackendRoute (Point2D start, Point2D end)
Definition at line 31 of file BackendRoute.java.
gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.BackendRoute (PathRoute route)
Definition at line 37 of file BackendRoute.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.setUpBackendRouteFromFrontEndRoute().
Member Function Documentation
BackendRoute gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.deepCopy ()
Definition at line 55 of file BackendRoute.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.BackendRoute(), and gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.myPoints.
List<VisibilityPoint> gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.getPoints ()
Definition at line 51 of file BackendRoute.java.
Referenced by gameEngine.actors.behaviors.BaseMovementBehavior.BaseMovementBehavior(), gameEngine.actors.BaseEnemy.initializeEnemy(), gameEngine.actors.behaviors.BaseMovementBehavior.setRoute(), gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testBackendRouteCreation(), and gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRouteTranslationTests.testRoutesTranslation().
void gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.setUpBackendRouteFromFrontEndRoute (PathRoute route) private
Definition at line 42 of file BackendRoute.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.BackendRoute().
Member Data Documentation
List<VisibilityPoint> gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.myPoints private
Definition at line 23 of file BackendRoute.java.
Referenced by gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoute.deepCopy().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/pathComponents/routeToPointTranslation/BackendRoute.java