voogasalad_LosTorres: gameEngine.actors.behaviors.FarthestRangeAttack Class Reference
gameEngine.actors.behaviors.FarthestRangeAttack Class Reference
Public Member Functions
FarthestRangeAttack (List< Double > list)
FarthestRangeAttack (double attackSpeed)
Comparator< BaseActor > defineComparison (BaseActor a)
IBehavior copy ()
Public Member Functions inherited from gameEngine.actors.behaviors.RangeAttack
RangeAttack (double attackSpeed)
RangeAttack (List< Double > list)
Public Member Functions inherited from gameEngine.actors.behaviors.BaseAttack
BaseAttack (double attackSpeed)
BaseAttack (List< Double > list)
void execute (BaseActor actor)
void setAttackSpeed (int i)
String toString ()
double getRange ()
Additional Inherited Members
Protected Member Functions inherited from gameEngine.actors.behaviors.RangeAttack
void shootActorFromActor (BaseActor target, BaseActor actor)
void performAttack (BaseActor actor)
abstract Comparator< BaseActor > defineComparison (BaseActor actor)
Protected Member Functions inherited from gameEngine.actors.behaviors.BaseAttack
boolean readyToShoot ()
abstract void performAttack (BaseActor actor)
Protected Attributes inherited from gameEngine.actors.behaviors.BaseAttack
List< Double > myList
double myAttackSpeed
double myRange
int myCooldown
Static Protected Attributes inherited from gameEngine.actors.behaviors.BaseAttack
static final int READY_TO_SHOOT = 0
Detailed Description
Definition at line 8 of file FarthestRangeAttack.java.
Constructor & Destructor Documentation
gameEngine.actors.behaviors.FarthestRangeAttack.FarthestRangeAttack (List< Double > list)
Definition at line 10 of file FarthestRangeAttack.java.
Referenced by gameEngine.actors.behaviors.FarthestRangeAttack.copy().
gameEngine.actors.behaviors.FarthestRangeAttack.FarthestRangeAttack (double attackSpeed)
Definition at line 14 of file FarthestRangeAttack.java.
Member Function Documentation
IBehavior gameEngine.actors.behaviors.FarthestRangeAttack.copy ()
Returns a copy of the behavior, which allows for copying entire actors
Returns
copy of the behavior
Implements gameEngine.actors.behaviors.IBehavior.
Definition at line 28 of file FarthestRangeAttack.java.
References gameEngine.actors.behaviors.FarthestRangeAttack.FarthestRangeAttack(), and gameEngine.actors.behaviors.BaseAttack.myList.
Comparator<BaseActor> gameEngine.actors.behaviors.FarthestRangeAttack.defineComparison (BaseActor a)
Definition at line 19 of file FarthestRangeAttack.java.
References gameEngine.actors.BaseActor.getBehavior().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/behaviors/FarthestRangeAttack.java