voogasalad_LosTorres: gamePlayer.mainClasses.welcomeScreen.startingOptions.MultiPlayerOptions Class Reference
gamePlayer.mainClasses.welcomeScreen.startingOptions.MultiPlayerOptions Class Reference
Public Member Functions
MultiPlayerOptions ()
Node getNewGameOption ()
Node getJoinGameOption ()
Private Attributes
Button newGameOption
Button joinGameOption
Additional Inherited Members
Protected Member Functions inherited from gamePlayer.mainClasses.welcomeScreen.startingOptions.Options
Button createOptionButton (ObjectProperty< String > objectProperty)
Detailed Description
Definition at line 8 of file MultiPlayerOptions.java.
Constructor & Destructor Documentation
gamePlayer.mainClasses.welcomeScreen.startingOptions.MultiPlayerOptions.MultiPlayerOptions ()
Definition at line 12 of file MultiPlayerOptions.java.
References gamePlayer.mainClasses.welcomeScreen.startingOptions.Options.createOptionButton(), utilities.multilanguage.MultiLanguageUtility.getStringProperty(), gamePlayer.mainClasses.guiBuilder.GuiText.JOIN_GAME, gamePlayer.mainClasses.guiBuilder.GuiConstants.MULTILANGUAGE, and gamePlayer.mainClasses.guiBuilder.GuiText.NEW_GAME.
Member Function Documentation
Node gamePlayer.mainClasses.welcomeScreen.startingOptions.MultiPlayerOptions.getJoinGameOption ()
Definition at line 25 of file MultiPlayerOptions.java.
References gamePlayer.mainClasses.welcomeScreen.startingOptions.MultiPlayerOptions.joinGameOption.
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.startMultiPlayerOptions(), and gamePlayer.mainClasses.welcomeScreen.GameStartManager.startMultiPlayerOptions().
Node gamePlayer.mainClasses.welcomeScreen.startingOptions.MultiPlayerOptions.getNewGameOption ()
Definition at line 21 of file MultiPlayerOptions.java.
References gamePlayer.mainClasses.welcomeScreen.startingOptions.MultiPlayerOptions.newGameOption.
Referenced by gamePlayer.mainClasses.managers.WelcomeManager.startMultiPlayerOptions(), and gamePlayer.mainClasses.welcomeScreen.GameStartManager.startMultiPlayerOptions().
Member Data Documentation
Button gamePlayer.mainClasses.welcomeScreen.startingOptions.MultiPlayerOptions.joinGameOption private
Definition at line 10 of file MultiPlayerOptions.java.
Referenced by gamePlayer.mainClasses.welcomeScreen.startingOptions.MultiPlayerOptions.getJoinGameOption().
Button gamePlayer.mainClasses.welcomeScreen.startingOptions.MultiPlayerOptions.newGameOption private
Definition at line 9 of file MultiPlayerOptions.java.
Referenced by gamePlayer.mainClasses.welcomeScreen.startingOptions.MultiPlayerOptions.getNewGameOption().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/mainClasses/welcomeScreen/startingOptions/MultiPlayerOptions.java