voogasalad_LosTorres: gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene Class Reference
gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene Class Reference
Public Member Functions
EnemyBuildingScene (BorderPane root, IEnemyConfiguring controller)
boolean actorSpecificFieldsValid ()
Public Member Functions inherited from gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene
ActorBuildingScene (BorderPane root, String title, String behaviorXMLFileLocation, String actorImageDirectory)
void update (Observable obs, Object arg1)
Public Member Functions inherited from gameAuthoring.scenes.BuildingScene
BuildingScene (BorderPane root, String title)
String getTitle ()
Scene getScene ()
Protected Member Functions
void makeNewActor (Map< String, IBehavior > iBehaviorMap)
void initializeActorsAndBuildActorDisplay ()
void finishBuildingActors ()
void configureAndDisplayRightPane ()
HBox addRequiredNumericalTextFields ()
void clearActorSpecificFields ()
Protected Member Functions inherited from gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene
abstract void initializeActorsAndBuildActorDisplay ()
abstract HBox addRequiredNumericalTextFields ()
abstract void makeNewActor (Map< String, IBehavior > iBehaviorMap)
void clearFields ()
abstract void clearActorSpecificFields ()
abstract boolean actorSpecificFieldsValid ()
abstract void configureAndDisplayRightPane ()
abstract void finishBuildingActors ()
Private Member Functions
boolean actorNamesAreUnique ()
Private Attributes
List< BaseEnemy > myEnemies
IEnemyConfiguring myEnemyConfiguringController
LabeledNumericalTextField myDamageField
Static Private Attributes
static final String TITLE = "Enemy"
static final String IMG_DIR = AuthorController.gameDir + "/enemyImages/"
static final String BEHAVIOR_XML_LOC
static final double FIELD_WIDTH = 100
Additional Inherited Members
Static Public Attributes inherited from gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene
static final int ACTOR_IMG_HEIGHT = 150
static final int ACTOR_IMG_WIDTH = 150
Static Public Attributes inherited from gameAuthoring.scenes.BuildingScene
static final String STYLESHEET_PACKAGE = "./gameAuthoring/Stylesheets/"
Protected Attributes inherited from gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene
DragAndDropImagePane myDragAndDrop
TextField myActorNameField
String myActorImgPath
List< BehaviorBuilder > myBehaviorBuilders
SliderContainer myRangeSliderContainer
Protected Attributes inherited from gameAuthoring.scenes.BuildingScene
BorderPane myPane
Static Protected Attributes inherited from gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene
static final String ADD_TOWER_IMG_PATH
static final int DRAG_AND_DROP_WIDTH = 550
Detailed Description
Scene to build a new enemy.
Author
Austin Kyker
Definition at line 24 of file EnemyBuildingScene.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.EnemyBuildingScene (BorderPane root, IEnemyConfiguring controller)
Definition at line 36 of file EnemyBuildingScene.java.
Member Function Documentation
boolean gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.actorNamesAreUnique () private
Definition at line 82 of file EnemyBuildingScene.java.
References gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.myActorNameField, and gameAuthoring.mainclasses.Constants.UNIQUE_NAMES_ERROR.
Referenced by gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.actorSpecificFieldsValid().
boolean gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.actorSpecificFieldsValid ()
Definition at line 78 of file EnemyBuildingScene.java.
References gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.actorNamesAreUnique(), and utilities.JavaFXutilities.numericalTextFields.LabeledNumericalTextField.isValueEntered().
HBox gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.addRequiredNumericalTextFields () protected
Definition at line 70 of file EnemyBuildingScene.java.
References gameAuthoring.mainclasses.Constants.DAMAGE, and gameAuthoring.mainclasses.Constants.SM_PADDING.
void gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.clearActorSpecificFields () protected
Definition at line 93 of file EnemyBuildingScene.java.
References utilities.JavaFXutilities.numericalTextFields.LabeledNumericalTextField.clearField().
void gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.configureAndDisplayRightPane () protected
Definition at line 66 of file EnemyBuildingScene.java.
void gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.finishBuildingActors () protected
Definition at line 61 of file EnemyBuildingScene.java.
References gameAuthoring.mainclasses.controllerInterfaces.IEnemyConfiguring.configureEnemies().
void gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.initializeActorsAndBuildActorDisplay () protected
Definition at line 54 of file EnemyBuildingScene.java.
References gameAuthoring.scenes.BuildingScene.myPane.
void gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.makeNewActor (Map< String, IBehavior > iBehaviorMap) protected
Definition at line 43 of file EnemyBuildingScene.java.
References gameAuthoring.mainclasses.controllerInterfaces.IEnemyConfiguring.fetchEnemyRoutes(), utilities.JavaFXutilities.numericalTextFields.LabeledNumericalTextField.getNumberEntered(), utilities.JavaFXutilities.slider.SliderContainer.getSliderValue(), gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.myActorImgPath, gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.myActorNameField, and gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.myRangeSliderContainer.
Member Data Documentation
final String gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.BEHAVIOR_XML_LOC static private
Initial value:
=
            "./src/gameAuthoring/Resources/actorBehaviors/EnemyBehaviors.xml"
Definition at line 28 of file EnemyBuildingScene.java.
final double gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.FIELD_WIDTH = 100 static private
Definition at line 30 of file EnemyBuildingScene.java.
final String gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.IMG_DIR = AuthorController.gameDir + "/enemyImages/" static private
Definition at line 27 of file EnemyBuildingScene.java.
LabeledNumericalTextField gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.myDamageField private
Definition at line 34 of file EnemyBuildingScene.java.
List<BaseEnemy> gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.myEnemies private
Definition at line 32 of file EnemyBuildingScene.java.
IEnemyConfiguring gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.myEnemyConfiguringController private
Definition at line 33 of file EnemyBuildingScene.java.
final String gameAuthoring.scenes.actorBuildingScenes.EnemyBuildingScene.TITLE = "Enemy" static private
Definition at line 26 of file EnemyBuildingScene.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/actorBuildingScenes/EnemyBuildingScene.java