voogasalad_LosTorres: gameAuthoring.mainclasses.controllerInterfaces.ILevelConfiguring Interface Reference
gameAuthoring.mainclasses.controllerInterfaces.ILevelConfiguring Interface Reference
Public Member Functions
void configureLevels (List< BaseLevel > levels)
List< BaseEnemy > fetchEnemies ()
String getBackgroundImagePath ()
Detailed Description
An interface for configuring levels. The level building scene needs access to the enemies, but not the towers.
Author
Austin Kyker
Definition at line 13 of file ILevelConfiguring.java.
Member Function Documentation
void gameAuthoring.mainclasses.controllerInterfaces.ILevelConfiguring.configureLevels (List< BaseLevel > levels)
Implemented in gameAuthoring.mainclasses.AuthorController.
Referenced by gameAuthoring.scenes.levelBuilding.LevelBuildingScene.update().
List<BaseEnemy> gameAuthoring.mainclasses.controllerInterfaces.ILevelConfiguring.fetchEnemies ()
Implemented in gameAuthoring.mainclasses.AuthorController.
Referenced by gameAuthoring.scenes.levelBuilding.LevelBuildingScene.setupLevelDisplay().
String gameAuthoring.mainclasses.controllerInterfaces.ILevelConfiguring.getBackgroundImagePath ()
Implemented in gameAuthoring.mainclasses.AuthorController.
Referenced by gameAuthoring.scenes.levelBuilding.LevelBuildingScene.setupLevelDisplay().
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/mainclasses/controllerInterfaces/ILevelConfiguring.java