voogasalad_LosTorres: gamePlayer.guiItems.controlDockButtons.sliders.SpeedSlider Class Reference
gamePlayer.guiItems.controlDockButtons.sliders.SpeedSlider Class Reference
Public Member Functions
void initialize (Dimension2D containerSize)
Node getNode ()
Public Member Functions inherited from gamePlayer.guiItems.controlDockButtons.ControlDockSlider
void initialize (Dimension2D containerSize)
Private Member Functions
void setUpSlider ()
Private Attributes
SpeedSliderListener myListener = GuiConstants.GUI_MANAGER
Additional Inherited Members
Static Public Attributes inherited from gamePlayer.guiItems.controlDockButtons.ControlDockSlider
static final String LABEL = "GameSpeed"
Static Public Attributes inherited from gamePlayer.guiItems.GuiItem
static String myPropertiesPath = "guiItems/"
Protected Member Functions inherited from gamePlayer.guiItems.controlDockButtons.ControlDockSlider
void setUpSizing (Dimension2D containerSize)
Protected Attributes inherited from gamePlayer.guiItems.controlDockButtons.ControlDockSlider
XMLParser myParser
SliderContainer mySlider
Detailed Description
Definition at line 17 of file SpeedSlider.java.
Member Function Documentation
Node gamePlayer.guiItems.controlDockButtons.sliders.SpeedSlider.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 41 of file SpeedSlider.java.
References gamePlayer.guiItems.controlDockButtons.ControlDockSlider.mySlider.
void gamePlayer.guiItems.controlDockButtons.sliders.SpeedSlider.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 22 of file SpeedSlider.java.
References gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_ELEMENT_PROPERTIES_PATH, gamePlayer.guiItems.controlDockButtons.ControlDockSlider.myParser, gamePlayer.guiItems.GuiItem.myPropertiesPath, gamePlayer.guiItems.controlDockButtons.ControlDockSlider.setUpSizing(), and gamePlayer.guiItems.controlDockButtons.sliders.SpeedSlider.setUpSlider().
void gamePlayer.guiItems.controlDockButtons.sliders.SpeedSlider.setUpSlider () private
Definition at line 30 of file SpeedSlider.java.
References gamePlayer.guiItemsListeners.SpeedSliderListener.changeSpeed(), utilities.JavaFXutilities.slider.SliderContainer.getValueProperty(), and gamePlayer.guiItems.controlDockButtons.ControlDockSlider.mySlider.
Referenced by gamePlayer.guiItems.controlDockButtons.sliders.SpeedSlider.initialize().
Member Data Documentation
SpeedSliderListener gamePlayer.guiItems.controlDockButtons.sliders.SpeedSlider.myListener = GuiConstants.GUI_MANAGER private
Definition at line 19 of file SpeedSlider.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItems/controlDockButtons/sliders/SpeedSlider.java