voogasalad_LosTorres: gamePlayer.unusedCodeWarehouse.guiItems.store.Store Class Reference
gamePlayer.unusedCodeWarehouse.guiItems.store.Store Class Reference
Public Member Functions
void initialize (Dimension2D containerSize)
Node getNode ()
void selectTower (String towerID)
void deselectTower ()
Static Public Member Functions
static Store getInstance ()
Package Attributes
Dimension2D myCellSize
Private Member Functions
void buildHeader ()
void buildInventoryContainer ()
void buildInventoryItems ()
Private Attributes
XMLParser myParser
Node myHeader
VBox myContainer
GridPane myGridPane
ScrollPane myScrollPane
Dimension2D myContentSize
int myNumColumns
Static Private Attributes
static Store myReference = null
Additional Inherited Members
Static Public Attributes inherited from gamePlayer.guiItems.GuiItem
static String myPropertiesPath = "guiItems/"
Detailed Description
Store GUI with all the possible towers you can buy. To add a new tower: (1) Create a new Properties File named <TowerName>.properties in the spriteResources.towers package (2) Add the <TowerName> to the Inventory List in the StoreProperties XML file in the gamePlayer.properties.guiItems package (3) Create an Image for the Cell to be displayed in the store with a picture of the tower, its name, and its cost (4) Put the image file in the main voogasalad directory (outside of src)
Author
brianbolze
Definition at line 29 of file Store.java.
Member Function Documentation
void gamePlayer.unusedCodeWarehouse.guiItems.store.Store.buildHeader () private
Definition at line 93 of file Store.java.
References utilities.XMLParsing.XMLParser.getValuesFromTag().
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.store.Store.initialize().
void gamePlayer.unusedCodeWarehouse.guiItems.store.Store.buildInventoryContainer () private
Definition at line 104 of file Store.java.
References utilities.XMLParsing.XMLParser.getDoubleValuesFromTag(), utilities.XMLParsing.XMLParser.getIntegerValuesFromTag(), and gamePlayer.unusedCodeWarehouse.guiItems.store.Store.myNumColumns.
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.store.Store.initialize().
void gamePlayer.unusedCodeWarehouse.guiItems.store.Store.buildInventoryItems () private
Definition at line 118 of file Store.java.
References gamePlayer.mainClasses.guiBuilder.GuiElement.getNode(), utilities.XMLParsing.XMLParser.getValuesFromTag(), and gamePlayer.mainClasses.guiBuilder.GuiElement.initialize().
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.store.Store.initialize().
void gamePlayer.unusedCodeWarehouse.guiItems.store.Store.deselectTower ()
Implements gamePlayer.unusedCodeWarehouse.SelectTowerListener.
Definition at line 88 of file Store.java.
static Store gamePlayer.unusedCodeWarehouse.guiItems.store.Store.getInstance () static
Definition at line 41 of file Store.java.
References gamePlayer.unusedCodeWarehouse.guiItems.store.Store.myReference.
Node gamePlayer.unusedCodeWarehouse.guiItems.store.Store.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 75 of file Store.java.
References gamePlayer.unusedCodeWarehouse.guiItems.store.Store.myContainer.
void gamePlayer.unusedCodeWarehouse.guiItems.store.Store.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 49 of file Store.java.
References gamePlayer.unusedCodeWarehouse.guiItems.store.Store.buildHeader(), gamePlayer.unusedCodeWarehouse.guiItems.store.Store.buildInventoryContainer(), gamePlayer.unusedCodeWarehouse.guiItems.store.Store.buildInventoryItems(), utilities.XMLParsing.XMLParser.getValuesFromTag(), and gamePlayer.guiItems.GuiItem.myPropertiesPath.
void gamePlayer.unusedCodeWarehouse.guiItems.store.Store.selectTower (String towerID)
Implements gamePlayer.unusedCodeWarehouse.SelectTowerListener.
Definition at line 80 of file Store.java.
References gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.getNode(), and gamePlayer.unusedCodeWarehouse.guiItems.store.UpgradeStore.initialize().
Member Data Documentation
Dimension2D gamePlayer.unusedCodeWarehouse.guiItems.store.Store.myCellSize package
Definition at line 36 of file Store.java.
VBox gamePlayer.unusedCodeWarehouse.guiItems.store.Store.myContainer private
Definition at line 33 of file Store.java.
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.store.Store.getNode().
Dimension2D gamePlayer.unusedCodeWarehouse.guiItems.store.Store.myContentSize private
Definition at line 36 of file Store.java.
GridPane gamePlayer.unusedCodeWarehouse.guiItems.store.Store.myGridPane private
Definition at line 34 of file Store.java.
Node gamePlayer.unusedCodeWarehouse.guiItems.store.Store.myHeader private
Definition at line 32 of file Store.java.
int gamePlayer.unusedCodeWarehouse.guiItems.store.Store.myNumColumns private
Definition at line 37 of file Store.java.
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.store.Store.buildInventoryContainer().
XMLParser gamePlayer.unusedCodeWarehouse.guiItems.store.Store.myParser private
Definition at line 31 of file Store.java.
Store gamePlayer.unusedCodeWarehouse.guiItems.store.Store.myReference = null static private
Definition at line 39 of file Store.java.
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.store.Store.getInstance().
ScrollPane gamePlayer.unusedCodeWarehouse.guiItems.store.Store.myScrollPane private
Definition at line 35 of file Store.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/unusedCodeWarehouse/guiItems/store/Store.java