voogasalad_LosTorres: gameEngine.actors.behaviors.GoldGenEffect Class Reference
gameEngine.actors.behaviors.GoldGenEffect Class Reference
Public Member Functions
GoldGenEffect (List< Double > list)
IBehavior copy ()
void during (BaseActor actor)
void start (BaseActor actor)
void end (BaseActor actor)
Public Member Functions inherited from gameEngine.actors.behaviors.BaseEffect
BaseEffect (double duration, double multiplier)
BaseEffect ()
BaseEffect (List< Double > list)
void execute (BaseActor actor)
abstract void during (BaseActor actor)
abstract void start (BaseActor actor)
abstract void end (BaseActor actor)
String toString ()
Private Attributes
double myGold
Additional Inherited Members
Protected Attributes inherited from gameEngine.actors.behaviors.BaseEffect
List< Double > myList
String myString
Package Attributes inherited from gameEngine.actors.behaviors.BaseEffect
double myDuration
double myInitialDuration
Detailed Description
Definition at line 8 of file GoldGenEffect.java.
Constructor & Destructor Documentation
gameEngine.actors.behaviors.GoldGenEffect.GoldGenEffect (List< Double > list)
Definition at line 11 of file GoldGenEffect.java.
Referenced by gameEngine.actors.behaviors.GoldGenEffect.copy().
Member Function Documentation
IBehavior gameEngine.actors.behaviors.GoldGenEffect.copy ()
Returns a copy of the behavior, which allows for copying entire actors
Returns
copy of the behavior
Implements gameEngine.actors.behaviors.IBehavior.
Definition at line 16 of file GoldGenEffect.java.
References gameEngine.actors.behaviors.GoldGenEffect.GoldGenEffect(), and gameEngine.actors.behaviors.BaseEffect.myList.
void gameEngine.actors.behaviors.GoldGenEffect.during (BaseActor actor)
Definition at line 22 of file GoldGenEffect.java.
void gameEngine.actors.behaviors.GoldGenEffect.end (BaseActor actor)
Definition at line 34 of file GoldGenEffect.java.
References gameEngine.actors.behaviors.BaseEffect.myDuration, and gameEngine.actors.behaviors.BaseEffect.myInitialDuration.
void gameEngine.actors.behaviors.GoldGenEffect.start (BaseActor actor)
Definition at line 27 of file GoldGenEffect.java.
References gameEngine.actors.BaseActor.changeAndNotify().
Member Data Documentation
double gameEngine.actors.behaviors.GoldGenEffect.myGold private
Definition at line 9 of file GoldGenEffect.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/actors/behaviors/GoldGenEffect.java