voogasalad_LosTorres: gamePlayer.guiContainers.coreContainers.RightContainer Class Reference
gamePlayer.guiContainers.coreContainers.RightContainer Class Reference
Public Member Functions
void initialize (Dimension2D containerSize)
Node getNode ()
Private Attributes
XMLParser myParser
Additional Inherited Members
Public Attributes inherited from gamePlayer.guiContainers.GuiContainer
String myPropertiesPath = "guiContainers/"
Detailed Description
GuiContainer that hosts GuiElements on the right side of the screen
Author
allankiplagat
Definition at line 21 of file RightContainer.java.
Member Function Documentation
Node gamePlayer.guiContainers.coreContainers.RightContainer.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 33 of file RightContainer.java.
void gamePlayer.guiContainers.coreContainers.RightContainer.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 25 of file RightContainer.java.
References gamePlayer.guiContainers.coreContainers.CoreContainerSetup.getChildList(), gamePlayer.guiContainers.coreContainers.CoreContainerSetup.initialize(), gamePlayer.mainClasses.guiBuilder.GuiConstants.RIGHT_CONTAINER_HEIGHT, and gamePlayer.mainClasses.guiBuilder.GuiConstants.RIGHT_CONTAINER_WIDTH.
Referenced by gamePlayer.mainClasses.guiBuilder.GuiBuilder.initializeCoreContainers().
Member Data Documentation
XMLParser gamePlayer.guiContainers.coreContainers.RightContainer.myParser private
Definition at line 22 of file RightContainer.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiContainers/coreContainers/RightContainer.java