voogasalad_LosTorres: gamePlayer.mainClasses.welcomeScreen.availableGames.GameChooser Class Reference
gamePlayer.mainClasses.welcomeScreen.availableGames.GameChooser Class Reference
Public Member Functions
GameChooser (String directory)
Static Public Attributes
static final double WIDTH = WelcomeScreen.CENTER_PANE_WIDTH
static final double HEIGHT = WelcomeScreen.CENTER_PANE_HEIGHT
Private Member Functions
void loadGameDescriptions (String directory)
Private Attributes
TilePane myPane
Detailed Description
Definition at line 8 of file GameChooser.java.
Constructor & Destructor Documentation
gamePlayer.mainClasses.welcomeScreen.availableGames.GameChooser.GameChooser (String directory)
Definition at line 13 of file GameChooser.java.
References gamePlayer.mainClasses.welcomeScreen.availableGames.GameChooser.loadGameDescriptions().
Member Function Documentation
void gamePlayer.mainClasses.welcomeScreen.availableGames.GameChooser.loadGameDescriptions (String directory) private
Definition at line 24 of file GameChooser.java.
References gamePlayer.mainClasses.welcomeScreen.availableGames.GameDescriptionLoader.getDescriptions().
Referenced by gamePlayer.mainClasses.welcomeScreen.availableGames.GameChooser.GameChooser().
Member Data Documentation
final double gamePlayer.mainClasses.welcomeScreen.availableGames.GameChooser.HEIGHT = WelcomeScreen.CENTER_PANE_HEIGHT static
Definition at line 11 of file GameChooser.java.
TilePane gamePlayer.mainClasses.welcomeScreen.availableGames.GameChooser.myPane private
Definition at line 9 of file GameChooser.java.
final double gamePlayer.mainClasses.welcomeScreen.availableGames.GameChooser.WIDTH = WelcomeScreen.CENTER_PANE_WIDTH static
Definition at line 10 of file GameChooser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/mainClasses/welcomeScreen/availableGames/GameChooser.java