voogasalad_LosTorres: gamePlayer.guiItemsListeners.StoreListener Interface Reference
gamePlayer.guiItemsListeners.StoreListener Interface Reference
Public Member Functions
void registerStore (Store store)
void fillStore (Collection< TowerInfoObject > towersAvailable)
void refreshStore ()
void placeTower (String towerName)
void escapePlace ()
Detailed Description
Definition at line 8 of file StoreListener.java.
Member Function Documentation
void gamePlayer.guiItemsListeners.StoreListener.escapePlace ()
Implemented in gamePlayer.mainClasses.managers.GuiManager.
Referenced by gamePlayer.guiItems.store.Store.checkEscape().
void gamePlayer.guiItemsListeners.StoreListener.fillStore (Collection< TowerInfoObject > towersAvailable)
Implemented in gamePlayer.mainClasses.managers.GuiManager.
void gamePlayer.guiItemsListeners.StoreListener.placeTower (String towerName)
Implemented in gamePlayer.mainClasses.managers.GuiManager.
Referenced by gamePlayer.guiItems.store.Store.placeTower().
void gamePlayer.guiItemsListeners.StoreListener.refreshStore ()
Implemented in gamePlayer.mainClasses.managers.GuiManager.
void gamePlayer.guiItemsListeners.StoreListener.registerStore (Store store)
Implemented in gamePlayer.mainClasses.managers.GuiManager.
Referenced by gamePlayer.guiItems.store.Store.initialize().
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItemsListeners/StoreListener.java