voogasalad_LosTorres: gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper Class Reference
gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper Class Reference
Public Member Functions
ZoomWrapper (Group group)
Private Member Functions
void bound (Bounds bounds)
void zoom (ZoomEvent event)
void scroll (ScrollEvent event)
void reposition ()
Private Attributes
Group myGroup
DoubleProperty ZOOM = new SimpleDoubleProperty(1)
DoubleProperty X_TRANS = new SimpleDoubleProperty(0)
DoubleProperty Y_TRANS = new SimpleDoubleProperty(0)
Detailed Description
Definition at line 12 of file ZoomWrapper.java.
Constructor & Destructor Documentation
gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper.ZoomWrapper (Group group)
Definition at line 19 of file ZoomWrapper.java.
References gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper.bound(), gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper.scroll(), and gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper.zoom().
Member Function Documentation
void gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper.bound (Bounds bounds) private
Definition at line 31 of file ZoomWrapper.java.
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper.ZoomWrapper().
void gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper.reposition () private
Definition at line 60 of file ZoomWrapper.java.
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper.scroll().
void gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper.scroll (ScrollEvent event) private
Definition at line 46 of file ZoomWrapper.java.
References gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper.reposition().
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper.ZoomWrapper().
void gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper.zoom (ZoomEvent event) private
Definition at line 38 of file ZoomWrapper.java.
Referenced by gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper.ZoomWrapper().
Member Data Documentation
Group gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper.myGroup private
Definition at line 14 of file ZoomWrapper.java.
DoubleProperty gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper.X_TRANS = new SimpleDoubleProperty(0) private
Definition at line 16 of file ZoomWrapper.java.
DoubleProperty gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper.Y_TRANS = new SimpleDoubleProperty(0) private
Definition at line 17 of file ZoomWrapper.java.
DoubleProperty gamePlayer.unusedCodeWarehouse.guiItems.gameWorldZoom.ZoomWrapper.ZOOM = new SimpleDoubleProperty(1) private
Definition at line 15 of file ZoomWrapper.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/unusedCodeWarehouse/guiItems/gameWorldZoom/ZoomWrapper.java