voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane Class Reference
gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane Class Reference
Public Member Functions
EnemyStartingLocationsPane (Group group, Path path, PathBuildingScene pathBuildingScene)
Public Member Functions inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane
EnemyLocationPane (Group group, Path path)
Public Member Functions inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
BuildingPane (Group group)
void drawLocation (Node component)
void drawPathComponent (Node component)
void refreshScreen ()
void removeComponentFromScreen (Node component)
void executeExitFunction ()
void executeEnterFunction ()
Private Member Functions
void createEnemyStartingLocationsSetupComponents ()
void addNewStartingLocation (MouseEvent event)
Private Attributes
Button mySaveStartsButton
PathBuildingScene myPathBuildingScene
Additional Inherited Members
Static Public Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
static final double DRAW_SCREEN_WIDTH_RATIO = .80
static final double DRAW_SCREEN_WIDTH
Protected Member Functions inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane
void createEnemyLocationsSetupComponents (Button button, String labelStr)
Protected Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane
Button myClearLocations
Path myPath
Static Protected Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
static Group myGroup
Detailed Description
Allows the user to place starting locations of the enemies on the screen.
Author
Austin Kyker
Definition at line 19 of file EnemyStartingLocationsPane.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane.EnemyStartingLocationsPane (Group group, Path path, PathBuildingScene pathBuildingScene)
Definition at line 24 of file EnemyStartingLocationsPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane.addNewStartingLocation(), gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane.createEnemyStartingLocationsSetupComponents(), utilities.multilanguage.MultiLanguageUtility.getInstance(), utilities.multilanguage.MultiLanguageUtility.getStringProperty(), and gameAuthoring.mainclasses.Constants.SET_START_LOCS.
Member Function Documentation
void gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane.addNewStartingLocation (MouseEvent event) private
Definition at line 43 of file EnemyStartingLocationsPane.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addStartingLocation(), gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.drawLocation(), and gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane.myPath.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane.EnemyStartingLocationsPane().
void gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane.createEnemyStartingLocationsSetupComponents () private
Definition at line 35 of file EnemyStartingLocationsPane.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.clearEnemyStartingLocations(), gameAuthoring.mainclasses.Constants.ENEMY_START_LOC_PROMPT, gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane.myClearLocations, and gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyLocationPane.myPath.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane.EnemyStartingLocationsPane().
Member Data Documentation
PathBuildingScene gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane.myPathBuildingScene private
Definition at line 22 of file EnemyStartingLocationsPane.java.
Button gameAuthoring.scenes.pathBuilding.buildingPanes.locationPane.EnemyStartingLocationsPane.mySaveStartsButton private
Definition at line 21 of file EnemyStartingLocationsPane.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/buildingPanes/locationPane/EnemyStartingLocationsPane.java