voogasalad_LosTorres: gameEngine.Data.RangeRestrictedCollection< T extends BaseActor > Class Template Reference
gameEngine.Data.RangeRestrictedCollection< T extends BaseActor > Class Template Reference
Public Member Functions
RangeRestrictedCollection (Collection< T > actors)
RangeRestrictedCollection ()
void clear ()
void remove (T actor)
void add (T actor)
List< BaseActor > getActorsInRange (BaseActor actor)
void clearAndExecuteRemoveBuffer ()
boolean addActorToRemoveBuffer (BaseActor actor)
Iterator< T > iterator ()
Private Member Functions
boolean shouldBeRemoved (T actor)
Private Attributes
Collection< T > myActorsList
Collection< T > myActorsToRemove
Detailed Description
Definition at line 12 of file RangeRestrictedCollection.java.
Constructor & Destructor Documentation
gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.RangeRestrictedCollection (Collection< T > actors)
Definition at line 18 of file RangeRestrictedCollection.java.
gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.RangeRestrictedCollection ()
Definition at line 23 of file RangeRestrictedCollection.java.
Member Function Documentation
void gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.add (T actor)
Definition at line 37 of file RangeRestrictedCollection.java.
Referenced by gameEngine.MainEngineManager.addEnemies(), gameEngine.MainEngineManager.addTower(), and gameEngine.MainEngineManager.update().
boolean gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.addActorToRemoveBuffer (BaseActor actor)
Definition at line 72 of file RangeRestrictedCollection.java.
void gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.clear ()
Definition at line 28 of file RangeRestrictedCollection.java.
Referenced by gameEngine.MainEngineManager.clear(), gameEngine.MainEngineManager.initializeGame(), gameEngine.MainEngineManager.loadAuthoringLevel(), gameEngine.MainEngineManager.onGameLose(), and gameEngine.MainEngineManager.onLevelEnd().
void gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.clearAndExecuteRemoveBuffer ()
Definition at line 61 of file RangeRestrictedCollection.java.
Referenced by gameEngine.MainEngineManager.gameUpdate().
List<BaseActor> gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.getActorsInRange (BaseActor actor)
Definition at line 44 of file RangeRestrictedCollection.java.
Referenced by gameEngine.MainEngineManager.getRequiredActors().
Iterator<T> gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.iterator ()
Definition at line 90 of file RangeRestrictedCollection.java.
void gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.remove (T actor)
Definition at line 32 of file RangeRestrictedCollection.java.
Referenced by gameEngine.MainEngineManager.removeTower().
boolean gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.shouldBeRemoved (T actor) private
Definition at line 68 of file RangeRestrictedCollection.java.
Referenced by gameEngine.Data.RangeRestrictedCollection< gameEngine.actors.BaseTower >.getActorsInRange().
Member Data Documentation
Collection<T> gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.myActorsList private
Definition at line 15 of file RangeRestrictedCollection.java.
Collection<T> gameEngine.Data.RangeRestrictedCollection< T extends BaseActor >.myActorsToRemove private
Definition at line 16 of file RangeRestrictedCollection.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameEngine/Data/RangeRestrictedCollection.java