voogasalad_LosTorres: utilities.errorPopup.ErrorPopup Class Reference
utilities.errorPopup.ErrorPopup Class Reference
Public Member Functions
ErrorPopup (String message)
Static Private Attributes
static final String ERROR_FILE_LOC
static final int ERROR_POPUP_WIDTH = 260
static final int ERROR_POPUP_HEIGHT = 225
static final String TITLE = "Error"
Detailed Description
Utility class that easily allows for the creation of error popups in a new window.
Author
Austin Kyker
Definition at line 20 of file ErrorPopup.java.
Constructor & Destructor Documentation
utilities.errorPopup.ErrorPopup.ErrorPopup (String message)
Definition at line 28 of file ErrorPopup.java.
References utilities.JavaFXutilities.imageView.StringToImageViewConverter.getImageView(), utilities.multilanguage.MultiLanguageUtility.getInstance(), utilities.multilanguage.MultiLanguageUtility.getStringProperty(), and gameAuthoring.mainclasses.Constants.SM_PADDING.
Member Data Documentation
final String utilities.errorPopup.ErrorPopup.ERROR_FILE_LOC static private
Initial value:
=
            "./src/utilities/errorPopup/error.PNG"
Definition at line 22 of file ErrorPopup.java.
final int utilities.errorPopup.ErrorPopup.ERROR_POPUP_HEIGHT = 225 static private
Definition at line 25 of file ErrorPopup.java.
final int utilities.errorPopup.ErrorPopup.ERROR_POPUP_WIDTH = 260 static private
Definition at line 24 of file ErrorPopup.java.
final String utilities.errorPopup.ErrorPopup.TITLE = "Error" static private
Definition at line 26 of file ErrorPopup.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/utilities/errorPopup/ErrorPopup.java