voogasalad_LosTorres: gameAuthoring.mainclasses.AuthorController Class Reference
gameAuthoring.mainclasses.AuthorController Class Reference
Public Member Functions
void start (Stage stage) throws Exception
void showPathBuildingScene ()
void showEnemyBuildingScene ()
void showTowerBuildingScene ()
void showLevelBuildingScene ()
void makeDirectory (String gameName, String gameType)
void configurePath (Path path)
void configureEnemies (List< BaseEnemy > enemies)
void configureTowers (List< TowerUpgradeGroup > towers)
void configureLevels (List< BaseLevel > levels)
List< BaseEnemy > fetchEnemies ()
List< BackendRoute > fetchEnemyRoutes ()
void setBackground (String imageFileName)
void setTowerRegions (boolean[][] backendTowerRegions)
void setGeneralSettings (GeneralSettingsWrapper wrapper)
void update (Observable o, Object arg)
String getBackgroundImagePath ()
Static Public Member Functions
static void main (String[] args)
Static Public Attributes
static final double SCREEN_WIDTH = 1100
static final double SCREEN_HEIGHT = 633
static String gameDir
Private Member Functions
void configureAndDisplayStage ()
void setSceneAndTitle (BuildingScene scene)
void showWelcomeScene ()
void showGeneralSettingScene ()
void showGSONWritingScene ()
void writeBackgroundImageToGameDir ()
boolean notEnoughTowers ()
boolean notEnoughEnemies ()
Private Attributes
EnemyBuildingScene myEnemyBuildingScene
TowerBuildingScene myTowerBuildingScene
PathBuildingScene myPathBuildingScene
LevelBuildingScene myLevelBuildingScene
GSONWritingScene myGSONWritingScene
WelcomeScene myWelcomeScene
GeneralSettingScene myGeneralSettingScene
List< BackendRoute > myBackendRoutes
List< BaseEnemy > myEnemies
List< TowerUpgradeGroup > myTowerGroups
List< BaseLevel > myLevels
Stage myStage
String myBackgroundImageFileName
Static Private Attributes
static final String ENGLISH_PROPERTIES
static final String CHINESE_PROPERTIES
static final String SPANISH_PROPERTIES
static final GSONFileWriter GSON_WRITER = new GSONFileWriter()
Detailed Description
The purpose of this class is to manage the different scenes (path building and author creation). The class also will hold the enemies, towers, and level objects which it will write to JSON files at the end of the authoring process.
Author
Austin Kyker
Definition at line 47 of file AuthorController.java.
Member Function Documentation
void gameAuthoring.mainclasses.AuthorController.configureAndDisplayStage () private
Definition at line 92 of file AuthorController.java.
Referenced by gameAuthoring.mainclasses.AuthorController.start().
void gameAuthoring.mainclasses.AuthorController.configureEnemies (List< BaseEnemy > enemies)
Implements gameAuthoring.mainclasses.controllerInterfaces.IEnemyConfiguring.
Definition at line 174 of file AuthorController.java.
References gameAuthoring.mainclasses.Constants.NOT_ENOUGH_ENEMIES_MSG, gameAuthoring.mainclasses.AuthorController.notEnoughEnemies(), and gameAuthoring.mainclasses.AuthorController.showTowerBuildingScene().
void gameAuthoring.mainclasses.AuthorController.configureLevels (List< BaseLevel > levels)
Implements gameAuthoring.mainclasses.controllerInterfaces.ILevelConfiguring.
Definition at line 204 of file AuthorController.java.
References gameAuthoring.mainclasses.AuthorController.showGSONWritingScene().
void gameAuthoring.mainclasses.AuthorController.configurePath (Path path)
Implements gameAuthoring.mainclasses.controllerInterfaces.IPathConfiguring.
Definition at line 168 of file AuthorController.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.routeToPointTranslation.BackendRoutesGenerator.getBackendRoutes(), and gameAuthoring.mainclasses.AuthorController.showEnemyBuildingScene().
void gameAuthoring.mainclasses.AuthorController.configureTowers (List< TowerUpgradeGroup > towers)
Implements gameAuthoring.mainclasses.controllerInterfaces.ITowerConfiguring.
Definition at line 193 of file AuthorController.java.
References gameAuthoring.mainclasses.Constants.NOT_ENOUGH_TOWERS_MSG, gameAuthoring.mainclasses.AuthorController.notEnoughTowers(), and gameAuthoring.mainclasses.AuthorController.showLevelBuildingScene().
List<BaseEnemy> gameAuthoring.mainclasses.AuthorController.fetchEnemies ()
Implements gameAuthoring.mainclasses.controllerInterfaces.ILevelConfiguring.
Definition at line 210 of file AuthorController.java.
References gameAuthoring.mainclasses.AuthorController.myEnemies.
List<BackendRoute> gameAuthoring.mainclasses.AuthorController.fetchEnemyRoutes ()
Implements gameAuthoring.mainclasses.controllerInterfaces.IEnemyConfiguring.
Definition at line 215 of file AuthorController.java.
References gameAuthoring.mainclasses.AuthorController.myBackendRoutes.
String gameAuthoring.mainclasses.AuthorController.getBackgroundImagePath ()
Implements gameAuthoring.mainclasses.controllerInterfaces.ILevelConfiguring.
Definition at line 241 of file AuthorController.java.
References gameAuthoring.mainclasses.AuthorController.myBackgroundImageFileName.
static void gameAuthoring.mainclasses.AuthorController.main (String[] args) static
Definition at line 79 of file AuthorController.java.
void gameAuthoring.mainclasses.AuthorController.makeDirectory (String gameName, String gameType)
Parameters
gameName
singleType SinglePlayer or Co-Op
Implements gameAuthoring.mainclasses.controllerInterfaces.IGeneralSettingsConfiguring.
Definition at line 160 of file AuthorController.java.
References gameAuthoring.mainclasses.AuthorController.showPathBuildingScene().
boolean gameAuthoring.mainclasses.AuthorController.notEnoughEnemies () private
Definition at line 188 of file AuthorController.java.
Referenced by gameAuthoring.mainclasses.AuthorController.configureEnemies().
boolean gameAuthoring.mainclasses.AuthorController.notEnoughTowers () private
Definition at line 184 of file AuthorController.java.
Referenced by gameAuthoring.mainclasses.AuthorController.configureTowers().
void gameAuthoring.mainclasses.AuthorController.setBackground (String imageFileName)
Implements gameAuthoring.mainclasses.controllerInterfaces.IPathConfiguring.
Definition at line 220 of file AuthorController.java.
void gameAuthoring.mainclasses.AuthorController.setGeneralSettings (GeneralSettingsWrapper wrapper)
Implements gameAuthoring.mainclasses.controllerInterfaces.IGeneralSettingsConfiguring.
Definition at line 230 of file AuthorController.java.
References utilities.GSON.GSONFileWriter.writeGeneralSettings().
void gameAuthoring.mainclasses.AuthorController.setSceneAndTitle (BuildingScene scene) private
Definition at line 120 of file AuthorController.java.
References gameAuthoring.scenes.BuildingScene.getScene(), and gameAuthoring.scenes.BuildingScene.getTitle().
Referenced by gameAuthoring.mainclasses.AuthorController.showEnemyBuildingScene(), gameAuthoring.mainclasses.AuthorController.showLevelBuildingScene(), gameAuthoring.mainclasses.AuthorController.showPathBuildingScene(), and gameAuthoring.mainclasses.AuthorController.showTowerBuildingScene().
void gameAuthoring.mainclasses.AuthorController.setTowerRegions (boolean backendTowerRegions[][])
Implements gameAuthoring.mainclasses.controllerInterfaces.IPathConfiguring.
Definition at line 225 of file AuthorController.java.
References utilities.GSON.GSONFileWriter.writeTowerRegions().
void gameAuthoring.mainclasses.AuthorController.showEnemyBuildingScene ()
Definition at line 102 of file AuthorController.java.
References gameAuthoring.mainclasses.AuthorController.setSceneAndTitle().
Referenced by gameAuthoring.mainclasses.AuthorController.configurePath().
void gameAuthoring.mainclasses.AuthorController.showGeneralSettingScene () private
Definition at line 131 of file AuthorController.java.
References gameAuthoring.scenes.GeneralSettingScene.getScene().
Referenced by gameAuthoring.mainclasses.AuthorController.update().
void gameAuthoring.mainclasses.AuthorController.showGSONWritingScene () private
Definition at line 136 of file AuthorController.java.
References gameAuthoring.mainclasses.AuthorController.writeBackgroundImageToGameDir(), and utilities.GSON.GSONFileWriter.writeGameFile().
Referenced by gameAuthoring.mainclasses.AuthorController.configureLevels().
void gameAuthoring.mainclasses.AuthorController.showLevelBuildingScene ()
Definition at line 114 of file AuthorController.java.
References gameAuthoring.mainclasses.AuthorController.setSceneAndTitle().
Referenced by gameAuthoring.mainclasses.AuthorController.configureTowers().
void gameAuthoring.mainclasses.AuthorController.showPathBuildingScene ()
Definition at line 96 of file AuthorController.java.
References gameAuthoring.mainclasses.AuthorController.setSceneAndTitle().
Referenced by gameAuthoring.mainclasses.AuthorController.makeDirectory().
void gameAuthoring.mainclasses.AuthorController.showTowerBuildingScene ()
Definition at line 108 of file AuthorController.java.
References gameAuthoring.mainclasses.AuthorController.setSceneAndTitle().
Referenced by gameAuthoring.mainclasses.AuthorController.configureEnemies().
void gameAuthoring.mainclasses.AuthorController.showWelcomeScene () private
Definition at line 125 of file AuthorController.java.
References gameAuthoring.scenes.WelcomeScene.getScene().
Referenced by gameAuthoring.mainclasses.AuthorController.start().
void gameAuthoring.mainclasses.AuthorController.start (Stage stage) throws Exception
Definition at line 84 of file AuthorController.java.
References gameAuthoring.mainclasses.AuthorController.configureAndDisplayStage(), utilities.multilanguage.MultiLanguageUtility.getInstance(), utilities.multilanguage.MultiLanguageUtility.initLanguages(), and gameAuthoring.mainclasses.AuthorController.showWelcomeScene().
void gameAuthoring.mainclasses.AuthorController.update (Observable o, Object arg)
Definition at line 236 of file AuthorController.java.
References gameAuthoring.mainclasses.AuthorController.showGeneralSettingScene().
void gameAuthoring.mainclasses.AuthorController.writeBackgroundImageToGameDir () private
Definition at line 144 of file AuthorController.java.
References gameAuthoring.mainclasses.Constants.BACKGROUND_IMG_NOT_COPIED, and gameAuthoring.mainclasses.AuthorController.gameDir.
Referenced by gameAuthoring.mainclasses.AuthorController.showGSONWritingScene().
Member Data Documentation
final String gameAuthoring.mainclasses.AuthorController.CHINESE_PROPERTIES static private
Initial value:
=
            "gameAuthoring.Resources.propertyFiles.Chinese.properties"
Definition at line 53 of file AuthorController.java.
final String gameAuthoring.mainclasses.AuthorController.ENGLISH_PROPERTIES static private
Initial value:
=
            "gameAuthoring.Resources.propertyFiles.English.properties"
Definition at line 51 of file AuthorController.java.
String gameAuthoring.mainclasses.AuthorController.gameDir static
Definition at line 61 of file AuthorController.java.
Referenced by gameAuthoring.mainclasses.AuthorController.writeBackgroundImageToGameDir().
final GSONFileWriter gameAuthoring.mainclasses.AuthorController.GSON_WRITER = new GSONFileWriter() static private
Definition at line 60 of file AuthorController.java.
List<BackendRoute> gameAuthoring.mainclasses.AuthorController.myBackendRoutes private
Definition at line 71 of file AuthorController.java.
Referenced by gameAuthoring.mainclasses.AuthorController.fetchEnemyRoutes().
String gameAuthoring.mainclasses.AuthorController.myBackgroundImageFileName private
Definition at line 77 of file AuthorController.java.
Referenced by gameAuthoring.mainclasses.AuthorController.getBackgroundImagePath().
List<BaseEnemy> gameAuthoring.mainclasses.AuthorController.myEnemies private
Definition at line 72 of file AuthorController.java.
Referenced by gameAuthoring.mainclasses.AuthorController.fetchEnemies().
EnemyBuildingScene gameAuthoring.mainclasses.AuthorController.myEnemyBuildingScene private
Definition at line 63 of file AuthorController.java.
GeneralSettingScene gameAuthoring.mainclasses.AuthorController.myGeneralSettingScene private
Definition at line 69 of file AuthorController.java.
GSONWritingScene gameAuthoring.mainclasses.AuthorController.myGSONWritingScene private
Definition at line 67 of file AuthorController.java.
LevelBuildingScene gameAuthoring.mainclasses.AuthorController.myLevelBuildingScene private
Definition at line 66 of file AuthorController.java.
List<BaseLevel> gameAuthoring.mainclasses.AuthorController.myLevels private
Definition at line 74 of file AuthorController.java.
PathBuildingScene gameAuthoring.mainclasses.AuthorController.myPathBuildingScene private
Definition at line 65 of file AuthorController.java.
Stage gameAuthoring.mainclasses.AuthorController.myStage private
Definition at line 76 of file AuthorController.java.
TowerBuildingScene gameAuthoring.mainclasses.AuthorController.myTowerBuildingScene private
Definition at line 64 of file AuthorController.java.
List<TowerUpgradeGroup> gameAuthoring.mainclasses.AuthorController.myTowerGroups private
Definition at line 73 of file AuthorController.java.
WelcomeScene gameAuthoring.mainclasses.AuthorController.myWelcomeScene private
Definition at line 68 of file AuthorController.java.
final double gameAuthoring.mainclasses.AuthorController.SCREEN_HEIGHT = 633 static
Definition at line 59 of file AuthorController.java.
Referenced by gameEngine.MainEngineManager.createGameSizedGridPane(), gameAuthoring.scenes.GeneralSettingScene.createRightImage(), gameAuthoring.scenes.pathBuilding.DefaultMapSelectionPane.DefaultMapSelectionPane(), gameAuthoring.scenes.GeneralSettingScene.GeneralSettingScene(), gameEngine.AI.GridPathFinder.getPath(), gameAuthoring.scenes.GSONWritingScene.GSONWritingScene(), gamePlayer.guiItems.gameWorld.GameWorld.initialize(), gameAuthoring.scenes.pathBuilding.buildingPanes.PathBackgroundSelectionPane.PathBackgroundSelectionPane(), gameAuthoring.scenes.pathBuilding.PathBuildingScene.setBackground(), gameAuthoring.scenes.actorBuildingScenes.ActorBuildingScene.setupDragAndDropForActorImage(), gameAuthoring.scenes.levelBuilding.LevelBuildingScene.setupLevelDisplay(), gameAuthoring.scenes.pathBuilding.buildingPanes.towerRegions.TowerRegionsPane.TowerRegionsPane(), and gameAuthoring.scenes.WelcomeScene.WelcomeScene().
final double gameAuthoring.mainclasses.AuthorController.SCREEN_WIDTH = 1100 static
Definition at line 58 of file AuthorController.java.
Referenced by gameAuthoring.scenes.GeneralSettingScene.createOptionFields(), gameAuthoring.scenes.GeneralSettingScene.createRightImage(), gameAuthoring.scenes.GeneralSettingScene.GeneralSettingScene(), gameAuthoring.scenes.GSONWritingScene.GSONWritingScene(), and gameAuthoring.scenes.WelcomeScene.WelcomeScene().
final String gameAuthoring.mainclasses.AuthorController.SPANISH_PROPERTIES static private
Initial value:
=
            "gameAuthoring.Resources.propertyFiles.Spanish.properties"
Definition at line 55 of file AuthorController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/mainclasses/AuthorController.java