voogasalad_LosTorres: gameAuthoring.scenes.levelBuilding.LevelBuildingScene Class Reference
gameAuthoring.scenes.levelBuilding.LevelBuildingScene Class Reference
Public Member Functions
LevelBuildingScene (BorderPane root, ILevelConfiguring controller)
void update (Observable arg0, Object arg1)
Public Member Functions inherited from gameAuthoring.scenes.BuildingScene
BuildingScene (BorderPane root, String title)
String getTitle ()
Scene getScene ()
Private Member Functions
void setupLevelDisplay ()
void createMenuAndAddNewLevelOption ()
Private Attributes
LevelBuildingDisplay myLevelsDisplay
ILevelConfiguring myLevelConfiguringController
Pane mySimulationPane
Static Private Attributes
static final String TITLE = "Level"
Additional Inherited Members
Static Public Attributes inherited from gameAuthoring.scenes.BuildingScene
static final String STYLESHEET_PACKAGE = "./gameAuthoring/Stylesheets/"
Protected Attributes inherited from gameAuthoring.scenes.BuildingScene
BorderPane myPane
Detailed Description
Allows the user to build a new level and also simulate the level.
Author
Austin Kyker, David Zhang
Definition at line 26 of file LevelBuildingScene.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.levelBuilding.LevelBuildingScene.LevelBuildingScene (BorderPane root, ILevelConfiguring controller)
Definition at line 34 of file LevelBuildingScene.java.
References gameAuthoring.scenes.levelBuilding.LevelBuildingScene.createMenuAndAddNewLevelOption(), and gameAuthoring.scenes.levelBuilding.LevelBuildingScene.setupLevelDisplay().
Member Function Documentation
void gameAuthoring.scenes.levelBuilding.LevelBuildingScene.createMenuAndAddNewLevelOption () private
Definition at line 59 of file LevelBuildingScene.java.
References gameAuthoring.scenes.levelBuilding.LevelBuildingDisplay.addLevel(), gameAuthoring.scenes.actorBuildingScenes.BuildingSceneMenu.addMenuItemToFileMenu(), utilities.multilanguage.MultiLanguageUtility.getInstance(), gameAuthoring.scenes.actorBuildingScenes.BuildingSceneMenu.getNode(), utilities.multilanguage.MultiLanguageUtility.getStringProperty(), gameAuthoring.scenes.BuildingScene.myPane, and gameAuthoring.mainclasses.Constants.NEW_LEVEL.
Referenced by gameAuthoring.scenes.levelBuilding.LevelBuildingScene.LevelBuildingScene().
void gameAuthoring.scenes.levelBuilding.LevelBuildingScene.setupLevelDisplay () private
Definition at line 41 of file LevelBuildingScene.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.DRAW_SCREEN_WIDTH, gameAuthoring.mainclasses.controllerInterfaces.ILevelConfiguring.fetchEnemies(), gameAuthoring.mainclasses.controllerInterfaces.ILevelConfiguring.getBackgroundImagePath(), utilities.JavaFXutilities.imageView.StringToImageViewConverter.getImageView(), gameAuthoring.scenes.BuildingScene.myPane, gameAuthoring.scenes.levelBuilding.LevelBuildingScene.mySimulationPane, and gameAuthoring.mainclasses.AuthorController.SCREEN_HEIGHT.
Referenced by gameAuthoring.scenes.levelBuilding.LevelBuildingScene.LevelBuildingScene().
void gameAuthoring.scenes.levelBuilding.LevelBuildingScene.update (Observable arg0, Object arg1)
This is called when the user hits finished from the file menu.
Definition at line 74 of file LevelBuildingScene.java.
References gameAuthoring.mainclasses.controllerInterfaces.ILevelConfiguring.configureLevels(), gameAuthoring.scenes.levelBuilding.LevelBuildingDisplay.isAllUserInputIsValid(), gameAuthoring.mainclasses.Constants.LEVEL_ERROR, and gameAuthoring.scenes.levelBuilding.LevelBuildingDisplay.transformToLevels().
Member Data Documentation
ILevelConfiguring gameAuthoring.scenes.levelBuilding.LevelBuildingScene.myLevelConfiguringController private
Definition at line 31 of file LevelBuildingScene.java.
LevelBuildingDisplay gameAuthoring.scenes.levelBuilding.LevelBuildingScene.myLevelsDisplay private
Definition at line 30 of file LevelBuildingScene.java.
Pane gameAuthoring.scenes.levelBuilding.LevelBuildingScene.mySimulationPane private
Definition at line 32 of file LevelBuildingScene.java.
Referenced by gameAuthoring.scenes.levelBuilding.LevelBuildingScene.setupLevelDisplay().
final String gameAuthoring.scenes.levelBuilding.LevelBuildingScene.TITLE = "Level" static private
Definition at line 28 of file LevelBuildingScene.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/levelBuilding/LevelBuildingScene.java