voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane Class Reference
gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane Class Reference
Public Member Functions
CurveDrawingPane (Group group, Path path)
void executeEnterFunction ()
void executeExitFunction ()
Public Member Functions inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
BuildingPane (Group group)
void drawLocation (Node component)
void drawPathComponent (Node component)
void refreshScreen ()
void removeComponentFromScreen (Node component)
void executeExitFunction ()
void executeEnterFunction ()
Private Member Functions
void addListeners ()
void removeListeners ()
void stretchLineToEndAtCurrentMousePosition (MouseEvent event)
void handleBuildScreenClick (MouseEvent event)
boolean clickedOnControlPoint (MouseEvent event)
void addControlPointSetters (PathCurve tempCurve)
void moveControlPoint1 (PathCurve tempCurve, Circle controlPoint1Setter, MouseEvent event)
void moveControlPoint2 (PathCurve tempCurve, Circle controlPoint2Setter, MouseEvent event)
void moveControlPointSetter (Circle controlPointSetter, MouseEvent event)
Circle getControlPointSetter (double x, double y)
Private Attributes
PathCurve myCurveBeingCreated
Path myPath
Group myGroup
List< Node > myControlPointSetters
Static Private Attributes
static final int CONTROL_POINT_SETTER_RADIUS = 10
static final int MIN_CURVE_LENGTH = 60
Additional Inherited Members
Static Public Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
static final double DRAW_SCREEN_WIDTH_RATIO = .80
static final double DRAW_SCREEN_WIDTH
Static Protected Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
static Group myGroup
Detailed Description
Defines the pane where the user can draw curves and the click-listener to actually create these curves. Click once to define the starting location of the curve, twice to define the ending location of the curve, and twice more to define the control points.
Author
Austin Kyker
Definition at line 24 of file CurveDrawingPane.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.CurveDrawingPane (Group group, Path path)
Definition at line 33 of file CurveDrawingPane.java.
Member Function Documentation
void gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.addControlPointSetters (PathCurve tempCurve) private
Definition at line 89 of file CurveDrawingPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.getControlPointSetter(), gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.moveControlPoint1(), gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.moveControlPoint2(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setControlPointSetters().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.handleBuildScreenClick().
void gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.addListeners () private
Definition at line 40 of file CurveDrawingPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.handleBuildScreenClick(), and gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.stretchLineToEndAtCurrentMousePosition().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.executeEnterFunction(), and gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.handleBuildScreenClick().
boolean gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.clickedOnControlPoint (MouseEvent event) private
Definition at line 82 of file CurveDrawingPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.handleBuildScreenClick().
void gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.executeEnterFunction ()
Definition at line 128 of file CurveDrawingPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.addListeners(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.getAllPathComponents().
void gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.executeExitFunction ()
Definition at line 137 of file CurveDrawingPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.removeListeners().
Circle gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.getControlPointSetter (double x, double y) private
Definition at line 121 of file CurveDrawingPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.addControlPointSetters().
void gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.handleBuildScreenClick (MouseEvent event) private
Definition at line 58 of file CurveDrawingPane.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.addComponentToPath(), gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.addControlPointSetters(), gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.addListeners(), gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.clickedOnControlPoint(), gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane.drawPathComponent(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.endPointIsSet(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.getLength(), gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.isEndPointSet, gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.MIN_CURVE_LENGTH, gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.myCurveBeingCreated, and gameAuthoring.scenes.pathBuilding.pathComponents.Path.tryToAddConnectComponentToEndingLocation().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.addListeners().
void gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.moveControlPoint1 (PathCurve tempCurve, Circle controlPoint1Setter, MouseEvent event) private
Definition at line 102 of file CurveDrawingPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.moveControlPointSetter(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setControlPoint1().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.addControlPointSetters().
void gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.moveControlPoint2 (PathCurve tempCurve, Circle controlPoint2Setter, MouseEvent event) private
Definition at line 109 of file CurveDrawingPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.moveControlPointSetter(), and gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.setControlPoint2().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.addControlPointSetters().
void gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.moveControlPointSetter (Circle controlPointSetter, MouseEvent event) private
Definition at line 116 of file CurveDrawingPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.moveControlPoint1(), and gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.moveControlPoint2().
void gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.removeListeners () private
Definition at line 45 of file CurveDrawingPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.executeExitFunction().
void gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.stretchLineToEndAtCurrentMousePosition (MouseEvent event) private
Definition at line 50 of file CurveDrawingPane.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathCurve.calculateAndSetControlPoints().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.addListeners().
Member Data Documentation
final int gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.CONTROL_POINT_SETTER_RADIUS = 10 static private
Definition at line 26 of file CurveDrawingPane.java.
final int gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.MIN_CURVE_LENGTH = 60 static private
Definition at line 27 of file CurveDrawingPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.handleBuildScreenClick().
List<Node> gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.myControlPointSetters private
Definition at line 31 of file CurveDrawingPane.java.
PathCurve gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.myCurveBeingCreated private
Definition at line 28 of file CurveDrawingPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.handleBuildScreenClick().
Group gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.myGroup private
Definition at line 30 of file CurveDrawingPane.java.
Path gameAuthoring.scenes.pathBuilding.buildingPanes.CurveDrawingPane.myPath private
Definition at line 29 of file CurveDrawingPane.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/buildingPanes/CurveDrawingPane.java