voogasalad_LosTorres: gamePlayer.guiItems.headsUpDisplay.HUD Class Reference
gamePlayer.guiItems.headsUpDisplay.HUD Class Reference
Public Member Functions
void initialize (Dimension2D containerSize)
void setGameStats (List< GameStat > stats)
Node getNode ()
Private Attributes
XMLParser myParser
TableView< GameStat > myTableView
Dimension2D mySize
Additional Inherited Members
Static Public Attributes inherited from gamePlayer.guiItems.GuiItem
static String myPropertiesPath = "guiItems/"
Detailed Description
This GuiItem initializes and manages the game statistics board (heads-up-display)
Author
allankiplagat
Definition at line 24 of file HUD.java.
Member Function Documentation
Node gamePlayer.guiItems.headsUpDisplay.HUD.getNode ()
Returns
this GuiElement's Node
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 71 of file HUD.java.
References gamePlayer.guiItems.headsUpDisplay.HUD.myTableView.
void gamePlayer.guiItems.headsUpDisplay.HUD.initialize (Dimension2D containerSize)
In this method, a GuiElement sets its node's size based on the containerSize and also initializes elements it hosts
Parameters
containerSize size of the container within which this GuiElement is hosted
Implements gamePlayer.mainClasses.guiBuilder.GuiElement.
Definition at line 30 of file HUD.java.
References utilities.JavaFXutilities.ratioSizing.RatiosToDim.convert(), utilities.XMLParsing.XMLParser.getDimension(), gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_ELEMENT_PROPERTIES_PATH, gamePlayer.mainClasses.guiBuilder.GuiConstants.GUI_MANAGER, gamePlayer.guiItems.GuiItem.myPropertiesPath, and gamePlayer.mainClasses.managers.GuiManager.registerStatsBoard().
void gamePlayer.guiItems.headsUpDisplay.HUD.setGameStats (List< GameStat > stats)
Parameters
stats the list of GameStats objects to be displayed
Definition at line 49 of file HUD.java.
References utilities.XMLParsing.XMLParser.getDoubleValuesFromTag().
Referenced by gamePlayer.mainClasses.managers.GuiManager.setGameStats().
Member Data Documentation
XMLParser gamePlayer.guiItems.headsUpDisplay.HUD.myParser private
Definition at line 25 of file HUD.java.
Dimension2D gamePlayer.guiItems.headsUpDisplay.HUD.mySize private
Definition at line 27 of file HUD.java.
TableView<GameStat> gamePlayer.guiItems.headsUpDisplay.HUD.myTableView private
Definition at line 26 of file HUD.java.
Referenced by gamePlayer.guiItems.headsUpDisplay.HUD.getNode().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gamePlayer/guiItems/headsUpDisplay/HUD.java