voogasalad_LosTorres: gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane Class Reference
gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane Class Reference
Public Member Functions
SelectComponentPane (Group group, Path path)
void addListenersToComponents ()
void removeListenerFromComponents ()
void executeEnterFunction ()
void executeExitFunction ()
Public Member Functions inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
BuildingPane (Group group)
void drawLocation (Node component)
void drawPathComponent (Node component)
void refreshScreen ()
void removeComponentFromScreen (Node component)
void executeExitFunction ()
void executeEnterFunction ()
Private Member Functions
void addSelectionListeners (PathComponent component)
void handleSelectionAndTryToConnectComponents (PathComponent component)
Private Attributes
Path myPath
double mouseX
double mouseY
Additional Inherited Members
Static Public Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
static final double DRAW_SCREEN_WIDTH_RATIO = .80
static final double DRAW_SCREEN_WIDTH
Static Protected Attributes inherited from gameAuthoring.scenes.pathBuilding.buildingPanes.BuildingPane
static Group myGroup
Detailed Description
Allows the user to select a route by clicking on PathComponents. When the user clicks on a component, the component becomes green and the user can drag it to a new spot if it is not connected to a starting or ending location or the user can remove it.
Author
Austin Kyker
Definition at line 19 of file SelectComponentPane.java.
Constructor & Destructor Documentation
gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.SelectComponentPane (Group group, Path path)
Definition at line 25 of file SelectComponentPane.java.
Member Function Documentation
void gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.addListenersToComponents ()
Definition at line 30 of file SelectComponentPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.addSelectionListeners(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.getAllPathComponents().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.executeEnterFunction().
void gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.addSelectionListeners (PathComponent component) private
Definition at line 44 of file SelectComponentPane.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.PathComponent.getNode(), gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.handleSelectionAndTryToConnectComponents(), gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.mouseX, gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.mouseY, and gameAuthoring.scenes.pathBuilding.pathComponents.Path.moveConnectedComponent().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.addListenersToComponents().
void gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.executeEnterFunction ()
Definition at line 73 of file SelectComponentPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.addListenersToComponents().
void gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.executeExitFunction ()
Definition at line 78 of file SelectComponentPane.java.
References gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.removeListenerFromComponents().
void gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.handleSelectionAndTryToConnectComponents (PathComponent component) private
Definition at line 67 of file SelectComponentPane.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.attemptToConnectRoutes(), and gameAuthoring.scenes.pathBuilding.pathComponents.Path.handleComponentSelection().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.addSelectionListeners().
void gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.removeListenerFromComponents ()
Definition at line 36 of file SelectComponentPane.java.
References gameAuthoring.scenes.pathBuilding.pathComponents.Path.getAllPathComponents().
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.executeExitFunction().
Member Data Documentation
double gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.mouseX private
Definition at line 22 of file SelectComponentPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.addSelectionListeners().
double gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.mouseY private
Definition at line 23 of file SelectComponentPane.java.
Referenced by gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.addSelectionListeners().
Path gameAuthoring.scenes.pathBuilding.buildingPanes.SelectComponentPane.myPath private
Definition at line 21 of file SelectComponentPane.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_LosTorres/repository/src/gameAuthoring/scenes/pathBuilding/buildingPanes/SelectComponentPane.java